import type { BrazilGuideLocalized } from "./types";

export const avesDoBrasilGuide: BrazilGuideLocalized = {
  pt: {
    destinationName: "Aves do Brasil",
    blurb: "Guia de birdwatching pelo Brasil: cerca de 1.900 espécies, do Cristalino ao Pantanal, da Caatinga a Noronha.",
    metaTitle: "Aves do Brasil: guia de birdwatching e onde observá-las",
    metaDescription: "Guia autoral de observação de aves no Brasil: endemismos, melhores meses, lodges especializados e roteiros do Cristalino ao Pantanal, da Mata Atlântica a Noronha.",
    keywords: "aves do brasil, birdwatching brasil, cristalino lodge aves, arara azul de lear, tuiuiú pantanal, serra dos tucanos, itatiaia aves, observação de aves brasil",
    h1: "Aves do Brasil: um país com quase 1.900 espécies catalogadas",
    aiAnswer: "O Brasil reúne cerca de 1.900 espécies de aves, mais que qualquer outro país; os melhores destinos são Cristalino Lodge e Alta Floresta (Amazônia), Itatiaia e Serra dos Tucanos (Mata Atlântica), Chapada dos Guimarães e Pantanal (aves de campo e várzea), e Boa Nova na Caatinga para a rara arara-azul-de-lear.",
    intro: [
      "Com quase 1.900 espécies registradas, o Brasil é o país com a maior diversidade de aves do planeta — mais que a Colômbia, mais que o Peru. Essa riqueza se espalha por biomas tão distintos que um único roteiro nunca esgota o assunto: cada bioma tem seu conjunto de endemismos, seu guia especialista, sua estação certa.",
      "Este guia nasceu de expedições feitas ao lado de ornitólogos e guias de campo, não de listas genéricas. Aqui estão os lugares que realmente entregam as espécies mais desejadas, os meses de maior atividade e o nível de exigência de cada roteiro.",
    ],
    seasons: {
      heading: "Melhores meses para observar aves no Brasil",
      intro: "Cada região tem sua janela ótima, quase sempre ligada à reprodução ou à seca dos rios.",
      windows: [
        { window: "Maio a setembro — seca amazônica e Pantanal", text: "Rios baixos concentram aves de várzea e savana; no Pantanal é a melhor época para tuiuiús, araras-azuis e a maior densidade de aves aquáticas do continente." },
        { window: "Setembro a dezembro — reprodução na Mata Atlântica", text: "Cantos territoriais no auge, ótima visibilidade de araponga, saíras e tangarás em Itatiaia, Serra dos Tucanos e Intervales." },
        { window: "Outubro a março — Caatinga e arara-azul-de-lear", text: "Após as primeiras chuvas, atividade reprodutiva sobe em Boa Nova; período também bom para aves de Emas e do Cerrado." },
        { window: "Ano todo — Cristalino e Fernando de Noronha", text: "O Cristalino oferece observação de alto nível o ano inteiro; Noronha entrega aves marinhas oceânicas com constância, com pico de nidificação entre setembro e março." },
      ],
    },
    experiences: {
      heading: "Onde observar as aves mais desejadas do Brasil",
      intro: "Seleção por bioma e espécie-alvo, sempre com guias especializados em campo.",
      items: [
        { title: "Cristalino Lodge e Alta Floresta", text: "Mais de 600 espécies registradas, torres de dossel a 50 metros e trilhas exclusivas. Referência mundial para arapongas-de-cabeça-nua, gaviões-reais e uma infinidade de araçaris." },
        { title: "Presidente Figueiredo (Amazonas)", text: "Cachoeiras e floresta de terra firme perto de Manaus, com boa chance de galo-da-serra e espécies de sub-bosque amazônico em roteiro mais curto." },
        { title: "Serra dos Tucanos e Itatiaia (Mata Atlântica)", text: "Comedouros e trilhas desenhados para fotografia, com espécies endêmicas como o tovacuçu e o soldadinho, além de beija-flores em alta densidade." },
        { title: "Intervales e Ubatuba (Mata Atlântica paulista)", text: "Um dos melhores redutos de araponga e jacutinga do país, com trilhas de floresta primária e guias especializados em vocalização." },
        { title: "Chapada dos Guimarães e Pantanal", text: "Transição de Cerrado e planície alagada: tuiuiús, araras-azuis, socós, jaburus e uma das maiores concentrações de aves de rapina do continente." },
        { title: "Boa Nova (Caatinga) e Parque das Emas", text: "Boa Nova protege uma das últimas populações da arara-azul-de-lear em estado selvagem; Emas entrega aves de campo aberto como a seriema e o tamanduá-bandeira como bônus." },
        { title: "Ilha do Marajó e Fernando de Noronha", text: "Marajó, com campos alagados e colônias de guarás; Noronha, arquipélago oceânico com atobás, fragatas e o rabo-de-palha, de fácil observação costeira." },
      ],
    },
    stays: {
      heading: "Lodges e bases para birdwatchers",
      intro: "Endereços desenhados — ou adaptados — para observação séria de aves.",
      items: [
        { name: "Cristalino Lodge", profile: "Birders sérios e fotógrafos", text: "Torres de dossel, trilhas exclusivas e guias residentes especializados em identificação por canto." },
        { name: "Serra dos Tucanos Lodge", profile: "Fotógrafos de Mata Atlântica", text: "Comedouros próximos aos quartos e trilhas de curta distância para espécies endêmicas." },
        { name: "Refúgio Ecológico Caiman (Pantanal)", profile: "Observadores de fauna em geral", text: "Programa de conservação da arara-azul integrado a passeios de observação de aves aquáticas." },
        { name: "Pousadas parceiras em Boa Nova", profile: "Especialistas em endemismos", text: "Guias locais que acompanham a população da arara-azul-de-lear diariamente." },
        { name: "Pousadas em Fernando de Noronha", profile: "Observadores de aves marinhas", text: "Trilhas costeiras a poucos minutos de colônias de atobás e fragatas." },
      ],
    },
    profiles: {
      heading: "Para quem funciona um roteiro de aves pelo Brasil",
      items: [
        { title: "Birders experientes com lista internacional", text: "Roteiros combinando Amazônia, Pantanal e Mata Atlântica entregam altíssimo número de novas espécies por viagem." },
        { title: "Fotógrafos de natureza", text: "Serra dos Tucanos e Cristalino oferecem infraestrutura pensada para foto, com comedouros e hides." },
        { title: "Casais com interesse geral em fauna", text: "Pantanal combina aves com onças, capivaras e jacarés, sem exigir conhecimento técnico prévio." },
      ],
    },
    itinerary: {
      heading: "Como montar um roteiro de observação de aves no Brasil",
      intro: "Poucos países permitem combinar tantos biomas de aves em uma única viagem — a logística aérea interna torna isso viável.",
      items: [
        { title: "Amazônia + Pantanal — 12 dias", text: "Cristalino Lodge seguido de Refúgio Caiman: floresta de dossel e planície alagada nos dois extremos de biodiversidade." },
        { title: "Mata Atlântica completa — 8 dias", text: "Itatiaia, Serra dos Tucanos e Intervales em sequência, cobrindo os principais endemismos do bioma." },
        { title: "Caatinga e Cerrado — 7 dias", text: "Boa Nova e Parque das Emas, roteiro raro que poucos birders internacionais fazem." },
        { title: "Noronha como fechamento — 4 dias", text: "Aves marinhas, mergulho e descompressão ao final de um roteiro mais técnico de observação terrestre." },
      ],
    },
    tips: {
      heading: "Dicas práticas para observar aves no Brasil",
      items: [
        "Reserve guias especializados com antecedência — os melhores têm agenda concorrida nos meses de pico.",
        "Leve binóculo próprio de qualidade; equipamentos de lodge nem sempre atendem birders experientes.",
        "Roupas neutras e sem estampa ajudam a não espantar espécies mais tímidas.",
        "Playback de canto deve ser usado com moderação e sempre orientado pelo guia local, respeitando espécies sensíveis.",
        "Amanheceres são o horário de maior atividade — planeje saídas antes do nascer do sol.",
        "Cheque exigências de vacina e repelente antes de expedições amazônicas mais longas.",
      ],
    },
    faq: [
      { q: "Quantas espécies de aves existem no Brasil?", a: "Cerca de 1.900 espécies catalogadas, a maior diversidade de aves de qualquer país do mundo." },
      { q: "Qual o melhor lugar do Brasil para birdwatching?", a: "Depende do objetivo: Cristalino Lodge para floresta amazônica de dossel, Pantanal para aves de planície alagada e Mata Atlântica para endemismos." },
      { q: "Onde ver a arara-azul-de-lear?", a: "Em Boa Nova, na Bahia, uma das últimas áreas com população selvagem estável dessa espécie ameaçada." },
      { q: "Preciso de experiência prévia para um roteiro de aves?", a: "Não — roteiros no Pantanal e na Amazônia funcionam bem para iniciantes, sempre com guia especializado." },
      { q: "Qual a melhor época para observar aves no Brasil?", a: "Maio a setembro para Pantanal e Amazônia seca; setembro a dezembro para reprodução na Mata Atlântica." },
      { q: "É possível combinar birdwatching com outros interesses de fauna?", a: "Sim — o Pantanal em particular combina observação de aves com onças-pintadas, capivaras e jacarés no mesmo roteiro." },
    ],
    cta: { heading: "Vamos desenhar seu roteiro de observação de aves", subheading: "Um consultor humano da Create Travel conecta você aos melhores guias e lodges especializados do Brasil.", button: "Falar com um travel designer" },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },

  en: {
    destinationName: "Birds of Brazil",
    blurb: "A birdwatching guide across Brazil: nearly 1,900 species, from Cristalino to the Pantanal, from the Caatinga to Noronha.",
    metaTitle: "Birds of Brazil: A Birdwatching Guide and Where to Find Them",
    metaDescription: "A curated birdwatching guide to Brazil: endemics, best months, specialist lodges and itineraries from Cristalino to the Pantanal, the Atlantic Forest to Noronha.",
    keywords: "birds of brazil, birdwatching brazil, cristalino lodge birding, lear's macaw, jabiru pantanal, serra dos tucanos, itatiaia birding, brazil birding tours",
    h1: "Birds of Brazil: a country with nearly 1,900 recorded species",
    aiAnswer: "Brazil holds around 1,900 recorded bird species, more than any other country; top destinations are Cristalino Lodge and Alta Floresta (Amazon), Itatiaia and Serra dos Tucanos (Atlantic Forest), Chapada dos Guimarães and the Pantanal, and Boa Nova in the Caatinga for the rare Lear's macaw.",
    intro: [
      "With nearly 1,900 recorded species, Brazil holds the greatest bird diversity on the planet — ahead of Colombia and Peru. This richness spreads across biomes so distinct that no single itinerary ever exhausts it: each has its own endemics, its own specialist guides, its own best season.",
      "This guide grew out of expeditions alongside ornithologists and field guides, not generic checklists. Here are the places that truly deliver the most sought-after species, peak activity months, and each itinerary's physical demands.",
    ],
    seasons: {
      heading: "Best months for birdwatching in Brazil",
      intro: "Each region has its optimal window, usually tied to breeding or river levels.",
      windows: [
        { window: "May to September — Amazon dry season and Pantanal", text: "Low rivers concentrate floodplain and savanna birds; the Pantanal's best season for jabirus, hyacinth macaws and the continent's densest waterbird concentrations." },
        { window: "September to December — Atlantic Forest breeding season", text: "Territorial calls peak, excellent visibility of bare-throated bellbirds, tanagers and manakins in Itatiaia, Serra dos Tucanos and Intervales." },
        { window: "October to March — Caatinga and Lear's macaw", text: "After the first rains, breeding activity rises in Boa Nova; also a good window for Emas and Cerrado birds." },
        { window: "Year-round — Cristalino and Fernando de Noronha", text: "Cristalino offers top-tier birding all year; Noronha delivers reliable pelagic and seabirds, with peak nesting between September and March." },
      ],
    },
    experiences: {
      heading: "Where to find Brazil's most sought-after birds",
      intro: "Curated by biome and target species, always with specialist field guides.",
      items: [
        { title: "Cristalino Lodge and Alta Floresta", text: "Over 600 recorded species, 50-metre canopy towers and exclusive trails. A world reference for bare-necked fruitcrows, harpy eagles and countless araçaris." },
        { title: "Presidente Figueiredo (Amazonas)", text: "Waterfalls and terra firme forest near Manaus, with good odds for Guianan cock-of-the-rock and understory Amazon species on a shorter itinerary." },
        { title: "Serra dos Tucanos and Itatiaia (Atlantic Forest)", text: "Feeders and trails designed for photography, with endemics and dense hummingbird activity." },
        { title: "Intervales and Ubatuba (São Paulo Atlantic Forest)", text: "Among the country's best strongholds for bare-throated bellbird and black-fronted piping guan, with primary forest trails and vocalisation specialists." },
        { title: "Chapada dos Guimarães and the Pantanal", text: "Cerrado meets floodplain: jabirus, hyacinth macaws, herons, storks and one of the continent's largest raptor concentrations." },
        { title: "Boa Nova (Caatinga) and Emas National Park", text: "Boa Nova protects one of the last wild populations of Lear's macaw; Emas delivers open-country birds like the red-legged seriema, with giant anteaters as a bonus." },
        { title: "Marajó Island and Fernando de Noronha", text: "Marajó, with flooded grasslands and scarlet ibis colonies; Noronha, an oceanic archipelago with boobies, frigatebirds and white-tailed tropicbirds, easily seen from the coast." },
      ],
    },
    stays: {
      heading: "Lodges and bases for birdwatchers",
      intro: "Addresses built — or adapted — for serious bird observation.",
      items: [
        { name: "Cristalino Lodge", profile: "Serious birders and photographers", text: "Canopy towers, exclusive trails and resident guides expert in call identification." },
        { name: "Serra dos Tucanos Lodge", profile: "Atlantic Forest photographers", text: "Feeders near the rooms and short trails to endemic species." },
        { name: "Caiman Ecological Refuge (Pantanal)", profile: "General wildlife observers", text: "Hyacinth macaw conservation programme integrated with waterbird outings." },
        { name: "Partner lodges in Boa Nova", profile: "Endemic specialists", text: "Local guides who track the Lear's macaw population daily." },
        { name: "Lodges in Fernando de Noronha", profile: "Seabird observers", text: "Coastal trails minutes from booby and frigatebird colonies." },
      ],
    },
    profiles: {
      heading: "Who a Brazil birding itinerary suits",
      items: [
        { title: "Experienced birders with an international list", text: "Itineraries combining Amazon, Pantanal and Atlantic Forest deliver a very high number of new species per trip." },
        { title: "Nature photographers", text: "Serra dos Tucanos and Cristalino offer infrastructure built for photography, with feeders and hides." },
        { title: "Couples with general wildlife interest", text: "The Pantanal pairs birding with jaguars, capybaras and caimans, requiring no prior technical knowledge." },
      ],
    },
    itinerary: {
      heading: "How to build a birdwatching itinerary in Brazil",
      intro: "Few countries let you combine so many bird biomes in one trip — Brazil's domestic flight network makes it feasible.",
      items: [
        { title: "Amazon + Pantanal — 12 days", text: "Cristalino Lodge followed by Caiman Refuge: canopy forest and floodplain at biodiversity's two extremes." },
        { title: "Full Atlantic Forest — 8 days", text: "Itatiaia, Serra dos Tucanos and Intervales in sequence, covering the biome's key endemics." },
        { title: "Caatinga and Cerrado — 7 days", text: "Boa Nova and Emas National Park, a rare itinerary few international birders attempt." },
        { title: "Noronha as a close — 4 days", text: "Seabirds, diving and decompression at the end of a more technical land-based birding trip." },
      ],
    },
    tips: {
      heading: "Practical tips for birdwatching in Brazil",
      items: [
        "Book specialist guides ahead — the best have busy calendars during peak months.",
        "Bring quality personal binoculars; lodge equipment doesn't always suit experienced birders.",
        "Neutral, unpatterned clothing helps avoid spooking shyer species.",
        "Call playback should be used sparingly and always guided by the local expert, respecting sensitive species.",
        "Dawn is peak activity time — plan outings before sunrise.",
        "Check vaccine and repellent requirements ahead of longer Amazon expeditions.",
      ],
    },
    faq: [
      { q: "How many bird species does Brazil have?", a: "Around 1,900 recorded species, the greatest bird diversity of any country in the world." },
      { q: "What is the best birdwatching destination in Brazil?", a: "It depends on the goal: Cristalino Lodge for Amazon canopy forest, the Pantanal for floodplain birds, and the Atlantic Forest for endemics." },
      { q: "Where can I see the Lear's macaw?", a: "In Boa Nova, Bahia, one of the last areas with a stable wild population of this endangered species." },
      { q: "Do I need prior experience for a birding itinerary?", a: "No — Pantanal and Amazon itineraries work well for beginners, always with a specialist guide." },
      { q: "What is the best time to birdwatch in Brazil?", a: "May to September for the Pantanal and dry Amazon; September to December for Atlantic Forest breeding season." },
      { q: "Can birdwatching be combined with other wildlife interests?", a: "Yes — the Pantanal in particular combines birding with jaguars, capybaras and caimans in the same itinerary." },
    ],
    cta: { heading: "Let's design your birdwatching itinerary", subheading: "A human consultant at Create Travel connects you with Brazil's best specialist guides and lodges.", button: "Talk to a travel designer" },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },

  es: {
    destinationName: "Aves de Brasil",
    blurb: "Guía de observación de aves por Brasil: casi 1.900 especies, de Cristalino al Pantanal, de la Caatinga a Noronha.",
    metaTitle: "Aves de Brasil: guía de birdwatching y dónde observarlas",
    metaDescription: "Guía de observación de aves en Brasil: endemismos, mejores meses, lodges especializados e itinerarios desde Cristalino hasta el Pantanal, de la Mata Atlántica a Noronha.",
    keywords: "aves de brasil, birdwatching brasil, cristalino lodge aves, guacamayo de lear, jabirú pantanal, serra dos tucanos, itatiaia aves, observación de aves brasil",
    h1: "Aves de Brasil: un país con casi 1.900 especies catalogadas",
    aiAnswer: "Brasil reúne cerca de 1.900 especies de aves, más que cualquier otro país; los mejores destinos son Cristalino Lodge y Alta Floresta (Amazonia), Itatiaia y Serra dos Tucanos (Mata Atlántica), Chapada dos Guimarães y el Pantanal, y Boa Nova en la Caatinga para el raro guacamayo de Lear.",
    intro: [
      "Con casi 1.900 especies registradas, Brasil tiene la mayor diversidad de aves del planeta, por delante de Colombia y Perú. Esta riqueza se extiende por biomas tan distintos que ningún itinerario único la agota: cada uno tiene sus endemismos, sus guías especialistas, su estación ideal.",
      "Esta guía nace de expediciones junto a ornitólogos y guías de campo, no de listas genéricas. Aquí están los lugares que realmente entregan las especies más buscadas, los meses de mayor actividad y el nivel de exigencia de cada itinerario.",
    ],
    seasons: {
      heading: "Mejores meses para observar aves en Brasil",
      intro: "Cada región tiene su ventana óptima, casi siempre ligada a la reproducción o al nivel de los ríos.",
      windows: [
        { window: "Mayo a septiembre — sequía amazónica y Pantanal", text: "Ríos bajos concentran aves de várzea y sabana; en el Pantanal es la mejor época para jabirús, guacamayos azules y la mayor densidad de aves acuáticas del continente." },
        { window: "Septiembre a diciembre — reproducción en la Mata Atlántica", text: "Cantos territoriales en su apogeo, excelente visibilidad de aves endémicas en Itatiaia, Serra dos Tucanos e Intervales." },
        { window: "Octubre a marzo — Caatinga y guacamayo de Lear", text: "Tras las primeras lluvias, sube la actividad reproductiva en Boa Nova; buen período también para las aves de Emas y el Cerrado." },
        { window: "Todo el año — Cristalino y Fernando de Noronha", text: "Cristalino ofrece observación de alto nivel todo el año; Noronha entrega aves marinas oceánicas con constancia, con pico de nidificación entre septiembre y marzo." },
      ],
    },
    experiences: {
      heading: "Dónde observar las aves más buscadas de Brasil",
      intro: "Selección por bioma y especie objetivo, siempre con guías especializados de campo.",
      items: [
        { title: "Cristalino Lodge y Alta Floresta", text: "Más de 600 especies registradas, torres de dosel a 50 metros y senderos exclusivos. Referencia mundial para aves y águilas harpías." },
        { title: "Presidente Figueiredo (Amazonas)", text: "Cascadas y bosque de tierra firme cerca de Manaos, con buena chance de gallito de las rocas en un itinerario más corto." },
        { title: "Serra dos Tucanos e Itatiaia (Mata Atlántica)", text: "Comederos y senderos diseñados para fotografía, con especies endémicas y alta densidad de colibríes." },
        { title: "Intervales y Ubatuba (Mata Atlántica paulista)", text: "Uno de los mejores refugios del país para aves endémicas amenazadas, con senderos de bosque primario." },
        { title: "Chapada dos Guimarães y Pantanal", text: "Transición de Cerrado y planicie inundada: jabirús, guacamayos azules, garzas y una de las mayores concentraciones de rapaces del continente." },
        { title: "Boa Nova (Caatinga) y Parque de las Emas", text: "Boa Nova protege una de las últimas poblaciones silvestres del guacamayo de Lear; Emas entrega aves de campo abierto y osos hormigueros como bono." },
        { title: "Isla de Marajó y Fernando de Noronha", text: "Marajó, con campos inundados y colonias de ibis escarlata; Noronha, archipiélago oceánico con piqueros y fragatas de fácil observación costera." },
      ],
    },
    stays: {
      heading: "Lodges y bases para observadores de aves",
      intro: "Direcciones diseñadas —o adaptadas— para observación seria de aves.",
      items: [
        { name: "Cristalino Lodge", profile: "Birders serios y fotógrafos", text: "Torres de dosel, senderos exclusivos y guías residentes expertos en identificación por canto." },
        { name: "Serra dos Tucanos Lodge", profile: "Fotógrafos de Mata Atlántica", text: "Comederos cerca de las habitaciones y senderos cortos hacia especies endémicas." },
        { name: "Refugio Ecológico Caiman (Pantanal)", profile: "Observadores de fauna en general", text: "Programa de conservación del guacamayo azul integrado a paseos de observación de aves acuáticas." },
        { name: "Posadas asociadas en Boa Nova", profile: "Especialistas en endemismos", text: "Guías locales que siguen diariamente la población del guacamayo de Lear." },
        { name: "Posadas en Fernando de Noronha", profile: "Observadores de aves marinas", text: "Senderos costeros a minutos de colonias de piqueros y fragatas." },
      ],
    },
    profiles: {
      heading: "Para quién funciona un itinerario de aves por Brasil",
      items: [
        { title: "Birders experimentados con lista internacional", text: "Itinerarios que combinan Amazonia, Pantanal y Mata Atlántica entregan un número muy alto de especies nuevas por viaje." },
        { title: "Fotógrafos de naturaleza", text: "Serra dos Tucanos y Cristalino ofrecen infraestructura pensada para foto, con comederos y escondites." },
        { title: "Parejas con interés general en fauna", text: "El Pantanal combina aves con jaguares, capibaras y yacarés, sin exigir conocimiento técnico previo." },
      ],
    },
    itinerary: {
      heading: "Cómo armar un itinerario de observación de aves en Brasil",
      intro: "Pocos países permiten combinar tantos biomas de aves en un solo viaje: la red aérea interna de Brasil lo hace viable.",
      items: [
        { title: "Amazonia + Pantanal — 12 días", text: "Cristalino Lodge seguido de Refugio Caiman: bosque de dosel y planicie inundada en los dos extremos de biodiversidad." },
        { title: "Mata Atlántica completa — 8 días", text: "Itatiaia, Serra dos Tucanos e Intervales en secuencia, cubriendo los principales endemismos del bioma." },
        { title: "Caatinga y Cerrado — 7 días", text: "Boa Nova y Parque de las Emas, itinerario raro que pocos birders internacionales realizan." },
        { title: "Noronha como cierre — 4 días", text: "Aves marinas, buceo y descompresión al final de un itinerario más técnico de observación terrestre." },
      ],
    },
    tips: {
      heading: "Consejos prácticos para observar aves en Brasil",
      items: [
        "Reserve guías especializados con antelación: los mejores tienen agenda ocupada en los meses pico.",
        "Lleve binoculares propios de calidad; el equipo del lodge no siempre satisface a birders experimentados.",
        "Ropa neutra y sin estampados ayuda a no espantar especies más tímidas.",
        "El playback de canto debe usarse con moderación y siempre guiado por el experto local.",
        "El amanecer es el horario de mayor actividad: planifique salidas antes de la salida del sol.",
        "Verifique requisitos de vacunas y repelente antes de expediciones amazónicas más largas.",
      ],
    },
    faq: [
      { q: "¿Cuántas especies de aves hay en Brasil?", a: "Cerca de 1.900 especies catalogadas, la mayor diversidad de aves de cualquier país del mundo." },
      { q: "¿Cuál es el mejor lugar de Brasil para birdwatching?", a: "Depende del objetivo: Cristalino Lodge para bosque amazónico de dosel, Pantanal para aves de planicie inundada y Mata Atlántica para endemismos." },
      { q: "¿Dónde ver el guacamayo de Lear?", a: "En Boa Nova, Bahía, una de las últimas áreas con población silvestre estable de esta especie amenazada." },
      { q: "¿Necesito experiencia previa para un itinerario de aves?", a: "No: los itinerarios en el Pantanal y la Amazonia funcionan bien para principiantes, siempre con guía especializado." },
      { q: "¿Cuál es la mejor época para observar aves en Brasil?", a: "Mayo a septiembre para Pantanal y Amazonia seca; septiembre a diciembre para la reproducción en la Mata Atlántica." },
      { q: "¿Se puede combinar birdwatching con otros intereses de fauna?", a: "Sí: el Pantanal en particular combina observación de aves con jaguares, capibaras y yacarés en el mismo itinerario." },
    ],
    cta: { heading: "Diseñemos su itinerario de observación de aves", subheading: "Un consultor humano de Create Travel lo conecta con los mejores guías y lodges especializados de Brasil.", button: "Hablar con un travel designer" },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },

  it: {
    destinationName: "Uccelli del Brasile",
    blurb: "Una guida al birdwatching in Brasile: quasi 1.900 specie, da Cristalino al Pantanal, dalla Caatinga a Noronha.",
    metaTitle: "Uccelli del Brasile: guida al birdwatching e dove osservarli",
    metaDescription: "Guida al birdwatching in Brasile: specie endemiche, mesi migliori, lodge specializzati e itinerari da Cristalino al Pantanal, dalla Mata Atlântica a Noronha.",
    keywords: "uccelli del brasile, birdwatching brasile, cristalino lodge birding, arara di lear, jabiru pantanal, serra dos tucanos, itatiaia birding, tour birdwatching brasile",
    h1: "Uccelli del Brasile: un paese con quasi 1.900 specie registrate",
    aiAnswer: "Il Brasile conta circa 1.900 specie di uccelli registrate, più di ogni altro paese; le mete migliori sono Cristalino Lodge e Alta Floresta (Amazzonia), Itatiaia e Serra dos Tucanos (Mata Atlântica), Chapada dos Guimarães e il Pantanal, e Boa Nova nella Caatinga per la rara arara di Lear.",
    intro: [
      "Con quasi 1.900 specie registrate, il Brasile ha la maggiore diversità di uccelli al mondo, davanti a Colombia e Perù. Questa ricchezza si estende su biomi così diversi che nessun singolo itinerario la esaurisce mai: ognuno ha i propri endemismi, le proprie guide specializzate, la propria stagione ideale.",
      "Questa guida nasce da spedizioni con ornitologi e guide di campo, non da liste generiche. Ecco i luoghi che offrono davvero le specie più ricercate, i mesi di massima attività e il livello di impegno di ciascun itinerario.",
    ],
    seasons: {
      heading: "Mesi migliori per il birdwatching in Brasile",
      intro: "Ogni regione ha la sua finestra ottimale, quasi sempre legata alla riproduzione o al livello dei fiumi.",
      windows: [
        { window: "Maggio a settembre — stagione secca amazzonica e Pantanal", text: "I fiumi bassi concentrano gli uccelli di várzea e savana; nel Pantanal è il periodo migliore per jabiru, are giacinto e la maggiore densità di uccelli acquatici del continente." },
        { window: "Settembre a dicembre — riproduzione nella Mata Atlântica", text: "Canti territoriali al culmine, ottima visibilità di specie endemiche a Itatiaia, Serra dos Tucanos e Intervales." },
        { window: "Ottobre a marzo — Caatinga e arara di Lear", text: "Dopo le prime piogge, l'attività riproduttiva aumenta a Boa Nova; buon periodo anche per gli uccelli di Emas e del Cerrado." },
        { window: "Tutto l'anno — Cristalino e Fernando de Noronha", text: "Cristalino offre birdwatching di alto livello tutto l'anno; Noronha regala uccelli marini con costanza, con picco di nidificazione tra settembre e marzo." },
      ],
    },
    experiences: {
      heading: "Dove osservare gli uccelli più ricercati del Brasile",
      intro: "Selezione per bioma e specie target, sempre con guide di campo specializzate.",
      items: [
        { title: "Cristalino Lodge e Alta Floresta", text: "Oltre 600 specie registrate, torri di dossale a 50 metri e sentieri esclusivi. Riferimento mondiale per uccelli e aquile arpie." },
        { title: "Presidente Figueiredo (Amazonas)", text: "Cascate e foresta di terra ferma vicino a Manaus, con buone probabilità di avvistare il gallo delle rocce in un itinerario più breve." },
        { title: "Serra dos Tucanos e Itatiaia (Mata Atlântica)", text: "Mangiatoie e sentieri pensati per la fotografia, con specie endemiche e alta densità di colibrì." },
        { title: "Intervales e Ubatuba (Mata Atlântica paulista)", text: "Uno dei migliori rifugi del paese per specie endemiche minacciate, con sentieri di foresta primaria." },
        { title: "Chapada dos Guimarães e Pantanal", text: "Transizione tra Cerrado e pianura allagata: jabiru, are giacinto, aironi e una delle maggiori concentrazioni di rapaci del continente." },
        { title: "Boa Nova (Caatinga) e Parco delle Emas", text: "Boa Nova protegge una delle ultime popolazioni selvatiche di arara di Lear; Emas offre uccelli di campo aperto e formichieri giganti come bonus." },
        { title: "Isola di Marajó e Fernando de Noronha", text: "Marajó, con campi allagati e colonie di ibis scarlatto; Noronha, arcipelago oceanico con sule e fregate facilmente osservabili dalla costa." },
      ],
    },
    stays: {
      heading: "Lodge e basi per birdwatcher",
      intro: "Indirizzi progettati — o adattati — per una seria osservazione degli uccelli.",
      items: [
        { name: "Cristalino Lodge", profile: "Birder seri e fotografi", text: "Torri di dossale, sentieri esclusivi e guide residenti esperte nell'identificazione tramite canto." },
        { name: "Serra dos Tucanos Lodge", profile: "Fotografi della Mata Atlântica", text: "Mangiatoie vicino alle camere e sentieri brevi verso specie endemiche." },
        { name: "Rifugio Ecologico Caiman (Pantanal)", profile: "Osservatori di fauna in generale", text: "Programma di conservazione dell'ara giacinto integrato con uscite di osservazione di uccelli acquatici." },
        { name: "Pousadas partner a Boa Nova", profile: "Specialisti in endemismi", text: "Guide locali che seguono quotidianamente la popolazione dell'arara di Lear." },
        { name: "Pousadas a Fernando de Noronha", profile: "Osservatori di uccelli marini", text: "Sentieri costieri a pochi minuti da colonie di sule e fregate." },
      ],
    },
    profiles: {
      heading: "Per chi funziona un itinerario di birdwatching in Brasile",
      items: [
        { title: "Birder esperti con lista internazionale", text: "Itinerari che combinano Amazzonia, Pantanal e Mata Atlântica offrono un altissimo numero di nuove specie per viaggio." },
        { title: "Fotografi di natura", text: "Serra dos Tucanos e Cristalino offrono infrastrutture pensate per la fotografia, con mangiatoie e capanni." },
        { title: "Coppie con interesse generale per la fauna", text: "Il Pantanal abbina il birdwatching a giaguari, capibara e caimani, senza richiedere conoscenze tecniche pregresse." },
      ],
    },
    itinerary: {
      heading: "Come costruire un itinerario di birdwatching in Brasile",
      intro: "Pochi paesi permettono di combinare così tanti biomi di uccelli in un solo viaggio: la rete aerea interna del Brasile lo rende possibile.",
      items: [
        { title: "Amazzonia + Pantanal — 12 giorni", text: "Cristalino Lodge seguito dal Rifugio Caiman: foresta di dossale e pianura allagata ai due estremi della biodiversità." },
        { title: "Mata Atlântica completa — 8 giorni", text: "Itatiaia, Serra dos Tucanos e Intervales in sequenza, coprendo i principali endemismi del bioma." },
        { title: "Caatinga e Cerrado — 7 giorni", text: "Boa Nova e Parco delle Emas, itinerario raro che pochi birder internazionali affrontano." },
        { title: "Noronha come chiusura — 4 giorni", text: "Uccelli marini, immersioni e decompressione alla fine di un itinerario più tecnico di osservazione terrestre." },
      ],
    },
    tips: {
      heading: "Consigli pratici per il birdwatching in Brasile",
      items: [
        "Prenotate guide specializzate in anticipo: le migliori hanno agende piene nei mesi di punta.",
        "Portate un binocolo personale di qualità; l'attrezzatura del lodge non sempre soddisfa i birder esperti.",
        "Abiti neutri e senza stampe aiutano a non spaventare le specie più timide.",
        "Il playback dei canti va usato con moderazione e sempre guidato dall'esperto locale.",
        "L'alba è l'orario di massima attività: pianificate le uscite prima del sorgere del sole.",
        "Verificate i requisiti di vaccino e repellente prima di spedizioni amazzoniche più lunghe.",
      ],
    },
    faq: [
      { q: "Quante specie di uccelli ci sono in Brasile?", a: "Circa 1.900 specie catalogate, la maggiore diversità di uccelli di qualsiasi paese al mondo." },
      { q: "Qual è il posto migliore in Brasile per il birdwatching?", a: "Dipende dall'obiettivo: Cristalino Lodge per la foresta amazzonica di dossale, il Pantanal per gli uccelli di pianura allagata e la Mata Atlântica per gli endemismi." },
      { q: "Dove vedere l'arara di Lear?", a: "A Boa Nova, in Bahia, una delle ultime aree con una popolazione selvatica stabile di questa specie minacciata." },
      { q: "Serve esperienza pregressa per un itinerario di birdwatching?", a: "No: gli itinerari in Pantanal e Amazzonia funzionano bene per principianti, sempre con guida specializzata." },
      { q: "Qual è il periodo migliore per il birdwatching in Brasile?", a: "Maggio a settembre per Pantanal e Amazzonia secca; settembre a dicembre per la riproduzione nella Mata Atlântica." },
      { q: "Si può combinare il birdwatching con altri interessi faunistici?", a: "Sì: il Pantanal in particolare combina birdwatching con giaguari, capibara e caimani nello stesso itinerario." },
    ],
    cta: { heading: "Progettiamo il vostro itinerario di birdwatching", subheading: "Un consulente umano di Create Travel vi collega alle migliori guide e lodge specializzati del Brasile.", button: "Parla con un travel designer" },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },

  de: {
    destinationName: "Vögel Brasiliens",
    blurb: "Ein Birdwatching-Guide durch Brasilien: fast 1.900 Arten, von Cristalino bis zum Pantanal, von der Caatinga bis Noronha.",
    metaTitle: "Vögel Brasiliens: Birdwatching-Guide und wo man sie findet",
    metaDescription: "Ein kuratierter Birdwatching-Guide zu Brasilien: Endemismen, beste Monate, spezialisierte Lodges und Routen von Cristalino bis zum Pantanal, vom Atlantischen Regenwald bis Noronha.",
    keywords: "vögel brasiliens, birdwatching brasilien, cristalino lodge vögel, hyazinth ara pantanal, jabiru pantanal, serra dos tucanos, itatiaia birding, brasilien vogelbeobachtung",
    h1: "Vögel Brasiliens: ein Land mit fast 1.900 erfassten Arten",
    aiAnswer: "Brasilien zählt rund 1.900 erfasste Vogelarten, mehr als jedes andere Land; die besten Ziele sind Cristalino Lodge und Alta Floresta (Amazonas), Itatiaia und Serra dos Tucanos (Atlantischer Regenwald), Chapada dos Guimarães und das Pantanal sowie Boa Nova in der Caatinga für den seltenen Lear-Ara.",
    intro: [
      "Mit fast 1.900 erfassten Arten besitzt Brasilien die größte Vogelvielfalt der Welt — vor Kolumbien und Peru. Dieser Reichtum erstreckt sich über so unterschiedliche Biome, dass keine einzelne Route ihn je ausschöpft: jedes hat seine eigenen Endemismen, seine Spezialführer, seine ideale Saison.",
      "Dieser Guide entstand aus Expeditionen mit Ornithologen und Feldführern, nicht aus generischen Listen. Hier sind die Orte, die die begehrtesten Arten wirklich liefern, die Monate höchster Aktivität und der Anspruch jeder Route.",
    ],
    seasons: {
      heading: "Beste Monate für Vogelbeobachtung in Brasilien",
      intro: "Jede Region hat ihr optimales Zeitfenster, meist verbunden mit Brutzeit oder Flusspegel.",
      windows: [
        { window: "Mai bis September — Amazonas-Trockenzeit und Pantanal", text: "Niedrige Flusspegel konzentrieren Überschwemmungs- und Savannenvögel; im Pantanal die beste Zeit für Jabirus, Hyazinth-Aras und die dichteste Wasservogelkonzentration des Kontinents." },
        { window: "September bis Dezember — Brutzeit im Atlantischen Regenwald", text: "Reviergesänge auf ihrem Höhepunkt, hervorragende Sichtbarkeit endemischer Arten in Itatiaia, Serra dos Tucanos und Intervales." },
        { window: "Oktober bis März — Caatinga und Lear-Ara", text: "Nach den ersten Regenfällen steigt die Brutaktivität in Boa Nova; auch gutes Fenster für Vögel in Emas und im Cerrado." },
        { window: "Ganzjährig — Cristalino und Fernando de Noronha", text: "Cristalino bietet ganzjährig Birding auf höchstem Niveau; Noronha liefert verlässlich Seevögel, mit Nistgipfel zwischen September und März." },
      ],
    },
    experiences: {
      heading: "Wo man Brasiliens begehrteste Vögel findet",
      intro: "Kuratiert nach Biom und Zielart, immer mit spezialisierten Feldführern.",
      items: [
        { title: "Cristalino Lodge und Alta Floresta", text: "Über 600 erfasste Arten, 50 Meter hohe Kronendachtürme und exklusive Wege. Weltweite Referenz für Vögel und Harpyien." },
        { title: "Presidente Figueiredo (Amazonas)", text: "Wasserfälle und Terra-firme-Wald nahe Manaus, mit guten Chancen auf den Felsenhahn auf einer kürzeren Route." },
        { title: "Serra dos Tucanos und Itatiaia (Atlantischer Regenwald)", text: "Futterstellen und Wege, die für Fotografie konzipiert sind, mit endemischen Arten und hoher Kolibri-Dichte." },
        { title: "Intervales und Ubatuba (Atlantischer Regenwald São Paulos)", text: "Eines der besten Rückzugsgebiete des Landes für bedrohte endemische Arten, mit Wegen durch Primärwald." },
        { title: "Chapada dos Guimarães und Pantanal", text: "Übergang von Cerrado zu Überschwemmungsebene: Jabirus, Hyazinth-Aras, Reiher und eine der größten Greifvogelkonzentrationen des Kontinents." },
        { title: "Boa Nova (Caatinga) und Emas-Nationalpark", text: "Boa Nova schützt eine der letzten wilden Populationen des Lear-Aras; Emas bietet Offenland-Vögel und Große Ameisenbären als Bonus." },
        { title: "Marajó-Insel und Fernando de Noronha", text: "Marajó mit überfluteten Feldern und Rotem-Ibis-Kolonien; Noronha, ein ozeanischer Archipel mit Tölpeln und Fregattvögeln, leicht von der Küste aus zu beobachten." },
      ],
    },
    stays: {
      heading: "Lodges und Basen für Birdwatcher",
      intro: "Adressen, die für ernsthafte Vogelbeobachtung gebaut — oder angepasst — wurden.",
      items: [
        { name: "Cristalino Lodge", profile: "Ernsthafte Birder und Fotografen", text: "Kronendachtürme, exklusive Wege und ansässige Führer, Experten für Ruf-Identifikation." },
        { name: "Serra dos Tucanos Lodge", profile: "Fotografen des Atlantischen Regenwaldes", text: "Futterstellen nahe den Zimmern und kurze Wege zu endemischen Arten." },
        { name: "Caiman Ökologisches Reservat (Pantanal)", profile: "Allgemeine Wildtierbeobachter", text: "Hyazinth-Ara-Schutzprogramm integriert mit Wasservogel-Ausflügen." },
        { name: "Partner-Pousadas in Boa Nova", profile: "Endemismus-Spezialisten", text: "Lokale Führer, die die Lear-Ara-Population täglich begleiten." },
        { name: "Pousadas auf Fernando de Noronha", profile: "Seevogel-Beobachter", text: "Küstenwege, wenige Minuten von Tölpel- und Fregattvogelkolonien entfernt." },
      ],
    },
    profiles: {
      heading: "Für wen eine Brasilien-Birding-Route passt",
      items: [
        { title: "Erfahrene Birder mit internationaler Liste", text: "Routen, die Amazonas, Pantanal und Atlantischen Regenwald kombinieren, liefern eine sehr hohe Anzahl neuer Arten pro Reise." },
        { title: "Naturfotografen", text: "Serra dos Tucanos und Cristalino bieten für Fotografie konzipierte Infrastruktur mit Futterstellen und Verstecken." },
        { title: "Paare mit allgemeinem Interesse an Wildtieren", text: "Das Pantanal verbindet Vogelbeobachtung mit Jaguaren, Wasserschweinen und Kaimanen, ohne Vorkenntnisse zu erfordern." },
      ],
    },
    itinerary: {
      heading: "Wie man eine Birding-Route durch Brasilien plant",
      intro: "Wenige Länder erlauben es, so viele Vogelbiome in einer Reise zu kombinieren — Brasiliens inländisches Flugnetz macht es möglich.",
      items: [
        { title: "Amazonas + Pantanal — 12 Tage", text: "Cristalino Lodge gefolgt von Caiman-Reservat: Kronendachwald und Überschwemmungsebene an den beiden Extremen der Biodiversität." },
        { title: "Kompletter Atlantischer Regenwald — 8 Tage", text: "Itatiaia, Serra dos Tucanos und Intervales nacheinander, die wichtigsten Endemismen des Bioms abdeckend." },
        { title: "Caatinga und Cerrado — 7 Tage", text: "Boa Nova und Emas-Nationalpark, eine seltene Route, die nur wenige internationale Birder unternehmen." },
        { title: "Noronha als Abschluss — 4 Tage", text: "Seevögel, Tauchen und Entspannung am Ende einer technischeren Land-Birding-Route." },
      ],
    },
    tips: {
      heading: "Praktische Tipps für Vogelbeobachtung in Brasilien",
      items: [
        "Buchen Sie Spezialführer im Voraus — die besten haben in den Spitzenmonaten volle Terminkalender.",
        "Bringen Sie ein hochwertiges eigenes Fernglas mit; Lodge-Ausrüstung genügt erfahrenen Birdern nicht immer.",
        "Neutrale, unauffällige Kleidung hilft, scheuere Arten nicht zu verschrecken.",
        "Ruf-Playback sollte sparsam und immer unter Anleitung des lokalen Experten eingesetzt werden.",
        "Morgengrauen ist die Zeit höchster Aktivität — planen Sie Ausflüge vor Sonnenaufgang.",
        "Prüfen Sie Impf- und Repellent-Anforderungen vor längeren Amazonas-Expeditionen.",
      ],
    },
    faq: [
      { q: "Wie viele Vogelarten gibt es in Brasilien?", a: "Etwa 1.900 erfasste Arten, die größte Vogelvielfalt jedes Landes der Welt." },
      { q: "Was ist der beste Ort in Brasilien für Vogelbeobachtung?", a: "Kommt aufs Ziel an: Cristalino Lodge für Amazonas-Kronendachwald, Pantanal für Überschwemmungsvögel, Atlantischer Regenwald für Endemismen." },
      { q: "Wo kann man den Lear-Ara sehen?", a: "In Boa Nova, Bahia, eines der letzten Gebiete mit stabiler Wildpopulation dieser bedrohten Art." },
      { q: "Braucht man Vorerfahrung für eine Birding-Route?", a: "Nein — Routen im Pantanal und Amazonas funktionieren gut für Anfänger, immer mit spezialisiertem Führer." },
      { q: "Was ist die beste Zeit für Vogelbeobachtung in Brasilien?", a: "Mai bis September für Pantanal und trockenen Amazonas; September bis Dezember für die Brutzeit im Atlantischen Regenwald." },
      { q: "Kann man Vogelbeobachtung mit anderen Wildtierinteressen kombinieren?", a: "Ja — besonders das Pantanal verbindet Vogelbeobachtung mit Jaguaren, Wasserschweinen und Kaimanen in derselben Route." },
    ],
    cta: { heading: "Lassen Sie uns Ihre Birding-Route gestalten", subheading: "Ein menschlicher Berater von Create Travel verbindet Sie mit Brasiliens besten Spezialführern und Lodges.", button: "Mit einem Travel Designer sprechen" },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },
};
