import type { BrazilGuideLocalized } from "./types";

export const conjugadoAmazoniaPantanalGuide: BrazilGuideLocalized = {
  pt: {
    destinationName: "Amazônia + Pantanal",
    blurb: "Floresta e planície alagada em uma só viagem: os dois grandes santuários de fauna do Brasil, de 12 a 14 noites.",
    metaTitle: "Amazônia + Pantanal: roteiro conjugado de 12 a 14 noites",
    metaDescription: "Como combinar Manaus/Rio Negro e a Transpantaneira/Porto Jofre em uma única viagem: melhor janela (julho a outubro), voos via Brasília ou São Paulo, fauna complementar e número de noites por trecho.",
    keywords: "amazonia e pantanal roteiro, viagem amazonia pantanal, transpantaneira porto jofre, rio negro anavilhanas, melhor epoca amazonia pantanal, onca pintada pantanal, roteiro fauna brasil",
    h1: "Amazônia + Pantanal: o roteiro conjugado dos dois grandes biomas de fauna do Brasil",
    aiAnswer: "O melhor roteiro para combinar Amazônia e Pantanal dura de 12 a 14 noites, com 4 a 5 noites de floresta em Manaus/Rio Negro e 5 a 7 noites de planície alagada em Cuiabá/Transpantaneira/Porto Jofre, na janela de julho a outubro (seca em ambos os biomas), com conexão aérea via Brasília ou São Paulo.",
    intro: [
      "Amazônia e Pantanal são frequentemente confundidos por quem nunca esteve no Brasil, mas são biomas opostos: um é floresta densa e fechada, o outro é savana alagada e aberta. Justamente por isso, combinados, formam o roteiro de fauna mais completo do país — o que se esconde na mata se revela na planície, e vice-versa.",
      "Este guia é conjugado por desenho: não trata os dois destinos separadamente, mas como uma única viagem de 12 a 14 noites, com a logística aérea, o número de noites por trecho e a janela climática que fazem os dois biomas funcionarem juntos sem perder o que cada um tem de melhor.",
    ],
    seasons: {
      heading: "A janela conjunta: julho a outubro",
      intro: "Amazônia e Pantanal têm calendários climáticos opostos ao longo do ano, mas se cruzam favoravelmente entre julho e outubro — e é nessa janela que recomendamos o roteiro conjugado.",
      windows: [
        { window: "Julho a agosto — vazante amazônica e início da seca pantaneira", text: "Na Amazônia, o rio começa a baixar e surgem os primeiros bancos de areia; no Pantanal, a seca começa a concentrar a fauna nas margens dos rios. Boa janela para começar pela floresta." },
        { window: "Setembro a outubro — seca em ambos os biomas", text: "O auge da temporada de onças na Transpantaneira coincide com a seca amazônica plena: praias de rio no Tapajós e no Rio Negro, e onças quase garantidas em Porto Jofre. É o mês mais recomendado do ano para o roteiro conjugado." },
        { window: "Novembro — transição, ainda viável", text: "Primeiras chuvas isoladas em ambos os biomas, mas a fauna pantaneira ainda está concentrada e a Amazônia ainda tem praias. Boa alternativa para quem não consegue viajar em setembro." },
        { window: "Dezembro a junho — evitar o roteiro conjugado", text: "O Pantanal enche e muitas estradas da Transpantaneira ficam intransitáveis; a Amazônia está em cheia, ótima para canoagem, mas sem sinergia de fauna com o Pantanal nesse período." },
      ],
    },
    experiences: {
      heading: "O que se vive em cada etapa",
      intro: "Cada bioma entrega experiências que o outro não tem — a viagem conjugada existe exatamente para reunir as duas.",
      items: [
        { title: "Rio Negro e Anavilhanas, Manaus (etapa 1)", text: "O maior arquipélago fluvial do mundo, água preta refletindo o céu, canoagem entre igarapés, botos-cor-de-rosa em Novo Airão e observação de aves e macacos no dossel da floresta." },
        { title: "Encontro das Águas e Manaus histórica (etapa 1)", text: "Os rios Negro e Solimões correndo lado a lado sem se misturar por seis quilômetros, visto de barco; à noite, o Teatro Amazonas e a gastronomia amazônica de tucupi e tambaqui." },
        { title: "Transpantaneira, de Cuiabá a Porto Jofre (etapa 2)", text: "145 km de estrada de terra com mais de cem pontes de madeira, atravessando fazendas onde capivaras, jacarés, tuiuiús e veados-campeiros aparecem a cada curva." },
        { title: "Rio Três Irmãos e Rio Cuiabá, Porto Jofre (etapa 2)", text: "A região com maior densidade de onças-pintadas do planeta, avistadas do barco nas margens dos rios entre junho e outubro — a probabilidade de avistamento aqui é a mais alta do mundo." },
        { title: "Fazendas-pousada do Pantanal Norte (etapa 2)", text: "Passeios a cavalo e de charrete entre bandos de araras-azuis e tuiuiús, cavalgadas ao amanhecer e observação noturna com holofote em busca de suçuaranas e tamanduás." },
      ],
    },
    stays: {
      heading: "Onde ficar em cada trecho",
      intro: "A base certa em cada bioma define o tipo de fauna que se vê e o conforto da viagem inteira.",
      items: [
        { name: "Anavilhanas Jungle Lodge (Rio Negro)", profile: "Primeira etapa, conforto e floresta", text: "Bangalôs voltados para o rio e guias de altíssimo nível — a base mais recomendada para quem inicia a viagem pela Amazônia." },
        { name: "Mirante do Gavião (Novo Airão)", profile: "Estadas curtas de alto padrão", text: "Arquitetura premiada à beira do Rio Negro, ideal para 2 a 3 noites antes de seguir ao Pantanal." },
        { name: "Pousadas fluviais de Porto Jofre", profile: "Observação intensiva de onças", text: "Bases flutuantes ou ribeirinhas com saídas de barco diárias ao amanhecer e ao entardecer, os horários de maior atividade das onças." },
        { name: "Fazendas-lodge da Transpantaneira", profile: "Pantanal terrestre e cavalgadas", text: "Propriedades históricas convertidas em pousadas de observação, com passeios a cavalo, charrete e safári noturno." },
        { name: "Hotéis de trânsito em Cuiabá", profile: "Noite de amortecimento", text: "Usados apenas para conexão segura entre o voo internacional/nacional e o trecho terrestre até a Transpantaneira." },
      ],
    },
    profiles: {
      heading: "Para quem funciona este roteiro conjugado",
      items: [
        { title: "Naturalistas e fotógrafos de vida selvagem", text: "O roteiro que mais retorna em qualidade de avistamento no Brasil: floresta fechada de um lado, planície aberta do outro." },
        { title: "Casais e pequenos grupos em viagem de referência", text: "Doze a catorze noites intensas, com pouco tempo de praia — ideal para quem já viajou muito e busca profundidade, não descanso." },
        { title: "Para quem talvez não funcione", text: "Viajantes com pouco tempo (menos de 10 dias) ou que buscam praia e descompressão devem escolher apenas um dos dois biomas, não os dois combinados." },
      ],
    },
    itinerary: {
      heading: "O encadeamento dia a dia: 13 noites de referência",
      intro: "A lógica do roteiro conjugado é sempre floresta primeiro, planície depois — a Amazônia exige mais adaptação ao calor úmido, e chegar descansado ao Pantanal rende mais avistamentos.",
      items: [
        { title: "Noites 1 a 5 — Manaus e Rio Negro", text: "Voo internacional ou doméstico até Manaus, uma noite de chegada na cidade e quatro noites de lodge no Rio Negro/Anavilhanas, com passeios de canoa, focagem noturna e banho com botos." },
        { title: "Trânsito — Manaus a Cuiabá via Brasília ou São Paulo", text: "Não há voo direto entre Manaus e Cuiabá com frequência diária; a conexão mais confiável passa por Brasília ou São Paulo, com duração total de viagem de 5 a 7 horas incluindo escala." },
        { title: "Noites 6 a 12 — Cuiabá, Transpantaneira e Porto Jofre", text: "Uma noite de chegada em Cuiabá, seguida de traslado terrestre de 3 a 4 horas pela Transpantaneira até fazendas-pousada intermediárias, e depois barco ou estrada até Porto Jofre para cinco a seis noites de observação intensiva de onças." },
        { title: "Noite 13 — Cuiabá, despedida", text: "Retorno terrestre a Cuiabá para pernoite de segurança antes do voo de saída, garantindo folga contra atrasos na estrada de terra." },
      ],
    },
    tips: {
      heading: "Dicas práticas para o roteiro conjugado",
      items: [
        "Reserve a conexão aérea Manaus–Cuiabá com folga: como passa por Brasília ou São Paulo, atrasos em um trecho afetam o outro.",
        "Vacina de febre amarela é exigida para a Amazônia e recomendada para o Pantanal — tome pelo menos dez dias antes do embarque.",
        "Leve roupas de cor neutra para o Pantanal (evite branco e cores vivas, que assustam a fauna) e roupas leves de manga longa para a Amazônia.",
        "Binóculo próprio é essencial nos dois biomas — no Pantanal, principalmente para aves como tuiuiús e araras a distância.",
        "A estrada da Transpantaneira é de terra e pode ficar difícil após chuvas fortes mesmo na estação seca; sempre reserve um dia de folga antes de voos de conexão.",
        "Setembro é o mês mais concorrido para hospedagem em Porto Jofre — reserve com pelo menos seis meses de antecedência.",
      ],
    },
    faq: [
      { q: "Quantas noites são necessárias para o roteiro Amazônia + Pantanal?", a: "De 12 a 14 noites, sendo 4 a 5 na Amazônia e 6 a 7 no Pantanal, incluindo noites de trânsito em Manaus e Cuiabá." },
      { q: "Qual é a melhor época para fazer as duas viagens juntas?", a: "Julho a outubro, quando ambos os biomas estão na estação seca — a Amazônia com praias de rio e o Pantanal com fauna concentrada nas margens." },
      { q: "Existe voo direto entre Manaus e Cuiabá?", a: "Não com frequência regular; a conexão mais confiável passa por Brasília ou São Paulo, somando de 5 a 7 horas de viagem total." },
      { q: "Onde a chance de ver onça-pintada é maior?", a: "Na região de Porto Jofre, no Pantanal, entre junho e outubro — a maior densidade de onças documentada no planeta. Na Amazônia, o avistamento de onças é raro." },
      { q: "É uma viagem fisicamente exigente?", a: "Moderada: caminhadas curtas e passeios de barco e 4x4 predominam sobre trekking pesado, mas o calor e a umidade em ambos os biomas pedem preparo para o clima." },
      { q: "Quanto custa este roteiro conjugado com a Create Travel?", a: "Não trabalhamos com valores de prateleira: o orçamento depende dos lodges, do número de noites e da época. Um consultor humano monta a proposta por escrito." },
    ],
    cta: { heading: "Vamos desenhar seu roteiro Amazônia + Pantanal", subheading: "Um consultor humano da Create Travel monta a logística aérea, os lodges e a janela certa para os dois biomas.", button: "Falar com um travel designer" },
    readingMinutes: 12,
    publishedAt: "2026-08-11",
  },

  en: {
    destinationName: "Amazon + Pantanal",
    blurb: "Rainforest and flooded plain in a single trip: Brazil's two great wildlife sanctuaries, over 12 to 14 nights.",
    metaTitle: "Amazon + Pantanal: A Combined 12–14 Night Itinerary",
    metaDescription: "How to combine Manaus/Rio Negro with the Transpantaneira/Porto Jofre in one trip: best window (July–October), flights via Brasília or São Paulo, complementary wildlife and nights per leg.",
    keywords: "amazon pantanal itinerary, combined amazon pantanal trip, transpantaneira porto jofre, rio negro anavilhanas, best time amazon pantanal, jaguar pantanal, brazil wildlife itinerary",
    h1: "Amazon + Pantanal: the combined itinerary of Brazil's two great wildlife biomes",
    aiAnswer: "The best itinerary combining the Amazon and the Pantanal lasts 12 to 14 nights: 4–5 nights of rainforest in Manaus/Rio Negro and 5–7 nights of flooded plain in Cuiabá/Transpantaneira/Porto Jofre, in the July–October window (dry season in both biomes), connecting via Brasília or São Paulo.",
    intro: [
      "The Amazon and the Pantanal are often confused by first-time visitors to Brazil, but they are opposite biomes: one dense, closed rainforest, the other open, flooded savanna. Combined, they form the country's most complete wildlife itinerary — what hides in the forest reveals itself on the plain, and vice versa.",
      "This guide is combined by design: it treats the two destinations not separately, but as a single 12-to-14-night trip, with the flight logistics, nights per leg and climate window that make both biomes work together without losing what each does best.",
    ],
    seasons: {
      heading: "The joint window: July to October",
      intro: "The Amazon and the Pantanal have opposite climate calendars through most of the year, but they overlap favorably between July and October — the window we recommend for the combined itinerary.",
      windows: [
        { window: "July to August — Amazon receding water, early Pantanal dry season", text: "In the Amazon, the river starts to drop and the first sandbanks appear; in the Pantanal, the dry season begins concentrating wildlife along riverbanks. A good window to start with the rainforest." },
        { window: "September to October — dry season in both biomes", text: "Peak jaguar season on the Transpantaneira coincides with full Amazon dry season: river beaches on the Tapajós and Rio Negro, and near-guaranteed jaguars at Porto Jofre. The most recommended month for the combined itinerary." },
        { window: "November — transition, still workable", text: "First isolated rains in both biomes, but Pantanal wildlife is still concentrated and the Amazon still has beaches. A good alternative for those who cannot travel in September." },
        { window: "December to June — avoid the combined itinerary", text: "The Pantanal floods and many Transpantaneira roads become impassable; the Amazon is at high water, great for canoeing, but with no wildlife synergy with the Pantanal in this period." },
      ],
    },
    experiences: {
      heading: "What each leg delivers",
      intro: "Each biome offers experiences the other lacks — the combined trip exists precisely to bring both together.",
      items: [
        { title: "Rio Negro & Anavilhanas, Manaus (leg 1)", text: "The world's largest river archipelago, black water mirroring the sky, canoeing through creeks, pink river dolphins in Novo Airão, and birds and monkeys in the canopy." },
        { title: "Meeting of Waters & historic Manaus (leg 1)", text: "The Negro and Solimões rivers running side by side without mixing for six kilometres, seen from a boat; at night, the Amazon Opera House and Amazonian cuisine of tucupi and tambaqui." },
        { title: "The Transpantaneira, Cuiabá to Porto Jofre (leg 2)", text: "145km of dirt road with over a hundred wooden bridges, crossing ranches where capybaras, caimans, jabiru storks and marsh deer appear at every bend." },
        { title: "Três Irmãos & Cuiabá rivers, Porto Jofre (leg 2)", text: "The highest jaguar density on the planet, spotted from boats along the riverbanks between June and October — the highest sighting probability in the world." },
        { title: "Northern Pantanal ranch lodges (leg 2)", text: "Horseback and cart rides among flocks of hyacinth macaws and jabiru storks, dawn rides and night spotlighting for pumas and anteaters." },
      ],
    },
    stays: {
      heading: "Where to stay on each leg",
      intro: "The right base in each biome determines the wildlife you see and the comfort of the entire trip.",
      items: [
        { name: "Anavilhanas Jungle Lodge (Rio Negro)", profile: "First leg, comfort and rainforest", text: "River-facing bungalows and top-tier guides — the most recommended base to start the trip in the Amazon." },
        { name: "Mirante do Gavião (Novo Airão)", profile: "Short high-end stays", text: "Award-winning architecture on the Rio Negro, ideal for 2–3 nights before heading to the Pantanal." },
        { name: "River guesthouses of Porto Jofre", profile: "Intensive jaguar watching", text: "Floating or riverside bases with daily boat outings at dawn and dusk, the peak jaguar activity hours." },
        { name: "Transpantaneira ranch lodges", profile: "Land-based Pantanal and horseback rides", text: "Historic properties converted into wildlife-watching guesthouses, with horseback, cart and night safari tours." },
        { name: "Transit hotels in Cuiabá", profile: "Buffer night", text: "Used only for a safe connection between the international/domestic flight and the ground leg to the Transpantaneira." },
      ],
    },
    profiles: {
      heading: "Who this combined itinerary suits",
      items: [
        { title: "Naturalists and wildlife photographers", text: "Brazil's highest-yield itinerary for sighting quality: closed forest on one side, open plain on the other." },
        { title: "Couples and small groups on a reference trip", text: "Twelve to fourteen intense nights, with little beach time — ideal for well-travelled guests seeking depth, not rest." },
        { title: "For whom this might not work", text: "Travellers with limited time (under 10 days) or seeking beach and decompression should choose only one biome, not both combined." },
      ],
    },
    itinerary: {
      heading: "Day-by-day flow: a 13-night reference plan",
      intro: "The logic of the combined itinerary is always rainforest first, plain after — the Amazon requires more adaptation to humid heat, and arriving rested in the Pantanal yields more sightings.",
      items: [
        { title: "Nights 1–5 — Manaus and Rio Negro", text: "International or domestic flight to Manaus, one arrival night in the city, and four lodge nights on the Rio Negro/Anavilhanas, with canoe outings, night spotting and dolphin swims." },
        { title: "Transit — Manaus to Cuiabá via Brasília or São Paulo", text: "There is no reliable daily direct flight between Manaus and Cuiabá; the most dependable connection runs via Brasília or São Paulo, totalling 5 to 7 hours including the layover." },
        { title: "Nights 6–12 — Cuiabá, Transpantaneira and Porto Jofre", text: "One arrival night in Cuiabá, followed by a 3–4 hour ground transfer along the Transpantaneira to intermediate ranch lodges, then boat or road to Porto Jofre for five to six nights of intensive jaguar watching." },
        { title: "Night 13 — Cuiabá, farewell", text: "Ground return to Cuiabá for a buffer night before departure, protecting against delays on the dirt road." },
      ],
    },
    tips: {
      heading: "Practical tips for the combined itinerary",
      items: [
        "Book the Manaus–Cuiabá connection with buffer time: since it routes through Brasília or São Paulo, a delay on one leg affects the other.",
        "Yellow fever vaccination is required for the Amazon and recommended for the Pantanal — take it at least ten days before departure.",
        "Wear neutral-colored clothing in the Pantanal (avoid white and bright colors, which spook wildlife) and lightweight long sleeves in the Amazon.",
        "Your own binoculars are essential in both biomes — in the Pantanal, especially for distant storks and macaws.",
        "The Transpantaneira dirt road can become difficult after heavy rain even in the dry season; always reserve a buffer day before connecting flights.",
        "September is the busiest month for lodging in Porto Jofre — book at least six months ahead.",
      ],
    },
    faq: [
      { q: "How many nights are needed for the Amazon + Pantanal itinerary?", a: "12 to 14 nights: 4–5 in the Amazon and 6–7 in the Pantanal, including transit nights in Manaus and Cuiabá." },
      { q: "What is the best time to do both trips together?", a: "July to October, when both biomes are in the dry season — the Amazon with river beaches, the Pantanal with concentrated wildlife along riverbanks." },
      { q: "Is there a direct flight between Manaus and Cuiabá?", a: "Not on a regular daily basis; the most reliable connection routes via Brasília or São Paulo, totalling 5 to 7 hours of travel." },
      { q: "Where is the chance of seeing a jaguar highest?", a: "The Porto Jofre region in the Pantanal, between June and October — the highest documented jaguar density on the planet. In the Amazon, jaguar sightings are rare." },
      { q: "Is this a physically demanding trip?", a: "Moderate: short walks, boat rides and 4x4 outings dominate over heavy trekking, but the heat and humidity in both biomes call for climate preparation." },
      { q: "How much does this combined itinerary cost with Create Travel?", a: "We do not work with fixed prices: budget depends on lodges, number of nights and season. A human consultant prepares a written proposal." },
    ],
    cta: { heading: "Let's design your Amazon + Pantanal itinerary", subheading: "A human consultant at Create Travel arranges the flight logistics, lodges and the right window for both biomes.", button: "Talk to a travel designer" },
    readingMinutes: 12,
    publishedAt: "2026-08-11",
  },

  es: {
    destinationName: "Amazonía + Pantanal",
    blurb: "Selva y planicie inundada en un solo viaje: los dos grandes santuarios de fauna de Brasil, de 12 a 14 noches.",
    metaTitle: "Amazonía + Pantanal: itinerario combinado de 12 a 14 noches",
    metaDescription: "Cómo combinar Manaos/Río Negro con la Transpantaneira/Porto Jofre en un solo viaje: mejor ventana (julio a octubre), vuelos vía Brasilia o São Paulo, fauna complementaria y noches por tramo.",
    keywords: "amazonia y pantanal itinerario, viaje combinado amazonia pantanal, transpantaneira porto jofre, rio negro anavilhanas, mejor epoca amazonia pantanal, jaguar pantanal, itinerario fauna brasil",
    h1: "Amazonía + Pantanal: el itinerario combinado de los dos grandes biomas de fauna de Brasil",
    aiAnswer: "El mejor itinerario para combinar la Amazonía y el Pantanal dura de 12 a 14 noches, con 4 a 5 noches de selva en Manaos/Río Negro y 5 a 7 noches de planicie inundada en Cuiabá/Transpantaneira/Porto Jofre, en la ventana de julio a octubre (seca en ambos biomas), con conexión aérea vía Brasilia o São Paulo.",
    intro: [
      "Amazonía y Pantanal suelen confundirse entre quienes nunca han estado en Brasil, pero son biomas opuestos: uno es selva densa y cerrada, el otro sabana inundada y abierta. Precisamente por eso, combinados, forman el itinerario de fauna más completo del país — lo que se esconde en la selva se revela en la llanura, y viceversa.",
      "Esta guía está pensada como combinada por diseño: no trata los dos destinos por separado, sino como un único viaje de 12 a 14 noches, con la logística aérea, el número de noches por tramo y la ventana climática que hacen que ambos biomas funcionen juntos sin perder lo mejor de cada uno.",
    ],
    seasons: {
      heading: "La ventana conjunta: julio a octubre",
      intro: "Amazonía y Pantanal tienen calendarios climáticos opuestos durante gran parte del año, pero se cruzan favorablemente entre julio y octubre — y es en esa ventana que recomendamos el itinerario combinado.",
      windows: [
        { window: "Julio a agosto — vaciante amazónica e inicio de la seca pantanera", text: "En la Amazonía, el río empieza a bajar y aparecen los primeros bancos de arena; en el Pantanal, la seca comienza a concentrar la fauna en las orillas de los ríos. Buena ventana para empezar por la selva." },
        { window: "Septiembre a octubre — seca en ambos biomas", text: "El auge de la temporada de jaguares en la Transpantaneira coincide con la seca amazónica plena: playas de río en el Tapajós y el Río Negro, y jaguares casi garantizados en Porto Jofre. El mes más recomendado del año para el itinerario combinado." },
        { window: "Noviembre — transición, aún viable", text: "Primeras lluvias aisladas en ambos biomas, pero la fauna pantanera sigue concentrada y la Amazonía aún tiene playas. Buena alternativa para quienes no pueden viajar en septiembre." },
        { window: "Diciembre a junio — evitar el itinerario combinado", text: "El Pantanal se inunda y muchos caminos de la Transpantaneira quedan intransitables; la Amazonía está en creciente, óptima para remar, pero sin sinergia de fauna con el Pantanal en este período." },
      ],
    },
    experiences: {
      heading: "Lo que se vive en cada etapa",
      intro: "Cada bioma ofrece experiencias que el otro no tiene — el viaje combinado existe precisamente para reunir ambas.",
      items: [
        { title: "Río Negro y Anavilhanas, Manaos (etapa 1)", text: "El mayor archipiélago fluvial del mundo, agua negra que refleja el cielo, remo entre igarapés, delfines rosados en Novo Airão y observación de aves y monos en el dosel." },
        { title: "Encuentro de las Aguas y Manaos histórica (etapa 1)", text: "Los ríos Negro y Solimões corriendo lado a lado sin mezclarse durante seis kilómetros, visto en barco; de noche, el Teatro Amazonas y la gastronomía amazónica de tucupí y tambaquí." },
        { title: "La Transpantaneira, de Cuiabá a Porto Jofre (etapa 2)", text: "145 km de camino de tierra con más de cien puentes de madera, cruzando haciendas donde carpinchos, caimanes, jabirús y venados de los pantanos aparecen en cada curva." },
        { title: "Ríos Três Irmãos y Cuiabá, Porto Jofre (etapa 2)", text: "La región con mayor densidad de jaguares del planeta, avistados en barco desde las orillas entre junio y octubre — la probabilidad de avistamiento aquí es la más alta del mundo." },
        { title: "Haciendas-posada del Pantanal Norte (etapa 2)", text: "Paseos a caballo y en carreta entre bandadas de guacamayos azules y jabirús, cabalgatas al amanecer y observación nocturna con reflector en busca de pumas y osos hormigueros." },
      ],
    },
    stays: {
      heading: "Dónde alojarse en cada tramo",
      intro: "La base correcta en cada bioma define el tipo de fauna que se ve y la comodidad de todo el viaje.",
      items: [
        { name: "Anavilhanas Jungle Lodge (Río Negro)", profile: "Primera etapa, comodidad y selva", text: "Bungalós frente al río y guías de altísimo nivel — la base más recomendada para iniciar el viaje por la Amazonía." },
        { name: "Mirante do Gavião (Novo Airão)", profile: "Estadías cortas de alto nivel", text: "Arquitectura premiada a orillas del Río Negro, ideal para 2 a 3 noches antes de seguir hacia el Pantanal." },
        { name: "Posadas fluviales de Porto Jofre", profile: "Observación intensiva de jaguares", text: "Bases flotantes o ribereñas con salidas diarias en barco al amanecer y al atardecer, los horarios de mayor actividad de los jaguares." },
        { name: "Haciendas-lodge de la Transpantaneira", profile: "Pantanal terrestre y cabalgatas", text: "Propiedades históricas convertidas en posadas de observación, con paseos a caballo, en carreta y safari nocturno." },
        { name: "Hoteles de tránsito en Cuiabá", profile: "Noche de amortiguación", text: "Usados solo para conexión segura entre el vuelo internacional/nacional y el tramo terrestre hasta la Transpantaneira." },
      ],
    },
    profiles: {
      heading: "Para quién funciona este itinerario combinado",
      items: [
        { title: "Naturalistas y fotógrafos de vida silvestre", text: "El itinerario con mejor rendimiento en calidad de avistamiento en Brasil: selva cerrada de un lado, planicie abierta del otro." },
        { title: "Parejas y grupos pequeños en un viaje de referencia", text: "Doce a catorce noches intensas, con poco tiempo de playa — ideal para quienes ya han viajado mucho y buscan profundidad, no descanso." },
        { title: "Para quién quizás no funcione", a: "" , title2: "" , text: "Viajeros con poco tiempo (menos de 10 días) o que buscan playa y descompresión deben elegir solo uno de los dos biomas, no ambos combinados." },
      ],
    },
    itinerary: {
      heading: "El encadenamiento día a día: 13 noches de referencia",
      intro: "La lógica del itinerario combinado es siempre selva primero, planicie después — la Amazonía exige más adaptación al calor húmedo, y llegar descansado al Pantanal rinde más avistamientos.",
      items: [
        { title: "Noches 1 a 5 — Manaos y Río Negro", text: "Vuelo internacional o doméstico hasta Manaos, una noche de llegada en la ciudad y cuatro noches de lodge en el Río Negro/Anavilhanas, con paseos en canoa, observación nocturna y baño con delfines." },
        { title: "Tránsito — Manaos a Cuiabá vía Brasilia o São Paulo", text: "No hay vuelo directo diario confiable entre Manaos y Cuiabá; la conexión más segura pasa por Brasilia o São Paulo, con una duración total de 5 a 7 horas incluyendo la escala." },
        { title: "Noches 6 a 12 — Cuiabá, Transpantaneira y Porto Jofre", text: "Una noche de llegada en Cuiabá, seguida de un traslado terrestre de 3 a 4 horas por la Transpantaneira hasta haciendas-posada intermedias, y luego barco o carretera hasta Porto Jofre para cinco a seis noches de observación intensiva de jaguares." },
        { title: "Noche 13 — Cuiabá, despedida", text: "Regreso terrestre a Cuiabá para pernoctar con seguridad antes del vuelo de salida, evitando riesgos por retrasos en el camino de tierra." },
      ],
    },
    tips: {
      heading: "Consejos prácticos para el itinerario combinado",
      items: [
        "Reserve la conexión aérea Manaos–Cuiabá con margen: como pasa por Brasilia o São Paulo, un retraso en un tramo afecta al otro.",
        "La vacuna contra la fiebre amarilla es obligatoria para la Amazonía y recomendada para el Pantanal — aplíquela al menos diez días antes del viaje.",
        "Lleve ropa de colores neutros para el Pantanal (evite blanco y colores vivos, que asustan a la fauna) y ropa ligera de manga larga para la Amazonía.",
        "Los binoculares propios son esenciales en ambos biomas — en el Pantanal, sobre todo para jabirús y guacamayos a distancia.",
        "El camino de la Transpantaneira es de tierra y puede complicarse tras lluvias fuertes incluso en la temporada seca; reserve siempre un día de margen antes de vuelos de conexión.",
        "Septiembre es el mes más solicitado para alojamiento en Porto Jofre — reserve con al menos seis meses de anticipación.",
      ],
    },
    faq: [
      { q: "¿Cuántas noches se necesitan para el itinerario Amazonía + Pantanal?", a: "De 12 a 14 noches: 4 a 5 en la Amazonía y 6 a 7 en el Pantanal, incluyendo noches de tránsito en Manaos y Cuiabá." },
      { q: "¿Cuál es la mejor época para hacer ambos viajes juntos?", a: "Julio a octubre, cuando ambos biomas están en temporada seca — la Amazonía con playas de río y el Pantanal con fauna concentrada en las orillas." },
      { q: "¿Existe vuelo directo entre Manaos y Cuiabá?", a: "No con frecuencia regular; la conexión más confiable pasa por Brasilia o São Paulo, sumando de 5 a 7 horas de viaje total." },
      { q: "¿Dónde es mayor la probabilidad de ver un jaguar?", a: "En la región de Porto Jofre, en el Pantanal, entre junio y octubre — la mayor densidad de jaguares documentada en el planeta. En la Amazonía, el avistamiento de jaguares es raro." },
      { q: "¿Es un viaje físicamente exigente?", a: "Moderado: predominan las caminatas cortas y los paseos en barco y 4x4 sobre el trekking intenso, aunque el calor y la humedad en ambos biomas requieren preparación." },
      { q: "¿Cuánto cuesta este itinerario combinado con Create Travel?", a: "No trabajamos con precios de estante: el presupuesto depende de los lodges, el número de noches y la época. Un consultor humano elabora la propuesta por escrito." },
    ],
    cta: { heading: "Diseñemos su itinerario Amazonía + Pantanal", subheading: "Un consultor humano de Create Travel organiza la logística aérea, los lodges y la ventana correcta para ambos biomas.", button: "Hablar con un travel designer" },
    readingMinutes: 12,
    publishedAt: "2026-08-11",
  },

  it: {
    destinationName: "Amazzonia + Pantanal",
    blurb: "Foresta e pianura allagata in un solo viaggio: i due grandi santuari faunistici del Brasile, da 12 a 14 notti.",
    metaTitle: "Amazzonia + Pantanal: itinerario combinato di 12-14 notti",
    metaDescription: "Come combinare Manaus/Rio Negro con la Transpantaneira/Porto Jofre in un solo viaggio: finestra migliore (luglio-ottobre), voli via Brasília o São Paulo, fauna complementare e notti per tratta.",
    keywords: "amazzonia e pantanal itinerario, viaggio combinato amazzonia pantanal, transpantaneira porto jofre, rio negro anavilhanas, periodo migliore amazzonia pantanal, giaguaro pantanal, itinerario fauna brasile",
    h1: "Amazzonia + Pantanal: l'itinerario combinato dei due grandi biomi faunistici del Brasile",
    aiAnswer: "Il miglior itinerario per combinare Amazzonia e Pantanal dura da 12 a 14 notti: 4-5 notti di foresta a Manaus/Rio Negro e 5-7 notti di pianura allagata a Cuiabá/Transpantaneira/Porto Jofre, nella finestra luglio-ottobre (secca in entrambi i biomi), con collegamento aereo via Brasília o São Paulo.",
    intro: [
      "Amazzonia e Pantanal sono spesso confusi da chi non è mai stato in Brasile, ma sono biomi opposti: uno è foresta densa e chiusa, l'altro savana allagata e aperta. Proprio per questo, combinati, formano l'itinerario faunistico più completo del paese — ciò che si nasconde nella foresta si rivela nella pianura, e viceversa.",
      "Questa guida è concepita come combinata per struttura: non tratta le due destinazioni separatamente, ma come un unico viaggio di 12-14 notti, con la logistica aerea, il numero di notti per tratta e la finestra climatica che fanno funzionare insieme i due biomi senza perdere ciò che ognuno offre di meglio.",
    ],
    seasons: {
      heading: "La finestra congiunta: luglio a ottobre",
      intro: "Amazzonia e Pantanal hanno calendari climatici opposti per gran parte dell'anno, ma si incrociano favorevolmente tra luglio e ottobre — la finestra che raccomandiamo per l'itinerario combinato.",
      windows: [
        { window: "Luglio ad agosto — deflusso amazzonico e inizio della secca pantaneira", text: "In Amazzonia il fiume inizia a scendere e appaiono i primi banchi di sabbia; nel Pantanal la secca comincia a concentrare la fauna lungo le rive. Buona finestra per iniziare dalla foresta." },
        { window: "Settembre a ottobre — secca in entrambi i biomi", text: "Il culmine della stagione dei giaguari sulla Transpantaneira coincide con la piena secca amazzonica: spiagge fluviali sul Tapajós e sul Rio Negro, e giaguari quasi garantiti a Porto Jofre. Il mese più consigliato per l'itinerario combinato." },
        { window: "Novembre — transizione, ancora praticabile", text: "Prime piogge isolate in entrambi i biomi, ma la fauna pantaneira è ancora concentrata e l'Amazzonia ha ancora le spiagge. Buona alternativa per chi non può viaggiare a settembre." },
        { window: "Dicembre a giugno — evitare l'itinerario combinato", text: "Il Pantanal si allaga e molte strade della Transpantaneira diventano impraticabili; l'Amazzonia è in piena, ottima per il canottaggio, ma senza sinergia faunistica con il Pantanal in questo periodo." },
      ],
    },
    experiences: {
      heading: "Cosa si vive in ogni tappa",
      intro: "Ogni bioma offre esperienze che l'altro non ha — il viaggio combinato esiste proprio per riunirle entrambe.",
      items: [
        { title: "Rio Negro e Anavilhanas, Manaus (tappa 1)", text: "Il più grande arcipelago fluviale del mondo, acqua nera che riflette il cielo, canoa tra gli igarapé, delfini rosa a Novo Airão e osservazione di uccelli e scimmie nel dosseletto." },
        { title: "Incontro delle Acque e Manaus storica (tappa 1)", text: "I fiumi Negro e Solimões che scorrono fianco a fianco senza mescolarsi per sei chilometri, visti in barca; di sera, il Teatro Amazonas e la gastronomia amazzonica di tucupi e tambaqui." },
        { title: "La Transpantaneira, da Cuiabá a Porto Jofre (tappa 2)", text: "145 km di strada sterrata con oltre cento ponti di legno, attraversando fattorie dove capibara, caimani, jabiru e cervi delle paludi appaiono a ogni curva." },
        { title: "Fiumi Três Irmãos e Cuiabá, Porto Jofre (tappa 2)", text: "La regione con la più alta densità di giaguari del pianeta, avvistati in barca lungo le rive tra giugno e ottobre — la probabilità di avvistamento più alta al mondo." },
        { title: "Fattorie-lodge del Pantanal Nord (tappa 2)", text: "Passeggiate a cavallo e in calesse tra stormi di are giacinto e jabiru, cavalcate all'alba e osservazione notturna con faro alla ricerca di puma e formichieri." },
      ],
    },
    stays: {
      heading: "Dove alloggiare in ogni tratta",
      intro: "La base giusta in ogni bioma determina il tipo di fauna che si vede e il comfort dell'intero viaggio.",
      items: [
        { name: "Anavilhanas Jungle Lodge (Rio Negro)", profile: "Prima tappa, comfort e foresta", text: "Bungalow affacciati sul fiume e guide di altissimo livello — la base più consigliata per iniziare il viaggio in Amazzonia." },
        { name: "Mirante do Gavião (Novo Airão)", profile: "Soggiorni brevi di alto livello", text: "Architettura premiata sulle rive del Rio Negro, ideale per 2-3 notti prima di proseguire verso il Pantanal." },
        { name: "Pousadas fluviali di Porto Jofre", profile: "Osservazione intensiva dei giaguari", text: "Basi galleggianti o rivierasche con uscite in barca giornaliere all'alba e al tramonto, gli orari di massima attività dei giaguari." },
        { name: "Fattorie-lodge della Transpantaneira", profile: "Pantanal terrestre e cavalcate", text: "Proprietà storiche convertite in pousadas di osservazione, con passeggiate a cavallo, in calesse e safari notturno." },
        { name: "Hotel di transito a Cuiabá", profile: "Notte cuscinetto", text: "Usati solo per una connessione sicura tra il volo internazionale/nazionale e la tratta terrestre verso la Transpantaneira." },
      ],
    },
    profiles: {
      heading: "Per chi funziona questo itinerario combinato",
      items: [
        { title: "Naturalisti e fotografi di fauna selvatica", text: "L'itinerario a più alto rendimento in qualità di avvistamento in Brasile: foresta chiusa da un lato, pianura aperta dall'altro." },
        { title: "Coppie e piccoli gruppi in un viaggio di riferimento", text: "Da dodici a quattordici notti intense, con poco tempo di spiaggia — ideale per chi ha già viaggiato molto e cerca profondità, non riposo." },
        { title: "Per chi forse non funziona", text: "Viaggiatori con poco tempo (meno di 10 giorni) o in cerca di spiaggia e decompressione dovrebbero scegliere solo uno dei due biomi, non entrambi combinati." },
      ],
    },
    itinerary: {
      heading: "Lo svolgimento giorno per giorno: 13 notti di riferimento",
      intro: "La logica dell'itinerario combinato è sempre foresta prima, pianura dopo — l'Amazzonia richiede più adattamento al caldo umido, e arrivare riposati al Pantanal rende più avvistamenti.",
      items: [
        { title: "Notti 1-5 — Manaus e Rio Negro", text: "Volo internazionale o nazionale fino a Manaus, una notte di arrivo in città e quattro notti di lodge sul Rio Negro/Anavilhanas, con uscite in canoa, avvistamento notturno e bagno con i delfini." },
        { title: "Transito — Manaus a Cuiabá via Brasília o São Paulo", text: "Non esiste un volo diretto giornaliero affidabile tra Manaus e Cuiabá; la connessione più sicura passa per Brasília o São Paulo, con una durata totale di 5-7 ore compreso lo scalo." },
        { title: "Notti 6-12 — Cuiabá, Transpantaneira e Porto Jofre", text: "Una notte di arrivo a Cuiabá, seguita da un trasferimento terrestre di 3-4 ore lungo la Transpantaneira fino a fattorie-lodge intermedie, poi barca o strada fino a Porto Jofre per cinque o sei notti di osservazione intensiva dei giaguari." },
        { title: "Notte 13 — Cuiabá, saluto finale", text: "Ritorno via terra a Cuiabá per una notte cuscinetto prima del volo di partenza, proteggendo da ritardi sulla strada sterrata." },
      ],
    },
    tips: {
      heading: "Consigli pratici per l'itinerario combinato",
      items: [
        "Prenotate la connessione Manaus–Cuiabá con margine: passando per Brasília o São Paulo, un ritardo su una tratta influisce sull'altra.",
        "Il vaccino contro la febbre gialla è obbligatorio per l'Amazzonia e consigliato per il Pantanal — fatelo almeno dieci giorni prima della partenza.",
        "Indossate abiti di colori neutri nel Pantanal (evitate bianco e colori vivaci, che spaventano la fauna) e abiti leggeri a maniche lunghe in Amazzonia.",
        "Il binocolo personale è essenziale in entrambi i biomi — nel Pantanal soprattutto per jabiru e are a distanza.",
        "La strada della Transpantaneira è sterrata e può diventare difficile dopo forti piogge anche nella stagione secca; riservate sempre un giorno cuscinetto prima dei voli di collegamento.",
        "Settembre è il mese più richiesto per l'alloggio a Porto Jofre — prenotate con almeno sei mesi di anticipo.",
      ],
    },
    faq: [
      { q: "Quante notti servono per l'itinerario Amazzonia + Pantanal?", a: "Da 12 a 14 notti: 4-5 in Amazzonia e 6-7 nel Pantanal, incluse le notti di transito a Manaus e Cuiabá." },
      { q: "Qual è il periodo migliore per fare entrambi i viaggi insieme?", a: "Luglio a ottobre, quando entrambi i biomi sono in stagione secca — l'Amazzonia con spiagge fluviali e il Pantanal con fauna concentrata lungo le rive." },
      { q: "Esiste un volo diretto tra Manaus e Cuiabá?", a: "Non con frequenza regolare; la connessione più affidabile passa per Brasília o São Paulo, per un totale di 5-7 ore di viaggio." },
      { q: "Dove è più alta la probabilità di vedere un giaguaro?", a: "Nella regione di Porto Jofre, nel Pantanal, tra giugno e ottobre — la più alta densità di giaguari documentata al mondo. In Amazzonia gli avvistamenti sono rari." },
      { q: "È un viaggio fisicamente impegnativo?", a: "Moderato: prevalgono brevi camminate e uscite in barca e 4x4 rispetto al trekking pesante, ma caldo e umidità in entrambi i biomi richiedono preparazione." },
      { q: "Quanto costa questo itinerario combinato con Create Travel?", a: "Non lavoriamo con listini fissi: il budget dipende dai lodge, dal numero di notti e dalla stagione. Un consulente umano prepara la proposta per iscritto." },
    ],
    cta: { heading: "Progettiamo il vostro itinerario Amazzonia + Pantanal", subheading: "Un consulente umano di Create Travel organizza la logistica aerea, i lodge e la finestra giusta per entrambi i biomi.", button: "Parla con un travel designer" },
    readingMinutes: 12,
    publishedAt: "2026-08-11",
  },

  de: {
    destinationName: "Amazonas + Pantanal",
    blurb: "Regenwald und überflutete Ebene in einer Reise: Brasiliens zwei große Wildtier-Refugien, über 12 bis 14 Nächte.",
    metaTitle: "Amazonas + Pantanal: kombinierte Route über 12–14 Nächte",
    metaDescription: "Wie man Manaus/Rio Negro mit der Transpantaneira/Porto Jofre in einer Reise kombiniert: bestes Zeitfenster (Juli-Oktober), Flüge via Brasília oder São Paulo, ergänzende Tierwelt und Nächte pro Etappe.",
    keywords: "amazonas pantanal reiseroute, kombinierte amazonas pantanal reise, transpantaneira porto jofre, rio negro anavilhanas, beste reisezeit amazonas pantanal, jaguar pantanal, brasilien tierwelt reiseroute",
    h1: "Amazonas + Pantanal: die kombinierte Route der zwei großen Wildtier-Biome Brasiliens",
    aiAnswer: "Die beste Route zur Kombination von Amazonas und Pantanal dauert 12 bis 14 Nächte: 4-5 Nächte Regenwald in Manaus/Rio Negro und 5-7 Nächte überflutete Ebene in Cuiabá/Transpantaneira/Porto Jofre, im Zeitfenster Juli bis Oktober (Trockenzeit in beiden Biomen), mit Flugverbindung über Brasília oder São Paulo.",
    intro: [
      "Amazonas und Pantanal werden von Brasilien-Erstbesuchern oft verwechselt, sind aber gegensätzliche Biome: das eine dichter, geschlossener Regenwald, das andere offene, überflutete Savanne. Gerade deshalb bilden sie kombiniert die vollständigste Tierbeobachtungsroute des Landes — was sich im Wald verbirgt, offenbart sich in der Ebene, und umgekehrt.",
      "Dieser Guide ist von Natur aus kombiniert angelegt: Er behandelt die beiden Ziele nicht getrennt, sondern als eine einzige 12-bis-14-nächtige Reise, mit der Flug logistik, der Nächteanzahl pro Etappe und dem Klimafenster, die beide Biome zusammen funktionieren lassen, ohne das Beste jedes einzelnen zu verlieren.",
    ],
    seasons: {
      heading: "Das gemeinsame Zeitfenster: Juli bis Oktober",
      intro: "Amazonas und Pantanal haben über weite Teile des Jahres gegensätzliche Klimakalender, überschneiden sich aber günstig zwischen Juli und Oktober — das Fenster, das wir für die kombinierte Route empfehlen.",
      windows: [
        { window: "Juli bis August — Amazonas-Rückgang und Beginn der Pantanal-Trockenzeit", text: "Im Amazonas beginnt der Fluss zu sinken, erste Sandbänke erscheinen; im Pantanal beginnt die Trockenzeit, Tierwelt entlang der Flussufer zu konzentrieren. Ein guter Zeitpunkt, um mit dem Regenwald zu beginnen." },
        { window: "September bis Oktober — Trockenzeit in beiden Biomen", text: "Die Hochsaison für Jaguare an der Transpantaneira fällt mit der vollen Amazonas-Trockenzeit zusammen: Flussstrände am Tapajós und Rio Negro, und nahezu garantierte Jaguare in Porto Jofre. Der empfehlenswerteste Monat für die kombinierte Route." },
        { window: "November — Übergang, noch machbar", text: "Erste vereinzelte Regenfälle in beiden Biomen, aber die Pantanal-Tierwelt ist noch konzentriert und der Amazonas hat noch Strände. Eine gute Alternative für alle, die im September nicht reisen können." },
        { window: "Dezember bis Juni — kombinierte Route vermeiden", text: "Der Pantanal überflutet und viele Transpantaneira-Straßen werden unpassierbar; der Amazonas führt Hochwasser, hervorragend zum Kanufahren, aber ohne Tierwelt-Synergie mit dem Pantanal in diesem Zeitraum." },
      ],
    },
    experiences: {
      heading: "Was jede Etappe bietet",
      intro: "Jedes Biom bietet Erlebnisse, die das andere nicht hat — die kombinierte Reise existiert genau, um beide zusammenzubringen.",
      items: [
        { title: "Rio Negro und Anavilhanas, Manaus (Etappe 1)", text: "Das größte Flussarchipel der Welt, schwarzes Wasser, das den Himmel spiegelt, Kanufahrten durch Bäche, rosa Flussdelfine in Novo Airão sowie Vogel- und Affenbeobachtung im Blätterdach." },
        { title: "Zusammenfluss der Wasser und historisches Manaus (Etappe 1)", text: "Die Flüsse Negro und Solimões, die sechs Kilometer nebeneinander fließen, ohne sich zu vermischen, vom Boot aus gesehen; abends das Amazonas-Opernhaus und die amazonische Küche mit Tucupi und Tambaqui." },
        { title: "Die Transpantaneira, von Cuiabá nach Porto Jofre (Etappe 2)", text: "145 km Schotterstraße mit über hundert Holzbrücken, durch Ranches, wo Capybaras, Kaimane, Jabirus und Sumpfhirsche an jeder Kurve auftauchen." },
        { title: "Flüsse Três Irmãos und Cuiabá, Porto Jofre (Etappe 2)", text: "Die Region mit der höchsten Jaguardichte des Planeten, vom Boot aus entlang der Flussufer zwischen Juni und Oktober beobachtet — die höchste Sichtungswahrscheinlichkeit weltweit." },
        { title: "Ranch-Lodges im nördlichen Pantanal (Etappe 2)", text: "Ausritte und Kutschfahrten zwischen Schwärmen von Hyazinth-Aras und Jabirus, Morgenritte und nächtliche Beobachtung mit Scheinwerfer auf der Suche nach Pumas und Ameisenbären." },
      ],
    },
    stays: {
      heading: "Wo man auf jeder Etappe übernachtet",
      intro: "Die richtige Basis in jedem Biom bestimmt die Tierwelt, die man sieht, und den Komfort der gesamten Reise.",
      items: [
        { name: "Anavilhanas Jungle Lodge (Rio Negro)", profile: "Erste Etappe, Komfort und Regenwald", text: "Flussblick-Bungalows und erstklassige Guides — die empfehlenswerteste Basis, um die Reise im Amazonas zu beginnen." },
        { name: "Mirante do Gavião (Novo Airão)", profile: "Kurze High-End-Aufenthalte", text: "Preisgekrönte Architektur am Rio Negro, ideal für 2-3 Nächte vor der Weiterreise ins Pantanal." },
        { name: "Flusspousadas in Porto Jofre", profile: "Intensive Jaguarbeobachtung", text: "Schwimmende oder ufernahe Basen mit täglichen Bootsausfahrten bei Sonnenaufgang und -untergang, den Stunden höchster Jaguaraktivität." },
        { name: "Ranch-Lodges der Transpantaneira", profile: "Land-Pantanal und Ausritte", text: "Historische Anwesen, umgewandelt in Beobachtungspousadas, mit Ausritten, Kutschfahrten und nächtlicher Safari." },
        { name: "Transithotels in Cuiabá", profile: "Pufferübernachtung", text: "Nur für eine sichere Verbindung zwischen dem internationalen/inländischen Flug und der Landetappe zur Transpantaneira genutzt." },
      ],
    },
    profiles: {
      heading: "Für wen diese kombinierte Route funktioniert",
      items: [
        { title: "Naturforscher und Wildtierfotografen", text: "Brasiliens ertragreichste Route für Beobachtungsqualität: geschlossener Wald auf der einen, offene Ebene auf der anderen Seite." },
        { title: "Paare und kleine Gruppen auf einer Referenzreise", text: "Zwölf bis vierzehn intensive Nächte mit wenig Strandzeit — ideal für vielgereiste Gäste, die Tiefe statt Erholung suchen." },
        { title: "Für wen es vielleicht nicht funktioniert", text: "Reisende mit wenig Zeit (unter 10 Tagen) oder auf der Suche nach Strand und Entspannung sollten nur eines der beiden Biome wählen, nicht beide kombiniert." },
      ],
    },
    itinerary: {
      heading: "Der Tag-für-Tag-Ablauf: ein 13-nächtiger Referenzplan",
      intro: "Die Logik der kombinierten Route ist stets Regenwald zuerst, Ebene danach — der Amazonas erfordert mehr Anpassung an feuchte Hitze, und ausgeruht im Pantanal anzukommen, bringt mehr Sichtungen.",
      items: [
        { title: "Nächte 1-5 — Manaus und Rio Negro", text: "Internationaler oder inländischer Flug nach Manaus, eine Ankunftsnacht in der Stadt und vier Lodge-Nächte am Rio Negro/Anavilhanas, mit Kanuausflügen, nächtlicher Tierbeobachtung und Schwimmen mit Delfinen." },
        { title: "Transit — Manaus nach Cuiabá via Brasília oder São Paulo", text: "Es gibt keinen zuverlässigen täglichen Direktflug zwischen Manaus und Cuiabá; die verlässlichste Verbindung führt über Brasília oder São Paulo, insgesamt 5 bis 7 Stunden inklusive Zwischenstopp." },
        { title: "Nächte 6-12 — Cuiabá, Transpantaneira und Porto Jofre", text: "Eine Ankunftsnacht in Cuiabá, gefolgt von einem 3-4-stündigen Landtransfer entlang der Transpantaneira zu Zwischen-Ranch-Lodges, dann Boot oder Straße nach Porto Jofre für fünf bis sechs Nächte intensiver Jaguarbeobachtung." },
        { title: "Nacht 13 — Cuiabá, Abschied", text: "Rückfahrt nach Cuiabá für eine Pufferübernachtung vor dem Abflug, als Schutz vor Verzögerungen auf der Schotterstraße." },
      ],
    },
    tips: {
      heading: "Praktische Tipps für die kombinierte Route",
      items: [
        "Buchen Sie die Verbindung Manaus–Cuiabá mit Puffer: Da sie über Brasília oder São Paulo führt, wirkt sich eine Verspätung auf einer Etappe auf die andere aus.",
        "Die Gelbfieberimpfung ist für den Amazonas Pflicht und für das Pantanal empfohlen — mindestens zehn Tage vor Abreise durchführen.",
        "Tragen Sie im Pantanal Kleidung in neutralen Farben (Weiß und grelle Farben vermeiden, die die Tierwelt verschrecken) und im Amazonas leichte, langärmelige Kleidung.",
        "Ein eigenes Fernglas ist in beiden Biomen unverzichtbar — im Pantanal besonders für entfernte Jabirus und Aras.",
        "Die Schotterstraße der Transpantaneira kann nach starkem Regen selbst in der Trockenzeit schwierig werden; reservieren Sie immer einen Pufferzeitpunkt vor Anschlussflügen.",
        "September ist der gefragteste Monat für Unterkünfte in Porto Jofre — mindestens sechs Monate im Voraus buchen.",
      ],
    },
    faq: [
      { q: "Wie viele Nächte benötigt man für die Route Amazonas + Pantanal?", a: "12 bis 14 Nächte: 4-5 im Amazonas und 6-7 im Pantanal, einschließlich Transitnächten in Manaus und Cuiabá." },
      { q: "Was ist die beste Zeit, um beide Reisen zusammen zu machen?", a: "Juli bis Oktober, wenn beide Biome in der Trockenzeit sind — der Amazonas mit Flussstränden, das Pantanal mit konzentrierter Tierwelt entlang der Ufer." },
      { q: "Gibt es einen Direktflug zwischen Manaus und Cuiabá?", a: "Nicht mit regelmäßiger täglicher Frequenz; die zuverlässigste Verbindung führt über Brasília oder São Paulo, insgesamt 5 bis 7 Stunden Reisezeit." },
      { q: "Wo ist die Chance, einen Jaguar zu sehen, am höchsten?", a: "In der Region Porto Jofre im Pantanal, zwischen Juni und Oktober — die höchste dokumentierte Jaguardichte des Planeten. Im Amazonas sind Jaguarsichtungen selten." },
      { q: "Ist dies eine körperlich anspruchsvolle Reise?", a: "Moderat: kurze Wanderungen sowie Boots- und 4x4-Ausflüge überwiegen gegenüber intensivem Trekking, aber Hitze und Feuchtigkeit in beiden Biomen erfordern klimatische Vorbereitung." },
      { q: "Was kostet diese kombinierte Route mit Create Travel?", a: "Wir arbeiten nicht mit Listenpreisen: Das Budget hängt von den Lodges, der Nächteanzahl und der Saison ab. Ein menschlicher Berater erstellt das Angebot schriftlich." },
    ],
    cta: { heading: "Lassen Sie uns Ihre Route Amazonas + Pantanal gestalten", subheading: "Ein menschlicher Berater von Create Travel organisiert die Flug logistik, die Lodges und das richtige Zeitfenster für beide Biome.", button: "Mit einem Travel Designer sprechen" },
    readingMinutes: 12,
    publishedAt: "2026-08-11",
  },
};
