import type { BrazilGuideLocalized } from "./types";

export const conjugadoRioBahiaNoronhaGuide: BrazilGuideLocalized = {
  pt: {
    destinationName: "Rio + Bahia + Fernando de Noronha",
    blurb: "Um roteiro conjugado de 14 noites entre a cidade mais fotografada do Brasil, a Bahia histórica e o mar mais transparente do Atlântico Sul.",
    metaTitle: "Rio + Bahia + Noronha: roteiro de 14 noites | Create Travel",
    metaDescription: "Guia autoral do roteiro conjugado Rio de Janeiro, Salvador/Trancoso e Fernando de Noronha: melhor época, voos, noites por trecho e experiências reais.",
    keywords: "roteiro rio bahia noronha, rio de janeiro trancoso fernando de noronha, roteiro 14 dias brasil, viagem bahia noronha, roteiro luxo brasil litoral",
    h1: "Rio, Bahia e Noronha: o roteiro conjugado que resume o litoral brasileiro",
    aiAnswer: "O roteiro conjugado Rio de Janeiro + Bahia (Salvador e Trancoso) + Fernando de Noronha funciona melhor entre setembro e março, com cerca de 14 noites: 4 no Rio, 6 na Bahia (2 em Salvador, 4 em Trancoso) e 4 em Noronha, encadeados por voos domésticos diretos ou com uma conexão em Recife.",
    intro: [
      "Existe um eixo brasileiro que, feito na ordem certa, funciona como um crescendo: começa na energia urbana do Rio de Janeiro, passa pela densidade histórica e afetiva da Bahia e termina na suspensão quase irreal de Fernando de Noronha. Não é um roteiro de 'checklist de praias' — é uma curva narrativa, cada trecho preparando o seguinte.",
      "Este guia nasce de dezenas de roteiros que desenhamos com essa mesma espinha dorsal, ajustando noites, ordem e conexões conforme o perfil do viajante. Aqui está o que aprendemos sobre a melhor forma de encadear os três destinos sem perder dias em aeroportos nem energia em trechos mal pensados.",
    ],
    seasons: {
      heading: "Melhor época para o roteiro Rio + Bahia + Noronha",
      intro: "Os três destinos têm janelas parecidas, mas Noronha impõe a regra mais rígida: o arquipélago tem cota diária de visitantes e sua melhor visibilidade submarina depende da estação.",
      windows: [
        { window: "Setembro a novembro", text: "Primavera carioca amena, Bahia com menos chuva e Noronha na transição para a estação seca, com visibilidade subaquática já excelente e mar mais calmo para mergulho e trilhas." },
        { window: "Dezembro a fevereiro", text: "Alta temporada brasileira: Rio e Bahia em festa (réveillon, verão, Carnaval em fevereiro), Noronha na estação chuvosa mas com chuvas curtas e visibilidade ainda boa nas primeiras semanas de dezembro." },
        { window: "Março", text: "Pós-Carnaval, cidades mais tranquilas, mar ainda quente no Rio e na Bahia. Boa janela para quem quer fugir das multidões sem abrir mão do calor." },
        { window: "Junho a agosto — evitar em Noronha", text: "É a estação seca no arquipélago, mas as ondas atlânticas ficam mais fortes na praia do Cachorro e do Boldró, o que reduz o mergulho livre; o Rio e a Bahia seguem agradáveis, com dias mais frescos." },
      ],
    },
    experiences: {
      heading: "O que se vive em cada trecho",
      intro: "Cada destino cumpre uma função narrativa distinta no roteiro — e é por isso que a ordem importa tanto quanto o conteúdo.",
      items: [
        { title: "Rio de Janeiro — a abertura urbana", text: "Cristo Redentor ao amanhecer antes das multidões, Pão de Açúcar ao pôr do sol, praias de Ipanema e Leblon, e um dia inteiro em Santa Teresa e na Lapa para sentir a cidade fora do cartão-postal." },
        { title: "Salvador — a imersão histórica", text: "O Pelourinho ao entardecer, quando a luz dourada acerta os casarões coloniais, um jantar de comida baiana de raiz e uma tarde dedicada à cultura afro-brasileira, do Terreiro de Jesus ao Mercado Modelo." },
        { title: "Trancoso — a desaceleração", text: "O Quadrado ao pôr do sol, praias como Nativos e Rio da Barra acessíveis de buggy, e a hospitalidade discreta que fez do vilarejo um refúgio de gente que já viu tudo e busca simplicidade com padrão altíssimo." },
        { title: "Fernando de Noronha — o clímax", text: "Baía do Sancho eleita repetidamente uma das mais bonitas do mundo, mergulho com golfinhos-rotadores na Baía dos Golfinhos ao amanhecer, trilhas de Atalaia com piscinas naturais e um pôr do sol no Forte dos Remédios que fecha o roteiro em silêncio." },
        { title: "Gastronomia como fio condutor", text: "Do moqueca de peixe em Salvador ao peixe fresco grelhado em Noronha, passando pela cena contemporânea carioca, a comida marca cada mudança de paisagem tanto quanto a geografia." },
        { title: "Cultura afro-brasileira", text: "Capoeira, candomblé e a herança dos terreiros dão à Bahia uma camada que nem Rio nem Noronha oferecem — é o trecho que aprofunda o roteiro, entre o urbano e o insular." },
      ],
    },
    stays: {
      heading: "Onde ficar em cada trecho",
      intro: "Selecionamos endereços que sustentam o padrão do roteiro do início ao fim, sem quedas de qualidade entre uma etapa e outra.",
      items: [
        { name: "Fasano Rio de Janeiro (Ipanema)", profile: "Casais e viajantes de design", text: "Endereço de referência na praia de Ipanema, arquitetura de Philippe Starck e uma das melhores vistas de pôr do sol da cidade." },
        { name: "Hotel Fasano Salvador ou Villa Bahia (Pelourinho)", profile: "Imersão histórica", text: "Casarões restaurados no centro histórico, a poucos passos do Pelourinho — a melhor forma de dormir dentro da história baiana." },
        { name: "Uxua Casa Hotel (Trancoso)", profile: "Design e discrição", text: "Casas de pescador reformadas ao redor do Quadrado, com um padrão de hospitalidade que define o conceito de luxo descalço." },
        { name: "Nannai Trancoso", profile: "Famílias e casais que buscam praia e conforto", text: "Bangalôs entre a Mata Atlântica e a praia, com uma das melhores estruturas de resort do sul da Bahia." },
        { name: "Pousada Maravilha (Fernando de Noronha)", profile: "Vista e romance", text: "Suítes suspensas com vista para o mar aberto, entre as mais fotografadas do arquipélago." },
        { name: "Nannai ou Teju-Açu (Fernando de Noronha)", profile: "Conforto discreto na ilha", text: "Estrutura simples mas competente, coerente com as regras ambientais rígidas da ilha, que limitam construção e ocupação." },
      ],
    },
    profiles: {
      heading: "Para quem este roteiro funciona",
      items: [
        { title: "Casais em viagem de aniversário ou lua de mel", text: "A curva emocional do roteiro — cidade, história, romance, natureza extrema — é ideal para celebrações redondas." },
        { title: "Viajantes que já conhecem o Rio e querem aprofundar", text: "Para quem já fez o Rio antes, sugerimos reduzir para 3 noites e ampliar Bahia e Noronha." },
        { title: "Famílias com adolescentes", text: "Funciona bem, mas Noronha exige atenção ao mergulho e trilhas com crianças pequenas — recomendamos filhos acima de 8 anos." },
        { title: "Para quem talvez não funcione", text: "Viajantes com pouco tempo (menos de 10 dias) devem escolher dois destinos, não três — o encadeamento perde qualidade e vira corrida de aeroporto." },
      ],
    },
    itinerary: {
      heading: "Como encadear o roteiro, trecho a trecho",
      intro: "A lógica aérea é decisiva: Noronha só recebe voos diretos de Recife, Natal e, sazonalmente, de São Paulo e Rio — por isso ela fica sempre por último ou por primeiro, nunca no meio.",
      items: [
        { title: "Dias 1 a 4 — Rio de Janeiro", text: "Chegada internacional ou doméstica no Galeão, quatro noites para cobrir cidade, praias e um dia de bastidores (Santa Teresa, Lapa). Voo doméstico para Salvador no dia 5, cerca de 2h de voo direto." },
        { title: "Dias 5 a 6 — Salvador", text: "Duas noites no centro histórico, tempo suficiente para Pelourinho, Elevador Lacerda e um jantar de comida baiana de raiz. Transfer rodoviário de cerca de 3h30 ou voo doméstico de 40 minutos até Porto Seguro, seguido de 1h de carro até Trancoso." },
        { title: "Dias 7 a 10 — Trancoso", text: "Quatro noites de desaceleração, buggy pelas praias do sul da Bahia, tempo de sobra no Quadrado. Retorno a Porto Seguro e voo com conexão em Recife até Fernando de Noronha (rota mais comum: Porto Seguro–Salvador ou Recife–Noronha)." },
        { title: "Dias 11 a 14 — Fernando de Noronha", text: "Quatro noites de mar, mergulho e trilhas, respeitando a cota diária do parque nacional marinho. Voo de retorno via Recife, com conexão para o Rio, São Paulo ou destino internacional." },
      ],
    },
    tips: {
      heading: "Dicas práticas para este roteiro",
      items: [
        "Fernando de Noronha cobra Taxa de Preservação Ambiental por dia de permanência, paga na chegada ou antecipadamente online.",
        "O ingresso do Parque Nacional Marinho é separado da taxa ambiental e deve ser adquirido com antecedência em alta temporada.",
        "Reserve os voos para Noronha com meses de antecedência: a malha é limitada e os preços sobem rápido.",
        "Em Trancoso, o Quadrado fica lotado ao pôr do sol na alta temporada — reserve mesa com antecedência se quiser jantar ali.",
        "Leve roupa leve e protetor solar biodegradável, exigido em Noronha para proteger os recifes.",
        "Planeje ao menos uma noite de folga entre trechos com conexão em Recife, para absorver eventuais atrasos sem comprometer o restante do roteiro.",
      ],
    },
    faq: [
      { q: "Quantas noites são ideais para o roteiro Rio + Bahia + Noronha?", a: "Catorze noites é o equilíbrio ideal: 4 no Rio, 6 na Bahia (2 em Salvador e 4 em Trancoso) e 4 em Noronha. É possível reduzir para 10 noites cortando Salvador." },
      { q: "Qual a melhor época para fazer esse roteiro?", a: "Setembro a março, com pico de qualidade entre setembro e novembro, quando Noronha tem mar mais calmo e as três cidades têm clima ameno." },
      { q: "Como se voa entre esses três destinos?", a: "Rio–Salvador é voo direto de cerca de 2h. Salvador ou Porto Seguro até Noronha exige conexão em Recife ou Natal, únicos aeroportos com voos diretos regulares ao arquipélago." },
      { q: "Vale a pena incluir Trancoso ou ir direto de Salvador para Noronha?", a: "Trancoso adiciona a camada de desaceleração e vilarejo boêmio que Salvador e Noronha não têm — recomendamos para roteiros de 12 noites ou mais." },
      { q: "É preciso reservar Fernando de Noronha com muita antecedência?", a: "Sim. A ilha tem cota diária de visitantes e a malha aérea é limitada; recomendamos reservar voos e pousadas com 4 a 6 meses de antecedência em alta temporada." },
      { q: "Esse roteiro funciona para famílias?", a: "Sim, especialmente com filhos a partir de 8 anos. Noronha pede atenção redobrada com crianças menores por causa das trilhas e do mergulho em mar aberto." },
    ],
    cta: {
      heading: "Vamos desenhar o seu Rio + Bahia + Noronha",
      subheading: "Um consultor humano da Create Travel ajusta noites, voos e endereços ao seu ritmo — sem perder tempo em conexões mal planejadas.",
      button: "Falar com um travel designer",
    },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },

  en: {
    destinationName: "Rio + Bahia + Fernando de Noronha",
    blurb: "A conjugated 14-night route between Brazil's most photographed city, historic Bahia and the clearest waters of the South Atlantic.",
    metaTitle: "Rio + Bahia + Noronha: 14-Night Itinerary | Create Travel",
    metaDescription: "An editorial guide to the conjugated route Rio de Janeiro, Salvador/Trancoso and Fernando de Noronha: best season, flights, nights per leg and real experiences.",
    keywords: "rio bahia noronha itinerary, rio de janeiro trancoso fernando de noronha, 14 day brazil itinerary, bahia noronha trip, luxury brazil coast itinerary",
    h1: "Rio, Bahia and Noronha: the conjugated route that sums up Brazil's coast",
    aiAnswer: "The conjugated Rio de Janeiro + Bahia (Salvador and Trancoso) + Fernando de Noronha route works best from September to March, over roughly 14 nights: 4 in Rio, 6 in Bahia (2 in Salvador, 4 in Trancoso) and 4 in Noronha, linked by direct domestic flights or a connection through Recife.",
    intro: [
      "There is a Brazilian axis that, done in the right order, builds like a crescendo: it opens with the urban energy of Rio de Janeiro, moves through the historic and emotional density of Bahia, and closes in the near-unreal suspension of Fernando de Noronha. This is not a checklist of beaches — it is a narrative arc, each leg setting up the next.",
      "This guide comes from dozens of itineraries built on this same backbone, adjusting nights, order and connections to each traveler's profile. Here is what we've learned about linking the three destinations without losing days at airports or momentum in poorly sequenced legs.",
    ],
    seasons: {
      heading: "Best time for the Rio + Bahia + Noronha route",
      intro: "The three destinations share similar windows, but Noronha sets the strictest rule: the archipelago caps daily visitors and its underwater visibility depends on the season.",
      windows: [
        { window: "September to November", text: "Mild Rio spring, drier Bahia and Noronha transitioning into its dry season, with excellent underwater visibility and calmer seas for diving and hiking." },
        { window: "December to February", text: "Brazilian high season: Rio and Bahia in full celebration mode (New Year's, summer, Carnival in February), Noronha in its rainy season but with short showers and still-good visibility in early December." },
        { window: "March", text: "Post-Carnival, quieter cities, still-warm sea in Rio and Bahia. A good window for avoiding crowds without losing the heat." },
        { window: "June to August — avoid in Noronha", text: "The archipelago's dry season, but stronger Atlantic swells at Cachorro and Boldró beaches reduce snorkeling conditions; Rio and Bahia stay pleasant with cooler days." },
      ],
    },
    experiences: {
      heading: "What each leg delivers",
      intro: "Each destination plays a distinct narrative role in the itinerary — which is why sequencing matters as much as content.",
      items: [
        { title: "Rio de Janeiro — the urban opening", text: "Christ the Redeemer at dawn before the crowds, Sugarloaf at sunset, Ipanema and Leblon beaches, and a full day in Santa Teresa and Lapa to feel the city beyond the postcard." },
        { title: "Salvador — the historic immersion", text: "Pelourinho at dusk, when golden light hits the colonial façades, a proper Bahian dinner, and an afternoon dedicated to Afro-Brazilian culture, from Terreiro de Jesus to Mercado Modelo." },
        { title: "Trancoso — the deceleration", text: "The Quadrado at sunset, beaches like Nativos and Rio da Barra reached by buggy, and the discreet hospitality that turned this village into a refuge for travelers who have seen it all and now seek understated luxury." },
        { title: "Fernando de Noronha — the climax", text: "Baía do Sancho, repeatedly named among the world's most beautiful beaches, dawn snorkeling with spinner dolphins at Baía dos Golfinhos, the Atalaia trail's natural pools, and a silent sunset at Forte dos Remédios to close the route." },
        { title: "Food as connective tissue", text: "From moqueca in Salvador to grilled fresh fish in Noronha, by way of Rio's contemporary dining scene, food marks each landscape shift as much as geography does." },
        { title: "Afro-Brazilian culture", text: "Capoeira, Candomblé and the legacy of the terreiros give Bahia a layer neither Rio nor Noronha offer — the leg that deepens the route between the urban and the insular." },
      ],
    },
    stays: {
      heading: "Where to stay on each leg",
      intro: "We chose addresses that sustain the route's standard from start to finish, with no dip in quality between legs.",
      items: [
        { name: "Fasano Rio de Janeiro (Ipanema)", profile: "Couples and design travelers", text: "A landmark address on Ipanema beach, Philippe Starck architecture and one of the city's best sunset views." },
        { name: "Hotel Fasano Salvador or Villa Bahia (Pelourinho)", profile: "Historic immersion", text: "Restored townhouses in the historic center, steps from Pelourinho — the best way to sleep inside Bahian history." },
        { name: "Uxua Casa Hotel (Trancoso)", profile: "Design and discretion", text: "Restored fishermen's houses around the Quadrado, defining barefoot luxury." },
        { name: "Nannai Trancoso", profile: "Families and comfort-seeking couples", text: "Bungalows between Atlantic Forest and beach, one of southern Bahia's best resort structures." },
        { name: "Pousada Maravilha (Fernando de Noronha)", profile: "Views and romance", text: "Suites suspended over open sea, among the archipelago's most photographed." },
        { name: "Nannai or Teju-Açu (Fernando de Noronha)", profile: "Discreet comfort on the island", text: "Simple yet competent structures, consistent with the island's strict environmental rules limiting construction." },
      ],
    },
    profiles: {
      heading: "Who this route works for",
      items: [
        { title: "Couples celebrating anniversaries or honeymoons", text: "The route's emotional arc — city, history, romance, extreme nature — suits milestone celebrations." },
        { title: "Travelers who already know Rio", text: "For repeat Rio visitors, we suggest cutting it to 3 nights and extending Bahia and Noronha." },
        { title: "Families with teenagers", text: "Works well, though Noronha requires attention with young children during diving and trails — we recommend kids age 8 and up." },
        { title: "Who this may not suit", text: "Travelers with under 10 days should pick two destinations, not three — the chain loses quality and becomes an airport sprint." },
      ],
    },
    itinerary: {
      heading: "How to link the route, leg by leg",
      intro: "Flight logic is decisive: Noronha only receives direct flights from Recife, Natal and, seasonally, São Paulo and Rio — which is why it always comes first or last, never in the middle.",
      items: [
        { title: "Days 1–4 — Rio de Janeiro", text: "Arrival at Galeão, four nights covering the city, beaches and a behind-the-scenes day (Santa Teresa, Lapa). Domestic flight to Salvador on day 5, roughly a 2h direct flight." },
        { title: "Days 5–6 — Salvador", text: "Two nights in the historic center, enough for Pelourinho, the Lacerda Elevator and a proper Bahian dinner. A 3h30 road transfer or a 40-minute domestic flight to Porto Seguro, followed by 1h by car to Trancoso." },
        { title: "Days 7–10 — Trancoso", text: "Four nights of deceleration, buggy rides along southern Bahia's beaches, plenty of time at the Quadrado. Return to Porto Seguro and fly with a Recife connection to Fernando de Noronha." },
        { title: "Days 11–14 — Fernando de Noronha", text: "Four nights of sea, diving and trails, respecting the marine national park's daily quota. Return flight via Recife, connecting to Rio, São Paulo or an international destination." },
      ],
    },
    tips: {
      heading: "Practical tips for this route",
      items: [
        "Fernando de Noronha charges an Environmental Preservation Fee per day of stay, paid on arrival or in advance online.",
        "The Marine National Park entry ticket is separate from the environmental fee and should be bought ahead during high season.",
        "Book Noronha flights months in advance: the route network is limited and fares rise quickly.",
        "In Trancoso, the Quadrado gets crowded at sunset in high season — book a table ahead if you want to dine there.",
        "Bring light clothing and biodegradable sunscreen, required in Noronha to protect the reefs.",
        "Plan at least one buffer night around Recife connections to absorb delays without derailing the rest of the trip.",
      ],
    },
    faq: [
      { q: "How many nights are ideal for the Rio + Bahia + Noronha route?", a: "Fourteen nights is the ideal balance: 4 in Rio, 6 in Bahia (2 in Salvador, 4 in Trancoso) and 4 in Noronha. It can be trimmed to 10 by cutting Salvador." },
      { q: "What's the best season for this route?", a: "September to March, peaking in quality between September and November, when Noronha has calmer seas and all three cities have mild weather." },
      { q: "How do you fly between these three destinations?", a: "Rio–Salvador is a direct flight of about 2h. Salvador or Porto Seguro to Noronha requires a connection through Recife or Natal, the only airports with regular direct flights to the archipelago." },
      { q: "Is it worth including Trancoso or going straight from Salvador to Noronha?", a: "Trancoso adds the deceleration and boho-village layer that neither Salvador nor Noronha offer — recommended for itineraries of 12+ nights." },
      { q: "Do you need to book Fernando de Noronha far in advance?", a: "Yes. The island has a daily visitor cap and limited flight capacity; we recommend booking flights and lodging 4 to 6 months ahead in high season." },
      { q: "Does this route work for families?", a: "Yes, especially with children 8 and older. Noronha requires extra attention with younger kids due to trails and open-sea diving." },
    ],
    cta: {
      heading: "Let's design your Rio + Bahia + Noronha",
      subheading: "A human consultant at Create Travel fine-tunes nights, flights and addresses to your pace — without wasted time on poorly planned connections.",
      button: "Talk to a travel designer",
    },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },

  es: {
    destinationName: "Río + Bahía + Fernando de Noronha",
    blurb: "Un itinerario conjugado de 14 noches entre la ciudad más fotografiada de Brasil, la Bahía histórica y las aguas más transparentes del Atlántico Sur.",
    metaTitle: "Río + Bahía + Noronha: itinerario de 14 noches | Create Travel",
    metaDescription: "Guía editorial del itinerario conjugado Río de Janeiro, Salvador/Trancoso y Fernando de Noronha: mejor época, vuelos, noches por tramo y experiencias reales.",
    keywords: "itinerario rio bahia noronha, rio de janeiro trancoso fernando de noronha, itinerario 14 dias brasil, viaje bahia noronha, itinerario lujo brasil litoral",
    h1: "Río, Bahía y Noronha: el itinerario conjugado que resume el litoral brasileño",
    aiAnswer: "El itinerario conjugado Río de Janeiro + Bahía (Salvador y Trancoso) + Fernando de Noronha funciona mejor entre septiembre y marzo, con unas 14 noches: 4 en Río, 6 en Bahía (2 en Salvador, 4 en Trancoso) y 4 en Noronha, conectadas por vuelos domésticos directos o con una conexión en Recife.",
    intro: [
      "Existe un eje brasileño que, hecho en el orden correcto, funciona como un crescendo: comienza con la energía urbana de Río de Janeiro, atraviesa la densidad histórica y afectiva de Bahía y termina en la suspensión casi irreal de Fernando de Noronha. No es una lista de playas — es un arco narrativo, donde cada tramo prepara el siguiente.",
      "Esta guía nace de decenas de itinerarios diseñados sobre esta misma columna vertebral, ajustando noches, orden y conexiones según el perfil del viajero. Esto es lo que aprendimos sobre cómo encadenar los tres destinos sin perder días en aeropuertos ni energía en tramos mal pensados.",
    ],
    seasons: {
      heading: "Mejor época para el itinerario Río + Bahía + Noronha",
      intro: "Los tres destinos tienen ventanas parecidas, pero Noronha impone la regla más estricta: el archipiélago tiene cupo diario de visitantes y su visibilidad submarina depende de la estación.",
      windows: [
        { window: "Septiembre a noviembre", text: "Primavera carioca templada, Bahía con menos lluvia y Noronha entrando en su estación seca, con visibilidad submarina excelente y mar más calmo para buceo y senderos." },
        { window: "Diciembre a febrero", text: "Temporada alta brasileña: Río y Bahía en fiesta (fin de año, verano, Carnaval en febrero), Noronha en su estación lluviosa pero con lluvias breves y buena visibilidad a principios de diciembre." },
        { window: "Marzo", text: "Postcarnaval, ciudades más tranquilas, mar aún cálido en Río y Bahía. Buena ventana para evitar multitudes sin renunciar al calor." },
        { window: "Junio a agosto — evitar en Noronha", text: "Es la estación seca del archipiélago, pero el oleaje atlántico se fortalece en las playas de Cachorro y Boldró, reduciendo las condiciones de buceo libre; Río y Bahía siguen agradables, con días más frescos." },
      ],
    },
    experiences: {
      heading: "Lo que se vive en cada tramo",
      intro: "Cada destino cumple una función narrativa distinta en el itinerario — por eso el orden importa tanto como el contenido.",
      items: [
        { title: "Río de Janeiro — la apertura urbana", text: "Cristo Redentor al amanecer antes de las multitudes, Pan de Azúcar al atardecer, playas de Ipanema y Leblon, y un día entero en Santa Teresa y Lapa para sentir la ciudad más allá de la postal." },
        { title: "Salvador — la inmersión histórica", text: "El Pelourinho al atardecer, cuando la luz dorada ilumina las fachadas coloniales, una cena de comida bahiana auténtica y una tarde dedicada a la cultura afrobrasileña, del Terreiro de Jesus al Mercado Modelo." },
        { title: "Trancoso — la desaceleración", text: "El Quadrado al atardecer, playas como Nativos y Rio da Barra accesibles en buggy, y la hospitalidad discreta que convirtió al pueblo en refugio de viajeros que ya lo han visto todo." },
        { title: "Fernando de Noronha — el clímax", text: "Baía do Sancho, elegida repetidamente entre las playas más bellas del mundo, buceo con delfines rotadores al amanecer en Baía dos Golfinhos, el sendero de Atalaia con piscinas naturales y un atardecer silencioso en el Fuerte de los Remedios." },
        { title: "La gastronomía como hilo conductor", text: "De la moqueca de pescado en Salvador al pescado fresco a la parrilla en Noronha, pasando por la escena contemporánea carioca, la comida marca cada cambio de paisaje tanto como la geografía." },
        { title: "Cultura afrobrasileña", text: "Capoeira, candomblé y la herencia de los terreiros dan a Bahía una capa que ni Río ni Noronha ofrecen — el tramo que profundiza el itinerario entre lo urbano y lo insular." },
      ],
    },
    stays: {
      heading: "Dónde alojarse en cada tramo",
      intro: "Seleccionamos direcciones que sostienen el estándar del itinerario de principio a fin, sin caídas de calidad entre etapas.",
      items: [
        { name: "Fasano Río de Janeiro (Ipanema)", profile: "Parejas y viajeros de diseño", text: "Dirección de referencia en la playa de Ipanema, arquitectura de Philippe Starck y una de las mejores vistas de atardecer de la ciudad." },
        { name: "Hotel Fasano Salvador o Villa Bahia (Pelourinho)", profile: "Inmersión histórica", text: "Casonas restauradas en el centro histórico, a pasos del Pelourinho — la mejor forma de dormir dentro de la historia bahiana." },
        { name: "Uxua Casa Hotel (Trancoso)", profile: "Diseño y discreción", text: "Casas de pescadores restauradas alrededor del Quadrado, definiendo el lujo descalzo." },
        { name: "Nannai Trancoso", profile: "Familias y parejas que buscan playa y confort", text: "Bungalós entre la Mata Atlántica y la playa, una de las mejores estructuras de resort del sur de Bahía." },
        { name: "Pousada Maravilha (Fernando de Noronha)", profile: "Vistas y romance", text: "Suites suspendidas frente al mar abierto, entre las más fotografiadas del archipiélago." },
        { name: "Nannai o Teju-Açu (Fernando de Noronha)", profile: "Confort discreto en la isla", text: "Estructura simple pero competente, coherente con las estrictas normas ambientales de la isla." },
      ],
    },
    profiles: {
      heading: "Para quién funciona este itinerario",
      items: [
        { title: "Parejas en aniversario o luna de miel", text: "El arco emocional del itinerario — ciudad, historia, romance, naturaleza extrema — es ideal para celebraciones importantes." },
        { title: "Viajeros que ya conocen Río", text: "Para quien ya visitó Río, sugerimos reducir a 3 noches y ampliar Bahía y Noronha." },
        { title: "Familias con adolescentes", text: "Funciona bien, aunque Noronha exige atención con niños pequeños durante buceo y senderos — recomendamos hijos mayores de 8 años." },
        { title: "Para quién quizás no funcione", text: "Viajeros con menos de 10 días deben elegir dos destinos, no tres — el encadenamiento pierde calidad y se vuelve una carrera de aeropuertos." },
      ],
    },
    itinerary: {
      heading: "Cómo encadenar el itinerario, tramo a tramo",
      intro: "La lógica aérea es decisiva: Noronha solo recibe vuelos directos desde Recife, Natal y, estacionalmente, São Paulo y Río — por eso siempre va primero o último, nunca en el medio.",
      items: [
        { title: "Días 1 a 4 — Río de Janeiro", text: "Llegada al aeropuerto de Galeão, cuatro noches para cubrir ciudad, playas y un día tras bambalinas (Santa Teresa, Lapa). Vuelo doméstico a Salvador el día 5, cerca de 2h de vuelo directo." },
        { title: "Días 5 a 6 — Salvador", text: "Dos noches en el centro histórico, suficiente para Pelourinho, el Ascensor Lacerda y una cena bahiana auténtica. Traslado terrestre de unas 3h30 o vuelo doméstico de 40 minutos hasta Porto Seguro, seguido de 1h en auto hasta Trancoso." },
        { title: "Días 7 a 10 — Trancoso", text: "Cuatro noches de desaceleración, buggy por las playas del sur de Bahía, tiempo de sobra en el Quadrado. Regreso a Porto Seguro y vuelo con conexión en Recife hasta Fernando de Noronha." },
        { title: "Días 11 a 14 — Fernando de Noronha", text: "Cuatro noches de mar, buceo y senderos, respetando el cupo diario del parque nacional marino. Vuelo de regreso vía Recife, con conexión a Río, São Paulo o destino internacional." },
      ],
    },
    tips: {
      heading: "Consejos prácticos para este itinerario",
      items: [
        "Fernando de Noronha cobra una Tasa de Preservación Ambiental por día de estadía, pagadera al llegar o de forma anticipada online.",
        "La entrada al Parque Nacional Marino es independiente de la tasa ambiental y debe adquirirse con antelación en temporada alta.",
        "Reserve los vuelos a Noronha con meses de antelación: la malla es limitada y los precios suben rápido.",
        "En Trancoso, el Quadrado se llena al atardecer en temporada alta — reserve mesa con antelación si desea cenar allí.",
        "Lleve ropa ligera y protector solar biodegradable, exigido en Noronha para proteger los arrecifes.",
        "Planifique al menos una noche de descanso alrededor de conexiones en Recife para absorber retrasos sin comprometer el resto del viaje.",
      ],
    },
    faq: [
      { q: "¿Cuántas noches son ideales para el itinerario Río + Bahía + Noronha?", a: "Catorce noches es el equilibrio ideal: 4 en Río, 6 en Bahía (2 en Salvador y 4 en Trancoso) y 4 en Noronha. Se puede reducir a 10 noches eliminando Salvador." },
      { q: "¿Cuál es la mejor época para este itinerario?", a: "De septiembre a marzo, con el pico de calidad entre septiembre y noviembre, cuando Noronha tiene mar más calmo y las tres ciudades tienen clima templado." },
      { q: "¿Cómo se vuela entre estos tres destinos?", a: "Río–Salvador es un vuelo directo de unas 2h. Salvador o Porto Seguro hasta Noronha requiere conexión en Recife o Natal, únicos aeropuertos con vuelos directos regulares al archipiélago." },
      { q: "¿Vale la pena incluir Trancoso o ir directo de Salvador a Noronha?", a: "Trancoso añade la capa de desaceleración y pueblo bohemio que ni Salvador ni Noronha ofrecen — recomendado para itinerarios de 12 noches o más." },
      { q: "¿Es necesario reservar Fernando de Noronha con mucha antelación?", a: "Sí. La isla tiene cupo diario de visitantes y la malla aérea es limitada; recomendamos reservar vuelos y alojamiento con 4 a 6 meses de antelación en temporada alta." },
      { q: "¿Este itinerario funciona para familias?", a: "Sí, especialmente con hijos a partir de 8 años. Noronha requiere atención adicional con niños menores por los senderos y el buceo en mar abierto." },
    ],
    cta: {
      heading: "Diseñemos su Río + Bahía + Noronha",
      subheading: "Un consultor humano de Create Travel ajusta noches, vuelos y direcciones a su ritmo — sin perder tiempo en conexiones mal planificadas.",
      button: "Hablar con un travel designer",
    },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },

  it: {
    destinationName: "Rio + Bahia + Fernando de Noronha",
    blurb: "Un itinerario coniugato di 14 notti tra la città più fotografata del Brasile, la Bahia storica e le acque più trasparenti dell'Atlantico del Sud.",
    metaTitle: "Rio + Bahia + Noronha: itinerario di 14 notti | Create Travel",
    metaDescription: "Guida editoriale all'itinerario coniugato Rio de Janeiro, Salvador/Trancoso e Fernando de Noronha: periodo migliore, voli, notti per tappa ed esperienze reali.",
    keywords: "itinerario rio bahia noronha, rio de janeiro trancoso fernando de noronha, itinerario 14 giorni brasile, viaggio bahia noronha, itinerario lusso brasile costa",
    h1: "Rio, Bahia e Noronha: l'itinerario coniugato che riassume la costa brasiliana",
    aiAnswer: "L'itinerario coniugato Rio de Janeiro + Bahia (Salvador e Trancoso) + Fernando de Noronha funziona meglio da settembre a marzo, con circa 14 notti: 4 a Rio, 6 in Bahia (2 a Salvador, 4 a Trancoso) e 4 a Noronha, collegate da voli domestici diretti o da una coincidenza a Recife.",
    intro: [
      "Esiste un asse brasiliano che, percorso nell'ordine giusto, funziona come un crescendo: si apre con l'energia urbana di Rio de Janeiro, attraversa la densità storica e affettiva della Bahia e si chiude nella sospensione quasi irreale di Fernando de Noronha. Non è una lista di spiagge — è un arco narrativo, dove ogni tappa prepara la successiva.",
      "Questa guida nasce da decine di itinerari costruiti su questa stessa spina dorsale, adattando notti, ordine e coincidenze al profilo del viaggiatore. Ecco cosa abbiamo imparato su come collegare i tre destini senza perdere giorni in aeroporto né energia in tappe mal pensate.",
    ],
    seasons: {
      heading: "Periodo migliore per l'itinerario Rio + Bahia + Noronha",
      intro: "I tre destini hanno finestre simili, ma Noronha impone la regola più rigida: l'arcipelago ha una quota giornaliera di visitatori e la sua visibilità subacquea dipende dalla stagione.",
      windows: [
        { window: "Da settembre a novembre", text: "Primavera carioca mite, Bahia con meno pioggia e Noronha in transizione verso la stagione secca, con visibilità subacquea eccellente e mare più calmo per immersioni e sentieri." },
        { window: "Da dicembre a febbraio", text: "Alta stagione brasiliana: Rio e Bahia in festa (capodanno, estate, carnevale a febbraio), Noronha nella stagione delle piogge ma con acquazzoni brevi e buona visibilità nelle prime settimane di dicembre." },
        { window: "Marzo", text: "Post-carnevale, città più tranquille, mare ancora caldo a Rio e in Bahia. Buona finestra per evitare la folla senza rinunciare al caldo." },
        { window: "Da giugno ad agosto — da evitare a Noronha", text: "È la stagione secca dell'arcipelago, ma il mare atlantico si fa più mosso sulle spiagge di Cachorro e Boldró, riducendo le condizioni per lo snorkeling; Rio e Bahia restano piacevoli, con giornate più fresche." },
      ],
    },
    experiences: {
      heading: "Cosa si vive in ogni tappa",
      intro: "Ogni destino svolge una funzione narrativa distinta nell'itinerario — per questo l'ordine conta quanto il contenuto.",
      items: [
        { title: "Rio de Janeiro — l'apertura urbana", text: "Cristo Redentore all'alba prima della folla, Pan di Zucchero al tramonto, le spiagge di Ipanema e Leblon, e un'intera giornata a Santa Teresa e Lapa per sentire la città oltre la cartolina." },
        { title: "Salvador — l'immersione storica", text: "Il Pelourinho al tramonto, quando la luce dorata illumina i palazzi coloniali, una cena di cucina bahiana autentica e un pomeriggio dedicato alla cultura afro-brasiliana, dal Terreiro de Jesus al Mercado Modelo." },
        { title: "Trancoso — la decelerazione", text: "Il Quadrado al tramonto, spiagge come Nativos e Rio da Barra raggiungibili in buggy, e l'ospitalità discreta che ha reso il villaggio un rifugio per chi ha già visto tutto." },
        { title: "Fernando de Noronha — il culmine", text: "Baía do Sancho, ripetutamente eletta tra le spiagge più belle al mondo, snorkeling all'alba con i delfini rotatori nella Baía dos Golfinhos, il sentiero di Atalaia con le sue piscine naturali e un tramonto silenzioso al Forte dos Remédios." },
        { title: "La gastronomia come filo conduttore", text: "Dalla moqueca di pesce a Salvador al pesce fresco alla griglia a Noronha, passando per la scena contemporanea carioca, il cibo segna ogni cambio di paesaggio quanto la geografia." },
        { title: "Cultura afro-brasiliana", text: "Capoeira, candomblé e l'eredità dei terreiros danno alla Bahia uno strato che né Rio né Noronha offrono — la tappa che approfondisce l'itinerario tra l'urbano e l'insulare." },
      ],
    },
    stays: {
      heading: "Dove alloggiare in ogni tappa",
      intro: "Abbiamo selezionato indirizzi che sostengono lo standard dell'itinerario dall'inizio alla fine, senza cali di qualità tra una tappa e l'altra.",
      items: [
        { name: "Fasano Rio de Janeiro (Ipanema)", profile: "Coppie e viaggiatori attenti al design", text: "Indirizzo di riferimento sulla spiaggia di Ipanema, architettura di Philippe Starck e una delle migliori viste al tramonto della città." },
        { name: "Hotel Fasano Salvador o Villa Bahia (Pelourinho)", profile: "Immersione storica", text: "Palazzi restaurati nel centro storico, a pochi passi dal Pelourinho — il modo migliore per dormire dentro la storia bahiana." },
        { name: "Uxua Casa Hotel (Trancoso)", profile: "Design e discrezione", text: "Case di pescatori restaurate intorno al Quadrado, che definiscono il lusso a piedi nudi." },
        { name: "Nannai Trancoso", profile: "Famiglie e coppie in cerca di spiaggia e comfort", text: "Bungalow tra la Foresta Atlantica e la spiaggia, una delle migliori strutture resort del sud della Bahia." },
        { name: "Pousada Maravilha (Fernando de Noronha)", profile: "Vista e romanticismo", text: "Suite sospese sul mare aperto, tra le più fotografate dell'arcipelago." },
        { name: "Nannai o Teju-Açu (Fernando de Noronha)", profile: "Comfort discreto sull'isola", text: "Struttura semplice ma competente, coerente con le rigide norme ambientali dell'isola." },
      ],
    },
    profiles: {
      heading: "Per chi funziona questo itinerario",
      items: [
        { title: "Coppie in viaggio per anniversario o luna di miele", text: "L'arco emotivo dell'itinerario — città, storia, romanticismo, natura estrema — è ideale per celebrazioni importanti." },
        { title: "Viaggiatori che già conoscono Rio", text: "Per chi ha già visitato Rio, suggeriamo di ridurre a 3 notti e ampliare Bahia e Noronha." },
        { title: "Famiglie con adolescenti", text: "Funziona bene, anche se Noronha richiede attenzione con i bambini piccoli durante immersioni e sentieri — consigliamo figli dagli 8 anni in su." },
        { title: "Per chi forse non funziona", text: "I viaggiatori con meno di 10 giorni dovrebbero scegliere due destini, non tre — la catena perde qualità e diventa una corsa in aeroporto." },
      ],
    },
    itinerary: {
      heading: "Come collegare l'itinerario, tappa per tappa",
      intro: "La logica aerea è decisiva: Noronha riceve voli diretti solo da Recife, Natal e, stagionalmente, San Paolo e Rio — per questo va sempre per prima o per ultima, mai nel mezzo.",
      items: [
        { title: "Giorni 1-4 — Rio de Janeiro", text: "Arrivo all'aeroporto Galeão, quattro notti per coprire città, spiagge e una giornata dietro le quinte (Santa Teresa, Lapa). Volo domestico per Salvador al giorno 5, circa 2h di volo diretto." },
        { title: "Giorni 5-6 — Salvador", text: "Due notti nel centro storico, sufficienti per Pelourinho, l'Ascensore Lacerda e una cena bahiana autentica. Trasferimento su strada di circa 3h30 o volo domestico di 40 minuti fino a Porto Seguro, seguito da 1h in auto fino a Trancoso." },
        { title: "Giorni 7-10 — Trancoso", text: "Quattro notti di decelerazione, buggy lungo le spiagge del sud della Bahia, tempo abbondante al Quadrado. Ritorno a Porto Seguro e volo con scalo a Recife fino a Fernando de Noronha." },
        { title: "Giorni 11-14 — Fernando de Noronha", text: "Quattro notti di mare, immersioni e sentieri, rispettando la quota giornaliera del parco nazionale marino. Volo di ritorno via Recife, con coincidenza per Rio, San Paolo o destinazione internazionale." },
      ],
    },
    tips: {
      heading: "Consigli pratici per questo itinerario",
      items: [
        "Fernando de Noronha applica una Tassa di Preservazione Ambientale per giorno di soggiorno, pagabile all'arrivo o anticipatamente online.",
        "Il biglietto del Parco Nazionale Marino è separato dalla tassa ambientale e va acquistato in anticipo in alta stagione.",
        "Prenotate i voli per Noronha con mesi di anticipo: la rete è limitata e le tariffe salgono rapidamente.",
        "A Trancoso, il Quadrado si affolla al tramonto in alta stagione — prenotate un tavolo in anticipo se volete cenare lì.",
        "Portate abiti leggeri e crema solare biodegradabile, obbligatoria a Noronha per proteggere le barriere coralline.",
        "Pianificate almeno una notte cuscinetto attorno alle coincidenze a Recife per assorbire eventuali ritardi senza compromettere il resto del viaggio.",
      ],
    },
    faq: [
      { q: "Quante notti sono ideali per l'itinerario Rio + Bahia + Noronha?", a: "Quattordici notti è l'equilibrio ideale: 4 a Rio, 6 in Bahia (2 a Salvador e 4 a Trancoso) e 4 a Noronha. Si può ridurre a 10 notti eliminando Salvador." },
      { q: "Qual è il periodo migliore per questo itinerario?", a: "Da settembre a marzo, con il picco di qualità tra settembre e novembre, quando Noronha ha il mare più calmo e le tre città hanno clima mite." },
      { q: "Come ci si sposta in aereo tra questi tre destini?", a: "Rio–Salvador è un volo diretto di circa 2h. Salvador o Porto Seguro fino a Noronha richiede uno scalo a Recife o Natal, unici aeroporti con voli diretti regolari verso l'arcipelago." },
      { q: "Vale la pena includere Trancoso o andare direttamente da Salvador a Noronha?", a: "Trancoso aggiunge lo strato di decelerazione e villaggio bohémien che né Salvador né Noronha offrono — consigliato per itinerari di 12 notti o più." },
      { q: "È necessario prenotare Fernando de Noronha con largo anticipo?", a: "Sì. L'isola ha una quota giornaliera di visitatori e la rete aerea è limitata; consigliamo di prenotare voli e alloggi 4-6 mesi prima in alta stagione." },
      { q: "Questo itinerario funziona per le famiglie?", a: "Sì, specialmente con figli dagli 8 anni in su. Noronha richiede maggiore attenzione con i bambini piccoli per i sentieri e le immersioni in mare aperto." },
    ],
    cta: {
      heading: "Progettiamo il vostro Rio + Bahia + Noronha",
      subheading: "Un consulente umano di Create Travel calibra notti, voli e indirizzi sul vostro ritmo — senza perdere tempo in coincidenze mal pianificate.",
      button: "Parla con un travel designer",
    },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },

  de: {
    destinationName: "Rio + Bahia + Fernando de Noronha",
    blurb: "Eine verbundene 14-Nächte-Route zwischen Brasiliens meistfotografierter Stadt, dem historischen Bahia und den klarsten Gewässern des Südatlantiks.",
    metaTitle: "Rio + Bahia + Noronha: 14-Nächte-Reiseroute | Create Travel",
    metaDescription: "Redaktioneller Guide zur verbundenen Route Rio de Janeiro, Salvador/Trancoso und Fernando de Noronha: beste Reisezeit, Flüge, Nächte pro Etappe und reale Erlebnisse.",
    keywords: "rio bahia noronha reiseroute, rio de janeiro trancoso fernando de noronha, 14 tage brasilien route, bahia noronha reise, luxus brasilien küste route",
    h1: "Rio, Bahia und Noronha: die verbundene Route, die Brasiliens Küste zusammenfasst",
    aiAnswer: "Die verbundene Route Rio de Janeiro + Bahia (Salvador und Trancoso) + Fernando de Noronha funktioniert am besten von September bis März, über etwa 14 Nächte: 4 in Rio, 6 in Bahia (2 in Salvador, 4 in Trancoso) und 4 in Noronha, verbunden durch direkte Inlandsflüge oder eine Umsteigeverbindung in Recife.",
    intro: [
      "Es gibt eine brasilianische Achse, die, in der richtigen Reihenfolge bereist, wie ein Crescendo funktioniert: Sie beginnt mit der urbanen Energie Rio de Janeiros, durchquert die historische und emotionale Dichte Bahias und endet in der fast unwirklichen Schwebe Fernando de Noronhas. Das ist keine Strandliste — es ist ein narrativer Bogen, bei dem jede Etappe die nächste vorbereitet.",
      "Dieser Guide entstand aus Dutzenden Reiserouten, die wir auf diesem gleichen Rückgrat gebaut haben, wobei wir Nächte, Reihenfolge und Verbindungen an das Profil jedes Reisenden angepasst haben. Hier ist, was wir darüber gelernt haben, wie man die drei Destinationen verbindet, ohne Tage an Flughäfen oder Schwung durch schlecht geplante Etappen zu verlieren.",
    ],
    seasons: {
      heading: "Beste Reisezeit für die Route Rio + Bahia + Noronha",
      intro: "Die drei Destinationen haben ähnliche Fenster, aber Noronha setzt die strengste Regel: Der Archipel begrenzt die tägliche Besucherzahl, und seine Unterwassersicht hängt von der Jahreszeit ab.",
      windows: [
        { window: "September bis November", text: "Milder Frühling in Rio, weniger Regen in Bahia und Noronha im Übergang zur Trockenzeit, mit exzellenter Unterwassersicht und ruhigerem Meer für Tauchen und Wanderungen." },
        { window: "Dezember bis Februar", text: "Brasilianische Hochsaison: Rio und Bahia im Feiermodus (Silvester, Sommer, Karneval im Februar), Noronha in der Regenzeit, aber mit kurzen Schauern und noch guter Sicht Anfang Dezember." },
        { window: "März", text: "Nach dem Karneval, ruhigere Städte, noch warmes Meer in Rio und Bahia. Gutes Fenster, um Menschenmassen zu meiden, ohne auf Wärme zu verzichten." },
        { window: "Juni bis August — in Noronha meiden", text: "Trockenzeit im Archipel, aber stärkere Atlantikwellen an den Stränden Cachorro und Boldró verschlechtern die Schnorchelbedingungen; Rio und Bahia bleiben angenehm, mit kühleren Tagen." },
      ],
    },
    experiences: {
      heading: "Was jede Etappe bietet",
      intro: "Jede Destination erfüllt eine eigene narrative Funktion in der Route — deshalb zählt die Reihenfolge genauso wie der Inhalt.",
      items: [
        { title: "Rio de Janeiro — die urbane Eröffnung", text: "Christusstatue bei Sonnenaufgang vor den Menschenmassen, Zuckerhut bei Sonnenuntergang, die Strände von Ipanema und Leblon und ein ganzer Tag in Santa Teresa und Lapa, um die Stadt jenseits der Postkarte zu spüren." },
        { title: "Salvador — die historische Vertiefung", text: "Das Pelourinho bei Dämmerung, wenn goldenes Licht die Kolonialfassaden trifft, ein authentisches bahianisches Abendessen und ein Nachmittag für afro-brasilianische Kultur, vom Terreiro de Jesus bis zum Mercado Modelo." },
        { title: "Trancoso — die Entschleunigung", text: "Das Quadrado bei Sonnenuntergang, Strände wie Nativos und Rio da Barra per Buggy erreichbar, und die diskrete Gastfreundschaft, die das Dorf zum Rückzugsort für Reisende machte, die schon alles gesehen haben." },
        { title: "Fernando de Noronha — der Höhepunkt", text: "Baía do Sancho, wiederholt zu einem der schönsten Strände der Welt gewählt, Schnorcheln mit Fleckendelfinen bei Sonnenaufgang in der Baía dos Golfinhos, der Atalaia-Pfad mit natürlichen Pools und ein stiller Sonnenuntergang am Forte dos Remédios." },
        { title: "Gastronomie als roter Faden", text: "Von der Fisch-Moqueca in Salvador über frisch gegrillten Fisch in Noronha bis zur zeitgenössischen Küche Rios prägt das Essen jeden Landschaftswechsel ebenso wie die Geografie." },
        { title: "Afro-brasilianische Kultur", text: "Capoeira, Candomblé und das Erbe der Terreiros verleihen Bahia eine Schicht, die weder Rio noch Noronha bieten — die Etappe, die die Route zwischen Stadt und Insel vertieft." },
      ],
    },
    stays: {
      heading: "Wo man auf jeder Etappe übernachtet",
      intro: "Wir haben Adressen ausgewählt, die den Standard der Route von Anfang bis Ende halten, ohne Qualitätseinbußen zwischen den Etappen.",
      items: [
        { name: "Fasano Rio de Janeiro (Ipanema)", profile: "Paare und designaffine Reisende", text: "Referenzadresse am Strand von Ipanema, Architektur von Philippe Starck und einer der besten Sonnenuntergangsblicke der Stadt." },
        { name: "Hotel Fasano Salvador oder Villa Bahia (Pelourinho)", profile: "Historische Vertiefung", text: "Restaurierte Herrenhäuser im historischen Zentrum, wenige Schritte vom Pelourinho — die beste Art, in der bahianischen Geschichte zu übernachten." },
        { name: "Uxua Casa Hotel (Trancoso)", profile: "Design und Diskretion", text: "Restaurierte Fischerhäuser rund um das Quadrado, die den Barfußluxus definieren." },
        { name: "Nannai Trancoso", profile: "Familien und komfortsuchende Paare", text: "Bungalows zwischen Atlantikwald und Strand, eine der besten Resortstrukturen im Süden Bahias." },
        { name: "Pousada Maravilha (Fernando de Noronha)", profile: "Aussicht und Romantik", text: "Über dem offenen Meer schwebende Suiten, unter den meistfotografierten des Archipels." },
        { name: "Nannai oder Teju-Açu (Fernando de Noronha)", profile: "Diskreter Komfort auf der Insel", text: "Einfache, aber kompetente Struktur, im Einklang mit den strengen Umweltauflagen der Insel." },
      ],
    },
    profiles: {
      heading: "Für wen diese Route funktioniert",
      items: [
        { title: "Paare zum Jahrestag oder auf Flitterwochen", text: "Der emotionale Bogen der Route — Stadt, Geschichte, Romantik, extreme Natur — eignet sich für runde Feiern." },
        { title: "Reisende, die Rio bereits kennen", text: "Für Wiederholungsreisende in Rio empfehlen wir, auf 3 Nächte zu kürzen und Bahia und Noronha zu verlängern." },
        { title: "Familien mit Teenagern", text: "Funktioniert gut, obwohl Noronha bei Tauchgängen und Wanderungen mit kleinen Kindern besondere Aufmerksamkeit erfordert — wir empfehlen Kinder ab 8 Jahren." },
        { title: "Für wen es vielleicht nicht passt", text: "Reisende mit weniger als 10 Tagen sollten zwei Destinationen wählen, nicht drei — die Kette verliert an Qualität und wird zum Flughafensprint." },
      ],
    },
    itinerary: {
      heading: "Wie man die Route Etappe für Etappe verbindet",
      intro: "Die Flugtaktik ist entscheidend: Noronha erhält nur Direktflüge aus Recife, Natal und saisonal aus São Paulo und Rio — deshalb steht es immer am Anfang oder Ende, nie in der Mitte.",
      items: [
        { title: "Tag 1-4 — Rio de Janeiro", text: "Ankunft am Flughafen Galeão, vier Nächte für Stadt, Strände und einen Tag hinter den Kulissen (Santa Teresa, Lapa). Inlandsflug nach Salvador an Tag 5, etwa 2h Direktflug." },
        { title: "Tag 5-6 — Salvador", text: "Zwei Nächte im historischen Zentrum, genug für Pelourinho, den Lacerda-Aufzug und ein authentisches bahianisches Abendessen. Landtransfer von etwa 3h30 oder 40-minütiger Inlandsflug nach Porto Seguro, gefolgt von 1h Autofahrt nach Trancoso." },
        { title: "Tag 7-10 — Trancoso", text: "Vier Nächte der Entschleunigung, Buggyfahrten entlang der Strände Südbahias, viel Zeit am Quadrado. Rückkehr nach Porto Seguro und Flug mit Umstieg in Recife nach Fernando de Noronha." },
        { title: "Tag 11-14 — Fernando de Noronha", text: "Vier Nächte Meer, Tauchen und Wandern unter Beachtung des täglichen Besucherlimits des Meeresnationalparks. Rückflug über Recife, mit Anschluss nach Rio, São Paulo oder internationalem Ziel." },
      ],
    },
    tips: {
      heading: "Praktische Tipps für diese Route",
      items: [
        "Fernando de Noronha erhebt eine Umweltschutzgebühr pro Aufenthaltstag, zahlbar bei Ankunft oder vorab online.",
        "Das Ticket für den Meeresnationalpark ist von der Umweltgebühr getrennt und sollte in der Hochsaison im Voraus gekauft werden.",
        "Buchen Sie Flüge nach Noronha Monate im Voraus: Das Streckennetz ist begrenzt und die Preise steigen schnell.",
        "In Trancoso wird das Quadrado in der Hochsaison bei Sonnenuntergang voll — reservieren Sie einen Tisch im Voraus, wenn Sie dort essen möchten.",
        "Bringen Sie leichte Kleidung und biologisch abbaubaren Sonnenschutz mit, der in Noronha zum Schutz der Riffe vorgeschrieben ist.",
        "Planen Sie mindestens eine Pufferübernachtung rund um Umstiege in Recife, um Verspätungen abzufedern, ohne den Rest der Reise zu gefährden.",
      ],
    },
    faq: [
      { q: "Wie viele Nächte sind ideal für die Route Rio + Bahia + Noronha?", a: "Vierzehn Nächte sind das ideale Gleichgewicht: 4 in Rio, 6 in Bahia (2 in Salvador und 4 in Trancoso) und 4 in Noronha. Man kann auf 10 Nächte kürzen, indem man Salvador streicht." },
      { q: "Was ist die beste Reisezeit für diese Route?", a: "September bis März, mit dem Qualitätshöhepunkt zwischen September und November, wenn Noronha ruhigeres Meer hat und alle drei Städte mildes Klima bieten." },
      { q: "Wie fliegt man zwischen diesen drei Destinationen?", a: "Rio–Salvador ist ein Direktflug von etwa 2h. Von Salvador oder Porto Seguro nach Noronha ist ein Umstieg in Recife oder Natal nötig, den einzigen Flughäfen mit regelmäßigen Direktflügen zum Archipel." },
      { q: "Lohnt es sich, Trancoso einzuplanen oder direkt von Salvador nach Noronha zu fliegen?", a: "Trancoso fügt die Schicht der Entschleunigung und des bohemienhaften Dorfes hinzu, die weder Salvador noch Noronha bieten — empfohlen für Routen ab 12 Nächten." },
      { q: "Muss man Fernando de Noronha weit im Voraus buchen?", a: "Ja. Die Insel begrenzt die tägliche Besucherzahl und das Flugnetz ist limitiert; wir empfehlen, Flüge und Unterkünfte 4 bis 6 Monate im Voraus in der Hochsaison zu buchen." },
      { q: "Funktioniert diese Route für Familien?", a: "Ja, besonders mit Kindern ab 8 Jahren. Noronha erfordert bei jüngeren Kindern wegen Wanderwegen und Tauchgängen im offenen Meer besondere Aufmerksamkeit." },
    ],
    cta: {
      heading: "Lassen Sie uns Ihre Rio + Bahia + Noronha-Route gestalten",
      subheading: "Ein persönlicher Berater von Create Travel passt Nächte, Flüge und Adressen an Ihr Tempo an — ohne Zeitverlust durch schlecht geplante Verbindungen.",
      button: "Mit einem Travel Designer sprechen",
    },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },
};
