import type { BrazilGuideLocalized } from "./types";

export const conjugadoBelemMarajoAlterGuide: BrazilGuideLocalized = {
  pt: {
    destinationName: "Belém + Ilha de Marajó + Alter do Chão",
    blurb: "A Amazônia paraense por inteiro: cidade histórica, ilha de búfalos, praias de rio e floresta profunda, em 13 noites.",
    metaTitle: "Belém + Marajó + Alter do Chão: roteiro conjugado de 13 noites",
    metaDescription: "Como combinar Belém, a Ilha de Marajó, Alter do Chão e um lodge de floresta no Rio Negro ou em Mamirauá em uma única viagem: logística real de travessias e voos, melhor janela (setembro a novembro) e onde ficar em cada trecho.",
    keywords: "belem marajo alter do chao roteiro, viagem para marajo, alter do chao roteiro, ilha do combu belem, ver-o-peso, praias de rio tapajos, lodge rio negro, mamiraua reserva",
    h1: "Belém + Ilha de Marajó + Alter do Chão: o roteiro conjugado da Amazônia paraense",
    aiAnswer: "O roteiro que combina Belém, Ilha de Marajó e Alter do Chão dura cerca de 13 noites: 3 em Belém, 3 em Marajó (via ferry/lancha a partir de Icoaraci), 3 em Alter do Chão/Tapajós (voo Belém–Santarém) e 4 em um lodge de floresta no Rio Negro (via Manaus) ou na Reserva Mamirauá (via Tefé), na janela seca de setembro a novembro, quando as praias de rio do Tapajós e Marajó estão no auge.",
    intro: [
      "Belém não é escala: é a porta de entrada para uma Amazônia que poucos roteiros exploram por inteiro. A cidade histórica do Grão-Pará dá lugar, a poucas horas de barco, à savana alagada de búfalos da Ilha de Marajó; e, com um voo curto, às praias de água doce de Alter do Chão, no rio Tapajós. Fechar a viagem em um lodge de floresta profunda — no Rio Negro ou em Mamirauá — completa o quadro: cidade, ilha, praia de rio e selva, quatro paisagens amazônicas que raramente aparecem juntas num mesmo itinerário.",
      "Este guia é conjugado por desenho: trata a travessia de Icoaraci a Soure, o voo Belém–Santarém e a conexão final via Manaus ou Tefé como parte de uma única lógica de viagem de referência, de cerca de 13 noites, com a janela climática e o número de noites por trecho que fazem os quatro destinos funcionarem em sequência.",
    ],
    seasons: {
      heading: "A janela certa: setembro a novembro",
      intro: "O Pará e o baixo Amazonas têm um regime de chuvas que concentra o período seco entre agosto e dezembro — é nessa janela, e sobretudo entre setembro e novembro, que o roteiro conjugado rende mais.",
      windows: [
        { window: "Agosto — início da vazante", text: "Os rios começam a baixar, as primeiras praias de areia branca aparecem no Tapajós e em Marajó, e o calor ainda é ameno em comparação aos meses seguintes. Boa janela para quem prioriza menor movimento de visitantes." },
        { window: "Setembro a novembro — auge da seca e das praias de rio", text: "As praias de Alter do Chão e do Tapajós atingem sua extensão máxima, os búfalos de Marajó se concentram nos campos mais secos e a navegação entre Icoaraci e Soure é mais estável. É a janela mais recomendada para o roteiro completo." },
        { window: "Dezembro a fevereiro — transição, ainda viável", text: "As primeiras chuvas isoladas já ocorrem, mas as praias de rio ainda existem e a paisagem fica mais verde. Alternativa razoável para quem não consegue viajar no pico da seca." },
        { window: "Março a julho — evitar as praias de rio", text: "A cheia amazônica submerge as praias do Tapajós e de Marajó; é a melhor época para canoagem em igarapés alagados, mas sem sinergia com o roteiro de praias e savanas propostas aqui." },
      ],
    },
    experiences: {
      heading: "O que se vive em cada etapa",
      intro: "Cada trecho da viagem entrega uma paisagem amazônica distinta — a soma das quatro é o que torna este roteiro raro.",
      items: [
        { title: "Ver-o-Peso e Ilha do Combu, Belém (etapa 1)", text: "O maior mercado a céu aberto da Amazônia ao amanhecer, com o cheiro de peixe fresco e ervas, seguido de uma tarde na Ilha do Combu, entre roças de cacau e restaurantes flutuantes de mão paraense." },
        { title: "Gastronomia amazônica em Belém (etapa 1)", text: "Tacacá nas barracas de rua ao entardecer, maniçoba de cozimento lento e pato no tucupi — uma das cozinhas regionais mais autorais do Brasil, reconhecida internacionalmente." },
        { title: "Fazendas de búfalo e Praia do Pesqueiro, Marajó (etapa 2)", text: "Cavalgadas e passeios de charrete entre búfalos que superam em número os habitantes da ilha, e tardes nas praias de água doce e areia clara voltadas para a Baía do Marajó." },
        { title: "Soure e os rios de Marajó (etapa 2)", text: "Passeios de bicicleta pelas ruas arenosas de Soure, observação de aves em igarapés e visitas a queijarias artesanais de búfala, tradição que remonta ao século XIX." },
        { title: "Praias de água doce de Alter do Chão (etapa 3)", text: "A ""Ilha do Amor"" e suas dunas de areia branca sobre o Rio Tapajós, com água cristalina de tom turquesa — um dos cenários mais fotografados da Amazônia na estação seca." },
        { title: "Floresta Nacional do Tapajós e Rio Arapiuns (etapa 3)", text: "Trilhas guiadas por comunidades ribeirinhas dentro da floresta nacional, e passeios de barco pelo Arapiuns, com águas escuras emolduradas por floresta intacta." },
        { title: "Lodge de floresta no Rio Negro ou em Mamirauá (etapa 4)", text: "Quatro noites finais de imersão profunda: canoagem entre igarapés e observação de botos-cor-de-rosa no Rio Negro, ou os lagos sazonalmente alagados e os macacos-uacari de Mamirauá, uma das reservas de fauna mais bem manejadas da Amazônia." },
      ],
    },
    stays: {
      heading: "Onde ficar em cada trecho",
      intro: "A escolha certa de base muda o ritmo e o conforto de cada etapa da viagem.",
      items: [
        { name: "Hotéis históricos do centro de Belém", profile: "Cidade e gastronomia", text: "Endereços próximos ao Ver-o-Peso e à Estação das Docas, ideais para explorar a pé o centro histórico e a cena gastronômica noturna." },
        { name: "Pousadas de praia em Soure, Marajó", profile: "Ilha e búfalos", text: "Pequenas pousadas junto à Praia do Pesqueiro ou ao centro de Soure, ponto de partida para cavalgadas e passeios às fazendas de búfalo." },
        { name: "Pousadas à beira do Tapajós, Alter do Chão", profile: "Praias de rio", text: "Endereços de charme com vista para o rio e para a Ilha do Amor, a poucos minutos a pé do vilarejo e do embarcadouro para o Arapiuns." },
        { name: "Lodges de floresta no Rio Negro (via Manaus)", profile: "Imersão final, conforto elevado", text: "Bangalôs voltados para o rio, com guias de altíssimo nível para canoagem, focagem noturna e observação de botos." },
        { name: "Pousada Uacari, Reserva Mamirauá (via Tefé)", profile: "Fauna e manejo científico", text: "Flutuante sobre o lago, gerido por instituto de pesquisa, com a maior concentração documentada de macacos-uacari-branco do mundo." },
      ],
    },
    profiles: {
      heading: "Para quem funciona este roteiro conjugado",
      items: [
        { title: "Casais e viajantes maduros em busca de profundidade cultural e natural", text: "Um roteiro que combina cidade histórica, cultura ribeirinha, praias inéditas e floresta densa sem repetir paisagem em nenhuma etapa." },
        { title: "Gastrônomos e apreciadores de cultura regional", text: "Belém sozinha já justifica uma viagem para quem se interessa por culinária autoral brasileira; somada a Marajó e Alter do Chão, forma um panorama cultural raro." },
        { title: "Para quem talvez não funcione", text: "Viajantes com menos de 10 dias disponíveis ou que buscam apenas observação intensiva de fauna (onças, por exemplo) devem considerar um roteiro focado em Mamirauá ou no Pantanal, não esta combinação de quatro etapas." },
      ],
    },
    itinerary: {
      heading: "O encadeamento dia a dia: 13 noites de referência",
      intro: "A lógica do roteiro é sempre cidade primeiro, depois ilha, depois praia de rio, e floresta profunda por último — a etapa de imersão mais intensa rende mais estando o viajante já adaptado ao calor e ao ritmo amazônico.",
      items: [
        { title: "Noites 1 a 3 — Belém", text: "Chegada ao Aeroporto Internacional de Belém, três noites na cidade com visitas ao Ver-o-Peso, à Ilha do Combu e ao circuito gastronômico, incluindo uma manhã inteira dedicada ao mercado." },
        { title: "Travessia — Icoaraci a Soure", text: "Traslado terrestre até o porto de Icoaraci, seguido de travessia de ferry (cerca de 3 horas) ou lancha rápida (cerca de 1h30) até Soure, na Ilha de Marajó; recomenda-se sair pela manhã para evitar ventos da tarde." },
        { title: "Noites 4 a 6 — Ilha de Marajó", text: "Três noites em Soure, com cavalgadas às fazendas de búfalo, tardes na Praia do Pesqueiro e visita a uma queijaria artesanal de búfala." },
        { title: "Trânsito — Marajó a Alter do Chão via Belém e Santarém", text: "Retorno de barco a Icoaraci/Belém, seguido de voo doméstico Belém–Santarém (cerca de 1 hora) e traslado terrestre de aproximadamente 40 minutos até Alter do Chão." },
        { title: "Noites 7 a 9 — Alter do Chão e Rio Tapajós", text: "Três noites com dias na Ilha do Amor, trilha na Floresta Nacional do Tapajós e passeio de barco pelo Rio Arapiuns entre comunidades ribeirinhas." },
        { title: "Trânsito — Santarém a Manaus ou a Tefé", text: "Voo doméstico Santarém–Manaus (cerca de 1h) para quem segue ao Rio Negro, ou Santarém–Tefé com conexão em Manaus para quem opta por Mamirauá, seguido de traslado fluvial até o lodge." },
        { title: "Noites 10 a 13 — Lodge de floresta (Rio Negro ou Mamirauá)", text: "Quatro noites de imersão final, com canoagem, focagem noturna, observação de botos ou de macacos-uacari, antes do voo de saída via Manaus." },
      ],
    },
    tips: {
      heading: "Dicas práticas para o roteiro conjugado",
      items: [
        "Reserve a travessia Icoaraci–Soure com antecedência e prefira o horário da manhã, quando a Baía do Marajó está mais calma.",
        "Confirme os horários de voo Belém–Santarém com folga: são poucas frequências diárias e cancelamentos por chuva forte não são raros mesmo na estação seca.",
        "Leve roupa de banho e protetor solar biodegradável desde a saída de Belém — as praias de Marajó e Alter do Chão aparecem já nos primeiros dias.",
        "Vacina de febre amarela é exigida para toda a região e deve ser tomada com pelo menos dez dias de antecedência.",
        "Dinheiro em espécie ainda é necessário em Soure e nas comunidades ribeirinhas do Arapiuns, onde cartões nem sempre funcionam.",
        "Se optar por Mamirauá em vez do Rio Negro, reserve com grande antecedência: a Pousada Uacari tem número limitado de acomodações por ser gerida por instituto de pesquisa.",
      ],
    },
    faq: [
      { q: "Quantas noites são necessárias para o roteiro Belém + Marajó + Alter do Chão?", a: "Cerca de 13 noites, sendo 3 em Belém, 3 em Marajó, 3 em Alter do Chão e 4 em um lodge de floresta final no Rio Negro ou em Mamirauá." },
      { q: "Como se vai de Belém à Ilha de Marajó?", a: "Por travessia fluvial a partir do porto de Icoaraci, em Belém, por ferry (cerca de 3 horas) ou lancha rápida (cerca de 1h30) até Soure." },
      { q: "Existe voo direto entre Belém e Alter do Chão?", a: "Não; voa-se de Belém a Santarém (cerca de 1 hora) e segue-se por terra por aproximadamente 40 minutos até Alter do Chão." },
      { q: "Qual é a melhor época para as praias de rio de Marajó e Alter do Chão?", a: "Entre setembro e novembro, no auge da estação seca, quando as praias atingem sua extensão máxima e os rios estão mais baixos." },
      { q: "Vale mais a pena fechar a viagem no Rio Negro ou em Mamirauá?", a: "O Rio Negro, via Manaus, tem acesso mais direto e infraestrutura de lodges mais ampla; Mamirauá, via Tefé, exige mais logística mas oferece uma das reservas de fauna mais bem manejadas da Amazônia, com avistamento praticamente garantido de macaco-uacari." },
      { q: "Quanto custa este roteiro conjugado com a Create Travel?", a: "Não trabalhamos com valores de prateleira: o orçamento depende dos lodges, da época e do trecho final escolhido. Um consultor humano monta a proposta por escrito." },
    ],
    cta: { heading: "Vamos desenhar seu roteiro Belém + Marajó + Alter do Chão", subheading: "Um consultor humano da Create Travel monta as travessias, os voos e a janela certa para os quatro trechos.", button: "Falar com um travel designer" },
    readingMinutes: 13,
    publishedAt: "2026-08-11",
  },

  en: {
    destinationName: "Belém + Marajó Island + Alter do Chão",
    blurb: "The Amazon of Pará in full: a historic city, a buffalo island, river beaches and deep rainforest, over 13 nights.",
    metaTitle: "Belém + Marajó + Alter do Chão: A Combined 13-Night Itinerary",
    metaDescription: "How to combine Belém, Marajó Island, Alter do Chão and a rainforest lodge on the Rio Negro or in Mamirauá in one trip: real crossing and flight logistics, best window (September–November) and where to stay on each leg.",
    keywords: "belem marajo alter do chao itinerary, marajo island trip, alter do chao itinerary, combu island belem, ver-o-peso market, tapajos river beaches, rio negro lodge, mamiraua reserve",
    h1: "Belém + Marajó Island + Alter do Chão: the combined itinerary of the Amazon of Pará",
    aiAnswer: "The itinerary combining Belém, Marajó Island and Alter do Chão lasts about 13 nights: 3 in Belém, 3 on Marajó (via ferry/speedboat from Icoaraci), 3 in Alter do Chão/Tapajós (flight from Belém to Santarém) and 4 at a rainforest lodge on the Rio Negro (via Manaus) or the Mamirauá Reserve (via Tefé), in the dry-season window from September to November, when the river beaches of Tapajós and Marajó peak.",
    intro: [
      "Belém is not a stopover: it is the gateway to an Amazon few itineraries explore in full. The historic city of Grão-Pará gives way, a few hours by boat away, to the flooded buffalo savanna of Marajó Island; and, with a short flight, to the freshwater beaches of Alter do Chão on the Tapajós River. Closing the trip at a deep-forest lodge — on the Rio Negro or in Mamirauá — completes the picture: city, island, river beach and rainforest, four Amazonian landscapes that rarely appear together in the same itinerary.",
      "This guide is combined by design: it treats the crossing from Icoaraci to Soure, the Belém–Santarém flight and the final connection via Manaus or Tefé as part of a single reference-trip logic, roughly 13 nights long, with the climate window and nights per leg that make the four destinations work in sequence.",
    ],
    seasons: {
      heading: "The right window: September to November",
      intro: "Pará and the lower Amazon have a rainfall pattern that concentrates the dry period between August and December — it is in this window, and especially between September and November, that the combined itinerary pays off most.",
      windows: [
        { window: "August — early low-water season", text: "Rivers begin to drop, the first white-sand beaches appear on the Tapajós and Marajó, and the heat is still milder than in the following months. A good window for those prioritising fewer visitors." },
        { window: "September to November — peak dry season and river beaches", text: "Alter do Chão and Tapajós beaches reach their maximum extent, Marajó's buffalo herds concentrate in the driest fields, and navigation between Icoaraci and Soure is more stable. The most recommended window for the full itinerary." },
        { window: "December to February — transition, still workable", text: "The first isolated rains have already started, but river beaches still exist and the landscape turns greener. A reasonable alternative for those unable to travel at the peak of the dry season." },
        { window: "March to July — avoid the river beaches", text: "The Amazon flood submerges the beaches of the Tapajós and Marajó; the best time for canoeing through flooded creeks, but with no synergy with the beach-and-savanna itinerary proposed here." },
      ],
    },
    experiences: {
      heading: "What each leg delivers",
      intro: "Each leg of the trip delivers a distinct Amazonian landscape — the sum of all four is what makes this itinerary rare.",
      items: [
        { title: "Ver-o-Peso and Combu Island, Belém (leg 1)", text: "The largest open-air market in the Amazon at dawn, with the smell of fresh fish and herbs, followed by an afternoon on Combu Island, among cacao groves and floating restaurants of local craftsmanship." },
        { title: "Amazonian cuisine in Belém (leg 1)", text: "Tacacá from street stalls at dusk, slow-cooked maniçoba and duck in tucupi — one of Brazil's most distinctive regional cuisines, internationally recognized." },
        { title: "Buffalo ranches and Pesqueiro Beach, Marajó (leg 2)", text: "Horseback and cart rides among buffalo that outnumber the island's human residents, and afternoons on freshwater beaches with pale sand facing Marajó Bay." },
        { title: "Soure and Marajó's rivers (leg 2)", text: "Bicycle rides through Soure's sandy streets, birdwatching along creeks, and visits to artisanal buffalo-cheese dairies, a tradition dating back to the 19th century." },
        { title: "Freshwater beaches of Alter do Chão (leg 3)", text: "The ""Ilha do Amor"" and its white-sand dunes over the Tapajós River, with crystal-clear turquoise water — one of the most photographed settings in the Amazon during the dry season." },
        { title: "Tapajós National Forest and the Arapiuns River (leg 3)", text: "Guided trails led by riverside communities inside the national forest, and boat trips along the Arapiuns, with dark waters framed by untouched forest." },
        { title: "Rainforest lodge on the Rio Negro or in Mamirauá (leg 4)", text: "Four final nights of deep immersion: canoeing through creeks and watching pink river dolphins on the Rio Negro, or the seasonally flooded lakes and uacari monkeys of Mamirauá, one of the best-managed wildlife reserves in the Amazon." },
      ],
    },
    stays: {
      heading: "Where to stay on each leg",
      intro: "The right base changes the pace and comfort of each leg of the trip.",
      items: [
        { name: "Historic hotels in downtown Belém", profile: "City and cuisine", text: "Addresses close to Ver-o-Peso and Estação das Docas, ideal for exploring the historic center on foot and the evening dining scene." },
        { name: "Beach guesthouses in Soure, Marajó", profile: "Island and buffalo", text: "Small guesthouses near Pesqueiro Beach or downtown Soure, the launch point for horseback rides and buffalo-ranch visits." },
        { name: "Riverside guesthouses in Alter do Chão", profile: "River beaches", text: "Charming addresses overlooking the river and Ilha do Amor, a short walk from the village and the pier to the Arapiuns." },
        { name: "Rainforest lodges on the Rio Negro (via Manaus)", profile: "Final immersion, elevated comfort", text: "River-facing bungalows with top-tier guides for canoeing, night spotting and dolphin watching." },
        { name: "Pousada Uacari, Mamirauá Reserve (via Tefé)", profile: "Wildlife and scientific management", text: "Floating lodge on the lake, run by a research institute, with the highest documented concentration of white uacari monkeys in the world." },
      ],
    },
    profiles: {
      heading: "Who this combined itinerary suits",
      items: [
        { title: "Couples and seasoned travellers seeking cultural and natural depth", text: "An itinerary combining historic city, riverside culture, uncommon beaches and dense rainforest without repeating scenery at any stage." },
        { title: "Food lovers and regional culture enthusiasts", text: "Belém alone justifies a trip for those interested in authentic Brazilian cuisine; combined with Marajó and Alter do Chão, it forms a rare cultural panorama." },
        { title: "For whom this might not work", text: "Travellers with fewer than 10 days available, or seeking only intensive wildlife watching (jaguars, for instance), should consider a Mamirauá- or Pantanal-focused itinerary instead of this four-leg combination." },
      ],
    },
    itinerary: {
      heading: "Day-by-day flow: a 13-night reference plan",
      intro: "The itinerary's logic is always city first, then island, then river beach, and deep rainforest last — the most intensive immersion leg pays off more once the traveller is already adapted to the Amazonian heat and pace.",
      items: [
        { title: "Nights 1–3 — Belém", text: "Arrival at Belém International Airport, three nights in the city with visits to Ver-o-Peso, Combu Island and the food circuit, including a full morning dedicated to the market." },
        { title: "Crossing — Icoaraci to Soure", text: "Ground transfer to the port of Icoaraci, followed by a ferry crossing (about 3 hours) or fast boat (about 1h30) to Soure, on Marajó Island; a morning departure is recommended to avoid afternoon winds." },
        { title: "Nights 4–6 — Marajó Island", text: "Three nights in Soure, with horseback rides to buffalo ranches, afternoons at Pesqueiro Beach and a visit to an artisanal buffalo-cheese dairy." },
        { title: "Transit — Marajó to Alter do Chão via Belém and Santarém", text: "Return by boat to Icoaraci/Belém, followed by a domestic flight from Belém to Santarém (about 1 hour) and a ground transfer of roughly 40 minutes to Alter do Chão." },
        { title: "Nights 7–9 — Alter do Chão and the Tapajós River", text: "Three nights with days on Ilha do Amor, a hike in Tapajós National Forest and a boat trip along the Arapiuns River among riverside communities." },
        { title: "Transit — Santarém to Manaus or Tefé", text: "Domestic flight from Santarém to Manaus (about 1 hour) for those continuing to the Rio Negro, or Santarém–Tefé with a connection in Manaus for those choosing Mamirauá, followed by a river transfer to the lodge." },
        { title: "Nights 10–13 — Rainforest lodge (Rio Negro or Mamirauá)", text: "Four final nights of immersion, with canoeing, night spotting, dolphin watching or uacari monkey sightings, before the departure flight via Manaus." },
      ],
    },
    tips: {
      heading: "Practical tips for the combined itinerary",
      items: [
        "Book the Icoaraci–Soure crossing in advance and prefer the morning departure, when Marajó Bay is calmer.",
        "Confirm Belém–Santarém flight times with buffer: frequencies are limited and cancellations due to heavy rain are not rare even in the dry season.",
        "Pack swimwear and biodegradable sunscreen from the outset — Marajó and Alter do Chão's beaches appear within the first days.",
        "Yellow fever vaccination is required for the whole region and should be taken at least ten days before departure.",
        "Cash is still needed in Soure and the riverside communities along the Arapiuns, where cards do not always work.",
        "If choosing Mamirauá over the Rio Negro, book well in advance: Pousada Uacari has a limited number of rooms as it is run by a research institute.",
      ],
    },
    faq: [
      { q: "How many nights are needed for the Belém + Marajó + Alter do Chão itinerary?", a: "About 13 nights: 3 in Belém, 3 on Marajó, 3 in Alter do Chão and 4 at a final rainforest lodge on the Rio Negro or in Mamirauá." },
      { q: "How do you get from Belém to Marajó Island?", a: "By river crossing from the port of Icoaraci, in Belém, by ferry (about 3 hours) or fast boat (about 1h30) to Soure." },
      { q: "Is there a direct flight between Belém and Alter do Chão?", a: "No; you fly from Belém to Santarém (about 1 hour) and continue by road for approximately 40 minutes to Alter do Chão." },
      { q: "What is the best time for the river beaches of Marajó and Alter do Chão?", a: "Between September and November, at the peak of the dry season, when the beaches reach their maximum extent and rivers are at their lowest." },
      { q: "Is it better to end the trip on the Rio Negro or in Mamirauá?", a: "The Rio Negro, via Manaus, offers more direct access and a wider lodge infrastructure; Mamirauá, via Tefé, requires more logistics but offers one of the best-managed wildlife reserves in the Amazon, with near-guaranteed uacari monkey sightings." },
      { q: "How much does this combined itinerary cost with Create Travel?", a: "We do not work with fixed price lists: the budget depends on the lodges, the season and the chosen final leg. A human consultant puts together a written proposal." },
    ],
    cta: { heading: "Let's design your Belém + Marajó + Alter do Chão itinerary", subheading: "A human consultant from Create Travel arranges the crossings, the flights and the right window for the four legs.", button: "Talk to a travel designer" },
    readingMinutes: 13,
    publishedAt: "2026-08-11",
  },

  es: {
    destinationName: "Belém + Isla de Marajó + Alter do Chão",
    blurb: "La Amazonía de Pará en su totalidad: ciudad histórica, isla de búfalos, playas de río y selva profunda, en 13 noches.",
    metaTitle: "Belém + Marajó + Alter do Chão: itinerario combinado de 13 noches",
    metaDescription: "Cómo combinar Belém, la Isla de Marajó, Alter do Chão y un lodge de selva en el Río Negro o en Mamirauá en un solo viaje: logística real de travesías y vuelos, mejor ventana (septiembre a noviembre) y dónde alojarse en cada tramo.",
    keywords: "belem marajo alter do chao itinerario, viaje a marajo, alter do chao itinerario, isla del combu belem, ver-o-peso, playas de rio tapajos, lodge rio negro, reserva mamiraua",
    h1: "Belém + Isla de Marajó + Alter do Chão: el itinerario combinado de la Amazonía de Pará",
    aiAnswer: "El itinerario que combina Belém, la Isla de Marajó y Alter do Chão dura unas 13 noches: 3 en Belém, 3 en Marajó (vía ferry/lancha desde Icoaraci), 3 en Alter do Chão/Tapajós (vuelo Belém–Santarém) y 4 en un lodge de selva en el Río Negro (vía Manaus) o en la Reserva Mamirauá (vía Tefé), en la ventana seca de septiembre a noviembre, cuando las playas de río del Tapajós y de Marajó están en su punto máximo.",
    intro: [
      "Belém no es una escala: es la puerta de entrada a una Amazonía que pocos itinerarios exploran por completo. La ciudad histórica del Grão-Pará da paso, a pocas horas en barco, a la sabana inundada de búfalos de la Isla de Marajó; y, con un vuelo corto, a las playas de agua dulce de Alter do Chão, en el río Tapajós. Cerrar el viaje en un lodge de selva profunda —en el Río Negro o en Mamirauá— completa el cuadro: ciudad, isla, playa de río y selva, cuatro paisajes amazónicos que rara vez aparecen juntos en un mismo itinerario.",
      "Esta guía está pensada como combinada por diseño: trata la travesía de Icoaraci a Soure, el vuelo Belém–Santarém y la conexión final vía Manaus o Tefé como parte de una única lógica de viaje de referencia, de unas 13 noches, con la ventana climática y el número de noches por tramo que hacen que los cuatro destinos funcionen en secuencia.",
    ],
    seasons: {
      heading: "La ventana adecuada: septiembre a noviembre",
      intro: "Pará y el bajo Amazonas tienen un régimen de lluvias que concentra el período seco entre agosto y diciembre — es en esa ventana, y sobre todo entre septiembre y noviembre, cuando el itinerario combinado rinde más.",
      windows: [
        { window: "Agosto — inicio de la bajante", text: "Los ríos comienzan a bajar, aparecen las primeras playas de arena blanca en el Tapajós y en Marajó, y el calor todavía es más suave que en los meses siguientes. Buena ventana para quienes priorizan menos afluencia de visitantes." },
        { window: "Septiembre a noviembre — apogeo de la seca y de las playas de río", text: "Las playas de Alter do Chão y del Tapajós alcanzan su extensión máxima, los búfalos de Marajó se concentran en los campos más secos y la navegación entre Icoaraci y Soure es más estable. Es la ventana más recomendada para el itinerario completo." },
        { window: "Diciembre a febrero — transición, todavía viable", text: "Ya ocurren las primeras lluvias aisladas, pero las playas de río todavía existen y el paisaje se vuelve más verde. Alternativa razonable para quienes no pueden viajar en el pico de la seca." },
        { window: "Marzo a julio — evitar las playas de río", text: "La crecida amazónica sumerge las playas del Tapajós y de Marajó; es la mejor época para el piragüismo en igarapés inundados, pero sin sinergia con el itinerario de playas y sabanas propuesto aquí." },
      ],
    },
    experiences: {
      heading: "Lo que se vive en cada etapa",
      intro: "Cada tramo del viaje ofrece un paisaje amazónico distinto — la suma de los cuatro es lo que hace raro a este itinerario.",
      items: [
        { title: "Ver-o-Peso e Isla del Combu, Belém (etapa 1)", text: "El mayor mercado al aire libre de la Amazonía al amanecer, con el olor a pescado fresco y hierbas, seguido de una tarde en la Isla del Combu, entre plantaciones de cacao y restaurantes flotantes de sabor local." },
        { title: "Gastronomía amazónica en Belém (etapa 1)", text: "Tacacá en los puestos callejeros al atardecer, maniçoba de cocción lenta y pato al tucupi — una de las cocinas regionales más distintivas de Brasil, reconocida internacionalmente." },
        { title: "Haciendas de búfalos y Playa de Pesqueiro, Marajó (etapa 2)", text: "Cabalgatas y paseos en carreta entre búfalos que superan en número a los habitantes de la isla, y tardes en playas de agua dulce y arena clara frente a la Bahía de Marajó." },
        { title: "Soure y los ríos de Marajó (etapa 2)", text: "Paseos en bicicleta por las calles arenosas de Soure, observación de aves en igarapés y visitas a queserías artesanales de búfala, tradición que se remonta al siglo XIX." },
        { title: "Playas de agua dulce de Alter do Chão (etapa 3)", text: "La ""Ilha do Amor"" y sus dunas de arena blanca sobre el Río Tapajós, con agua cristalina de tono turquesa — uno de los escenarios más fotografiados de la Amazonía en la estación seca." },
        { title: "Bosque Nacional del Tapajós y Río Arapiuns (etapa 3)", text: "Senderos guiados por comunidades ribereñas dentro del bosque nacional, y paseos en barco por el Arapiuns, con aguas oscuras enmarcadas por selva intacta." },
        { title: "Lodge de selva en el Río Negro o en Mamirauá (etapa 4)", text: "Cuatro noches finales de inmersión profunda: piragüismo entre igarapés y observación de delfines rosados en el Río Negro, o los lagos inundados estacionalmente y los monos uacarí de Mamirauá, una de las reservas de fauna mejor gestionadas de la Amazonía." },
      ],
    },
    stays: {
      heading: "Dónde alojarse en cada tramo",
      intro: "La base correcta cambia el ritmo y la comodidad de cada etapa del viaje.",
      items: [
        { name: "Hoteles históricos del centro de Belém", profile: "Ciudad y gastronomía", text: "Direcciones cercanas al Ver-o-Peso y a la Estação das Docas, ideales para explorar a pie el centro histórico y la escena gastronómica nocturna." },
        { name: "Posadas de playa en Soure, Marajó", profile: "Isla y búfalos", text: "Pequeñas posadas junto a la Playa de Pesqueiro o en el centro de Soure, punto de partida para cabalgatas y visitas a haciendas de búfalos." },
        { name: "Posadas junto al Tapajós, Alter do Chão", profile: "Playas de río", text: "Direcciones con encanto y vista al río y a la Ilha do Amor, a pocos minutos a pie del pueblo y del embarcadero hacia el Arapiuns." },
        { name: "Lodges de selva en el Río Negro (vía Manaus)", profile: "Inmersión final, alto confort", text: "Bungalós frente al río, con guías de altísimo nivel para piragüismo, observación nocturna y avistamiento de delfines." },
        { name: "Pousada Uacari, Reserva Mamirauá (vía Tefé)", profile: "Fauna y gestión científica", text: "Flotante sobre el lago, gestionada por un instituto de investigación, con la mayor concentración documentada de monos uacarí blanco del mundo." },
      ],
    },
    profiles: {
      heading: "Para quién funciona este itinerario combinado",
      items: [
        { title: "Parejas y viajeros experimentados en busca de profundidad cultural y natural", text: "Un itinerario que combina ciudad histórica, cultura ribereña, playas poco comunes y selva densa sin repetir paisaje en ninguna etapa." },
        { title: "Amantes de la gastronomía y de la cultura regional", text: "Belém por sí sola ya justifica un viaje para quienes se interesan por la cocina brasileña de autor; sumada a Marajó y Alter do Chão, forma un panorama cultural poco frecuente." },
        { title: "Para quién quizá no funcione", text: "Viajeros con menos de 10 días disponibles o que buscan solo observación intensiva de fauna (jaguares, por ejemplo) deberían considerar un itinerario centrado en Mamirauá o en el Pantanal, no esta combinación de cuatro etapas." },
      ],
    },
    itinerary: {
      heading: "El encadenamiento día a día: 13 noches de referencia",
      intro: "La lógica del itinerario es siempre ciudad primero, luego isla, luego playa de río, y selva profunda al final — la etapa de inmersión más intensa rinde más cuando el viajero ya está adaptado al calor y al ritmo amazónico.",
      items: [
        { title: "Noches 1 a 3 — Belém", text: "Llegada al Aeropuerto Internacional de Belém, tres noches en la ciudad con visitas al Ver-o-Peso, a la Isla del Combu y al circuito gastronómico, incluyendo una mañana entera dedicada al mercado." },
        { title: "Travesía — Icoaraci a Soure", text: "Traslado terrestre hasta el puerto de Icoaraci, seguido de travesía en ferry (unas 3 horas) o lancha rápida (aproximadamente 1h30) hasta Soure, en la Isla de Marajó; se recomienda salir por la mañana para evitar vientos de la tarde." },
        { title: "Noches 4 a 6 — Isla de Marajó", text: "Tres noches en Soure, con cabalgatas a las haciendas de búfalos, tardes en la Playa de Pesqueiro y visita a una quesería artesanal de búfala." },
        { title: "Tránsito — Marajó a Alter do Chão vía Belém y Santarém", text: "Regreso en barco a Icoaraci/Belém, seguido de vuelo doméstico Belém–Santarém (aproximadamente 1 hora) y traslado terrestre de unos 40 minutos hasta Alter do Chão." },
        { title: "Noches 7 a 9 — Alter do Chão y Río Tapajós", text: "Tres noches con días en la Ilha do Amor, senderismo en el Bosque Nacional del Tapajós y paseo en barco por el Río Arapiuns entre comunidades ribereñas." },
        { title: "Tránsito — Santarém a Manaus o a Tefé", text: "Vuelo doméstico Santarém–Manaus (aproximadamente 1h) para quienes continúan hacia el Río Negro, o Santarém–Tefé con conexión en Manaus para quienes eligen Mamirauá, seguido de traslado fluvial hasta el lodge." },
        { title: "Noches 10 a 13 — Lodge de selva (Río Negro o Mamirauá)", text: "Cuatro noches finales de inmersión, con piragüismo, observación nocturna, avistamiento de delfines o de monos uacarí, antes del vuelo de salida vía Manaus." },
      ],
    },
    tips: {
      heading: "Consejos prácticos para el itinerario combinado",
      items: [
        "Reserve la travesía Icoaraci–Soure con antelación y prefiera el horario de la mañana, cuando la Bahía de Marajó está más calmada.",
        "Confirme los horarios del vuelo Belém–Santarém con margen: hay pocas frecuencias diarias y las cancelaciones por lluvias fuertes no son raras incluso en la estación seca.",
        "Lleve traje de baño y protector solar biodegradable desde la salida de Belém — las playas de Marajó y Alter do Chão aparecen ya en los primeros días.",
        "La vacuna de la fiebre amarilla es obligatoria en toda la región y debe aplicarse al menos diez días antes de la salida.",
        "El efectivo sigue siendo necesario en Soure y en las comunidades ribereñas del Arapiuns, donde las tarjetas no siempre funcionan.",
        "Si opta por Mamirauá en lugar del Río Negro, reserve con mucha antelación: la Pousada Uacari tiene un número limitado de habitaciones por ser gestionada por un instituto de investigación.",
      ],
    },
    faq: [
      { q: "¿Cuántas noches se necesitan para el itinerario Belém + Marajó + Alter do Chão?", a: "Unas 13 noches: 3 en Belém, 3 en Marajó, 3 en Alter do Chão y 4 en un lodge de selva final en el Río Negro o en Mamirauá." },
      { q: "¿Cómo se llega de Belém a la Isla de Marajó?", a: "Por travesía fluvial desde el puerto de Icoaraci, en Belém, en ferry (unas 3 horas) o lancha rápida (aproximadamente 1h30) hasta Soure." },
      { q: "¿Existe vuelo directo entre Belém y Alter do Chão?", a: "No; se vuela de Belém a Santarém (aproximadamente 1 hora) y se continúa por tierra unos 40 minutos hasta Alter do Chão." },
      { q: "¿Cuál es la mejor época para las playas de río de Marajó y Alter do Chão?", a: "Entre septiembre y noviembre, en el apogeo de la estación seca, cuando las playas alcanzan su extensión máxima y los ríos están más bajos." },
      { q: "¿Conviene más cerrar el viaje en el Río Negro o en Mamirauá?", a: "El Río Negro, vía Manaus, tiene un acceso más directo y una infraestructura de lodges más amplia; Mamirauá, vía Tefé, exige más logística pero ofrece una de las reservas de fauna mejor gestionadas de la Amazonía, con avistamiento prácticamente garantizado de mono uacarí." },
      { q: "¿Cuánto cuesta este itinerario combinado con Create Travel?", a: "No trabajamos con listas de precios fijas: el presupuesto depende de los lodges, la época y el tramo final elegido. Un consultor humano elabora la propuesta por escrito." },
    ],
    cta: { heading: "Diseñemos su itinerario Belém + Marajó + Alter do Chão", subheading: "Un consultor humano de Create Travel organiza las travesías, los vuelos y la ventana adecuada para los cuatro tramos.", button: "Hablar con un travel designer" },
    readingMinutes: 13,
    publishedAt: "2026-08-11",
  },

  it: {
    destinationName: "Belém + Isola di Marajó + Alter do Chão",
    blurb: "L'Amazzonia del Pará nella sua interezza: città storica, isola dei bufali, spiagge fluviali e foresta profonda, in 13 notti.",
    metaTitle: "Belém + Marajó + Alter do Chão: itinerario combinato di 13 notti",
    metaDescription: "Come combinare Belém, l'Isola di Marajó, Alter do Chão e un lodge nella foresta sul Rio Negro o a Mamirauá in un unico viaggio: logistica reale di traversate e voli, finestra ideale (settembre-novembre) e dove alloggiare in ogni tappa.",
    keywords: "belem marajo alter do chao itinerario, viaggio a marajo, alter do chao itinerario, isola do combu belem, ver-o-peso, spiagge fluviali tapajos, lodge rio negro, riserva mamiraua",
    h1: "Belém + Isola di Marajó + Alter do Chão: l'itinerario combinato dell'Amazzonia del Pará",
    aiAnswer: "L'itinerario che combina Belém, l'Isola di Marajó e Alter do Chão dura circa 13 notti: 3 a Belém, 3 a Marajó (via traghetto/motoscafo da Icoaraci), 3 ad Alter do Chão/Tapajós (volo Belém–Santarém) e 4 in un lodge nella foresta sul Rio Negro (via Manaus) o alla Riserva Mamirauá (via Tefé), nella finestra secca da settembre a novembre, quando le spiagge fluviali del Tapajós e di Marajó sono al loro apice.",
    intro: [
      "Belém non è uno scalo: è la porta d'ingresso a un'Amazzonia che pochi itinerari esplorano per intero. La città storica del Grão-Pará lascia il posto, a poche ore di barca, alla savana allagata dei bufali dell'Isola di Marajó; e, con un volo breve, alle spiagge di acqua dolce di Alter do Chão, sul fiume Tapajós. Chiudere il viaggio in un lodge di foresta profonda — sul Rio Negro o a Mamirauá — completa il quadro: città, isola, spiaggia fluviale e foresta, quattro paesaggi amazzonici che raramente compaiono insieme in uno stesso itinerario.",
      "Questa guida è concepita come combinata: tratta la traversata da Icoaraci a Soure, il volo Belém–Santarém e la connessione finale via Manaus o Tefé come parte di un'unica logica di viaggio di riferimento, di circa 13 notti, con la finestra climatica e il numero di notti per tappa che fanno funzionare le quattro destinazioni in sequenza.",
    ],
    seasons: {
      heading: "La finestra giusta: da settembre a novembre",
      intro: "Il Pará e il basso rio delle Amazzoni hanno un regime di piogge che concentra il periodo secco tra agosto e dicembre — è in questa finestra, e soprattutto tra settembre e novembre, che l'itinerario combinato rende di più.",
      windows: [
        { window: "Agosto — inizio della magra", text: "I fiumi iniziano a calare, compaiono le prime spiagge di sabbia bianca sul Tapajós e a Marajó, e il caldo è ancora più mite rispetto ai mesi successivi. Buona finestra per chi predilige meno afflusso di visitatori." },
        { window: "Settembre a novembre — apice della secca e delle spiagge fluviali", text: "Le spiagge di Alter do Chão e del Tapajós raggiungono la massima estensione, i bufali di Marajó si concentrano nei campi più asciutti e la navigazione tra Icoaraci e Soure è più stabile. È la finestra più consigliata per l'itinerario completo." },
        { window: "Dicembre a febbraio — transizione, ancora percorribile", text: "Iniziano già le prime piogge isolate, ma le spiagge fluviali esistono ancora e il paesaggio diventa più verde. Alternativa ragionevole per chi non riesce a viaggiare al culmine della secca." },
        { window: "Marzo a luglio — evitare le spiagge fluviali", text: "La piena amazzonica sommerge le spiagge del Tapajós e di Marajó; è il periodo migliore per la canoa negli igarapé allagati, ma senza sinergia con l'itinerario di spiagge e savane qui proposto." },
      ],
    },
    experiences: {
      heading: "Cosa si vive in ogni tappa",
      intro: "Ogni tappa del viaggio regala un paesaggio amazzonico distinto — la somma delle quattro è ciò che rende raro questo itinerario.",
      items: [
        { title: "Ver-o-Peso e Isola del Combu, Belém (tappa 1)", text: "Il più grande mercato all'aperto dell'Amazzonia all'alba, con l'odore di pesce fresco ed erbe, seguito da un pomeriggio sull'Isola del Combu, tra piantagioni di cacao e ristoranti galleggianti dal sapore locale." },
        { title: "Gastronomia amazzonica a Belém (tappa 1)", text: "Tacacá dai chioschi di strada al tramonto, maniçoba a cottura lenta e anatra al tucupi — una delle cucine regionali più autentiche del Brasile, riconosciuta a livello internazionale." },
        { title: "Fattorie di bufali e Spiaggia di Pesqueiro, Marajó (tappa 2)", text: "Passeggiate a cavallo e in calesse tra bufali che superano in numero gli abitanti dell'isola, e pomeriggi su spiagge di acqua dolce e sabbia chiara affacciate sulla Baia di Marajó." },
        { title: "Soure e i fiumi di Marajó (tappa 2)", text: "Giri in bicicletta per le strade sabbiose di Soure, birdwatching lungo gli igarapé e visite a caseifici artigianali di bufala, tradizione che risale al XIX secolo." },
        { title: "Spiagge di acqua dolce di Alter do Chão (tappa 3)", text: "La ""Ilha do Amor"" e le sue dune di sabbia bianca sul Rio Tapajós, con acque cristalline color turchese — uno degli scenari più fotografati dell'Amazzonia nella stagione secca." },
        { title: "Foresta Nazionale del Tapajós e Rio Arapiuns (tappa 3)", text: "Sentieri guidati da comunità rivierasche dentro la foresta nazionale, e gite in barca lungo l'Arapiuns, con acque scure incorniciate da foresta intatta." },
        { title: "Lodge di foresta sul Rio Negro o a Mamirauá (tappa 4)", text: "Quattro notti finali di immersione profonda: canoa tra gli igarapé e osservazione dei delfini rosa sul Rio Negro, oppure i laghi allagati stagionalmente e le scimmie uacari di Mamirauá, una delle riserve faunistiche meglio gestite dell'Amazzonia." },
      ],
    },
    stays: {
      heading: "Dove alloggiare in ogni tappa",
      intro: "La base giusta cambia il ritmo e il comfort di ogni tappa del viaggio.",
      items: [
        { name: "Hotel storici nel centro di Belém", profile: "Città e gastronomia", text: "Indirizzi vicini a Ver-o-Peso e alla Estação das Docas, ideali per esplorare a piedi il centro storico e la scena gastronomica serale." },
        { name: "Pousadas di spiaggia a Soure, Marajó", profile: "Isola e bufali", text: "Piccole pousadas vicino alla Spiaggia di Pesqueiro o nel centro di Soure, punto di partenza per cavalcate e visite alle fattorie di bufali." },
        { name: "Pousadas sul Tapajós, Alter do Chão", profile: "Spiagge fluviali", text: "Indirizzi di charme con vista sul fiume e sull'Ilha do Amor, a pochi minuti a piedi dal villaggio e dall'imbarcadero verso l'Arapiuns." },
        { name: "Lodge di foresta sul Rio Negro (via Manaus)", profile: "Immersione finale, comfort elevato", text: "Bungalow affacciati sul fiume, con guide di altissimo livello per canoa, avvistamenti notturni e osservazione dei delfini." },
        { name: "Pousada Uacari, Riserva Mamirauá (via Tefé)", profile: "Fauna e gestione scientifica", text: "Struttura galleggiante sul lago, gestita da un istituto di ricerca, con la maggiore concentrazione documentata al mondo di scimmie uacari bianche." },
      ],
    },
    profiles: {
      heading: "Per chi funziona questo itinerario combinato",
      items: [
        { title: "Coppie e viaggiatori esperti in cerca di profondità culturale e naturale", text: "Un itinerario che combina città storica, cultura fluviale, spiagge insolite e foresta densa senza ripetere il paesaggio in nessuna tappa." },
        { title: "Buongustai e appassionati di cultura regionale", text: "Belém da sola giustifica già un viaggio per chi si interessa alla cucina brasiliana d'autore; unita a Marajó e Alter do Chão, forma un panorama culturale raro." },
        { title: "Per chi forse non funziona", text: "Viaggiatori con meno di 10 giorni disponibili o che cercano solo osservazione intensiva della fauna (giaguari, ad esempio) dovrebbero considerare un itinerario incentrato su Mamirauá o sul Pantanal, non questa combinazione di quattro tappe." },
      ],
    },
    itinerary: {
      heading: "Il susseguirsi giorno per giorno: 13 notti di riferimento",
      intro: "La logica dell'itinerario è sempre città prima, poi isola, poi spiaggia fluviale, e foresta profonda per ultima — la tappa di immersione più intensa rende di più quando il viaggiatore è già adattato al caldo e al ritmo amazzonico.",
      items: [
        { title: "Notti 1-3 — Belém", text: "Arrivo all'Aeroporto Internazionale di Belém, tre notti in città con visite a Ver-o-Peso, all'Isola del Combu e al circuito gastronomico, con un'intera mattinata dedicata al mercato." },
        { title: "Traversata — da Icoaraci a Soure", text: "Trasferimento via terra fino al porto di Icoaraci, seguito da traversata in traghetto (circa 3 ore) o motoscafo veloce (circa 1h30) fino a Soure, sull'Isola di Marajó; si consiglia la partenza mattutina per evitare i venti pomeridiani." },
        { title: "Notti 4-6 — Isola di Marajó", text: "Tre notti a Soure, con cavalcate alle fattorie di bufali, pomeriggi sulla Spiaggia di Pesqueiro e visita a un caseificio artigianale di bufala." },
        { title: "Transito — da Marajó ad Alter do Chão via Belém e Santarém", text: "Ritorno in barca a Icoaraci/Belém, seguito da volo domestico Belém–Santarém (circa 1 ora) e trasferimento via terra di circa 40 minuti fino ad Alter do Chão." },
        { title: "Notti 7-9 — Alter do Chão e il Rio Tapajós", text: "Tre notti con giornate sull'Ilha do Amor, escursione nella Foresta Nazionale del Tapajós e gita in barca lungo il Rio Arapiuns tra comunità rivierasche." },
        { title: "Transito — da Santarém a Manaus o a Tefé", text: "Volo domestico Santarém–Manaus (circa 1h) per chi prosegue verso il Rio Negro, oppure Santarém–Tefé con scalo a Manaus per chi sceglie Mamirauá, seguito da trasferimento fluviale fino al lodge." },
        { title: "Notti 10-13 — Lodge di foresta (Rio Negro o Mamirauá)", text: "Quattro notti finali di immersione, con canoa, avvistamenti notturni, osservazione di delfini o di scimmie uacari, prima del volo di partenza via Manaus." },
      ],
    },
    tips: {
      heading: "Consigli pratici per l'itinerario combinato",
      items: [
        "Prenotate la traversata Icoaraci–Soure con anticipo e preferite l'orario mattutino, quando la Baia di Marajó è più calma.",
        "Confermate gli orari del volo Belém–Santarém con margine: le frequenze giornaliere sono poche e le cancellazioni per piogge forti non sono rare anche in stagione secca.",
        "Portate costume da bagno e crema solare biodegradabile fin dalla partenza da Belém — le spiagge di Marajó e Alter do Chão compaiono già nei primi giorni.",
        "Il vaccino contro la febbre gialla è obbligatorio per tutta la regione e va effettuato almeno dieci giorni prima della partenza.",
        "Il contante è ancora necessario a Soure e nelle comunità rivierasche dell'Arapiuns, dove le carte non sempre funzionano.",
        "Se si opta per Mamirauá invece del Rio Negro, prenotate con largo anticipo: la Pousada Uacari ha un numero limitato di camere, essendo gestita da un istituto di ricerca.",
      ],
    },
    faq: [
      { q: "Quante notti servono per l'itinerario Belém + Marajó + Alter do Chão?", a: "Circa 13 notti: 3 a Belém, 3 a Marajó, 3 ad Alter do Chão e 4 in un lodge di foresta finale sul Rio Negro o a Mamirauá." },
      { q: "Come si arriva da Belém all'Isola di Marajó?", a: "Con una traversata fluviale dal porto di Icoaraci, a Belém, in traghetto (circa 3 ore) o motoscafo veloce (circa 1h30) fino a Soure." },
      { q: "Esiste un volo diretto tra Belém e Alter do Chão?", a: "No; si vola da Belém a Santarém (circa 1 ora) e si prosegue via terra per circa 40 minuti fino ad Alter do Chão." },
      { q: "Qual è il periodo migliore per le spiagge fluviali di Marajó e Alter do Chão?", a: "Tra settembre e novembre, all'apice della stagione secca, quando le spiagge raggiungono la massima estensione e i fiumi sono più bassi." },
      { q: "Conviene chiudere il viaggio sul Rio Negro o a Mamirauá?", a: "Il Rio Negro, via Manaus, ha un accesso più diretto e un'infrastruttura di lodge più ampia; Mamirauá, via Tefé, richiede più logistica ma offre una delle riserve faunistiche meglio gestite dell'Amazzonia, con avvistamento pressoché garantito della scimmia uacari." },
      { q: "Quanto costa questo itinerario combinato con Create Travel?", a: "Non lavoriamo con listini fissi: il budget dipende dai lodge, dalla stagione e dalla tappa finale scelta. Un consulente umano elabora la proposta per iscritto." },
    ],
    cta: { heading: "Progettiamo il vostro itinerario Belém + Marajó + Alter do Chão", subheading: "Un consulente umano di Create Travel organizza le traversate, i voli e la finestra giusta per le quattro tappe.", button: "Parla con un travel designer" },
    readingMinutes: 13,
    publishedAt: "2026-08-11",
  },

  de: {
    destinationName: "Belém + Insel Marajó + Alter do Chão",
    blurb: "Das Amazonasgebiet von Pará in seiner ganzen Vielfalt: historische Stadt, Büffelinsel, Flussstrände und tiefer Regenwald, über 13 Nächte.",
    metaTitle: "Belém + Marajó + Alter do Chão: kombinierte 13-Nächte-Reiseroute",
    metaDescription: "Wie man Belém, die Insel Marajó, Alter do Chão und eine Regenwald-Lodge am Rio Negro oder in Mamirauá in einer Reise verbindet: reale Logistik von Überfahrten und Flügen, beste Reisezeit (September bis November) und Unterkünfte je Etappe.",
    keywords: "belem marajo alter do chao reiseroute, reise nach marajo, alter do chao reiseroute, insel combu belem, ver-o-peso markt, tapajos flussstrände, rio negro lodge, mamiraua reservat",
    h1: "Belém + Insel Marajó + Alter do Chão: die kombinierte Reiseroute durch das Amazonasgebiet von Pará",
    aiAnswer: "Die Reiseroute, die Belém, die Insel Marajó und Alter do Chão verbindet, dauert etwa 13 Nächte: 3 in Belém, 3 auf Marajó (per Fähre/Schnellboot ab Icoaraci), 3 in Alter do Chão/Tapajós (Flug Belém–Santarém) und 4 in einer Regenwald-Lodge am Rio Negro (über Manaus) oder im Mamirauá-Reservat (über Tefé), in der Trockenzeit von September bis November, wenn die Flussstrände des Tapajós und von Marajó ihren Höhepunkt erreichen.",
    intro: [
      "Belém ist kein Zwischenstopp, sondern das Tor zu einem Amazonasgebiet, das nur wenige Reiserouten vollständig erschließen. Die historische Stadt des Grão-Pará weicht wenige Bootsstunden entfernt der überfluteten Büffelsavanne der Insel Marajó; und mit einem kurzen Flug den Süßwasserstränden von Alter do Chão am Rio Tapajós. Den Abschluss der Reise in einer tiefen Regenwald-Lodge — am Rio Negro oder in Mamirauá — vervollständigt das Bild: Stadt, Insel, Flussstrand und Urwald, vier amazonische Landschaften, die selten gemeinsam in derselben Reiseroute vorkommen.",
      "Dieser Guide ist als kombinierte Route konzipiert: Er behandelt die Überfahrt von Icoaraci nach Soure, den Flug Belém–Santarém und die abschließende Verbindung über Manaus oder Tefé als Teil einer einzigen Reiselogik von etwa 13 Nächten, mit dem Klimafenster und der Nächtezahl je Etappe, die die vier Ziele nacheinander funktionieren lassen.",
    ],
    seasons: {
      heading: "Die richtige Reisezeit: September bis November",
      intro: "Pará und der untere Amazonas haben ein Niederschlagsmuster, das die Trockenzeit zwischen August und Dezember konzentriert — in diesem Fenster, besonders zwischen September und November, lohnt sich die kombinierte Route am meisten.",
      windows: [
        { window: "August — Beginn der Niedrigwasserzeit", text: "Die Flüsse beginnen zu sinken, die ersten weißen Sandstrände erscheinen am Tapajós und auf Marajó, und die Hitze ist noch milder als in den Folgemonaten. Gute Zeit für alle, die weniger Besucherverkehr bevorzugen." },
        { window: "September bis November — Höhepunkt der Trockenzeit und der Flussstrände", text: "Die Strände von Alter do Chão und am Tapajós erreichen ihre maximale Ausdehnung, die Büffelherden auf Marajó konzentrieren sich auf den trockensten Feldern, und die Überfahrt zwischen Icoaraci und Soure ist stabiler. Die empfohlenste Zeit für die vollständige Route." },
        { window: "Dezember bis Februar — Übergang, noch machbar", text: "Erste vereinzelte Regenfälle setzen bereits ein, doch die Flussstrände bestehen noch und die Landschaft wird grüner. Vernünftige Alternative für alle, die nicht zum Höhepunkt der Trockenzeit reisen können." },
        { window: "März bis Juli — Flussstrände meiden", text: "Das Amazonashochwasser überflutet die Strände am Tapajós und auf Marajó; beste Zeit für Kanufahrten durch überflutete Igarapés, aber ohne Synergie mit der hier vorgeschlagenen Strand- und Savannenroute." },
      ],
    },
    experiences: {
      heading: "Was sich in jeder Etappe erlebt",
      intro: "Jede Etappe der Reise bietet eine eigene amazonische Landschaft — die Summe der vier macht diese Reiseroute selten.",
      items: [
        { title: "Ver-o-Peso und Insel Combu, Belém (Etappe 1)", text: "Der größte Freiluftmarkt des Amazonasgebiets bei Sonnenaufgang, mit dem Duft von frischem Fisch und Kräutern, gefolgt von einem Nachmittag auf der Insel Combu zwischen Kakaoplantagen und schwimmenden Restaurants lokaler Küche." },
        { title: "Amazonische Küche in Belém (Etappe 1)", text: "Tacacá an den Straßenständen bei Sonnenuntergang, langsam gegartes Maniçoba und Ente in Tucupi — eine der eigenständigsten Regionalküchen Brasiliens, international anerkannt." },
        { title: "Büffelfarmen und Praia do Pesqueiro, Marajó (Etappe 2)", text: "Reit- und Kutschfahrten zwischen Büffeln, die zahlenmäßig die Einwohner der Insel übertreffen, und Nachmittage an Süßwasserstränden mit hellem Sand mit Blick auf die Bucht von Marajó." },
        { title: "Soure und die Flüsse von Marajó (Etappe 2)", text: "Fahrradtouren durch die sandigen Straßen von Soure, Vogelbeobachtung an Igarapés und Besuche handwerklicher Büffelkäsereien, eine Tradition, die auf das 19. Jahrhundert zurückgeht." },
        { title: "Süßwasserstrände von Alter do Chão (Etappe 3)", text: "Die ""Ilha do Amor"" mit ihren weißen Sanddünen über dem Rio Tapajós und kristallklarem türkisfarbenem Wasser — eine der meistfotografierten Kulissen des Amazonasgebiets in der Trockenzeit." },
        { title: "Nationalwald Tapajós und Rio Arapiuns (Etappe 3)", text: "Von Flussgemeinden geführte Wanderungen innerhalb des Nationalwalds und Bootsfahrten auf dem Arapiuns, mit dunklem Wasser, gerahmt von unberührtem Regenwald." },
        { title: "Regenwald-Lodge am Rio Negro oder in Mamirauá (Etappe 4)", text: "Vier abschließende Nächte tiefer Immersion: Kanufahrten durch Igarapés und Beobachtung rosa Flussdelfine am Rio Negro, oder die saisonal überfluteten Seen und Uakari-Affen von Mamirauá, eines der bestgeführten Wildtierreservate des Amazonasgebiets." },
      ],
    },
    stays: {
      heading: "Wo man in jeder Etappe übernachtet",
      intro: "Die richtige Basis bestimmt Tempo und Komfort jeder Etappe der Reise.",
      items: [
        { name: "Historische Hotels im Zentrum von Belém", profile: "Stadt und Gastronomie", text: "Adressen in der Nähe von Ver-o-Peso und der Estação das Docas, ideal, um das historische Zentrum und die abendliche Restaurantszene zu Fuß zu erkunden." },
        { name: "Strand-Pousadas in Soure, Marajó", profile: "Insel und Büffel", text: "Kleine Pousadas nahe der Praia do Pesqueiro oder im Zentrum von Soure, Ausgangspunkt für Ausritte und Besuche der Büffelfarmen." },
        { name: "Pousadas am Tapajós, Alter do Chão", profile: "Flussstrände", text: "Charmante Adressen mit Blick auf den Fluss und die Ilha do Amor, wenige Gehminuten vom Dorf und vom Anleger zum Arapiuns entfernt." },
        { name: "Regenwald-Lodges am Rio Negro (über Manaus)", profile: "Abschließende Immersion, gehobener Komfort", text: "Zum Fluss ausgerichtete Bungalows mit erstklassigen Guides für Kanufahrten, nächtliche Beobachtungen und Delfinsichtungen." },
        { name: "Pousada Uacari, Mamirauá-Reservat (über Tefé)", profile: "Wildtiere und wissenschaftliches Management", text: "Schwimmende Unterkunft auf dem See, geführt von einem Forschungsinstitut, mit der weltweit höchsten dokumentierten Konzentration weißer Uakari-Affen." },
      ],
    },
    profiles: {
      heading: "Für wen diese kombinierte Reiseroute geeignet ist",
      items: [
        { title: "Paare und erfahrene Reisende auf der Suche nach kultureller und natürlicher Tiefe", text: "Eine Reiseroute, die historische Stadt, Flusskultur, ungewöhnliche Strände und dichten Regenwald vereint, ohne die Landschaft in irgendeiner Etappe zu wiederholen." },
        { title: "Feinschmecker und Liebhaber regionaler Kultur", text: "Belém allein rechtfertigt bereits eine Reise für alle, die sich für brasilianische Autorenküche interessieren; zusammen mit Marajó und Alter do Chão entsteht ein seltenes kulturelles Panorama." },
        { title: "Für wen es vielleicht nicht passt", text: "Reisende mit weniger als 10 verfügbaren Tagen oder mit Fokus ausschließlich auf intensive Wildtierbeobachtung (z. B. Jaguare) sollten eher eine auf Mamirauá oder das Pantanal fokussierte Route in Betracht ziehen, nicht diese vierteilige Kombination." },
      ],
    },
    itinerary: {
      heading: "Der Tag-für-Tag-Ablauf: 13 Nächte als Referenz",
      intro: "Die Logik der Reiseroute ist immer Stadt zuerst, dann Insel, dann Flussstrand und tiefer Regenwald zuletzt — die intensivste Immersionsetappe lohnt sich mehr, wenn der Reisende bereits an Hitze und amazonischen Rhythmus gewöhnt ist.",
      items: [
        { title: "Nächte 1–3 — Belém", text: "Ankunft am internationalen Flughafen von Belém, drei Nächte in der Stadt mit Besuchen von Ver-o-Peso, der Insel Combu und der gastronomischen Route, einschließlich eines ganzen Vormittags auf dem Markt." },
        { title: "Überfahrt — Icoaraci nach Soure", text: "Transfer über Land zum Hafen von Icoaraci, gefolgt von einer Fährüberfahrt (ca. 3 Stunden) oder einem Schnellboot (ca. 1,5 Stunden) nach Soure auf der Insel Marajó; eine morgendliche Abfahrt wird empfohlen, um Nachmittagswinde zu vermeiden." },
        { title: "Nächte 4–6 — Insel Marajó", text: "Drei Nächte in Soure, mit Ausritten zu Büffelfarmen, Nachmittagen an der Praia do Pesqueiro und dem Besuch einer handwerklichen Büffelkäserei." },
        { title: "Transit — Marajó nach Alter do Chão über Belém und Santarém", text: "Rückfahrt mit dem Boot nach Icoaraci/Belém, gefolgt von einem Inlandsflug Belém–Santarém (ca. 1 Stunde) und einem Landtransfer von etwa 40 Minuten nach Alter do Chão." },
        { title: "Nächte 7–9 — Alter do Chão und der Rio Tapajós", text: "Drei Nächte mit Tagen auf der Ilha do Amor, einer Wanderung im Nationalwald Tapajós und einer Bootsfahrt auf dem Rio Arapiuns durch Flussgemeinden." },
        { title: "Transit — Santarém nach Manaus oder Tefé", text: "Inlandsflug Santarém–Manaus (ca. 1 Stunde) für alle, die weiter zum Rio Negro reisen, oder Santarém–Tefé mit Zwischenstopp in Manaus für Mamirauá, gefolgt von einem Flusstransfer zur Lodge." },
        { title: "Nächte 10–13 — Regenwald-Lodge (Rio Negro oder Mamirauá)", text: "Vier abschließende Immersionsnächte mit Kanufahrten, nächtlichen Beobachtungen, Delfin- oder Uakari-Affen-Sichtungen vor dem Rückflug über Manaus." },
      ],
    },
    tips: {
      heading: "Praktische Tipps für die kombinierte Reiseroute",
      items: [
        "Buchen Sie die Überfahrt Icoaraci–Soure frühzeitig und bevorzugen Sie den Vormittag, wenn die Bucht von Marajó ruhiger ist.",
        "Bestätigen Sie die Flugzeiten Belém–Santarém mit Puffer: Es gibt nur wenige tägliche Verbindungen, und Absagen wegen starken Regens sind auch in der Trockenzeit nicht selten.",
        "Packen Sie Badebekleidung und biologisch abbaubaren Sonnenschutz bereits ab Belém ein — die Strände von Marajó und Alter do Chão erscheinen schon in den ersten Tagen.",
        "Die Gelbfieberimpfung ist für die gesamte Region vorgeschrieben und sollte mindestens zehn Tage vor Abreise erfolgen.",
        "Bargeld wird in Soure und den Flussgemeinden am Arapiuns weiterhin benötigt, da Karten nicht immer funktionieren.",
        "Wer sich für Mamirauá statt des Rio Negro entscheidet, sollte weit im Voraus buchen: Die Pousada Uacari hat als forschungsgeführte Einrichtung nur eine begrenzte Zimmerzahl.",
      ],
    },
    faq: [
      { q: "Wie viele Nächte braucht man für die Route Belém + Marajó + Alter do Chão?", a: "Etwa 13 Nächte: 3 in Belém, 3 auf Marajó, 3 in Alter do Chão und 4 in einer abschließenden Regenwald-Lodge am Rio Negro oder in Mamirauá." },
      { q: "Wie kommt man von Belém zur Insel Marajó?", a: "Per Flussüberfahrt vom Hafen Icoaraci in Belém, per Fähre (ca. 3 Stunden) oder Schnellboot (ca. 1,5 Stunden) nach Soure." },
      { q: "Gibt es einen Direktflug zwischen Belém und Alter do Chão?", a: "Nein; man fliegt von Belém nach Santarém (ca. 1 Stunde) und fährt anschließend etwa 40 Minuten über Land nach Alter do Chão." },
      { q: "Was ist die beste Zeit für die Flussstrände von Marajó und Alter do Chão?", a: "Zwischen September und November, auf dem Höhepunkt der Trockenzeit, wenn die Strände ihre maximale Ausdehnung erreichen und die Flüsse am niedrigsten stehen." },
      { q: "Lohnt es sich mehr, die Reise am Rio Negro oder in Mamirauá zu beenden?", a: "Der Rio Negro über Manaus bietet direkteren Zugang und eine breitere Lodge-Infrastruktur; Mamirauá über Tefé erfordert mehr Logistik, bietet aber eines der bestgeführten Wildtierreservate des Amazonasgebiets mit nahezu garantierten Uakari-Affen-Sichtungen." },
      { q: "Was kostet diese kombinierte Reiseroute mit Create Travel?", a: "Wir arbeiten nicht mit Listenpreisen: Das Budget hängt von den Lodges, der Saison und der gewählten Abschlussetappe ab. Ein menschlicher Berater erstellt das Angebot schriftlich." },
    ],
    cta: { heading: "Lassen Sie uns Ihre Route Belém + Marajó + Alter do Chão gestalten", subheading: "Ein menschlicher Berater von Create Travel organisiert die Überfahrten, die Flüge und die richtige Reisezeit für die vier Etappen.", button: "Mit einem Travel Designer sprechen" },
    readingMinutes: 13,
    publishedAt: "2026-08-11",
  },
};
