import type { BrazilGuideLocalized } from "./types";

export const conjugadoCostasNordesteGuide: BrazilGuideLocalized = {
  pt: {
    destinationName: "Costas do Nordeste",
    blurb: "Roteiro conjugado de 13 noites entre Ceará, Maranhão e Bahia: Jericoacoara, Lençóis Maranhenses e as costas dos Coqueiros e do Dendê.",
    metaTitle: "Costas do Nordeste: roteiro de 13 noites | Create Travel",
    metaDescription: "Guia autoral do roteiro conjugado Jericoacoara, Lençóis Maranhenses, Rota das Emoções e Bahia (Praia do Forte e Maraú/Boipeba): melhor época, voos e travessias.",
    keywords: "roteiro jericoacoara lençóis maranhenses, roteiro costas do nordeste, rota das emoções, praia do forte roteiro, maraú boipeba roteiro, roteiro bahia ceará maranhão",
    h1: "Costas do Nordeste: o roteiro conjugado de Jericoacoara a Boipeba",
    aiAnswer: "O roteiro conjugado das Costas do Nordeste liga Jericoacoara e Preá (Ceará), Lençóis Maranhenses e a Rota das Emoções (Maranhão-Piauí) e a Bahia (Costa dos Coqueiros e Costa do Dendê) em cerca de 13 noites, entre julho e novembro, encadeado por voos até Fortaleza, Jericoacoara (JJD), São Luís e Salvador, com transfers 4x4 e travessias de barco entre os trechos internos.",
    intro: [
      "Poucas combinações revelam tão bem a diversidade do litoral brasileiro quanto esta: das dunas móveis e ventos constantes de Jericoacoara às lagoas turquesa dos Lençóis Maranhenses, até as águas mornas e a herança afro-baiana da Costa dos Coqueiros e da Costa do Dendê. São três Nordestes distintos, unidos por um fio condutor de areia, vento e mar.",
      "Este guia nasce da experiência de encadear esses três trechos em uma única viagem de cerca de 13 noites, respeitando a logística real de voos regionais, aeroportos pequenos como o de Jericoacoara e as travessias de 4x4 e barco que fazem parte da rota — nunca um obstáculo, sempre parte da narrativa.",
    ],
    seasons: {
      heading: "Melhor época para o roteiro Costas do Nordeste",
      intro: "A janela entre julho e novembro concentra o melhor dos três trechos: ventos ideais para Jericoacoara, lagoas cheias nos Lençóis Maranhenses e o fim da estação chuvosa na Bahia.",
      windows: [
        { window: "Julho a agosto", text: "Ventos alísios no auge em Jericoacoara e Preá, ideais para kitesurf; lagoas dos Lençóis ainda com bom volume de água acumulada da chuva de meados do ano." },
        { window: "Setembro", text: "Combinação ideal de sol forte, lagoas ainda cheias no Maranhão e mar calmo na Bahia — mês de transição sem grandes desvantagens em nenhum trecho." },
        { window: "Outubro", text: "Início do período mais seco no Maranhão, quando as lagoas começam a baixar; excelente ainda para o Ceará e para a Bahia, com dias mais estáveis." },
        { window: "Novembro", text: "Últimas semanas antes da baixa das lagoas maranhenses se acentuar; boa janela para fechar o roteiro pela Bahia, já com o verão se anunciando." },
      ],
    },
    experiences: {
      heading: "O que se vive em cada trecho",
      intro: "Cada costa tem uma identidade própria — de vento e duna, de água doce sobre areia branca, e de mar morno com raízes afro-brasileiras.",
      items: [
        { title: "Jericoacoara e Preá — vento, duna e pôr do sol", text: "A Duna do Pôr do Sol em Jeri, aplaudida todas as tardes, e Preá como base de kitesurf de referência mundial, com lagoas de Paraíso e Torta a poucos minutos de buggy." },
        { title: "Lençóis Maranhenses — lagoas sobre dunas brancas", text: "Um deserto de areia branca pontilhado por lagoas de água doce e transparente, mais dramático entre junho e setembro, quando o volume acumulado das chuvas está no auge." },
        { title: "Rota das Emoções — Delta do Parnaíba e Atins", text: "O encontro do Rio Parnaíba com o Atlântico em um dos raros deltas em mar aberto do planeta, navegado de lancha entre mangues e dunas, com Barreirinhas e a vila de pescadores de Atins como bases." },
        { title: "Costa dos Coqueiros — Praia do Forte", text: "Coqueirais intermináveis, recifes de corais visitáveis a pé na maré baixa e o Projeto Tamar, referência mundial em conservação de tartarugas marinhas." },
        { title: "Costa do Dendê — Península de Maraú e Boipeba", text: "Vilarejos sem carros, praias de areia branca emolduradas por coqueiros e uma culinária de dendê e frutos do mar que resume a Bahia mais autêntica." },
        { title: "Travessias como parte da experiência", text: "4x4 pelas dunas entre Jericoacoara e o Delta, lancha entre Barreirinhas e Atins, e balsa ou barco para alcançar Boipeba — cada deslocamento é também paisagem." },
      ],
    },
    stays: {
      heading: "Onde ficar em cada trecho",
      intro: "A hotelaria varia de pousadas de charme discretas a resorts de praia estruturados, sempre priorizando integração com a paisagem.",
      items: [
        { name: "Vila Kalango ou Pousada Jardim do Éden (Jericoacoara)", profile: "Charme e proximidade da vila", text: "Endereços de referência na vila de Jeri, a poucos passos da Duna do Pôr do Sol e do centro." },
        { name: "Vila Yaya ou Villa Preá (Preá)", profile: "Kitesurf e sossego", text: "Base mais tranquila que Jeri, voltada a quem prioriza a prática de kitesurf e menos agito noturno." },
        { name: "Pousadas de Atins ou Barreirinhas", profile: "Portas de entrada aos Lençóis", text: "Estrutura simples e funcional, adequada para duas a três noites de exploração das lagoas e do Delta do Parnaíba." },
        { name: "Txai Resort ou Tivoli Ecoresort Praia do Forte", profile: "Resort estruturado com praia particular", text: "Endereços de referência na Costa dos Coqueiros para quem busca conforto pleno após os trechos mais rústicos do Maranhão." },
        { name: "Kiaroa Eco Resort (Maraú) ou pousadas de charme em Boipeba", profile: "Isolamento e autenticidade na Costa do Dendê", text: "Fechamento do roteiro em vilarejos sem carros, com praias desertas e ritmo mais lento." },
      ],
    },
    profiles: {
      heading: "Para quem este roteiro funciona",
      items: [
        { title: "Casais e viajantes que buscam praia com personalidade", text: "Ideal para quem quer ir além do óbvio litoral baiano e conhecer paisagens de duna e delta pouco exploradas por estrangeiros." },
        { title: "Praticantes de kitesurf e esportes de vento", text: "Jericoacoara e Preá estão entre os melhores spots do mundo entre julho e novembro, com ventos constantes e lagoas de apoio." },
        { title: "Fotógrafos e amantes de paisagens únicas", text: "Os Lençóis Maranhenses e o Delta do Parnaíba oferecem cenários raros, sobretudo ao amanhecer e ao entardecer." },
        { title: "Para quem talvez não funcione", text: "Viajantes que rejeitam trechos com infraestrutura simples (Atins, Barreirinhas) devem considerar reduzir o roteiro apenas a Jericoacoara e Bahia, com hotelaria mais robusta." },
      ],
    },
    itinerary: {
      heading: "Como encadear o roteiro, trecho a trecho",
      intro: "A lógica combina voos regionais e travessias terrestres e marítimas, com Fortaleza, Jericoacoara, São Luís e Salvador como portas de entrada e saída de cada bloco.",
      items: [
        { title: "Dias 1 a 4 — Jericoacoara e Preá", text: "Chegada a Fortaleza (voo internacional ou doméstico) e conexão até o aeroporto de Jericoacoara (JJD), a cerca de 20 minutos de buggy da vila. Quatro noites entre dunas, lagoas e a base de kitesurf em Preá." },
        { title: "Dias 5 a 8 — Lençóis Maranhenses e Rota das Emoções", text: "Transfer 4x4 pela Rota das Emoções até Barreirinhas ou Atins, atravessando o Delta do Parnaíba de lancha, ou voo até São Luís com conexão terrestre. Quatro noites para lagoas, dunas e o encontro do rio com o mar." },
        { title: "Dias 9 a 13 — Bahia: Costa dos Coqueiros e Costa do Dendê", text: "Voo de São Luís a Salvador com conexão, transfer até Praia do Forte (cerca de 1h) para duas noites, seguido de travessia terrestre e de barco até a Península de Maraú ou Boipeba para três noites finais." },
        { title: "Retorno", text: "Transfer de barco e/ou terrestre de volta a Salvador para o voo de saída, fechando o roteiro pelo mesmo eixo aéreo de entrada." },
      ],
    },
    tips: {
      heading: "Dicas práticas para este roteiro",
      items: [
        "O aeroporto de Jericoacoara (JJD) recebe voos diretos de poucos hubs; confirme a malha aérea da temporada antes de fechar as datas.",
        "Leve roupa de banho, calçado de trilha leve para as dunas e proteção solar reforçada — o sol e o vento do litoral nordestino desidratam rapidamente.",
        "A travessia entre Barreirinhas e Atins é feita de lancha pelo rio e pelo mar; em dias de maré desfavorável, o percurso pode ser mais longo.",
        "Boipeba não tem carros: o deslocamento na ilha é a pé, de bicicleta ou trator — planeje bagagem leve para esse trecho.",
        "Reserve com antecedência a travessia até a Península de Maraú, feita por balsa e estrada, especialmente na alta temporada.",
        "Sinal de celular é instável em Atins e em partes de Boipeba; avise a família antes da viagem.",
      ],
    },
    faq: [
      { q: "Quantas noites são ideais para o roteiro Costas do Nordeste?", a: "Treze noites é o equilíbrio ideal: 4 em Jericoacoara e Preá, 4 nos Lençóis Maranhenses e Rota das Emoções, e 5 na Bahia entre Praia do Forte e Maraú/Boipeba." },
      { q: "Qual a melhor época para esse roteiro?", a: "Julho a novembro, quando os ventos favorecem Jericoacoara, as lagoas dos Lençóis Maranhenses estão em bom volume e a Bahia tem mar mais calmo." },
      { q: "Como se chega a Jericoacoara?", a: "Pelo aeroporto de Jericoacoara (JJD), com voos regionais a partir de Fortaleza, ou por transfer terrestre de cerca de 4 a 5 horas desde a capital cearense." },
      { q: "É preciso 4x4 para o trecho do Maranhão?", a: "Sim, os deslocamentos pela Rota das Emoções e o acesso a Atins exigem veículos 4x4 e, em parte do trajeto, travessia de balsa e lancha." },
      { q: "Como se chega a Boipeba e à Península de Maraú?", a: "Por combinação de transfer terrestre, balsa e barco a partir de Salvador ou Ilhéus; não há acesso rodoviário direto de carro particular até Boipeba." },
      { q: "Esse roteiro é confortável para viajantes acima de 60 anos?", a: "É viável com boa disposição para trechos de barco e estrada; recomendamos hospedagens de maior estrutura em cada bloco e ritmo mais pausado entre as travessias." },
    ],
    cta: {
      heading: "Vamos desenhar o seu roteiro pelas Costas do Nordeste",
      subheading: "Um consultor humano da Create Travel organiza voos regionais, transfers 4x4 e travessias de barco para uma viagem fluida entre Ceará, Maranhão e Bahia.",
      button: "Falar com um travel designer",
    },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },

  en: {
    destinationName: "Northeast Coasts",
    blurb: "A conjugated 13-night route across Ceará, Maranhão and Bahia: Jericoacoara, Lençóis Maranhenses and the Coqueiros and Dendê coasts.",
    metaTitle: "Northeast Coasts: 13-Night Itinerary | Create Travel",
    metaDescription: "An editorial guide to the conjugated route Jericoacoara, Lençóis Maranhenses, Rota das Emoções and Bahia (Praia do Forte and Maraú/Boipeba): best season, flights and crossings.",
    keywords: "jericoacoara lençóis maranhenses itinerary, northeast brazil coast route, rota das emoções, praia do forte itinerary, maraú boipeba itinerary, bahia ceará maranhão trip",
    h1: "Northeast Coasts: the conjugated route from Jericoacoara to Boipeba",
    aiAnswer: "The conjugated Northeast Coasts route links Jericoacoara and Preá (Ceará), Lençóis Maranhenses and the Rota das Emoções (Maranhão-Piauí) and Bahia (Costa dos Coqueiros and Costa do Dendê) over roughly 13 nights, between July and November, connected by flights via Fortaleza, Jericoacoara (JJD), São Luís and Salvador, with 4x4 transfers and boat crossings linking the inland legs.",
    intro: [
      "Few combinations reveal Brazil's coastal diversity as well as this one: from the shifting dunes and steady winds of Jericoacoara to the turquoise lagoons of Lençóis Maranhenses, through to the warm waters and Afro-Bahian heritage of the Costa dos Coqueiros and Costa do Dendê. These are three distinct Northeasts, joined by a thread of sand, wind and sea.",
      "This guide comes from experience linking these three legs in a single trip of roughly 13 nights, respecting the real logistics of regional flights, small airports like Jericoacoara's, and the 4x4 and boat crossings that are part of the route — never an obstacle, always part of the narrative.",
    ],
    seasons: {
      heading: "Best time for the Northeast Coasts route",
      intro: "The window between July and November brings out the best in all three legs: ideal winds for Jericoacoara, full lagoons in Lençóis Maranhenses, and the end of Bahia's rainy season.",
      windows: [
        { window: "July to August", text: "Trade winds peak in Jericoacoara and Preá, ideal for kitesurfing; Lençóis lagoons still hold good water from mid-year rains." },
        { window: "September", text: "Ideal combination of strong sun, still-full lagoons in Maranhão and calm sea in Bahia — a transition month with no real downside in any leg." },
        { window: "October", text: "Start of Maranhão's drier period, when lagoons begin to recede; still excellent for Ceará and Bahia, with more stable days." },
        { window: "November", text: "Last weeks before the Maranhão lagoons drop more noticeably; a good window to close the route in Bahia as summer approaches." },
      ],
    },
    experiences: {
      heading: "What each leg delivers",
      intro: "Each coast has its own identity — wind and dune, fresh water over white sand, and warm sea with Afro-Brazilian roots.",
      items: [
        { title: "Jericoacoara and Preá — wind, dune and sunset", text: "The Sunset Dune in Jeri, applauded every evening, and Preá as a world-class kitesurf base, with Paraíso and Torta lagoons minutes away by buggy." },
        { title: "Lençóis Maranhenses — lagoons over white dunes", text: "A white sand desert dotted with clear freshwater lagoons, most dramatic between June and September when accumulated rainwater peaks." },
        { title: "Rota das Emoções — Parnaíba Delta and Atins", text: "The meeting of the Parnaíba River with the Atlantic in one of the world's rare open-sea deltas, navigated by boat among mangroves and dunes, with Barreirinhas and the fishing village of Atins as bases." },
        { title: "Costa dos Coqueiros — Praia do Forte", text: "Endless coconut groves, coral reefs walkable at low tide, and Projeto Tamar, a world reference in sea turtle conservation." },
        { title: "Costa do Dendê — Maraú Peninsula and Boipeba", text: "Car-free villages, white sand beaches framed by coconut palms, and a dendê-and-seafood cuisine that sums up Bahia at its most authentic." },
        { title: "Crossings as part of the experience", text: "4x4 across the dunes between Jericoacoara and the Delta, boat between Barreirinhas and Atins, and ferry or boat to reach Boipeba — each transfer is itself scenery." },
      ],
    },
    stays: {
      heading: "Where to stay on each leg",
      intro: "Lodging ranges from discreet boutique inns to fully structured beach resorts, always prioritizing integration with the landscape.",
      items: [
        { name: "Vila Kalango or Pousada Jardim do Éden (Jericoacoara)", profile: "Charm and proximity to the village", text: "Reference addresses in Jeri village, steps from the Sunset Dune and town center." },
        { name: "Vila Yaya or Villa Preá (Preá)", profile: "Kitesurfing and quiet", text: "A calmer base than Jeri, geared to those prioritizing kitesurfing over nightlife." },
        { name: "Inns in Atins or Barreirinhas", profile: "Gateways to Lençóis", text: "Simple, functional structure, suited to two to three nights exploring the lagoons and the Parnaíba Delta." },
        { name: "Txai Resort or Tivoli Ecoresort Praia do Forte", profile: "Structured resort with private beach", text: "Reference addresses on the Costa dos Coqueiros for those seeking full comfort after Maranhão's more rustic legs." },
        { name: "Kiaroa Eco Resort (Maraú) or boutique inns in Boipeba", profile: "Isolation and authenticity on the Costa do Dendê", text: "Closing the route in car-free villages, with deserted beaches and a slower rhythm." },
      ],
    },
    profiles: {
      heading: "Who this route works for",
      items: [
        { title: "Couples and travelers seeking beaches with personality", text: "Ideal for those wanting to go beyond the obvious Bahian coast and discover dune and delta landscapes few foreigners know." },
        { title: "Kitesurfers and wind-sport enthusiasts", text: "Jericoacoara and Preá rank among the world's best spots between July and November, with steady winds and supporting lagoons." },
        { title: "Photographers and lovers of unique landscapes", text: "Lençóis Maranhenses and the Parnaíba Delta offer rare scenery, especially at dawn and dusk." },
        { title: "Who this may not suit", text: "Travelers who reject simple-infrastructure legs (Atins, Barreirinhas) should consider trimming the route to just Jericoacoara and Bahia, with more robust lodging." },
      ],
    },
    itinerary: {
      heading: "How to link the route, leg by leg",
      intro: "The logic combines regional flights with overland and sea crossings, using Fortaleza, Jericoacoara, São Luís and Salvador as entry and exit gateways for each block.",
      items: [
        { title: "Days 1–4 — Jericoacoara and Preá", text: "Arrival in Fortaleza (international or domestic flight) and connection to Jericoacoara airport (JJD), about 20 minutes by buggy from the village. Four nights among dunes, lagoons and the kitesurf base in Preá." },
        { title: "Days 5–8 — Lençóis Maranhenses and Rota das Emoções", text: "4x4 transfer along the Rota das Emoções to Barreirinhas or Atins, crossing the Parnaíba Delta by boat, or a flight to São Luís with an overland connection. Four nights for lagoons, dunes and the meeting of river and sea." },
        { title: "Days 9–13 — Bahia: Costa dos Coqueiros and Costa do Dendê", text: "Flight from São Luís to Salvador with a connection, transfer to Praia do Forte (about 1h) for two nights, followed by an overland and boat crossing to the Maraú Peninsula or Boipeba for the final three nights." },
        { title: "Return", text: "Boat and/or overland transfer back to Salvador for the departure flight, closing the route through the same air axis used to enter." },
      ],
    },
    tips: {
      heading: "Practical tips for this route",
      items: [
        "Jericoacoara airport (JJD) receives direct flights from only a few hubs; confirm the season's route map before locking in dates.",
        "Bring swimwear, light trail shoes for the dunes, and reinforced sun protection — the northeastern coast's sun and wind dehydrate quickly.",
        "The Barreirinhas-Atins crossing is made by boat along the river and sea; on unfavorable tide days the trip can take longer.",
        "Boipeba has no cars: getting around the island is on foot, by bicycle or tractor — pack light for this leg.",
        "Book the crossing to the Maraú Peninsula (by ferry and road) in advance, especially in high season.",
        "Phone signal is unstable in Atins and parts of Boipeba; let family know before the trip.",
      ],
    },
    faq: [
      { q: "How many nights are ideal for the Northeast Coasts route?", a: "Thirteen nights is the ideal balance: 4 in Jericoacoara and Preá, 4 in Lençóis Maranhenses and the Rota das Emoções, and 5 in Bahia between Praia do Forte and Maraú/Boipeba." },
      { q: "What's the best season for this route?", a: "July to November, when winds favor Jericoacoara, Lençóis Maranhenses lagoons hold good volume, and Bahia's sea is calmer." },
      { q: "How do you get to Jericoacoara?", a: "Via Jericoacoara airport (JJD), with regional flights from Fortaleza, or by an overland transfer of about 4 to 5 hours from the state capital." },
      { q: "Is a 4x4 needed for the Maranhão leg?", a: "Yes, transfers along the Rota das Emoções and access to Atins require 4x4 vehicles and, for part of the route, a ferry and boat crossing." },
      { q: "How do you reach Boipeba and the Maraú Peninsula?", a: "Through a combination of overland transfer, ferry and boat from Salvador or Ilhéus; there is no direct road access by private car to Boipeba." },
      { q: "Is this route comfortable for travelers over 60?", a: "It's feasible with a good disposition for boat and road legs; we recommend better-structured lodging in each block and a more unhurried pace between crossings." },
    ],
    cta: {
      heading: "Let's design your Northeast Coasts route",
      subheading: "A human consultant at Create Travel arranges regional flights, 4x4 transfers and boat crossings for a smooth trip across Ceará, Maranhão and Bahia.",
      button: "Talk to a travel designer",
    },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },

  es: {
    destinationName: "Costas del Nordeste",
    blurb: "Ruta conjugada de 13 noches por Ceará, Maranhão y Bahía: Jericoacoara, Lençóis Maranhenses y las costas de Coqueiros y Dendê.",
    metaTitle: "Costas del Nordeste: itinerario de 13 noches | Create Travel",
    metaDescription: "Guía editorial de la ruta conjugada Jericoacoara, Lençóis Maranhenses, Rota das Emoções y Bahía (Praia do Forte y Maraú/Boipeba): mejor época, vuelos y travesías.",
    keywords: "itinerario jericoacoara lençóis maranhenses, ruta costas del nordeste brasil, rota das emoções, itinerario praia do forte, itinerario maraú boipeba, viaje bahía ceará maranhão",
    h1: "Costas del Nordeste: la ruta conjugada de Jericoacoara a Boipeba",
    aiAnswer: "La ruta conjugada Costas del Nordeste une Jericoacoara y Preá (Ceará), Lençóis Maranhenses y la Rota das Emoções (Maranhão-Piauí) y Bahía (Costa dos Coqueiros y Costa do Dendê) en unas 13 noches, entre julio y noviembre, conectada por vuelos vía Fortaleza, Jericoacoara (JJD), São Luís y Salvador, con transfers 4x4 y travesías en barco entre los tramos internos.",
    intro: [
      "Pocas combinaciones revelan tan bien la diversidad del litoral brasileño como esta: de las dunas móviles y vientos constantes de Jericoacoara a las lagunas turquesa de Lençóis Maranhenses, hasta las aguas cálidas y la herencia afrobahiana de la Costa dos Coqueiros y la Costa do Dendê. Son tres Nordestes distintos, unidos por un hilo de arena, viento y mar.",
      "Esta guía nace de la experiencia de encadenar estos tres tramos en un solo viaje de unas 13 noches, respetando la logística real de vuelos regionales, aeropuertos pequeños como el de Jericoacoara y las travesías en 4x4 y barco que forman parte de la ruta — nunca un obstáculo, siempre parte del relato.",
    ],
    seasons: {
      heading: "Mejor época para la ruta Costas del Nordeste",
      intro: "La ventana entre julio y noviembre concentra lo mejor de los tres tramos: vientos ideales para Jericoacoara, lagunas llenas en Lençóis Maranhenses y el fin de la temporada de lluvias en Bahía.",
      windows: [
        { window: "Julio a agosto", text: "Vientos alisios en su punto máximo en Jericoacoara y Preá, ideales para kitesurf; lagunas de Lençóis aún con buen volumen de agua de las lluvias de mediados de año." },
        { window: "Septiembre", text: "Combinación ideal de sol fuerte, lagunas aún llenas en Maranhão y mar calmo en Bahía — mes de transición sin grandes desventajas en ningún tramo." },
        { window: "Octubre", text: "Inicio del período más seco en Maranhão, cuando las lagunas empiezan a bajar; excelente aún para Ceará y Bahía, con días más estables." },
        { window: "Noviembre", text: "Últimas semanas antes de que baje más la laguna maranhense; buena ventana para cerrar la ruta por Bahía, con el verano ya asomando." },
      ],
    },
    experiences: {
      heading: "Lo que se vive en cada tramo",
      intro: "Cada costa tiene una identidad propia — de viento y duna, de agua dulce sobre arena blanca, y de mar cálido con raíces afrobrasileñas.",
      items: [
        { title: "Jericoacoara y Preá — viento, duna y atardecer", text: "La Duna do Pôr do Sol en Jeri, aplaudida cada tarde, y Preá como base de kitesurf de referencia mundial, con las lagunas de Paraíso y Torta a pocos minutos en buggy." },
        { title: "Lençóis Maranhenses — lagunas sobre dunas blancas", text: "Un desierto de arena blanca salpicado de lagunas de agua dulce y transparente, más espectacular entre junio y septiembre, cuando el volumen de lluvias acumulado está en su punto máximo." },
        { title: "Rota das Emoções — Delta del Parnaíba y Atins", text: "El encuentro del río Parnaíba con el Atlántico en uno de los raros deltas en mar abierto del planeta, navegado en lancha entre manglares y dunas, con Barreirinhas y el pueblo pesquero de Atins como bases." },
        { title: "Costa dos Coqueiros — Praia do Forte", text: "Cocotales interminables, arrecifes de coral visitables a pie en marea baja y el Proyecto Tamar, referencia mundial en conservación de tortugas marinas." },
        { title: "Costa do Dendê — Península de Maraú y Boipeba", text: "Pueblos sin coches, playas de arena blanca enmarcadas por cocoteros y una cocina de dendê y mariscos que resume la Bahía más auténtica." },
        { title: "Travesías como parte de la experiencia", text: "4x4 por las dunas entre Jericoacoara y el Delta, lancha entre Barreirinhas y Atins, y balsa o barco para llegar a Boipeba — cada traslado es también paisaje." },
      ],
    },
    stays: {
      heading: "Dónde alojarse en cada tramo",
      intro: "La hotelería varía entre posadas de encanto discretas y resorts de playa estructurados, siempre priorizando la integración con el paisaje.",
      items: [
        { name: "Vila Kalango o Pousada Jardim do Éden (Jericoacoara)", profile: "Encanto y cercanía al pueblo", text: "Direcciones de referencia en el pueblo de Jeri, a pasos de la Duna do Pôr do Sol y del centro." },
        { name: "Vila Yaya o Villa Preá (Preá)", profile: "Kitesurf y tranquilidad", text: "Base más tranquila que Jeri, orientada a quienes priorizan la práctica de kitesurf sobre la vida nocturna." },
        { name: "Posadas de Atins o Barreirinhas", profile: "Puertas de entrada a Lençóis", text: "Estructura simple y funcional, adecuada para dos o tres noches de exploración de las lagunas y del Delta del Parnaíba." },
        { name: "Txai Resort o Tivoli Ecoresort Praia do Forte", profile: "Resort estructurado con playa privada", text: "Direcciones de referencia en la Costa dos Coqueiros para quienes buscan pleno confort tras los tramos más rústicos de Maranhão." },
        { name: "Kiaroa Eco Resort (Maraú) o posadas de encanto en Boipeba", profile: "Aislamiento y autenticidad en la Costa do Dendê", text: "Cierre de la ruta en pueblos sin coches, con playas desiertas y un ritmo más lento." },
      ],
    },
    profiles: {
      heading: "Para quién funciona esta ruta",
      items: [
        { title: "Parejas y viajeros que buscan playas con personalidad", text: "Ideal para quienes quieren ir más allá del litoral bahiano obvio y conocer paisajes de dunas y delta poco explorados por extranjeros." },
        { title: "Practicantes de kitesurf y deportes de viento", text: "Jericoacoara y Preá están entre los mejores spots del mundo entre julio y noviembre, con vientos constantes y lagunas de apoyo." },
        { title: "Fotógrafos y amantes de paisajes únicos", text: "Los Lençóis Maranhenses y el Delta del Parnaíba ofrecen escenarios raros, sobre todo al amanecer y al atardecer." },
        { title: "Para quién quizá no funcione", text: "Viajeros que rechazan tramos con infraestructura simple (Atins, Barreirinhas) deben considerar reducir la ruta solo a Jericoacoara y Bahía, con hotelería más robusta." },
      ],
    },
    itinerary: {
      heading: "Cómo encadenar la ruta, tramo a tramo",
      intro: "La lógica combina vuelos regionales con travesías terrestres y marítimas, con Fortaleza, Jericoacoara, São Luís y Salvador como puertas de entrada y salida de cada bloque.",
      items: [
        { title: "Días 1 a 4 — Jericoacoara y Preá", text: "Llegada a Fortaleza (vuelo internacional o doméstico) y conexión al aeropuerto de Jericoacoara (JJD), a unos 20 minutos en buggy del pueblo. Cuatro noches entre dunas, lagunas y la base de kitesurf en Preá." },
        { title: "Días 5 a 8 — Lençóis Maranhenses y Rota das Emoções", text: "Transfer 4x4 por la Rota das Emoções hasta Barreirinhas o Atins, cruzando el Delta del Parnaíba en lancha, o vuelo a São Luís con conexión terrestre. Cuatro noches para lagunas, dunas y el encuentro del río con el mar." },
        { title: "Días 9 a 13 — Bahía: Costa dos Coqueiros y Costa do Dendê", text: "Vuelo de São Luís a Salvador con conexión, transfer a Praia do Forte (cerca de 1h) para dos noches, seguido de travesía terrestre y en barco hasta la Península de Maraú o Boipeba para las tres noches finales." },
        { title: "Regreso", text: "Transfer en barco y/o terrestre de vuelta a Salvador para el vuelo de salida, cerrando la ruta por el mismo eje aéreo de entrada." },
      ],
    },
    tips: {
      heading: "Consejos prácticos para esta ruta",
      items: [
        "El aeropuerto de Jericoacoara (JJD) recibe vuelos directos de pocos hubs; confirme la malla aérea de la temporada antes de cerrar las fechas.",
        "Lleve traje de baño, calzado de senderismo ligero para las dunas y protección solar reforzada — el sol y el viento del litoral nordestino deshidratan rápido.",
        "La travesía entre Barreirinhas y Atins se hace en lancha por el río y el mar; en días de marea desfavorable el trayecto puede ser más largo.",
        "Boipeba no tiene coches: el desplazamiento en la isla es a pie, en bicicleta o tractor — planifique equipaje ligero para este tramo.",
        "Reserve con antelación la travesía hasta la Península de Maraú, hecha por balsa y carretera, especialmente en temporada alta.",
        "La señal de celular es inestable en Atins y en partes de Boipeba; avise a la familia antes del viaje.",
      ],
    },
    faq: [
      { q: "¿Cuántas noches son ideales para la ruta Costas del Nordeste?", a: "Trece noches es el equilibrio ideal: 4 en Jericoacoara y Preá, 4 en Lençóis Maranhenses y la Rota das Emoções, y 5 en Bahía entre Praia do Forte y Maraú/Boipeba." },
      { q: "¿Cuál es la mejor época para esta ruta?", a: "De julio a noviembre, cuando los vientos favorecen Jericoacoara, las lagunas de Lençóis Maranhenses tienen buen volumen y Bahía tiene el mar más calmo." },
      { q: "¿Cómo se llega a Jericoacoara?", a: "Por el aeropuerto de Jericoacoara (JJD), con vuelos regionales desde Fortaleza, o por transfer terrestre de unas 4 a 5 horas desde la capital cearense." },
      { q: "¿Se necesita 4x4 para el tramo de Maranhão?", a: "Sí, los traslados por la Rota das Emoções y el acceso a Atins requieren vehículos 4x4 y, en parte del trayecto, travesía en balsa y lancha." },
      { q: "¿Cómo se llega a Boipeba y a la Península de Maraú?", a: "Por combinación de transfer terrestre, balsa y barco desde Salvador o Ilhéus; no hay acceso directo por carretera en auto particular hasta Boipeba." },
      { q: "¿Esta ruta es cómoda para viajeros mayores de 60 años?", a: "Es viable con buena disposición para tramos de barco y carretera; recomendamos alojamientos de mayor estructura en cada bloque y un ritmo más pausado entre travesías." },
    ],
    cta: {
      heading: "Diseñemos su ruta por las Costas del Nordeste",
      subheading: "Un consultor humano de Create Travel organiza vuelos regionales, transfers 4x4 y travesías en barco para un viaje fluido entre Ceará, Maranhão y Bahía.",
      button: "Hablar con un travel designer",
    },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },

  it: {
    destinationName: "Coste del Nordeste",
    blurb: "Itinerario coniugato di 13 notti tra Ceará, Maranhão e Bahia: Jericoacoara, Lençóis Maranhenses e le coste di Coqueiros e Dendê.",
    metaTitle: "Coste del Nordeste: itinerario di 13 notti | Create Travel",
    metaDescription: "Guida editoriale all'itinerario coniugato Jericoacoara, Lençóis Maranhenses, Rota das Emoções e Bahia (Praia do Forte e Maraú/Boipeba): stagione ideale, voli e traversate.",
    keywords: "itinerario jericoacoara lençóis maranhenses, itinerario coste nordeste brasile, rota das emoções, itinerario praia do forte, itinerario maraú boipeba, viaggio bahia ceará maranhão",
    h1: "Coste del Nordeste: l'itinerario coniugato da Jericoacoara a Boipeba",
    aiAnswer: "L'itinerario coniugato Coste del Nordeste unisce Jericoacoara e Preá (Ceará), Lençóis Maranhenses e la Rota das Emoções (Maranhão-Piauí) e la Bahia (Costa dos Coqueiros e Costa do Dendê) in circa 13 notti, tra luglio e novembre, collegati da voli via Fortaleza, Jericoacoara (JJD), São Luís e Salvador, con transfer 4x4 e traversate in barca tra le tappe interne.",
    intro: [
      "Poche combinazioni rivelano così bene la diversità della costa brasiliana come questa: dalle dune mobili e i venti costanti di Jericoacoara alle lagune turchesi di Lençóis Maranhenses, fino alle acque tiepide e all'eredità afro-baiana della Costa dos Coqueiros e della Costa do Dendê. Sono tre Nordeste distinti, uniti da un filo di sabbia, vento e mare.",
      "Questa guida nasce dall'esperienza di collegare queste tre tappe in un unico viaggio di circa 13 notti, rispettando la logistica reale dei voli regionali, degli aeroporti piccoli come quello di Jericoacoara e delle traversate in 4x4 e barca che fanno parte del percorso — mai un ostacolo, sempre parte della narrazione.",
    ],
    seasons: {
      heading: "Periodo migliore per l'itinerario Coste del Nordeste",
      intro: "La finestra tra luglio e novembre concentra il meglio delle tre tappe: venti ideali per Jericoacoara, lagune piene a Lençóis Maranhenses e fine della stagione delle piogge in Bahia.",
      windows: [
        { window: "Luglio-agosto", text: "Alisei al culmine a Jericoacoara e Preá, ideali per il kitesurf; lagune di Lençóis ancora con buon volume d'acqua dalle piogge di metà anno." },
        { window: "Settembre", text: "Combinazione ideale di sole forte, lagune ancora piene in Maranhão e mare calmo in Bahia — mese di transizione senza grandi svantaggi in nessuna tappa." },
        { window: "Ottobre", text: "Inizio del periodo più secco in Maranhão, quando le lagune iniziano a calare; ancora eccellente per Ceará e Bahia, con giornate più stabili." },
        { window: "Novembre", text: "Ultime settimane prima che il calo delle lagune maranhensi si accentui; buona finestra per chiudere l'itinerario in Bahia, con l'estate ormai alle porte." },
      ],
    },
    experiences: {
      heading: "Cosa si vive in ogni tappa",
      intro: "Ogni costa ha un'identità propria — di vento e duna, di acqua dolce su sabbia bianca, e di mare tiepido con radici afro-brasiliane.",
      items: [
        { title: "Jericoacoara e Preá — vento, duna e tramonto", text: "La Duna do Pôr do Sol a Jeri, applaudita ogni sera, e Preá come base di kitesurf di riferimento mondiale, con le lagune di Paraíso e Torta a pochi minuti in buggy." },
        { title: "Lençóis Maranhenses — lagune su dune bianche", text: "Un deserto di sabbia bianca punteggiato da lagune di acqua dolce trasparente, più spettacolare tra giugno e settembre, quando il volume di pioggia accumulato è al culmine." },
        { title: "Rota das Emoções — Delta del Parnaíba e Atins", text: "L'incontro del fiume Parnaíba con l'Atlantico in uno dei rari delta in mare aperto del pianeta, navigato in barca tra manghi e dune, con Barreirinhas e il villaggio di pescatori di Atins come basi." },
        { title: "Costa dos Coqueiros — Praia do Forte", text: "Palmeti di cocco infiniti, barriere coralline visitabili a piedi con la bassa marea e il Projeto Tamar, riferimento mondiale nella conservazione delle tartarughe marine." },
        { title: "Costa do Dendê — Penisola di Maraú e Boipeba", text: "Villaggi senza auto, spiagge di sabbia bianca incorniciate da palme da cocco e una cucina di olio di dendê e frutti di mare che riassume la Bahia più autentica." },
        { title: "Traversate come parte dell'esperienza", text: "4x4 tra le dune fra Jericoacoara e il Delta, barca tra Barreirinhas e Atins, e traghetto o barca per raggiungere Boipeba — ogni spostamento è anche paesaggio." },
      ],
    },
    stays: {
      heading: "Dove alloggiare in ogni tappa",
      intro: "L'ospitalità varia da pousadas di charme discrete a resort di spiaggia strutturati, sempre privilegiando l'integrazione con il paesaggio.",
      items: [
        { name: "Vila Kalango o Pousada Jardim do Éden (Jericoacoara)", profile: "Charme e vicinanza al villaggio", text: "Indirizzi di riferimento nel villaggio di Jeri, a pochi passi dalla Duna do Pôr do Sol e dal centro." },
        { name: "Vila Yaya o Villa Preá (Preá)", profile: "Kitesurf e tranquillità", text: "Base più tranquilla di Jeri, adatta a chi privilegia il kitesurf rispetto alla vita notturna." },
        { name: "Pousadas di Atins o Barreirinhas", profile: "Porte d'accesso a Lençóis", text: "Struttura semplice e funzionale, adatta a due o tre notti di esplorazione delle lagune e del Delta del Parnaíba." },
        { name: "Txai Resort o Tivoli Ecoresort Praia do Forte", profile: "Resort strutturato con spiaggia privata", text: "Indirizzi di riferimento sulla Costa dos Coqueiros per chi cerca pieno comfort dopo le tappe più rustiche del Maranhão." },
        { name: "Kiaroa Eco Resort (Maraú) o pousadas di charme a Boipeba", profile: "Isolamento e autenticità sulla Costa do Dendê", text: "Chiusura dell'itinerario in villaggi senza auto, con spiagge deserte e ritmo più lento." },
      ],
    },
    profiles: {
      heading: "Per chi funziona questo itinerario",
      items: [
        { title: "Coppie e viaggiatori in cerca di spiagge con personalità", text: "Ideale per chi vuole andare oltre l'ovvia costa baiana e scoprire paesaggi di dune e delta poco esplorati dagli stranieri." },
        { title: "Praticanti di kitesurf e sport del vento", text: "Jericoacoara e Preá sono tra i migliori spot al mondo tra luglio e novembre, con venti costanti e lagune di supporto." },
        { title: "Fotografi e amanti di paesaggi unici", text: "I Lençóis Maranhenses e il Delta del Parnaíba offrono scenari rari, soprattutto all'alba e al tramonto." },
        { title: "Per chi forse non funziona", text: "I viaggiatori che rifiutano tappe con infrastrutture semplici (Atins, Barreirinhas) dovrebbero considerare di ridurre l'itinerario solo a Jericoacoara e Bahia, con hotellerie più robuste." },
      ],
    },
    itinerary: {
      heading: "Come collegare l'itinerario, tappa per tappa",
      intro: "La logica combina voli regionali con traversate terrestri e marittime, con Fortaleza, Jericoacoara, São Luís e Salvador come porte d'ingresso e uscita di ogni blocco.",
      items: [
        { title: "Giorni 1-4 — Jericoacoara e Preá", text: "Arrivo a Fortaleza (volo internazionale o domestico) e coincidenza per l'aeroporto di Jericoacoara (JJD), a circa 20 minuti in buggy dal villaggio. Quattro notti tra dune, lagune e la base di kitesurf a Preá." },
        { title: "Giorni 5-8 — Lençóis Maranhenses e Rota das Emoções", text: "Transfer 4x4 lungo la Rota das Emoções fino a Barreirinhas o Atins, attraversando il Delta del Parnaíba in barca, oppure volo per São Luís con coincidenza terrestre. Quattro notti per lagune, dune e l'incontro tra fiume e mare." },
        { title: "Giorni 9-13 — Bahia: Costa dos Coqueiros e Costa do Dendê", text: "Volo da São Luís a Salvador con coincidenza, transfer a Praia do Forte (circa 1h) per due notti, seguito da traversata terrestre e in barca fino alla Penisola di Maraú o Boipeba per le tre notti finali." },
        { title: "Ritorno", text: "Transfer in barca e/o terrestre di ritorno a Salvador per il volo di partenza, chiudendo l'itinerario sullo stesso asse aereo d'ingresso." },
      ],
    },
    tips: {
      heading: "Consigli pratici per questo itinerario",
      items: [
        "L'aeroporto di Jericoacoara (JJD) riceve voli diretti da pochi hub; confermare la rete aerea della stagione prima di fissare le date.",
        "Portare costume da bagno, scarpe leggere da trekking per le dune e protezione solare rinforzata — il sole e il vento della costa nordestina disidratano rapidamente.",
        "La traversata tra Barreirinhas e Atins avviene in barca lungo il fiume e il mare; nei giorni di marea sfavorevole il tragitto può allungarsi.",
        "Boipeba non ha auto: gli spostamenti sull'isola avvengono a piedi, in bicicletta o trattore — pianificare bagagli leggeri per questa tappa.",
        "Prenotare in anticipo la traversata verso la Penisola di Maraú, fatta con traghetto e strada, specialmente in alta stagione.",
        "Il segnale telefonico è instabile ad Atins e in parti di Boipeba; avvisare la famiglia prima del viaggio.",
      ],
    },
    faq: [
      { q: "Quante notti sono ideali per l'itinerario Coste del Nordeste?", a: "Tredici notti è l'equilibrio ideale: 4 a Jericoacoara e Preá, 4 a Lençóis Maranhenses e sulla Rota das Emoções, e 5 in Bahia tra Praia do Forte e Maraú/Boipeba." },
      { q: "Qual è il periodo migliore per questo itinerario?", a: "Da luglio a novembre, quando i venti favoriscono Jericoacoara, le lagune di Lençóis Maranhenses hanno buon volume e la Bahia ha il mare più calmo." },
      { q: "Come si arriva a Jericoacoara?", a: "Tramite l'aeroporto di Jericoacoara (JJD), con voli regionali da Fortaleza, o con transfer terrestre di circa 4-5 ore dalla capitale cearense." },
      { q: "Serve un 4x4 per la tappa del Maranhão?", a: "Sì, gli spostamenti lungo la Rota das Emoções e l'accesso ad Atins richiedono veicoli 4x4 e, per parte del percorso, traversate in traghetto e barca." },
      { q: "Come si arriva a Boipeba e alla Penisola di Maraú?", a: "Con una combinazione di transfer terrestre, traghetto e barca da Salvador o Ilhéus; non esiste accesso stradale diretto in auto privata fino a Boipeba." },
      { q: "Questo itinerario è comodo per viaggiatori oltre i 60 anni?", a: "È fattibile con buona disposizione per tratti in barca e strada; consigliamo alloggi più strutturati in ogni blocco e un ritmo più pausato tra le traversate." },
    ],
    cta: {
      heading: "Progettiamo il vostro itinerario sulle Coste del Nordeste",
      subheading: "Un consulente umano di Create Travel organizza voli regionali, transfer 4x4 e traversate in barca per un viaggio fluido tra Ceará, Maranhão e Bahia.",
      button: "Parla con un travel designer",
    },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },

  de: {
    destinationName: "Küsten des Nordostens",
    blurb: "Eine kombinierte 13-nächtige Route durch Ceará, Maranhão und Bahia: Jericoacoara, Lençóis Maranhenses und die Küsten Coqueiros und Dendê.",
    metaTitle: "Küsten des Nordostens: 13-Nächte-Reiseroute | Create Travel",
    metaDescription: "Ein redaktioneller Guide zur kombinierten Route Jericoacoara, Lençóis Maranhenses, Rota das Emoções und Bahia (Praia do Forte und Maraú/Boipeba): beste Reisezeit, Flüge und Überfahrten.",
    keywords: "jericoacoara lençóis maranhenses reiseroute, nordost-brasilien küste route, rota das emoções, praia do forte reiseroute, maraú boipeba reiseroute, bahia ceará maranhão reise",
    h1: "Küsten des Nordostens: die kombinierte Route von Jericoacoara bis Boipeba",
    aiAnswer: "Die kombinierte Route Küsten des Nordostens verbindet Jericoacoara und Preá (Ceará), Lençóis Maranhenses und die Rota das Emoções (Maranhão-Piauí) sowie Bahia (Costa dos Coqueiros und Costa do Dendê) über rund 13 Nächte, zwischen Juli und November, verknüpft durch Flüge über Fortaleza, Jericoacoara (JJD), São Luís und Salvador, mit 4x4-Transfers und Bootsüberfahrten zwischen den Binnenetappen.",
    intro: [
      "Nur wenige Kombinationen zeigen die Vielfalt der brasilianischen Küste so gut wie diese: von den wandernden Dünen und beständigen Winden Jericoacoaras über die türkisfarbenen Lagunen der Lençóis Maranhenses bis zu den warmen Gewässern und dem afro-bahianischen Erbe der Costa dos Coqueiros und der Costa do Dendê. Es sind drei unterschiedliche Nordosten, verbunden durch einen roten Faden aus Sand, Wind und Meer.",
      "Dieser Guide entstand aus der Erfahrung, diese drei Etappen in einer einzigen Reise von rund 13 Nächten zu verknüpfen, unter Berücksichtigung der realen Logistik von Regionalflügen, kleinen Flughäfen wie dem von Jericoacoara sowie der 4x4- und Bootsüberfahrten, die Teil der Route sind — nie ein Hindernis, immer Teil der Erzählung.",
    ],
    seasons: {
      heading: "Beste Reisezeit für die Route Küsten des Nordostens",
      intro: "Das Zeitfenster zwischen Juli und November bündelt das Beste aller drei Etappen: ideale Winde für Jericoacoara, volle Lagunen in den Lençóis Maranhenses und das Ende der Regenzeit in Bahia.",
      windows: [
        { window: "Juli bis August", text: "Passatwinde auf ihrem Höhepunkt in Jericoacoara und Preá, ideal zum Kitesurfen; Lagunen der Lençóis noch mit gutem Wasservolumen aus den Regenfällen der Jahresmitte." },
        { window: "September", text: "Ideale Kombination aus starker Sonne, noch vollen Lagunen in Maranhão und ruhiger See in Bahia — ein Übergangsmonat ohne größere Nachteile in irgendeiner Etappe." },
        { window: "Oktober", text: "Beginn der trockeneren Periode in Maranhão, wenn die Lagunen zu sinken beginnen; weiterhin ausgezeichnet für Ceará und Bahia, mit stabileren Tagen." },
        { window: "November", text: "Letzte Wochen, bevor der Rückgang der maranhensischen Lagunen sich verstärkt; gutes Zeitfenster, um die Route in Bahia abzuschließen, während der Sommer naht." },
      ],
    },
    experiences: {
      heading: "Was jede Etappe bietet",
      intro: "Jede Küste hat eine eigene Identität — Wind und Düne, Süßwasser über weißem Sand, und warmes Meer mit afro-brasilianischen Wurzeln.",
      items: [
        { title: "Jericoacoara und Preá — Wind, Düne und Sonnenuntergang", text: "Die Duna do Pôr do Sol in Jeri, jeden Abend beklatscht, und Preá als weltweit anerkannte Kitesurf-Basis, mit den Lagunen Paraíso und Torta wenige Minuten per Buggy entfernt." },
        { title: "Lençóis Maranhenses — Lagunen über weißen Dünen", text: "Eine Wüste aus weißem Sand, durchsetzt mit klaren Süßwasserlagunen, am eindrucksvollsten zwischen Juni und September, wenn das angesammelte Regenvolumen seinen Höhepunkt erreicht." },
        { title: "Rota das Emoções — Parnaíba-Delta und Atins", text: "Das Zusammentreffen des Flusses Parnaíba mit dem Atlantik in einem der seltenen offenen Meeresdeltas der Welt, per Boot zwischen Mangroven und Dünen befahren, mit Barreirinhas und dem Fischerdorf Atins als Basen." },
        { title: "Costa dos Coqueiros — Praia do Forte", text: "Endlose Kokospalmenhaine, bei Ebbe zu Fuß erreichbare Korallenriffe und das Projeto Tamar, weltweite Referenz im Schutz von Meeresschildkröten." },
        { title: "Costa do Dendê — Halbinsel Maraú und Boipeba", text: "Autofreie Dörfer, weiße Sandstrände gerahmt von Kokospalmen und eine Küche aus Dendê-Öl und Meeresfrüchten, die das authentischste Bahia zusammenfasst." },
        { title: "Überfahrten als Teil der Erfahrung", text: "4x4 über die Dünen zwischen Jericoacoara und dem Delta, Boot zwischen Barreirinhas und Atins, und Fähre oder Boot, um Boipeba zu erreichen — jeder Transfer ist selbst Landschaft." },
      ],
    },
    stays: {
      heading: "Wo man auf jeder Etappe übernachtet",
      intro: "Die Hotellerie reicht von diskreten charmanten Pousadas bis zu strukturierten Strandresorts, stets mit Fokus auf die Einbindung in die Landschaft.",
      items: [
        { name: "Vila Kalango oder Pousada Jardim do Éden (Jericoacoara)", profile: "Charme und Nähe zum Dorf", text: "Referenzadressen im Dorf Jeri, nur wenige Schritte von der Duna do Pôr do Sol und dem Zentrum entfernt." },
        { name: "Vila Yaya oder Villa Preá (Preá)", profile: "Kitesurfen und Ruhe", text: "Ruhigere Basis als Jeri, geeignet für alle, die Kitesurfen vor Nachtleben priorisieren." },
        { name: "Pousadas in Atins oder Barreirinhas", profile: "Tore zu den Lençóis", text: "Einfache, funktionale Struktur, geeignet für zwei bis drei Nächte zur Erkundung der Lagunen und des Parnaíba-Deltas." },
        { name: "Txai Resort oder Tivoli Ecoresort Praia do Forte", profile: "Strukturiertes Resort mit Privatstrand", text: "Referenzadressen an der Costa dos Coqueiros für alle, die nach den rustikaleren Etappen Maranhãos vollen Komfort suchen." },
        { name: "Kiaroa Eco Resort (Maraú) oder charmante Pousadas in Boipeba", profile: "Abgeschiedenheit und Authentizität an der Costa do Dendê", text: "Abschluss der Route in autofreien Dörfern, mit menschenleeren Stränden und langsamerem Rhythmus." },
      ],
    },
    profiles: {
      heading: "Für wen diese Route funktioniert",
      items: [
        { title: "Paare und Reisende, die Strände mit Charakter suchen", text: "Ideal für alle, die über die offensichtliche bahianische Küste hinausgehen und wenig von Ausländern erkundete Dünen- und Deltalandschaften entdecken möchten." },
        { title: "Kitesurfer und Windsportler", text: "Jericoacoara und Preá zählen zwischen Juli und November zu den besten Spots der Welt, mit beständigen Winden und unterstützenden Lagunen." },
        { title: "Fotografen und Liebhaber einzigartiger Landschaften", text: "Die Lençóis Maranhenses und das Parnaíba-Delta bieten seltene Szenerien, besonders bei Sonnenaufgang und -untergang." },
        { title: "Für wen es vielleicht nicht passt", text: "Reisende, die Etappen mit einfacher Infrastruktur (Atins, Barreirinhas) ablehnen, sollten erwägen, die Route auf Jericoacoara und Bahia mit solider Hotellerie zu beschränken." },
      ],
    },
    itinerary: {
      heading: "Wie man die Route Etappe für Etappe verknüpft",
      intro: "Die Logik kombiniert Regionalflüge mit Land- und Seeüberfahrten, wobei Fortaleza, Jericoacoara, São Luís und Salvador als Ein- und Ausstiegstore jedes Blocks dienen.",
      items: [
        { title: "Tage 1 bis 4 — Jericoacoara und Preá", text: "Ankunft in Fortaleza (internationaler oder inländischer Flug) und Anschluss zum Flughafen Jericoacoara (JJD), etwa 20 Minuten per Buggy vom Dorf entfernt. Vier Nächte zwischen Dünen, Lagunen und der Kitesurf-Basis in Preá." },
        { title: "Tage 5 bis 8 — Lençóis Maranhenses und Rota das Emoções", text: "4x4-Transfer entlang der Rota das Emoções nach Barreirinhas oder Atins, mit Bootsüberquerung des Parnaíba-Deltas, oder Flug nach São Luís mit Landanschluss. Vier Nächte für Lagunen, Dünen und das Zusammentreffen von Fluss und Meer." },
        { title: "Tage 9 bis 13 — Bahia: Costa dos Coqueiros und Costa do Dendê", text: "Flug von São Luís nach Salvador mit Anschluss, Transfer nach Praia do Forte (etwa 1 Std.) für zwei Nächte, gefolgt von einer Land- und Bootsüberfahrt zur Halbinsel Maraú oder nach Boipeba für die letzten drei Nächte." },
        { title: "Rückreise", text: "Boots- und/oder Landtransfer zurück nach Salvador zum Abflug, womit sich die Route über dieselbe Flugachse schließt, über die sie begann." },
      ],
    },
    tips: {
      heading: "Praktische Tipps für diese Route",
      items: [
        "Der Flughafen Jericoacoara (JJD) empfängt Direktflüge nur von wenigen Drehkreuzen; das saisonale Flugnetz vor Buchung der Termine bestätigen.",
        "Badebekleidung, leichte Wanderschuhe für die Dünen und verstärkten Sonnenschutz mitbringen — Sonne und Wind der nordöstlichen Küste dehydrieren schnell.",
        "Die Überfahrt zwischen Barreirinhas und Atins erfolgt per Boot über Fluss und Meer; an Tagen mit ungünstiger Tide kann die Fahrt länger dauern.",
        "Boipeba hat keine Autos: Fortbewegung auf der Insel erfolgt zu Fuß, per Fahrrad oder Traktor — für diese Etappe leichtes Gepäck einplanen.",
        "Die Überfahrt zur Halbinsel Maraú, per Fähre und Straße, vor allem in der Hochsaison im Voraus buchen.",
        "Handysignal ist in Atins und Teilen von Boipeba unbeständig; die Familie vor der Reise informieren.",
      ],
    },
    faq: [
      { q: "Wie viele Nächte sind ideal für die Route Küsten des Nordostens?", a: "Dreizehn Nächte sind das ideale Gleichgewicht: 4 in Jericoacoara und Preá, 4 in den Lençóis Maranhenses und auf der Rota das Emoções sowie 5 in Bahia zwischen Praia do Forte und Maraú/Boipeba." },
      { q: "Was ist die beste Reisezeit für diese Route?", a: "Juli bis November, wenn die Winde Jericoacoara begünstigen, die Lagunen der Lençóis Maranhenses gut gefüllt sind und das Meer in Bahia ruhiger ist." },
      { q: "Wie erreicht man Jericoacoara?", a: "Über den Flughafen Jericoacoara (JJD) mit Regionalflügen ab Fortaleza, oder per Landtransfer von etwa 4 bis 5 Stunden ab der Landeshauptstadt." },
      { q: "Wird ein 4x4 für die Maranhão-Etappe benötigt?", a: "Ja, Transfers entlang der Rota das Emoções und der Zugang nach Atins erfordern 4x4-Fahrzeuge und, auf einem Teil der Strecke, eine Fähr- und Bootsüberfahrt." },
      { q: "Wie erreicht man Boipeba und die Halbinsel Maraú?", a: "Durch eine Kombination aus Landtransfer, Fähre und Boot ab Salvador oder Ilhéus; es gibt keinen direkten Straßenzugang mit dem eigenen Auto nach Boipeba." },
      { q: "Ist diese Route für Reisende über 60 angenehm?", a: "Sie ist mit guter Bereitschaft für Boots- und Landetappen machbar; wir empfehlen besser strukturierte Unterkünfte in jedem Block und ein ruhigeres Tempo zwischen den Überfahrten." },
    ],
    cta: {
      heading: "Lassen Sie uns Ihre Route entlang der Küsten des Nordostens gestalten",
      subheading: "Ein persönlicher Berater von Create Travel organisiert Regionalflüge, 4x4-Transfers und Bootsüberfahrten für eine reibungslose Reise zwischen Ceará, Maranhão und Bahia.",
      button: "Mit einem Travel Designer sprechen",
    },
    readingMinutes: 11,
    publishedAt: "2026-08-11",
  },
};
