import type { BrazilGuideLocalized } from "./types";

export const conjugadoSulSerraCanyonsGuide: BrazilGuideLocalized = {
  pt: {
    destinationName: "Serra, Canyons e Litoral Catarinense",
    blurb: "Roteiro conjugado de 11 noites pelo Sul do Brasil: canyons de Cambará do Sul, vinícolas da Serra Gaúcha e litoral de Santa Catarina com baleias-francas.",
    metaTitle: "Serra, Canyons e Litoral Catarinense: roteiro de 11 noites | Create Travel",
    metaDescription: "Guia autoral do roteiro conjugado Cambará do Sul, Serra Gaúcha e Praia do Rosa: melhor época, distâncias reais e baleia franca de julho a novembro.",
    keywords: "roteiro sul do brasil, canyons aparados da serra, roteiro vale dos vinhedos, praia do rosa baleia franca, roteiro gramado bento gonçalves florianópolis",
    h1: "Serra, Canyons e Litoral Catarinense: o roteiro conjugado do Sul do Brasil",
    aiAnswer: "O roteiro conjugado pelos canyons de Cambará do Sul, a Serra Gaúcha vinícola e o litoral de Santa Catarina funciona melhor entre junho e setembro, com cerca de 11 noites: 3 nos canyons, 4 entre Bento Gonçalves e Gramado, e 4 na Praia do Rosa e Florianópolis, encadeados de carro a partir de Porto Alegre com saída por Florianópolis.",
    intro: [
      "O Sul do Brasil guarda uma paisagem que contradiz o imaginário tropical do país: paredões de basalto com quase mil metros de queda vertical, vinhedos organizados em terraços entre morros de araucária e um litoral atlântico frio o suficiente para receber baleias-francas todos os invernos. É um roteiro de estações marcadas, estradas sinuosas e uma gastronomia de vinho e queijo que rivaliza com destinos europeus.",
      "Este guia nasce da experiência de encadear os canyons de Aparados da Serra e da Serra Geral, a rota de vinícolas do Vale dos Vinhedos e Pinto Bandeira, e o litoral catarinense da Praia do Rosa e Florianópolis, respeitando as distâncias reais de estrada entre Porto Alegre, a Serra Gaúcha e o litoral de Santa Catarina.",
    ],
    seasons: {
      heading: "Melhor época para o roteiro Serra, Canyons e Litoral Catarinense",
      intro: "O inverno e o início da primavera do Sul do Brasil, entre junho e setembro, concentram céu mais limpo nos canyons, temperaturas agradáveis para caminhadas na Serra Gaúcha e a temporada de observação da baleia franca no litoral.",
      windows: [
        { window: "Junho a julho", text: "Frio seco, noites geladas na Serra Gaúcha e em Cambará do Sul, e início da temporada de baleias-francas na Praia do Rosa, que se estende até novembro." },
        { window: "Agosto", text: "Mês de menor volume de chuva no ano na região dos canyons, com visibilidade mais consistente para o Cânion Itaimbezinho e o Cânion Fortaleza." },
        { window: "Setembro", text: "Transição para a primavera, vinhedos em brotação no Vale dos Vinhedos e temperaturas mais amenas para o litoral de Santa Catarina." },
        { window: "Dezembro a fevereiro — evitar canyons e vinícolas", text: "Verão gaúcho e catarinense: calor intenso na Serra e no vale, praias lotadas em Florianópolis e ausência da baleia franca, que já migrou para águas antárticas." },
      ],
    },
    experiences: {
      heading: "O que se vive em cada trecho",
      intro: "Cada etapa tem geografia e ritmo próprios — dos paredões verticais dos canyons ao brinde entre parreiras, até o mar frio onde as baleias vêm parir.",
      items: [
        { title: "Cânion Itaimbezinho e Cânion Fortaleza", text: "No Parque Nacional de Aparados da Serra e no Parque Nacional da Serra Geral, trilhas de borda revelam paredões de quase 720 metros de altura, com araucárias centenárias e neblina que sobe do vale ao amanhecer." },
        { title: "Vale dos Vinhedos e Pinto Bandeira", text: "Vinícolas centenárias de imigração italiana produzem espumantes de método tradicional em altitude — um roteiro de degustação entre casarões de pedra e videiras organizadas em curvas de nível." },
        { title: "Gramado e a Serra Gaúcha em clima europeu", text: "Arquitetura de inspiração alemã e italiana, gastronomia de fondue e chocolate, e passeios de trem entre morros que lembram paisagens alpinas fora do eixo tropical do Brasil." },
        { title: "Baleia franca na Praia do Rosa", text: "Entre julho e novembro, fêmeas de baleia franca austral vêm parir e amamentar filhotes a poucos metros da areia — um dos raros espetáculos de vida selvagem visível da praia sem embarcação, no litoral sul de Santa Catarina." },
        { title: "Florianópolis e suas dezenas de praias", text: "A Ilha de Santa Catarina alterna praias de surf, lagoas e vilas de pescadores açorianos, com a Lagoa da Conceição e a Barra da Lagoa como bases de charme para caminhar e comer bem." },
        { title: "Estradas panorâmicas entre serra e litoral", text: "O trajeto de carro entre Cambará do Sul, a Serra Gaúcha e o litoral catarinense atravessa a Serra do Rio do Rastro e trechos da BR-101, com mirantes que valem parada." },
      ],
    },
    stays: {
      heading: "Onde ficar em cada trecho",
      intro: "A hotelaria do Sul combina charme rústico de montanha, resorts vinícolas de arquitetura contemporânea e pousadas de praia com vista para o mar aberto.",
      items: [
        { name: "Pousadas de charme em Cambará do Sul e São Francisco de Paula", profile: "Base para os canyons", text: "Endereços rústicos e aconchegantes, com lareira, próximos às entradas dos parques nacionais de Aparados da Serra e Serra Geral." },
        { name: "Cabernet Fonte Suíça ou Vinocap (Bento Gonçalves)", profile: "Imersão vinícola em altitude", text: "Hospedagem em meio a vinhedos do Vale dos Vinhedos, com vista para os terraços de uva e proximidade das vinícolas de espumante." },
        { name: "Hotéis de charme em Gramado", profile: "Conforto europeu na Serra Gaúcha", text: "Endereços com arquitetura de inspiração alpina, spas e gastronomia refinada, ideais para duas noites de descanso entre os canyons e o litoral." },
        { name: "Pousadas de charme na Praia do Rosa", profile: "Vista para o mar das baleias", text: "Pousadas em penhascos e dunas com vista privilegiada para a temporada de baleias-francas, entre julho e novembro." },
        { name: "Hotéis boutique na Lagoa da Conceição (Florianópolis)", profile: "Base urbana e de praia", text: "Endereços de charme junto à lagoa, com fácil acesso às praias de surf e à vida gastronômica da ilha." },
      ],
    },
    profiles: {
      heading: "Para quem este roteiro funciona",
      items: [
        { title: "Casais de meia-idade em busca de estações marcadas", text: "Perfeito para quem quer sentir frio no Brasil, com lareiras, vinho e paisagens de outono e inverno fora do imaginário tropical." },
        { title: "Amantes de vinho e gastronomia", text: "O Vale dos Vinhedos e Pinto Bandeira oferecem uma das cenas de espumante mais maduras da América do Sul, com produtores de terceira e quarta geração italiana." },
        { title: "Observadores de vida selvagem", text: "A temporada de baleia franca na Praia do Rosa é um dos raros encontros de mamíferos marinhos visíveis da costa sem sair de barco." },
        { title: "Para quem talvez não funcione", text: "Viajantes que buscam apenas praia e calor intenso devem evitar o trecho de inverno na Serra Gaúcha e nos canyons, e considerar apenas o litoral catarinense no verão — sem baleias." },
      ],
    },
    itinerary: {
      heading: "Como encadear o roteiro, trecho a trecho",
      intro: "A lógica aqui é rodoviária entre a serra e o litoral, com Porto Alegre como porta aérea de entrada e Florianópolis como porta de saída.",
      items: [
        { title: "Dias 1 a 3 — Cambará do Sul e os canyons", text: "Chegada a Porto Alegre e cerca de 3h30 de carro até Cambará do Sul. Três noites para o Cânion Itaimbezinho, o Cânion Fortaleza e trilhas de borda no Parque Nacional de Aparados da Serra." },
        { title: "Dias 4 a 7 — Serra Gaúcha: Vale dos Vinhedos e Gramado", text: "Cerca de 2h30 de estrada até Bento Gonçalves. Duas noites entre vinícolas do Vale dos Vinhedos e Pinto Bandeira, seguidas de duas noites em Gramado, a 1h de distância, para gastronomia e passeios de montanha." },
        { title: "Dias 8 a 11 — Litoral de Santa Catarina: Praia do Rosa e Florianópolis", text: "Deslocamento de cerca de 4h30 de carro até a Praia do Rosa, com parada opcional na Serra do Rio do Rastro. Duas noites para observação de baleias-francas (julho a novembro) e duas noites em Florianópolis, a 1h30 de distância, para praias e gastronomia da ilha." },
        { title: "Retorno", text: "Voo de Florianópolis para São Paulo ou Rio de Janeiro com conexão internacional, fechando o roteiro pela porta aérea catarinense." },
      ],
    },
    tips: {
      heading: "Dicas práticas para este roteiro",
      items: [
        "Leve roupas de frio de verdade: as noites em Cambará do Sul e na Serra Gaúcha entre junho e agosto podem chegar perto de zero grau.",
        "Reserve as trilhas de borda dos canyons com antecedência em dias de fim de semana, quando a procura aumenta mesmo fora da alta temporada.",
        "A observação de baleias-francas na Praia do Rosa pode ser feita da areia ou de mirantes, sem necessidade de embarcação — respeite a distância recomendada pelos guias locais.",
        "A Serra do Rio do Rastro, entre a Serra Gaúcha e o litoral catarinense, tem curvas fechadas e neblina frequente; evite dirigir esse trecho à noite.",
        "O Vale dos Vinhedos funciona melhor com carro próprio ou motorista particular, já que as vinícolas ficam espalhadas por estradas rurais sem transporte público.",
        "Considere alugar carro em Porto Alegre e devolvê-lo em Florianópolis, evitando repetir o trajeto de volta.",
      ],
    },
    faq: [
      { q: "Quantas noites são ideais para o roteiro Serra, Canyons e Litoral Catarinense?", a: "Onze noites é o equilíbrio ideal: 3 nos canyons de Cambará do Sul, 4 entre o Vale dos Vinhedos e Gramado, e 4 na Praia do Rosa e Florianópolis." },
      { q: "Qual a melhor época para ver baleias-francas na Praia do Rosa?", a: "De julho a novembro, com pico de avistamentos entre agosto e outubro, quando fêmeas amamentam filhotes próximo à costa." },
      { q: "É preciso alugar carro para esse roteiro?", a: "Sim. O deslocamento entre os canyons, a Serra Gaúcha e o litoral catarinense depende de estrada, e boa parte das vinícolas e mirantes não tem transporte público." },
      { q: "Quais são as portas aéreas de entrada e saída?", a: "Porto Alegre para a chegada, com acesso rodoviário aos canyons e à Serra Gaúcha, e Florianópolis para a saída, após o trecho de litoral." },
      { q: "Dá para fazer esse roteiro no verão?", a: "É possível, mas sem baleias-francas e com calor mais intenso na Serra Gaúcha; o inverno e o início da primavera concentram as melhores condições para todo o encadeamento." },
      { q: "Esse roteiro é confortável para viajantes acima de 60 anos?", a: "Sim, com boa condição física para caminhadas leves a moderadas nas trilhas de borda dos canyons; o restante do roteiro combina estrada e passeios de ritmo tranquilo." },
    ],
    cta: {
      heading: "Vamos desenhar o seu roteiro pelo Sul do Brasil",
      subheading: "Um consultor humano da Create Travel organiza motoristas, reservas de vinícolas e pousadas de charme para uma travessia bem encadeada entre serra e litoral.",
      button: "Falar com um travel designer",
    },
    readingMinutes: 10,
    publishedAt: "2026-08-11",
  },

  en: {
    destinationName: "Serra, Canyons & Santa Catarina Coast",
    blurb: "A conjugated 11-night route through southern Brazil: the Cambará do Sul canyons, Serra Gaúcha wine country and the Santa Catarina coast with right whales.",
    metaTitle: "Serra, Canyons & Santa Catarina Coast: 11-Night Itinerary | Create Travel",
    metaDescription: "An editorial guide to the conjugated route through Cambará do Sul, Serra Gaúcha and Praia do Rosa: best season, real distances and right whales from July to November.",
    keywords: "southern brazil itinerary, aparados da serra canyons, vale dos vinhedos wine route, praia do rosa right whale, gramado bento gonçalves florianópolis itinerary",
    h1: "Serra, Canyons & Santa Catarina Coast: the conjugated route through southern Brazil",
    aiAnswer: "The conjugated route through the Cambará do Sul canyons, the wine-growing Serra Gaúcha and the Santa Catarina coast works best from June to September, over roughly 11 nights: 3 in the canyons, 4 between Bento Gonçalves and Gramado, and 4 in Praia do Rosa and Florianópolis, linked by road from Porto Alegre with departure via Florianópolis.",
    intro: [
      "Southern Brazil holds a landscape that contradicts the country's tropical image: basalt walls with nearly a thousand meters of vertical drop, vineyards terraced among araucaria-covered hills, and an Atlantic coastline cold enough to host right whales every winter. It's a route of distinct seasons, winding roads and a wine-and-cheese gastronomy that rivals European destinations.",
      "This guide comes from experience linking the Aparados da Serra and Serra Geral canyons, the wine route through Vale dos Vinhedos and Pinto Bandeira, and the Santa Catarina coast of Praia do Rosa and Florianópolis, respecting the real road distances between Porto Alegre, the Serra Gaúcha and the Santa Catarina coast.",
    ],
    seasons: {
      heading: "Best time for the Serra, Canyons & Santa Catarina Coast route",
      intro: "Southern Brazil's winter and early spring, from June to September, bring clearer skies to the canyons, pleasant hiking temperatures in the Serra Gaúcha and right whale season along the coast.",
      windows: [
        { window: "June to July", text: "Dry cold, freezing nights in the Serra Gaúcha and Cambará do Sul, and the start of right whale season in Praia do Rosa, which runs through November." },
        { window: "August", text: "The driest month of the year in the canyon region, with more consistent visibility at Itaimbezinho and Fortaleza canyons." },
        { window: "September", text: "Transition into spring, budding vines in Vale dos Vinhedos and milder temperatures on the Santa Catarina coast." },
        { window: "December to February — avoid canyons and wineries", text: "Southern Brazilian summer: intense heat in the Serra and the valley, crowded beaches in Florianópolis, and no right whales, already migrated to Antarctic waters." },
      ],
    },
    experiences: {
      heading: "What each leg delivers",
      intro: "Each stage has its own geography and rhythm — from the canyons' vertical walls to a toast among vines, to the cold sea where whales come to give birth.",
      items: [
        { title: "Itaimbezinho and Fortaleza canyons", text: "In Aparados da Serra and Serra Geral national parks, rim trails reveal walls nearly 720 meters high, with centuries-old araucaria trees and mist rising from the valley at dawn." },
        { title: "Vale dos Vinhedos and Pinto Bandeira", text: "Century-old wineries founded by Italian immigrants produce traditional-method sparkling wines at altitude — a tasting route among stone farmhouses and contour-planted vines." },
        { title: "Gramado and the Serra Gaúcha's European climate", text: "German- and Italian-inspired architecture, fondue and chocolate gastronomy, and train rides through hills reminiscent of alpine landscapes outside Brazil's tropical axis." },
        { title: "Right whales at Praia do Rosa", text: "Between July and November, female southern right whales come to give birth and nurse calves just meters from the sand — one of the rare wildlife spectacles visible from shore without a boat, on Santa Catarina's southern coast." },
        { title: "Florianópolis and its dozens of beaches", text: "Santa Catarina Island alternates surf beaches, lagoons and Azorean fishing villages, with Lagoa da Conceição and Barra da Lagoa as charming bases for walking and eating well." },
        { title: "Panoramic roads between mountains and coast", text: "The drive between Cambará do Sul, the Serra Gaúcha and the Santa Catarina coast crosses Serra do Rio do Rastro and stretches of the BR-101 highway, with viewpoints worth a stop." },
      ],
    },
    stays: {
      heading: "Where to stay on each leg",
      intro: "Southern hospitality combines rustic mountain charm, contemporary wine-country resorts and beach inns overlooking the open sea.",
      items: [
        { name: "Charming inns in Cambará do Sul and São Francisco de Paula", profile: "Base for the canyons", text: "Rustic, cozy addresses with fireplaces, near the entrances to Aparados da Serra and Serra Geral national parks." },
        { name: "Cabernet Fonte Suíça or Vinocap (Bento Gonçalves)", profile: "High-altitude wine immersion", text: "Lodging amid the vineyards of Vale dos Vinhedos, overlooking grape terraces and close to sparkling wine producers." },
        { name: "Charming hotels in Gramado", profile: "European comfort in the Serra Gaúcha", text: "Alpine-inspired architecture, spas and refined gastronomy, ideal for two nights of rest between the canyons and the coast." },
        { name: "Charming inns in Praia do Rosa", profile: "Views over the whales' sea", text: "Clifftop and dune inns with privileged views of right whale season, between July and November." },
        { name: "Boutique hotels in Lagoa da Conceição (Florianópolis)", profile: "Urban and beach base", text: "Charming addresses by the lagoon, with easy access to surf beaches and the island's dining scene." },
      ],
    },
    profiles: {
      heading: "Who this route works for",
      items: [
        { title: "Middle-aged couples seeking distinct seasons", text: "Perfect for those who want to feel cold in Brazil, with fireplaces, wine and autumn-winter landscapes outside the tropical imagination." },
        { title: "Wine and gastronomy lovers", text: "Vale dos Vinhedos and Pinto Bandeira offer one of South America's most mature sparkling wine scenes, with third- and fourth-generation Italian producers." },
        { title: "Wildlife watchers", text: "Right whale season at Praia do Rosa is one of the rare encounters with marine mammals visible from the coast without leaving by boat." },
        { title: "Who this may not suit", text: "Travelers seeking only beaches and intense heat should skip the winter leg in the Serra Gaúcha and canyons, and consider only the Santa Catarina coast in summer — without whales." },
      ],
    },
    itinerary: {
      heading: "How to link the route, leg by leg",
      intro: "Logic here is overland between mountains and coast, with Porto Alegre as the air gateway in and Florianópolis as the gateway out.",
      items: [
        { title: "Days 1–3 — Cambará do Sul and the canyons", text: "Arrival in Porto Alegre and about a 3h30 drive to Cambará do Sul. Three nights for Itaimbezinho canyon, Fortaleza canyon and rim trails in Aparados da Serra National Park." },
        { title: "Days 4–7 — Serra Gaúcha: Vale dos Vinhedos and Gramado", text: "About 2h30 by road to Bento Gonçalves. Two nights among wineries in Vale dos Vinhedos and Pinto Bandeira, followed by two nights in Gramado, an hour away, for gastronomy and mountain outings." },
        { title: "Days 8–11 — Santa Catarina coast: Praia do Rosa and Florianópolis", text: "About a 4h30 drive to Praia do Rosa, with an optional stop at Serra do Rio do Rastro. Two nights for right whale watching (July to November) and two nights in Florianópolis, 1h30 away, for beaches and island dining." },
        { title: "Return", text: "Flight from Florianópolis to São Paulo or Rio de Janeiro with an international connection, closing the route through the Santa Catarina air gateway." },
      ],
    },
    tips: {
      heading: "Practical tips for this route",
      items: [
        "Bring real cold-weather clothing: nights in Cambará do Sul and the Serra Gaúcha between June and August can approach freezing.",
        "Book canyon rim trails in advance on weekends, when demand rises even outside peak season.",
        "Right whale watching at Praia do Rosa can be done from the sand or viewpoints, no boat needed — respect the distance recommended by local guides.",
        "Serra do Rio do Rastro, between the Serra Gaúcha and the Santa Catarina coast, has tight curves and frequent fog; avoid driving this stretch at night.",
        "Vale dos Vinhedos works best with a private car or driver, since wineries are spread along rural roads without public transport.",
        "Consider renting a car in Porto Alegre and returning it in Florianópolis, avoiding a repeat drive back.",
      ],
    },
    faq: [
      { q: "How many nights are ideal for the Serra, Canyons & Santa Catarina Coast route?", a: "Eleven nights is the ideal balance: 3 in the Cambará do Sul canyons, 4 between Vale dos Vinhedos and Gramado, and 4 in Praia do Rosa and Florianópolis." },
      { q: "What's the best time to see right whales at Praia do Rosa?", a: "From July to November, with peak sightings between August and October, when females nurse calves close to shore." },
      { q: "Do I need to rent a car for this route?", a: "Yes. Travel between the canyons, the Serra Gaúcha and the Santa Catarina coast depends on the road, and most wineries and viewpoints have no public transport." },
      { q: "What are the air gateways in and out?", a: "Porto Alegre for arrival, with road access to the canyons and Serra Gaúcha, and Florianópolis for departure after the coastal leg." },
      { q: "Can this route be done in summer?", a: "It's possible, but without right whales and with more intense heat in the Serra Gaúcha; winter and early spring hold the best conditions for the whole route." },
      { q: "Is this route comfortable for travelers over 60?", a: "Yes, with reasonable fitness for light to moderate hikes on the canyon rim trails; the rest of the route combines driving and unhurried outings." },
    ],
    cta: {
      heading: "Let's design your route through southern Brazil",
      subheading: "A human consultant at Create Travel arranges drivers, winery reservations and charming inns for a well-linked crossing between mountains and coast.",
      button: "Talk to a travel designer",
    },
    readingMinutes: 10,
    publishedAt: "2026-08-11",
  },

  es: {
    destinationName: "Sierra, Cañones y Litoral de Santa Catarina",
    blurb: "Ruta conjugada de 11 noches por el Sur de Brasil: los cañones de Cambará do Sul, las viñas de la Serra Gaúcha y el litoral de Santa Catarina con ballenas francas.",
    metaTitle: "Sierra, Cañones y Litoral de Santa Catarina: itinerario de 11 noches | Create Travel",
    metaDescription: "Guía editorial de la ruta conjugada Cambará do Sul, Serra Gaúcha y Praia do Rosa: mejor época, distancias reales y ballena franca de julio a noviembre.",
    keywords: "itinerario sur de brasil, cañones aparados da serra, ruta del vino vale dos vinhedos, praia do rosa ballena franca, itinerario gramado bento gonçalves florianópolis",
    h1: "Sierra, Cañones y Litoral de Santa Catarina: la ruta conjugada del Sur de Brasil",
    aiAnswer: "La ruta conjugada por los cañones de Cambará do Sul, la Serra Gaúcha vitivinícola y el litoral de Santa Catarina funciona mejor entre junio y septiembre, con unas 11 noches: 3 en los cañones, 4 entre Bento Gonçalves y Gramado, y 4 en Praia do Rosa y Florianópolis, enlazadas por carretera desde Porto Alegre con salida por Florianópolis.",
    intro: [
      "El Sur de Brasil guarda un paisaje que contradice el imaginario tropical del país: paredones de basalto con casi mil metros de caída vertical, viñedos organizados en terrazas entre colinas de araucarias y un litoral atlántico lo bastante frío como para recibir ballenas francas cada invierno. Es una ruta de estaciones marcadas, carreteras sinuosas y una gastronomía de vino y queso que rivaliza con destinos europeos.",
      "Esta guía nace de la experiencia de enlazar los cañones de Aparados da Serra y Serra Geral, la ruta vitivinícola de Vale dos Vinhedos y Pinto Bandeira, y el litoral catarinense de Praia do Rosa y Florianópolis, respetando las distancias reales de carretera entre Porto Alegre, la Serra Gaúcha y el litoral de Santa Catarina.",
    ],
    seasons: {
      heading: "Mejor época para la ruta Sierra, Cañones y Litoral de Santa Catarina",
      intro: "El invierno y el inicio de la primavera del Sur de Brasil, entre junio y septiembre, concentran cielos más despejados en los cañones, temperaturas agradables para caminar en la Serra Gaúcha y la temporada de observación de la ballena franca en el litoral.",
      windows: [
        { window: "Junio a julio", text: "Frío seco, noches heladas en la Serra Gaúcha y en Cambará do Sul, e inicio de la temporada de ballenas francas en Praia do Rosa, que se extiende hasta noviembre." },
        { window: "Agosto", text: "Mes de menor volumen de lluvia del año en la región de los cañones, con visibilidad más consistente en el Cañón Itaimbezinho y el Cañón Fortaleza." },
        { window: "Septiembre", text: "Transición hacia la primavera, viñedos en brote en el Vale dos Vinhedos y temperaturas más suaves en el litoral de Santa Catarina." },
        { window: "Diciembre a febrero — evitar cañones y bodegas", text: "Verano gaúcho y catarinense: calor intenso en la sierra y el valle, playas abarrotadas en Florianópolis y ausencia de la ballena franca, ya migrada a aguas antárticas." },
      ],
    },
    experiences: {
      heading: "Qué se vive en cada tramo",
      intro: "Cada etapa tiene geografía y ritmo propios — de los paredones verticales de los cañones a un brindis entre viñas, hasta el mar frío donde las ballenas vienen a parir.",
      items: [
        { title: "Cañón Itaimbezinho y Cañón Fortaleza", text: "En los Parques Nacionales de Aparados da Serra y Serra Geral, senderos de borde revelan paredones de casi 720 metros de altura, con araucarias centenarias y niebla que sube del valle al amanecer." },
        { title: "Vale dos Vinhedos y Pinto Bandeira", text: "Bodegas centenarias de inmigración italiana producen espumantes de método tradicional en altitud — una ruta de degustación entre casonas de piedra y viñas organizadas en curvas de nivel." },
        { title: "Gramado y la Serra Gaúcha en clima europeo", text: "Arquitectura de inspiración alemana e italiana, gastronomía de fondue y chocolate, y paseos en tren entre colinas que recuerdan paisajes alpinos fuera del eje tropical de Brasil." },
        { title: "Ballena franca en Praia do Rosa", text: "Entre julio y noviembre, hembras de ballena franca austral vienen a parir y amamantar crías a pocos metros de la arena — uno de los pocos espectáculos de vida silvestre visibles desde la playa sin embarcación, en el litoral sur de Santa Catarina." },
        { title: "Florianópolis y sus decenas de playas", text: "La Isla de Santa Catarina alterna playas de surf, lagunas y pueblos de pescadores azorianos, con la Lagoa da Conceição y Barra da Lagoa como bases de encanto para caminar y comer bien." },
        { title: "Carreteras panorámicas entre sierra y litoral", text: "El trayecto en coche entre Cambará do Sul, la Serra Gaúcha y el litoral catarinense atraviesa la Serra do Rio do Rastro y tramos de la BR-101, con miradores que valen una parada." },
      ],
    },
    stays: {
      heading: "Dónde alojarse en cada tramo",
      intro: "La hotelería del Sur combina encanto rústico de montaña, resorts vitivinícolas de arquitectura contemporánea y posadas de playa con vista al mar abierto.",
      items: [
        { name: "Posadas con encanto en Cambará do Sul y São Francisco de Paula", profile: "Base para los cañones", text: "Direcciones rústicas y acogedoras, con chimenea, cerca de las entradas de los parques nacionales de Aparados da Serra y Serra Geral." },
        { name: "Cabernet Fonte Suíça o Vinocap (Bento Gonçalves)", profile: "Inmersión vitivinícola en altitud", text: "Alojamiento entre viñedos del Vale dos Vinhedos, con vista a las terrazas de uva y cercanía a las bodegas de espumante." },
        { name: "Hoteles con encanto en Gramado", profile: "Confort europeo en la Serra Gaúcha", text: "Direcciones con arquitectura de inspiración alpina, spas y gastronomía refinada, ideales para dos noches de descanso entre los cañones y el litoral." },
        { name: "Posadas con encanto en Praia do Rosa", profile: "Vista al mar de las ballenas", text: "Posadas en acantilados y dunas con vista privilegiada a la temporada de ballenas francas, entre julio y noviembre." },
        { name: "Hoteles boutique en Lagoa da Conceição (Florianópolis)", profile: "Base urbana y de playa", text: "Direcciones con encanto junto a la laguna, con fácil acceso a las playas de surf y a la vida gastronómica de la isla." },
      ],
    },
    profiles: {
      heading: "Para quién funciona esta ruta",
      items: [
        { title: "Parejas de mediana edad en busca de estaciones marcadas", text: "Perfecto para quienes quieren sentir frío en Brasil, con chimeneas, vino y paisajes de otoño e invierno fuera del imaginario tropical." },
        { title: "Amantes del vino y la gastronomía", text: "El Vale dos Vinhedos y Pinto Bandeira ofrecen una de las escenas de espumante más maduras de Sudamérica, con productores de tercera y cuarta generación italiana." },
        { title: "Observadores de vida silvestre", text: "La temporada de ballena franca en Praia do Rosa es uno de los pocos encuentros de mamíferos marinos visibles desde la costa sin salir en barco." },
        { title: "Para quién quizás no funcione", text: "Viajeros que buscan solo playa y calor intenso deben evitar el tramo de invierno en la Serra Gaúcha y los cañones, y considerar solo el litoral catarinense en verano — sin ballenas." },
      ],
    },
    itinerary: {
      heading: "Cómo enlazar la ruta, tramo a tramo",
      intro: "La lógica aquí es por carretera entre la sierra y el litoral, con Porto Alegre como puerta aérea de entrada y Florianópolis como puerta de salida.",
      items: [
        { title: "Días 1 a 3 — Cambará do Sul y los cañones", text: "Llegada a Porto Alegre y unas 3h30 en coche hasta Cambará do Sul. Tres noches para el Cañón Itaimbezinho, el Cañón Fortaleza y senderos de borde en el Parque Nacional de Aparados da Serra." },
        { title: "Días 4 a 7 — Serra Gaúcha: Vale dos Vinhedos y Gramado", text: "Unas 2h30 por carretera hasta Bento Gonçalves. Dos noches entre bodegas del Vale dos Vinhedos y Pinto Bandeira, seguidas de dos noches en Gramado, a una hora de distancia, para gastronomía y paseos de montaña." },
        { title: "Días 8 a 11 — Litoral de Santa Catarina: Praia do Rosa y Florianópolis", text: "Desplazamiento de unas 4h30 en coche hasta Praia do Rosa, con parada opcional en la Serra do Rio do Rastro. Dos noches para observación de ballenas francas (julio a noviembre) y dos noches en Florianópolis, a 1h30 de distancia, para playas y gastronomía de la isla." },
        { title: "Regreso", text: "Vuelo de Florianópolis a São Paulo o Río de Janeiro con conexión internacional, cerrando la ruta por la puerta aérea catarinense." },
      ],
    },
    tips: {
      heading: "Consejos prácticos para esta ruta",
      items: [
        "Lleve ropa de frío de verdad: las noches en Cambará do Sul y la Serra Gaúcha entre junio y agosto pueden acercarse a cero grados.",
        "Reserve los senderos de borde de los cañones con antelación en fines de semana, cuando la demanda aumenta incluso fuera de temporada alta.",
        "La observación de ballenas francas en Praia do Rosa puede hacerse desde la arena o miradores, sin necesidad de embarcación — respete la distancia recomendada por los guías locales.",
        "La Serra do Rio do Rastro, entre la Serra Gaúcha y el litoral catarinense, tiene curvas cerradas y niebla frecuente; evite conducir ese tramo de noche.",
        "El Vale dos Vinhedos funciona mejor con coche propio o chófer particular, ya que las bodegas están repartidas por carreteras rurales sin transporte público.",
        "Considere alquilar el coche en Porto Alegre y devolverlo en Florianópolis, evitando repetir el trayecto de vuelta.",
      ],
    },
    faq: [
      { q: "¿Cuántas noches son ideales para la ruta Sierra, Cañones y Litoral de Santa Catarina?", a: "Once noches es el equilibrio ideal: 3 en los cañones de Cambará do Sul, 4 entre el Vale dos Vinhedos y Gramado, y 4 en Praia do Rosa y Florianópolis." },
      { q: "¿Cuál es la mejor época para ver ballenas francas en Praia do Rosa?", a: "De julio a noviembre, con pico de avistamientos entre agosto y octubre, cuando las hembras amamantan crías cerca de la costa." },
      { q: "¿Es necesario alquilar coche para esta ruta?", a: "Sí. El desplazamiento entre los cañones, la Serra Gaúcha y el litoral catarinense depende de la carretera, y buena parte de las bodegas y miradores no tienen transporte público." },
      { q: "¿Cuáles son las puertas aéreas de entrada y salida?", a: "Porto Alegre para la llegada, con acceso por carretera a los cañones y la Serra Gaúcha, y Florianópolis para la salida, tras el tramo de litoral." },
      { q: "¿Se puede hacer esta ruta en verano?", a: "Es posible, pero sin ballenas francas y con calor más intenso en la Serra Gaúcha; el invierno y el inicio de la primavera concentran las mejores condiciones para todo el recorrido." },
      { q: "¿Esta ruta es cómoda para viajeros mayores de 60 años?", a: "Sí, con buena condición física para caminatas leves a moderadas en los senderos de borde de los cañones; el resto de la ruta combina carretera y paseos de ritmo tranquilo." },
    ],
    cta: {
      heading: "Diseñemos su ruta por el Sur de Brasil",
      subheading: "Un consultor humano de Create Travel organiza chóferes, reservas de bodegas y posadas con encanto para un recorrido bien enlazado entre sierra y litoral.",
      button: "Hablar con un travel designer",
    },
    readingMinutes: 10,
    publishedAt: "2026-08-11",
  },

  it: {
    destinationName: "Serra, Canyon e Litorale di Santa Catarina",
    blurb: "Itinerario coniugato di 11 notti nel Sud del Brasile: i canyon di Cambará do Sul, le cantine della Serra Gaúcha e il litorale di Santa Catarina con le balene franche.",
    metaTitle: "Serra, Canyon e Litorale di Santa Catarina: itinerario di 11 notti | Create Travel",
    metaDescription: "Guida editoriale all'itinerario coniugato Cambará do Sul, Serra Gaúcha e Praia do Rosa: periodo migliore, distanze reali e balena franca da luglio a novembre.",
    keywords: "itinerario sud del brasile, canyon aparados da serra, strada del vino vale dos vinhedos, praia do rosa balena franca, itinerario gramado bento gonçalves florianópolis",
    h1: "Serra, Canyon e Litorale di Santa Catarina: l'itinerario coniugato del Sud del Brasile",
    aiAnswer: "L'itinerario coniugato tra i canyon di Cambará do Sul, la Serra Gaúcha vinicola e il litorale di Santa Catarina funziona meglio da giugno a settembre, con circa 11 notti: 3 nei canyon, 4 tra Bento Gonçalves e Gramado, e 4 a Praia do Rosa e Florianópolis, collegate su strada da Porto Alegre con partenza da Florianópolis.",
    intro: [
      "Il Sud del Brasile custodisce un paesaggio che contraddice l'immaginario tropicale del paese: pareti di basalto con quasi mille metri di dislivello verticale, vigneti terrazzati tra colline di araucarie e un litorale atlantico abbastanza freddo da accogliere balene franche ogni inverno. È un itinerario di stagioni marcate, strade tortuose e una gastronomia di vino e formaggio che rivaleggia con destinazioni europee.",
      "Questa guida nasce dall'esperienza di collegare i canyon di Aparados da Serra e Serra Geral, la strada del vino di Vale dos Vinhedos e Pinto Bandeira, e il litorale catarinense di Praia do Rosa e Florianópolis, rispettando le distanze stradali reali tra Porto Alegre, la Serra Gaúcha e il litorale di Santa Catarina.",
    ],
    seasons: {
      heading: "Periodo migliore per l'itinerario Serra, Canyon e Litorale di Santa Catarina",
      intro: "L'inverno e l'inizio della primavera del Sud del Brasile, tra giugno e settembre, concentrano cieli più limpidi nei canyon, temperature gradevoli per le camminate nella Serra Gaúcha e la stagione di osservazione della balena franca sul litorale.",
      windows: [
        { window: "Giugno-luglio", text: "Freddo secco, notti gelide nella Serra Gaúcha e a Cambará do Sul, e inizio della stagione delle balene franche a Praia do Rosa, che si estende fino a novembre." },
        { window: "Agosto", text: "Il mese con minor piovosità dell'anno nella regione dei canyon, con visibilità più costante al Canyon Itaimbezinho e al Canyon Fortaleza." },
        { window: "Settembre", text: "Transizione verso la primavera, vigneti in germoglio nel Vale dos Vinhedos e temperature più miti sul litorale di Santa Catarina." },
        { window: "Dicembre-febbraio — da evitare per canyon e cantine", text: "Estate gaúcha e catarinense: caldo intenso sulla Serra e nella valle, spiagge affollate a Florianópolis e assenza della balena franca, già migrata verso le acque antartiche." },
      ],
    },
    experiences: {
      heading: "Cosa si vive in ogni tappa",
      intro: "Ogni tappa ha una geografia e un ritmo propri — dalle pareti verticali dei canyon a un brindisi tra i filari, fino al mare freddo dove le balene vengono a partorire.",
      items: [
        { title: "Canyon Itaimbezinho e Canyon Fortaleza", text: "Nei Parchi Nazionali di Aparados da Serra e Serra Geral, sentieri panoramici sull'orlo rivelano pareti alte quasi 720 metri, con araucarie secolari e nebbia che sale dalla valle all'alba." },
        { title: "Vale dos Vinhedos e Pinto Bandeira", text: "Cantine secolari fondate da immigrati italiani producono spumanti con metodo tradizionale in altitudine — un percorso di degustazione tra case di pietra e vigneti disposti a terrazze." },
        { title: "Gramado e la Serra Gaúcha dal clima europeo", text: "Architettura di ispirazione tedesca e italiana, gastronomia a base di fonduta e cioccolato, e gite in treno tra colline che ricordano paesaggi alpini fuori dall'asse tropicale del Brasile." },
        { title: "Balena franca a Praia do Rosa", text: "Tra luglio e novembre, femmine di balena franca australe vengono a partorire e allattare i cuccioli a pochi metri dalla spiaggia — uno dei rari spettacoli di fauna selvatica visibili da terra senza barca, sul litorale sud di Santa Catarina." },
        { title: "Florianópolis e le sue decine di spiagge", text: "L'Isola di Santa Catarina alterna spiagge da surf, lagune e villaggi di pescatori di origine azzorriana, con Lagoa da Conceição e Barra da Lagoa come basi affascinanti per passeggiare e mangiare bene." },
        { title: "Strade panoramiche tra serra e litorale", text: "Il tragitto in auto tra Cambará do Sul, la Serra Gaúcha e il litorale catarinense attraversa la Serra do Rio do Rastro e tratti della BR-101, con belvedere che meritano una sosta." },
      ],
    },
    stays: {
      heading: "Dove alloggiare in ogni tappa",
      intro: "L'ospitalità del Sud combina fascino rustico di montagna, resort vinicoli di architettura contemporanea e locande di spiaggia affacciate sul mare aperto.",
      items: [
        { name: "Locande di charme a Cambará do Sul e São Francisco de Paula", profile: "Base per i canyon", text: "Indirizzi rustici e accoglienti, con camino, vicini agli ingressi dei parchi nazionali di Aparados da Serra e Serra Geral." },
        { name: "Cabernet Fonte Suíça o Vinocap (Bento Gonçalves)", profile: "Immersione vinicola in altitudine", text: "Alloggio tra i vigneti del Vale dos Vinhedos, con vista sui terrazzamenti di uva e vicinanza alle cantine di spumante." },
        { name: "Hotel di charme a Gramado", profile: "Comfort europeo nella Serra Gaúcha", text: "Indirizzi con architettura di ispirazione alpina, spa e gastronomia raffinata, ideali per due notti di riposo tra i canyon e il litorale." },
        { name: "Locande di charme a Praia do Rosa", profile: "Vista sul mare delle balene", text: "Locande su scogliere e dune con vista privilegiata sulla stagione delle balene franche, tra luglio e novembre." },
        { name: "Hotel boutique a Lagoa da Conceição (Florianópolis)", profile: "Base urbana e di spiaggia", text: "Indirizzi di charme accanto alla laguna, con facile accesso alle spiagge da surf e alla vita gastronomica dell'isola." },
      ],
    },
    profiles: {
      heading: "Per chi funziona questo itinerario",
      items: [
        { title: "Coppie di mezza età in cerca di stagioni marcate", text: "Perfetto per chi vuole sentire freddo in Brasile, con camini, vino e paesaggi autunnali e invernali fuori dall'immaginario tropicale." },
        { title: "Amanti del vino e della gastronomia", text: "Il Vale dos Vinhedos e Pinto Bandeira offrono una delle scene di spumante più mature del Sud America, con produttori italiani di terza e quarta generazione." },
        { title: "Osservatori di fauna selvatica", text: "La stagione della balena franca a Praia do Rosa è uno dei rari incontri con mammiferi marini visibili dalla costa senza uscire in barca." },
        { title: "Per chi forse non funziona", text: "I viaggiatori in cerca di sola spiaggia e caldo intenso dovrebbero evitare la tappa invernale nella Serra Gaúcha e nei canyon, e considerare solo il litorale catarinense d'estate — senza balene." },
      ],
    },
    itinerary: {
      heading: "Come collegare l'itinerario, tappa per tappa",
      intro: "La logica qui è stradale tra la serra e il litorale, con Porto Alegre come porta aerea d'ingresso e Florianópolis come porta d'uscita.",
      items: [
        { title: "Giorni 1-3 — Cambará do Sul e i canyon", text: "Arrivo a Porto Alegre e circa 3h30 di auto fino a Cambará do Sul. Tre notti per il Canyon Itaimbezinho, il Canyon Fortaleza e i sentieri sull'orlo nel Parco Nazionale di Aparados da Serra." },
        { title: "Giorni 4-7 — Serra Gaúcha: Vale dos Vinhedos e Gramado", text: "Circa 2h30 di strada fino a Bento Gonçalves. Due notti tra le cantine del Vale dos Vinhedos e Pinto Bandeira, seguite da due notti a Gramado, a un'ora di distanza, per gastronomia e gite in montagna." },
        { title: "Giorni 8-11 — Litorale di Santa Catarina: Praia do Rosa e Florianópolis", text: "Spostamento di circa 4h30 in auto fino a Praia do Rosa, con sosta opzionale alla Serra do Rio do Rastro. Due notti per l'osservazione delle balene franche (luglio-novembre) e due notti a Florianópolis, a 1h30 di distanza, per spiagge e gastronomia dell'isola." },
        { title: "Ritorno", text: "Volo da Florianópolis a São Paulo o Rio de Janeiro con coincidenza internazionale, chiudendo l'itinerario dalla porta aerea catarinense." },
      ],
    },
    tips: {
      heading: "Consigli pratici per questo itinerario",
      items: [
        "Portare vestiti davvero invernali: le notti a Cambará do Sul e nella Serra Gaúcha tra giugno e agosto possono avvicinarsi allo zero.",
        "Prenotare i sentieri sull'orlo dei canyon in anticipo nei weekend, quando la richiesta aumenta anche fuori dall'alta stagione.",
        "L'osservazione delle balene franche a Praia do Rosa può avvenire dalla spiaggia o dai belvedere, senza bisogno di imbarcazione — rispettare la distanza raccomandata dalle guide locali.",
        "La Serra do Rio do Rastro, tra la Serra Gaúcha e il litorale catarinense, ha curve strette e nebbia frequente; evitare di guidare questo tratto di notte.",
        "Il Vale dos Vinhedos funziona meglio con auto propria o autista privato, poiché le cantine sono sparse lungo strade rurali senza trasporto pubblico.",
        "Considerare di noleggiare l'auto a Porto Alegre e restituirla a Florianópolis, evitando di ripetere il tragitto di ritorno.",
      ],
    },
    faq: [
      { q: "Quante notti sono ideali per l'itinerario Serra, Canyon e Litorale di Santa Catarina?", a: "Undici notti è l'equilibrio ideale: 3 nei canyon di Cambará do Sul, 4 tra il Vale dos Vinhedos e Gramado, e 4 a Praia do Rosa e Florianópolis." },
      { q: "Qual è il periodo migliore per vedere le balene franche a Praia do Rosa?", a: "Da luglio a novembre, con picco degli avvistamenti tra agosto e ottobre, quando le femmine allattano i cuccioli vicino alla costa." },
      { q: "È necessario noleggiare un'auto per questo itinerario?", a: "Sì. Lo spostamento tra i canyon, la Serra Gaúcha e il litorale catarinense dipende dalla strada, e gran parte delle cantine e dei belvedere non ha trasporto pubblico." },
      { q: "Quali sono le porte aeree di ingresso e uscita?", a: "Porto Alegre per l'arrivo, con accesso stradale ai canyon e alla Serra Gaúcha, e Florianópolis per la partenza, dopo la tappa costiera." },
      { q: "Si può fare questo itinerario in estate?", a: "È possibile, ma senza balene franche e con caldo più intenso nella Serra Gaúcha; l'inverno e l'inizio della primavera concentrano le migliori condizioni per l'intero percorso." },
      { q: "Questo itinerario è comodo per viaggiatori over 60?", a: "Sì, con una buona condizione fisica per camminate leggere-moderate sui sentieri sull'orlo dei canyon; il resto dell'itinerario combina strada e gite dal ritmo tranquillo." },
    ],
    cta: {
      heading: "Disegniamo il vostro itinerario nel Sud del Brasile",
      subheading: "Un consulente umano di Create Travel organizza autisti, prenotazioni di cantine e locande di charme per un percorso ben collegato tra serra e litorale.",
      button: "Parlare con un travel designer",
    },
    readingMinutes: 10,
    publishedAt: "2026-08-11",
  },

  de: {
    destinationName: "Serra, Canyons und Küste von Santa Catarina",
    blurb: "Eine kombinierte 11-Nächte-Route durch Südbrasilien: die Canyons von Cambará do Sul, die Weinregion Serra Gaúcha und die Küste von Santa Catarina mit Glattwalen.",
    metaTitle: "Serra, Canyons und Küste von Santa Catarina: 11-Nächte-Reiseroute | Create Travel",
    metaDescription: "Ein redaktioneller Guide zur kombinierten Route Cambará do Sul, Serra Gaúcha und Praia do Rosa: beste Reisezeit, reale Entfernungen und Glattwale von Juli bis November.",
    keywords: "südbrasilien reiseroute, aparados da serra canyons, weinstraße vale dos vinhedos, praia do rosa glattwal, reiseroute gramado bento gonçalves florianópolis",
    h1: "Serra, Canyons und Küste von Santa Catarina: die kombinierte Route durch Südbrasilien",
    aiAnswer: "Die kombinierte Route durch die Canyons von Cambará do Sul, die Weinregion Serra Gaúcha und die Küste von Santa Catarina funktioniert am besten von Juni bis September, mit etwa 11 Nächten: 3 in den Canyons, 4 zwischen Bento Gonçalves und Gramado und 4 in Praia do Rosa und Florianópolis, verbunden per Straße ab Porto Alegre mit Abreise über Florianópolis.",
    intro: [
      "Südbrasilien birgt eine Landschaft, die dem tropischen Bild des Landes widerspricht: Basaltwände mit fast tausend Metern Höhenunterschied, terrassierte Weinberge zwischen Araukarien-Hügeln und eine Atlantikküste, die kalt genug ist, um jeden Winter Glattwale zu beherbergen. Es ist eine Route mit ausgeprägten Jahreszeiten, kurvenreichen Straßen und einer Wein- und Käsegastronomie, die europäischen Destinationen Konkurrenz macht.",
      "Dieser Guide entstand aus der Erfahrung, die Canyons von Aparados da Serra und Serra Geral, die Weinroute durch Vale dos Vinhedos und Pinto Bandeira sowie die Küste von Santa Catarina mit Praia do Rosa und Florianópolis zu verbinden, unter Berücksichtigung der realen Straßenentfernungen zwischen Porto Alegre, der Serra Gaúcha und der Küste von Santa Catarina.",
    ],
    seasons: {
      heading: "Beste Reisezeit für die Route Serra, Canyons und Küste von Santa Catarina",
      intro: "Der Winter und das frühe Frühjahr Südbrasiliens, zwischen Juni und September, bringen klarere Himmel in den Canyons, angenehme Wandertemperaturen in der Serra Gaúcha und die Saison der Glattwal-Beobachtung an der Küste.",
      windows: [
        { window: "Juni bis Juli", text: "Trockene Kälte, eisige Nächte in der Serra Gaúcha und in Cambará do Sul, und Beginn der Glattwalsaison in Praia do Rosa, die bis November andauert." },
        { window: "August", text: "Der niederschlagsärmste Monat des Jahres in der Canyon-Region, mit beständigerer Sicht auf den Canyon Itaimbezinho und den Canyon Fortaleza." },
        { window: "September", text: "Übergang zum Frühling, austreibende Weinreben im Vale dos Vinhedos und mildere Temperaturen an der Küste von Santa Catarina." },
        { window: "Dezember bis Februar — für Canyons und Weingüter meiden", text: "Südbrasilianischer Sommer: intensive Hitze in der Serra und im Tal, überfüllte Strände in Florianópolis und keine Glattwale, die bereits in antarktische Gewässer gezogen sind." },
      ],
    },
    experiences: {
      heading: "Was jeder Abschnitt bietet",
      intro: "Jede Etappe hat ihre eigene Geografie und ihren eigenen Rhythmus — von den senkrechten Canyon-Wänden über einen Toast zwischen Rebstöcken bis zum kalten Meer, in dem Wale ihre Jungen zur Welt bringen.",
      items: [
        { title: "Canyon Itaimbezinho und Canyon Fortaleza", text: "In den Nationalparks Aparados da Serra und Serra Geral zeigen Randwanderwege fast 720 Meter hohe Felswände mit jahrhundertealten Araukarien und Nebel, der im Morgengrauen aus dem Tal aufsteigt." },
        { title: "Vale dos Vinhedos und Pinto Bandeira", text: "Jahrhundertealte Weingüter italienischer Einwanderer produzieren Schaumweine nach traditioneller Methode in großer Höhe — eine Verkostungsroute zwischen Steinhäusern und in Höhenlinien angelegten Weinreben." },
        { title: "Gramado und die Serra Gaúcha im europäischen Klima", text: "Deutsch und italienisch inspirierte Architektur, Fondue- und Schokoladenküche sowie Zugfahrten durch Hügel, die an alpine Landschaften außerhalb Brasiliens tropischer Achse erinnern." },
        { title: "Glattwale in Praia do Rosa", text: "Zwischen Juli und November kommen Südkaper-Weibchen an, um wenige Meter vom Sand entfernt Kälber zu gebären und zu säugen — eines der seltenen Wildtierschauspiele, die von der Küste aus ohne Boot sichtbar sind, an der Südküste von Santa Catarina." },
        { title: "Florianópolis und seine Dutzenden Strände", text: "Die Insel Santa Catarina wechselt zwischen Surfstränden, Lagunen und Fischerdörfern azoreischer Prägung, mit Lagoa da Conceição und Barra da Lagoa als charmanten Basen zum Spazieren und guten Essen." },
        { title: "Panoramastraßen zwischen Bergen und Küste", text: "Die Autofahrt zwischen Cambará do Sul, der Serra Gaúcha und der Küste von Santa Catarina durchquert die Serra do Rio do Rastro und Abschnitte der Fernstraße BR-101, mit Aussichtspunkten, die einen Halt wert sind." },
      ],
    },
    stays: {
      heading: "Wo man in jedem Abschnitt übernachtet",
      intro: "Die Hotellerie im Süden verbindet rustikalen Bergcharme, zeitgenössisch gestaltete Weingutsresorts und Strandpensionen mit Blick auf das offene Meer.",
      items: [
        { name: "Charmante Pensionen in Cambará do Sul und São Francisco de Paula", profile: "Basis für die Canyons", text: "Rustikale, gemütliche Adressen mit Kamin, nahe den Eingängen der Nationalparks Aparados da Serra und Serra Geral." },
        { name: "Cabernet Fonte Suíça oder Vinocap (Bento Gonçalves)", profile: "Wein-Eintauchen in der Höhe", text: "Unterkunft inmitten der Weinberge des Vale dos Vinhedos, mit Blick auf die Rebterrassen und in der Nähe der Schaumwein-Weingüter." },
        { name: "Charmante Hotels in Gramado", profile: "Europäischer Komfort in der Serra Gaúcha", text: "Adressen mit alpin inspirierter Architektur, Spas und raffinierter Gastronomie, ideal für zwei Nächte der Erholung zwischen den Canyons und der Küste." },
        { name: "Charmante Pensionen in Praia do Rosa", profile: "Blick auf das Meer der Wale", text: "Pensionen auf Klippen und Dünen mit privilegiertem Blick auf die Glattwalsaison zwischen Juli und November." },
        { name: "Boutique-Hotels in Lagoa da Conceição (Florianópolis)", profile: "Städtische und Strand-Basis", text: "Charmante Adressen an der Lagune, mit einfachem Zugang zu Surfstränden und dem gastronomischen Leben der Insel." },
      ],
    },
    profiles: {
      heading: "Für wen diese Route funktioniert",
      items: [
        { title: "Paare mittleren Alters auf der Suche nach ausgeprägten Jahreszeiten", text: "Perfekt für alle, die Kälte in Brasilien erleben möchten, mit Kaminen, Wein und Herbst-Winter-Landschaften jenseits des tropischen Klischees." },
        { title: "Wein- und Genussliebhaber", text: "Vale dos Vinhedos und Pinto Bandeira bieten eine der reifsten Schaumwein-Szenen Südamerikas, mit Produzenten italienischer Herkunft in dritter und vierter Generation." },
        { title: "Wildtierbeobachter", text: "Die Glattwalsaison in Praia do Rosa ist eine der seltenen Begegnungen mit Meeressäugern, die von der Küste aus ohne Boot sichtbar sind." },
        { title: "Für wen es vielleicht nicht passt", text: "Reisende, die nur Strand und intensive Hitze suchen, sollten den Winterabschnitt in der Serra Gaúcha und den Canyons meiden und nur die Küste von Santa Catarina im Sommer in Betracht ziehen — ohne Wale." },
      ],
    },
    itinerary: {
      heading: "Wie man die Route Abschnitt für Abschnitt verbindet",
      intro: "Die Logik hier ist überland zwischen Bergen und Küste, mit Porto Alegre als Einreise-Flugtor und Florianópolis als Ausreisetor.",
      items: [
        { title: "Tage 1–3 — Cambará do Sul und die Canyons", text: "Ankunft in Porto Alegre und etwa 3,5 Stunden Fahrt nach Cambará do Sul. Drei Nächte für den Canyon Itaimbezinho, den Canyon Fortaleza und Randwanderwege im Nationalpark Aparados da Serra." },
        { title: "Tage 4–7 — Serra Gaúcha: Vale dos Vinhedos und Gramado", text: "Etwa 2,5 Stunden Fahrt nach Bento Gonçalves. Zwei Nächte zwischen Weingütern im Vale dos Vinhedos und Pinto Bandeira, gefolgt von zwei Nächten in Gramado, eine Stunde entfernt, für Gastronomie und Bergausflüge." },
        { title: "Tage 8–11 — Küste von Santa Catarina: Praia do Rosa und Florianópolis", text: "Etwa 4,5 Stunden Fahrt nach Praia do Rosa, mit optionalem Halt an der Serra do Rio do Rastro. Zwei Nächte für Glattwal-Beobachtung (Juli bis November) und zwei Nächte in Florianópolis, 1,5 Stunden entfernt, für Strände und Inselgastronomie." },
        { title: "Rückreise", text: "Flug von Florianópolis nach São Paulo oder Rio de Janeiro mit internationalem Anschluss, wodurch sich die Route über das Flugtor von Santa Catarina schließt." },
      ],
    },
    tips: {
      heading: "Praktische Tipps für diese Route",
      items: [
        "Bringen Sie echte Winterkleidung mit: Die Nächte in Cambará do Sul und der Serra Gaúcha können zwischen Juni und August nahe dem Gefrierpunkt liegen.",
        "Buchen Sie die Randwanderwege der Canyons am Wochenende im Voraus, da die Nachfrage auch außerhalb der Hauptsaison steigt.",
        "Die Glattwal-Beobachtung in Praia do Rosa kann vom Strand oder von Aussichtspunkten aus erfolgen, ohne Boot — respektieren Sie den von örtlichen Führern empfohlenen Abstand.",
        "Die Serra do Rio do Rastro zwischen der Serra Gaúcha und der Küste von Santa Catarina hat enge Kurven und häufigen Nebel; vermeiden Sie es, diesen Abschnitt nachts zu fahren.",
        "Das Vale dos Vinhedos funktioniert am besten mit eigenem Auto oder privatem Fahrer, da die Weingüter über Landstraßen ohne öffentlichen Nahverkehr verstreut liegen.",
        "Erwägen Sie, das Auto in Porto Alegre zu mieten und in Florianópolis zurückzugeben, um die Rückfahrt zu vermeiden.",
      ],
    },
    faq: [
      { q: "Wie viele Nächte sind ideal für die Route Serra, Canyons und Küste von Santa Catarina?", a: "Elf Nächte sind das ideale Gleichgewicht: 3 in den Canyons von Cambará do Sul, 4 zwischen Vale dos Vinhedos und Gramado und 4 in Praia do Rosa und Florianópolis." },
      { q: "Wann ist die beste Zeit, um Glattwale in Praia do Rosa zu sehen?", a: "Von Juli bis November, mit Höhepunkt der Sichtungen zwischen August und Oktober, wenn Weibchen ihre Kälber nahe der Küste säugen." },
      { q: "Muss man für diese Route ein Auto mieten?", a: "Ja. Der Transfer zwischen den Canyons, der Serra Gaúcha und der Küste von Santa Catarina hängt von der Straße ab, und ein Großteil der Weingüter und Aussichtspunkte hat keinen öffentlichen Nahverkehr." },
      { q: "Welche Flugtore dienen als Ein- und Ausreise?", a: "Porto Alegre für die Ankunft mit Straßenzugang zu den Canyons und der Serra Gaúcha, und Florianópolis für die Abreise nach dem Küstenabschnitt." },
      { q: "Kann man diese Route im Sommer machen?", a: "Es ist möglich, aber ohne Glattwale und mit intensiverer Hitze in der Serra Gaúcha; Winter und frühes Frühjahr bieten die besten Bedingungen für die gesamte Route." },
      { q: "Ist diese Route für Reisende über 60 angenehm?", a: "Ja, mit angemessener körperlicher Fitness für leichte bis moderate Wanderungen auf den Randwegen der Canyons; der Rest der Route kombiniert Autofahrten und Ausflüge in ruhigem Tempo." },
    ],
    cta: {
      heading: "Lassen Sie uns Ihre Route durch Südbrasilien gestalten",
      subheading: "Ein menschlicher Berater von Create Travel organisiert Fahrer, Weingut-Reservierungen und charmante Pensionen für eine gut verbundene Reise zwischen Bergen und Küste.",
      button: "Mit einem Travel Designer sprechen",
    },
    readingMinutes: 10,
    publishedAt: "2026-08-11",
  },
};
