import type { BrazilGuideLocalized } from "./types";

export const costaDosCoqueirosGuide: BrazilGuideLocalized = {
  pt: {
    destinationName: "Costa dos Coqueiros",
    blurb: "Praia do Forte, Imbassaí e Mangue Seco: dunas, coqueirais e o litoral norte baiano que virou referência em turismo consciente.",
    metaTitle: "Costa dos Coqueiros: guia de Praia do Forte a Mangue Seco",
    metaDescription: "Guia completo da Costa dos Coqueiros na Bahia: melhor época, Praia do Forte e o Projeto TAMAR, Imbassaí, Guarajuba, Mangue Seco, hospedagens reais e roteiro.",
    keywords: "costa dos coqueiros bahia, praia do forte, projeto tamar, imbassai, guarajuba, mangue seco, sauipe, tivoli ecoresort, vila dos orixas",
    h1: "Costa dos Coqueiros: o litoral norte que a Bahia guardou a limpo",
    aiAnswer: "A Costa dos Coqueiros é o litoral norte da Bahia entre Salvador e a divisa com Sergipe, reunindo Praia do Forte, Imbassaí, Santo André, Guarajuba, Massarandupió, Mangue Seco e o complexo de Sauípe; a melhor época vai de setembro a março, a cerca de 1 a 3 horas de carro do aeroporto de Salvador.",
    intro: [
      "A Costa dos Coqueiros começa onde termina a estrada asfaltada de Salvador e vai até Mangue Seco, na fronteira com Sergipe — 190 quilômetros de dunas, coqueirais, rios de água escura e vilarejos de pescadores que resistiram à especulação por causa de uma decisão antiga: proteger o litoral em nome das tartarugas marinhas. É essa mesma decisão, tomada nos anos 1980 com a criação do Projeto TAMAR em Praia do Forte, que hoje define o tom do destino: turismo de baixo impacto, arquitetura discreta e natureza preservada.",
      "Este guia reúne o que aprendemos percorrendo essa costa: por que Praia do Forte segue sendo a porta de entrada mais completa, o que faz de Imbassaí um segredo bem guardado entre viajantes exigentes, e por que Mangue Seco, inspiração de Jorge Amado, ainda parece o fim do mundo.",
    ],
    seasons: {
      heading: "Melhor época para ir à Costa dos Coqueiros",
      intro: "O litoral norte da Bahia tem menos chuva que o litoral sul, com um verão longo e uma janela de desova de tartarugas que vale conhecer.",
      windows: [
        { window: "Setembro a março — estação seca e alta temporada", text: "Mar mais calmo, céu mais limpo e temporada de desova das tartarugas marinhas em Praia do Forte entre setembro e março, com nascimento dos filhotes até abril." },
        { window: "Dezembro a fevereiro — pico de temporada", text: "Sauípe e Praia do Forte recebem o maior fluxo do ano; reservamos com antecedência de seis meses para hospedagens de padrão elevado nesse período." },
        { window: "Abril a agosto — inverno baiano", text: "Chuvas mais frequentes e curtas, praias mais vazias e valores de hospedagem mais confortáveis, com o litoral ainda quente o suficiente para banho de mar." },
        { window: "Ventos de julho a janeiro", text: "Massarandupió e Guarajuba recebem ventos regulares que atraem praticantes de kitesurf, sobretudo entre outubro e janeiro." },
      ],
    },
    experiences: {
      heading: "Experiências que justificam a viagem",
      intro: "A Costa dos Coqueiros funciona por trechos — cada vilarejo tem uma vocação diferente.",
      items: [
        { title: "Projeto TAMAR em Praia do Forte", text: "Centro de visitantes com tanques de observação de tartarugas marinhas e programa de conservação que nasceu ali nos anos 1980. Parada obrigatória, sobretudo com crianças." },
        { title: "Rio Imbassaí de bote ou caiaque", text: "O rio de água escura corta dunas e mata atlântica antes de desaguar no mar, em um passeio curto e silencioso que contrasta com a badalação de Praia do Forte." },
        { title: "Farol de Praia do Forte e o Castelo Garcia D'Ávila", text: "Ruínas do século XVI, uma das primeiras construções de pedra do Brasil colonial, a poucos minutos do centro do vilarejo." },
        { title: "Dunas de Massarandupió e Praia do Forno", text: "Areia branca e vegetação de restinga preservada, com trechos de naturismo e acesso restrito a veículos — um respiro de isolamento a menos de uma hora de Praia do Forte." },
        { title: "Mangue Seco e as dunas de Jorge Amado", text: "Cenário do livro 'Tieta do Agreste', com dunas que descem direto no mar e travessia de canoa pelo Rio Real, na fronteira com Sergipe." },
        { title: "Guarajuba e as piscinas naturais de recife", text: "Faixa de praia mais urbanizada, com recifes de coral na maré baixa e boa estrutura de restaurantes de praia sem perder o clima de vilarejo." },
      ],
    },
    stays: {
      heading: "Onde ficar na Costa dos Coqueiros — endereços por perfil",
      intro: "Conhecemos pessoalmente cada um destes endereços; a escolha certa depende do ritmo que você busca — resort completo, pousada de charme ou refúgio isolado.",
      items: [
        { name: "Tivoli Ecoresort Praia do Forte", profile: "Famílias e casais que buscam resort completo", text: "Referência de resort de praia na Bahia, com estrutura ampla, spa e proximidade ao vilarejo de Praia do Forte a pé." },
        { name: "Vila dos Orixás (Praia do Forte)", profile: "Casais que buscam intimidade e design", text: "Poucas suítes com piscina privativa, arquitetura discreta em meio à vegetação nativa, a poucos minutos do centro do vilarejo." },
        { name: "Pousada Porto da Lua (Imbassaí)", profile: "Viajantes que buscam sossego autêntico", text: "Endereço pequeno e acolhedor à beira do rio de Imbassaí, com atendimento próximo e acesso fácil às dunas e ao mar." },
      ],
    },
    profiles: {
      heading: "Para quem a Costa dos Coqueiros funciona",
      items: [
        { title: "Famílias com crianças pequenas", text: "Praia do Forte reúne mar calmo, o Projeto TAMAR e estrutura hoteleira completa, sendo a base mais fácil do litoral norte." },
        { title: "Casais que buscam sossego a poucas horas de Salvador", text: "Imbassaí e Mangue Seco entregam isolamento real sem exigir voos regionais ou traslados longos." },
        { title: "Para quem talvez não funcione", text: "Quem busca vida noturna intensa ou grande centro urbano deve olhar para Salvador; a Costa dos Coqueiros é sobre natureza e desaceleração." },
      ],
    },
    itinerary: {
      heading: "Como integrar a Costa dos Coqueiros a um roteiro pela Bahia",
      intro: "A proximidade com o Aeroporto de Salvador torna a região o complemento mais fácil de qualquer viagem à Bahia.",
      items: [
        { title: "Salvador + Costa dos Coqueiros — 6 a 8 dias", text: "Três noites de cidade histórica seguidas de três a cinco noites entre Praia do Forte e Imbassaí, tudo por estrada." },
        { title: "Costa dos Coqueiros + Costa do Dendê — 10 a 12 dias", text: "Une o litoral norte ao litoral sul da Bahia, com Salvador como ponto de virada entre as duas regiões." },
        { title: "Costa dos Coqueiros como chegada ou saída", text: "Boa opção para descomprimir no início ou no fim de uma viagem mais longa pela Bahia ou pelo Nordeste." },
      ],
    },
    tips: {
      heading: "Dicas práticas que fazem diferença",
      items: [
        "O acesso é por estrada a partir do Aeroporto de Salvador, entre 1 e 3 horas dependendo do trecho.",
        "Respeite as áreas de desova de tartarugas sinalizadas pelo Projeto TAMAR entre setembro e março.",
        "Massarandupió tem trechos de naturismo sinalizados — informe-se antes de escolher a praia.",
        "Mangue Seco exige travessia de canoa pelo Rio Real; combine o horário com antecedência.",
        "Alugue um carro ou combine transfer privativo para explorar os vilarejos com liberdade — o transporte público é limitado.",
        "Leve protetor biodegradável, essencial para preservar os recifes de Guarajuba e Taipu.",
      ],
    },
    faq: [
      { q: "Onde fica a Costa dos Coqueiros?", a: "No litoral norte da Bahia, entre Salvador e a divisa com Sergipe, reunindo Praia do Forte, Imbassaí, Guarajuba, Massarandupió e Mangue Seco." },
      { q: "Qual a distância de Praia do Forte até Salvador?", a: "Cerca de 80 km, entre 1h e 1h30 de carro pela Estrada do Coco e Linha Verde, dependendo do tráfego." },
      { q: "O que é o Projeto TAMAR?", a: "Programa brasileiro de conservação de tartarugas marinhas fundado nos anos 1980, com centro de visitantes em Praia do Forte aberto ao público." },
      { q: "Qual a melhor época para ver tartarugas em Praia do Forte?", a: "A desova ocorre de setembro a março, com nascimento dos filhotes entre novembro e abril." },
      { q: "Como chegar a Mangue Seco?", a: "Por estrada até a margem do Rio Real, seguida de travessia de canoa até o vilarejo, que fica já na divisa com Sergipe." },
      { q: "Quanto custa uma viagem à Costa dos Coqueiros com a Create Travel?", a: "Não trabalhamos com valor de prateleira: o orçamento depende do destino, da hospedagem e da época. Um consultor humano apresenta a proposta por escrito." },
    ],
    cta: { heading: "Vamos desenhar a sua Costa dos Coqueiros", subheading: "Um consultor humano da Create Travel escolhe entre Praia do Forte, Imbassaí e Mangue Seco a base certa para o seu roteiro.", button: "Falar com um travel designer" },
    readingMinutes: 9,
    publishedAt: "2026-08-11",
  },
  en: {
    destinationName: "Coconut Coast",
    blurb: "Praia do Forte, Imbassaí and Mangue Seco: dunes, coconut groves and Bahia's northern coast, a benchmark for conscious tourism.",
    metaTitle: "Coconut Coast Guide: Praia do Forte to Mangue Seco",
    metaDescription: "A complete guide to Bahia's Coconut Coast: best time to visit, Praia do Forte and Project TAMAR, Imbassaí, Guarajuba, Mangue Seco, real hotels and itinerary tips.",
    keywords: "costa dos coqueiros bahia, praia do forte, tamar project, imbassai, guarajuba, mangue seco, sauipe, tivoli ecoresort, vila dos orixas",
    h1: "The Coconut Coast: Bahia's northern shoreline kept pristine on purpose",
    aiAnswer: "The Coconut Coast is Bahia's northern shoreline between Salvador and the Sergipe border, covering Praia do Forte, Imbassaí, Santo André, Guarajuba, Massarandupió, Mangue Seco and the Sauípe resort complex; the best season runs September to March, 1 to 3 hours by road from Salvador airport.",
    intro: [
      "The Coconut Coast begins where Salvador's paved road ends and stretches to Mangue Seco, at the border with Sergipe — 190 kilometres of dunes, coconut groves, dark-water rivers and fishing villages that resisted overdevelopment thanks to a decision made decades ago: protect the coastline for sea turtles. That same decision, taken in the 1980s with the founding of Project TAMAR in Praia do Forte, still sets the destination's tone today: low-impact tourism, understated architecture and preserved nature.",
      "This guide gathers what we learned travelling this coast: why Praia do Forte remains the most complete gateway, what makes Imbassaí a well-kept secret among discerning travellers, and why Mangue Seco, the setting of a Jorge Amado novel, still feels like the end of the world.",
    ],
    seasons: {
      heading: "Best time to visit the Coconut Coast",
      intro: "Bahia's northern coast gets less rain than the south, with a long summer and a sea turtle nesting window worth knowing about.",
      windows: [
        { window: "September to March — dry season and peak travel", text: "Calmer sea, clearer skies and sea turtle nesting season at Praia do Forte, with hatchlings emerging until April." },
        { window: "December to February — peak season", text: "Sauípe and Praia do Forte see the year's heaviest traffic; we book six months ahead for high-standard lodging in this window." },
        { window: "April to August — Bahian winter", text: "More frequent but shorter rain, emptier beaches and gentler rates, while the coast stays warm enough for swimming." },
        { window: "Winds from July to January", text: "Massarandupió and Guarajuba get steady winds that draw kitesurfers, especially between October and January." },
      ],
    },
    experiences: {
      heading: "Experiences worth the trip",
      intro: "The Coconut Coast works stretch by stretch — each village has its own character.",
      items: [
        { title: "Project TAMAR at Praia do Forte", text: "A visitor centre with sea turtle observation tanks and the conservation programme born there in the 1980s. A must, especially with children." },
        { title: "Imbassaí River by canoe or kayak", text: "The dark-water river cuts through dunes and Atlantic Forest before meeting the sea, in a short, quiet trip that contrasts with Praia do Forte's buzz." },
        { title: "Praia do Forte lighthouse and Garcia D'Ávila Castle", text: "16th-century ruins, one of colonial Brazil's earliest stone buildings, minutes from the village centre." },
        { title: "Massarandupió dunes and Praia do Forno", text: "White sand and preserved restinga vegetation, with designated naturist stretches and restricted vehicle access — under an hour from Praia do Forte." },
        { title: "Mangue Seco and Jorge Amado's dunes", text: "The setting of the novel 'Tieta do Agreste', with dunes running straight into the sea and a canoe crossing over the Real River at the Sergipe border." },
        { title: "Guarajuba's natural reef pools", text: "A more built-up stretch of beach, with coral reefs at low tide and a good selection of beach restaurants without losing its village feel." },
      ],
    },
    stays: {
      heading: "Where to stay on the Coconut Coast — addresses by profile",
      intro: "We know each of these addresses personally; the right pick depends on the pace you want — full resort, boutique inn or isolated hideaway.",
      items: [
        { name: "Tivoli Ecoresort Praia do Forte", profile: "Families and couples seeking a full resort", text: "A benchmark beach resort in Bahia, with ample facilities, a spa and walking access to Praia do Forte village." },
        { name: "Vila dos Orixás (Praia do Forte)", profile: "Couples seeking intimacy and design", text: "A handful of suites with private pools, understated architecture amid native vegetation, minutes from the village centre." },
        { name: "Pousada Porto da Lua (Imbassaí)", profile: "Travellers seeking authentic quiet", text: "A small, welcoming address on the Imbassaí riverbank, with close attention and easy access to dunes and sea." },
      ],
    },
    profiles: {
      heading: "Who the Coconut Coast is for",
      items: [
        { title: "Families with young children", text: "Praia do Forte combines calm sea, Project TAMAR and full hotel infrastructure, making it the easiest base on the northern coast." },
        { title: "Couples seeking quiet a few hours from Salvador", text: "Imbassaí and Mangue Seco deliver real isolation without requiring regional flights or long transfers." },
        { title: "Who it might not suit", text: "Travellers seeking intense nightlife or a big city should look at Salvador instead; the Coconut Coast is about nature and slowing down." },
      ],
    },
    itinerary: {
      heading: "How to combine the Coconut Coast with a Bahia itinerary",
      intro: "Proximity to Salvador's airport makes this region the easiest add-on to any Bahia trip.",
      items: [
        { title: "Salvador + Coconut Coast — 6 to 8 days", text: "Three nights of historic city followed by three to five nights between Praia do Forte and Imbassaí, all by road." },
        { title: "Coconut Coast + Dendê Coast — 10 to 12 days", text: "Joins the northern and southern coasts of Bahia, with Salvador as the turning point between the two regions." },
        { title: "Coconut Coast as arrival or departure", text: "A good way to decompress at the start or end of a longer trip through Bahia or the Northeast." },
      ],
    },
    tips: {
      heading: "Practical tips that make a difference",
      items: [
        "Access is by road from Salvador's airport, between 1 and 3 hours depending on the stretch.",
        "Respect turtle nesting areas marked by Project TAMAR between September and March.",
        "Massarandupió has designated naturist stretches — check before choosing a beach.",
        "Mangue Seco requires a canoe crossing over the Real River; arrange the timing ahead.",
        "Rent a car or arrange a private transfer to explore the villages freely — public transport is limited.",
        "Bring biodegradable sunscreen, essential to protect the reefs at Guarajuba and Taipu.",
      ],
    },
    faq: [
      { q: "Where is the Coconut Coast?", a: "On Bahia's northern shoreline, between Salvador and the Sergipe border, covering Praia do Forte, Imbassaí, Guarajuba, Massarandupió and Mangue Seco." },
      { q: "How far is Praia do Forte from Salvador?", a: "About 80 km, 1 to 1.5 hours by car via Estrada do Coco and Linha Verde, depending on traffic." },
      { q: "What is Project TAMAR?", a: "A Brazilian sea turtle conservation programme founded in the 1980s, with a visitor centre in Praia do Forte open to the public." },
      { q: "When is the best time to see turtles at Praia do Forte?", a: "Nesting runs September to March, with hatchlings emerging between November and April." },
      { q: "How do you get to Mangue Seco?", a: "By road to the bank of the Real River, followed by a canoe crossing to the village, which sits right at the Sergipe border." },
      { q: "How much does a trip to the Coconut Coast with Create Travel cost?", a: "We do not work with shelf pricing: the budget depends on the destination, accommodation and season. A human consultant presents the proposal in writing." },
    ],
    cta: { heading: "Let's design your Coconut Coast", subheading: "A human consultant at Create Travel chooses between Praia do Forte, Imbassaí and Mangue Seco the right base for your itinerary.", button: "Talk to a travel designer" },
    readingMinutes: 9,
    publishedAt: "2026-08-11",
  },
  es: {
    destinationName: "Costa de los Cocoteros",
    blurb: "Praia do Forte, Imbassaí y Mangue Seco: dunas, cocotales y el litoral norte de Bahía, referencia en turismo consciente.",
    metaTitle: "Costa de los Cocoteros: guía de Praia do Forte a Mangue Seco",
    metaDescription: "Guía completa de la Costa de los Cocoteros en Bahía: mejor época, Praia do Forte y el Proyecto TAMAR, Imbassaí, Guarajuba, Mangue Seco, hospedajes reales y ruta.",
    keywords: "costa dos coqueiros bahia, praia do forte, proyecto tamar, imbassai, guarajuba, mangue seco, sauipe, tivoli ecoresort, vila dos orixas",
    h1: "Costa de los Cocoteros: el litoral norte que Bahía mantuvo intacto",
    aiAnswer: "La Costa de los Cocoteros es el litoral norte de Bahía entre Salvador y el límite con Sergipe, con Praia do Forte, Imbassaí, Santo André, Guarajuba, Massarandupió, Mangue Seco y el complejo de Sauípe; la mejor época va de septiembre a marzo, a 1-3 horas en auto del aeropuerto de Salvador.",
    intro: [
      "La Costa de los Cocoteros comienza donde termina la carretera pavimentada de Salvador y llega hasta Mangue Seco, en el límite con Sergipe — 190 kilómetros de dunas, cocotales, ríos de agua oscura y pueblos de pescadores que resistieron la especulación gracias a una decisión antigua: proteger el litoral en nombre de las tortugas marinas. Esa misma decisión, tomada en los años 80 con la creación del Proyecto TAMAR en Praia do Forte, define hoy el tono del destino: turismo de bajo impacto, arquitectura discreta y naturaleza preservada.",
      "En esta guía reunimos lo que aprendimos recorriendo esta costa: por qué Praia do Forte sigue siendo la puerta de entrada más completa, qué hace de Imbassaí un secreto bien guardado entre viajeros exigentes, y por qué Mangue Seco, inspiración de Jorge Amado, todavía parece el fin del mundo.",
    ],
    seasons: {
      heading: "Mejor época para ir a la Costa de los Cocoteros",
      intro: "El litoral norte de Bahía tiene menos lluvia que el litoral sur, con un verano largo y una temporada de desove de tortugas que vale la pena conocer.",
      windows: [
        { window: "Septiembre a marzo — estación seca y temporada alta", text: "Mar más calmo, cielo más limpio y temporada de desove de tortugas marinas en Praia do Forte, con nacimiento de crías hasta abril." },
        { window: "Diciembre a febrero — pico de temporada", text: "Sauípe y Praia do Forte reciben el mayor flujo del año; reservamos con seis meses de antelación los hospedajes de alto nivel en este período." },
        { window: "Abril a agosto — invierno bahiano", text: "Lluvias más frecuentes y cortas, playas más vacías y tarifas más cómodas, con el litoral aún cálido para bañarse." },
        { window: "Vientos de julio a enero", text: "Massarandupió y Guarajuba reciben vientos regulares que atraen a practicantes de kitesurf, sobre todo entre octubre y enero." },
      ],
    },
    experiences: {
      heading: "Experiencias que justifican el viaje",
      intro: "La Costa de los Cocoteros funciona por tramos — cada pueblo tiene una vocación distinta.",
      items: [
        { title: "Proyecto TAMAR en Praia do Forte", text: "Centro de visitantes con tanques de observación de tortugas marinas y el programa de conservación nacido allí en los años 80. Parada obligatoria, sobre todo con niños." },
        { title: "Río Imbassaí en bote o kayak", text: "El río de agua oscura atraviesa dunas y selva atlántica antes de desembocar en el mar, en un paseo corto y silencioso que contrasta con el bullicio de Praia do Forte." },
        { title: "Faro de Praia do Forte y el Castillo Garcia D'Ávila", text: "Ruinas del siglo XVI, una de las primeras construcciones de piedra del Brasil colonial, a pocos minutos del centro del pueblo." },
        { title: "Dunas de Massarandupió y Praia do Forno", text: "Arena blanca y vegetación de restinga preservada, con tramos naturistas y acceso restringido a vehículos — un respiro de aislamiento a menos de una hora de Praia do Forte." },
        { title: "Mangue Seco y las dunas de Jorge Amado", text: "Escenario de la novela 'Tieta do Agreste', con dunas que bajan directo al mar y travesía en canoa por el Río Real, en el límite con Sergipe." },
        { title: "Guarajuba y las piscinas naturales de arrecife", text: "Franja de playa más urbanizada, con arrecifes de coral en marea baja y buena oferta de restaurantes de playa sin perder el aire de pueblo." },
      ],
    },
    stays: {
      heading: "Dónde alojarse en la Costa de los Cocoteros — direcciones por perfil",
      intro: "Conocemos personalmente cada una de estas direcciones; la elección correcta depende del ritmo que busques — resort completo, posada con encanto o refugio aislado.",
      items: [
        { name: "Tivoli Ecoresort Praia do Forte", profile: "Familias y parejas que buscan resort completo", text: "Referencia de resort de playa en Bahía, con amplia estructura, spa y cercanía al pueblo de Praia do Forte a pie." },
        { name: "Vila dos Orixás (Praia do Forte)", profile: "Parejas que buscan intimidad y diseño", text: "Pocas suites con piscina privada, arquitectura discreta entre vegetación nativa, a pocos minutos del centro del pueblo." },
        { name: "Pousada Porto da Lua (Imbassaí)", profile: "Viajeros que buscan tranquilidad auténtica", text: "Dirección pequeña y acogedora junto al río de Imbassaí, con atención cercana y fácil acceso a dunas y mar." },
      ],
    },
    profiles: {
      heading: "Para quién funciona la Costa de los Cocoteros",
      items: [
        { title: "Familias con niños pequeños", text: "Praia do Forte reúne mar calmo, el Proyecto TAMAR y estructura hotelera completa, siendo la base más fácil del litoral norte." },
        { title: "Parejas que buscan tranquilidad a pocas horas de Salvador", text: "Imbassaí y Mangue Seco ofrecen aislamiento real sin exigir vuelos regionales ni traslados largos." },
        { title: "Para quien tal vez no funcione", text: "Quien busca vida nocturna intensa o un gran centro urbano debe mirar hacia Salvador; la Costa de los Cocoteros es sobre naturaleza y desaceleración." },
      ],
    },
    itinerary: {
      heading: "Cómo integrar la Costa de los Cocoteros a un itinerario por Bahía",
      intro: "La cercanía al aeropuerto de Salvador convierte a la región en el complemento más fácil de cualquier viaje a Bahía.",
      items: [
        { title: "Salvador + Costa de los Cocoteros — 6 a 8 días", text: "Tres noches de ciudad histórica seguidas de tres a cinco noches entre Praia do Forte e Imbassaí, todo por carretera." },
        { title: "Costa de los Cocoteros + Costa del Dendê — 10 a 12 días", text: "Une el litoral norte con el litoral sur de Bahía, con Salvador como punto de transición entre las dos regiones." },
        { title: "Costa de los Cocoteros como llegada o salida", text: "Buena opción para descomprimir al inicio o al final de un viaje más largo por Bahía o el Nordeste." },
      ],
    },
    tips: {
      heading: "Consejos prácticos que marcan la diferencia",
      items: [
        "El acceso es por carretera desde el aeropuerto de Salvador, entre 1 y 3 horas según el tramo.",
        "Respeta las áreas de desove de tortugas señalizadas por el Proyecto TAMAR entre septiembre y marzo.",
        "Massarandupió tiene tramos naturistas señalizados — infórmate antes de elegir la playa.",
        "Mangue Seco requiere travesía en canoa por el Río Real; coordina el horario con antelación.",
        "Alquila un auto o coordina traslado privado para explorar los pueblos con libertad — el transporte público es limitado.",
        "Lleva protector biodegradable, esencial para preservar los arrecifes de Guarajuba y Taipu.",
      ],
    },
    faq: [
      { q: "¿Dónde está la Costa de los Cocoteros?", a: "En el litoral norte de Bahía, entre Salvador y el límite con Sergipe, con Praia do Forte, Imbassaí, Guarajuba, Massarandupió y Mangue Seco." },
      { q: "¿A qué distancia está Praia do Forte de Salvador?", a: "Unos 80 km, entre 1 y 1,5 horas en auto por la Estrada do Coco y Linha Verde, según el tráfico." },
      { q: "¿Qué es el Proyecto TAMAR?", a: "Programa brasileño de conservación de tortugas marinas fundado en los años 80, con centro de visitantes en Praia do Forte abierto al público." },
      { q: "¿Cuál es la mejor época para ver tortugas en Praia do Forte?", a: "El desove ocurre de septiembre a marzo, con nacimiento de crías entre noviembre y abril." },
      { q: "¿Cómo llegar a Mangue Seco?", a: "Por carretera hasta la orilla del Río Real, seguida de travesía en canoa hasta el pueblo, ya en el límite con Sergipe." },
      { q: "¿Cuánto cuesta un viaje a la Costa de los Cocoteros con Create Travel?", a: "No trabajamos con valores de estante: el presupuesto depende del destino, del hospedaje y de la época. Un consultor humano presenta la propuesta por escrito." },
    ],
    cta: { heading: "Diseñemos tu Costa de los Cocoteros", subheading: "Un consultor humano de Create Travel elige entre Praia do Forte, Imbassaí y Mangue Seco la base correcta para tu itinerario.", button: "Hablar con un travel designer" },
    readingMinutes: 9,
    publishedAt: "2026-08-11",
  },
  it: {
    destinationName: "Costa dos Coqueiros",
    blurb: "Praia do Forte, Imbassaí e Mangue Seco: dune, palmeti di cocco e il litorale settentrionale bahiano, riferimento del turismo consapevole.",
    metaTitle: "Costa dos Coqueiros: guida da Praia do Forte a Mangue Seco",
    metaDescription: "Guida completa alla Costa dos Coqueiros in Bahia: periodo migliore, Praia do Forte e il Progetto TAMAR, Imbassaí, Guarajuba, Mangue Seco, alloggi reali e itinerario.",
    keywords: "costa dos coqueiros bahia, praia do forte, progetto tamar, imbassai, guarajuba, mangue seco, sauipe, tivoli ecoresort, vila dos orixas",
    h1: "Costa dos Coqueiros: il litorale settentrionale che la Bahia ha protetto",
    aiAnswer: "La Costa dos Coqueiros è il litorale settentrionale della Bahia tra Salvador e il confine con Sergipe, comprendente Praia do Forte, Imbassaí, Santo André, Guarajuba, Massarandupió, Mangue Seco e il complesso di Sauípe; il periodo migliore va da settembre a marzo, a 1-3 ore d'auto dall'aeroporto di Salvador.",
    intro: [
      "La Costa dos Coqueiros inizia dove finisce la strada asfaltata di Salvador e arriva fino a Mangue Seco, al confine con Sergipe — 190 chilometri di dune, palmeti di cocco, fiumi dalle acque scure e villaggi di pescatori che hanno resistito alla speculazione grazie a una decisione presa decenni fa: proteggere il litorale in nome delle tartarughe marine. Quella stessa decisione, presa negli anni '80 con la fondazione del Progetto TAMAR a Praia do Forte, definisce ancora oggi il tono della destinazione: turismo a basso impatto, architettura discreta e natura preservata.",
      "In questa guida raccogliamo ciò che abbiamo imparato percorrendo questa costa: perché Praia do Forte resta la porta d'accesso più completa, cosa rende Imbassaí un segreto ben custodito tra i viaggiatori esigenti, e perché Mangue Seco, ispirazione di Jorge Amado, sembra ancora la fine del mondo.",
    ],
    seasons: {
      heading: "Periodo migliore per visitare la Costa dos Coqueiros",
      intro: "Il litorale settentrionale della Bahia ha meno pioggia di quello meridionale, con un'estate lunga e una finestra di deposizione delle tartarughe da conoscere.",
      windows: [
        { window: "Da settembre a marzo — stagione secca e alta stagione", text: "Mare più calmo, cielo più limpido e stagione di deposizione delle uova delle tartarughe marine a Praia do Forte, con nascita dei cuccioli fino ad aprile." },
        { window: "Da dicembre a febbraio — picco di stagione", text: "Sauípe e Praia do Forte registrano il maggior afflusso dell'anno; prenotiamo con sei mesi di anticipo gli alloggi di alto livello in questo periodo." },
        { window: "Da aprile ad agosto — inverno bahiano", text: "Piogge più frequenti ma brevi, spiagge più vuote e tariffe più accessibili, con il litorale ancora caldo abbastanza per il bagno." },
        { window: "Venti da luglio a gennaio", text: "Massarandupió e Guarajuba ricevono venti costanti che attraggono i kitesurfisti, soprattutto tra ottobre e gennaio." },
      ],
    },
    experiences: {
      heading: "Esperienze che giustificano il viaggio",
      intro: "La Costa dos Coqueiros funziona per tratti — ogni villaggio ha una propria vocazione.",
      items: [
        { title: "Progetto TAMAR a Praia do Forte", text: "Centro visitatori con vasche di osservazione delle tartarughe marine e il programma di conservazione nato lì negli anni '80. Tappa obbligata, soprattutto con i bambini." },
        { title: "Fiume Imbassaí in barca o kayak", text: "Il fiume dalle acque scure attraversa dune e foresta atlantica prima di sfociare in mare, in un'escursione breve e silenziosa che contrasta con l'animazione di Praia do Forte." },
        { title: "Faro di Praia do Forte e il Castello Garcia D'Ávila", text: "Rovine del XVI secolo, una delle prime costruzioni in pietra del Brasile coloniale, a pochi minuti dal centro del villaggio." },
        { title: "Dune di Massarandupió e Praia do Forno", text: "Sabbia bianca e vegetazione di restinga preservata, con tratti naturisti segnalati e accesso limitato ai veicoli — un respiro di isolamento a meno di un'ora da Praia do Forte." },
        { title: "Mangue Seco e le dune di Jorge Amado", text: "Ambientazione del romanzo 'Tieta do Agreste', con dune che scendono direttamente nel mare e traversata in canoa sul Rio Real, al confine con Sergipe." },
        { title: "Guarajuba e le piscine naturali di scogliera", text: "Tratto di spiaggia più urbanizzato, con scogliere coralline a marea bassa e una buona offerta di ristoranti sulla spiaggia senza perdere l'atmosfera di villaggio." },
      ],
    },
    stays: {
      heading: "Dove alloggiare sulla Costa dos Coqueiros — indirizzi per profilo",
      intro: "Conosciamo personalmente ognuno di questi indirizzi; la scelta giusta dipende dal ritmo desiderato — resort completo, pousada di charme o rifugio isolato.",
      items: [
        { name: "Tivoli Ecoresort Praia do Forte", profile: "Famiglie e coppie che cercano un resort completo", text: "Riferimento tra i resort balneari della Bahia, con struttura ampia, spa e vicinanza al villaggio di Praia do Forte raggiungibile a piedi." },
        { name: "Vila dos Orixás (Praia do Forte)", profile: "Coppie che cercano intimità e design", text: "Poche suite con piscina privata, architettura discreta immersa nella vegetazione nativa, a pochi minuti dal centro del villaggio." },
        { name: "Pousada Porto da Lua (Imbassaí)", profile: "Viaggiatori che cercano tranquillità autentica", text: "Un indirizzo piccolo e accogliente sulle rive del fiume Imbassaí, con attenzione personalizzata e facile accesso a dune e mare." },
      ],
    },
    profiles: {
      heading: "Per chi funziona la Costa dos Coqueiros",
      items: [
        { title: "Famiglie con bambini piccoli", text: "Praia do Forte unisce mare calmo, il Progetto TAMAR e una struttura alberghiera completa, essendo la base più semplice del litorale settentrionale." },
        { title: "Coppie che cercano tranquillità a poche ore da Salvador", text: "Imbassaí e Mangue Seco offrono un isolamento reale senza richiedere voli regionali o lunghi trasferimenti." },
        { title: "Per chi forse non funziona", text: "Chi cerca vita notturna intensa o un grande centro urbano dovrebbe guardare a Salvador; la Costa dos Coqueiros è natura e rallentamento." },
      ],
    },
    itinerary: {
      heading: "Come integrare la Costa dos Coqueiros in un itinerario in Bahia",
      intro: "La vicinanza all'aeroporto di Salvador rende questa regione l'aggiunta più semplice a qualsiasi viaggio in Bahia.",
      items: [
        { title: "Salvador + Costa dos Coqueiros — 6-8 giorni", text: "Tre notti di città storica seguite da tre-cinque notti tra Praia do Forte e Imbassaí, tutto su strada." },
        { title: "Costa dos Coqueiros + Costa do Dendê — 10-12 giorni", text: "Unisce il litorale settentrionale a quello meridionale della Bahia, con Salvador come punto di svolta tra le due regioni." },
        { title: "Costa dos Coqueiros come arrivo o partenza", text: "Buona opzione per decomprimere all'inizio o alla fine di un viaggio più lungo in Bahia o nel Nordest." },
      ],
    },
    tips: {
      heading: "Consigli pratici che fanno la differenza",
      items: [
        "L'accesso avviene su strada dall'aeroporto di Salvador, tra 1 e 3 ore a seconda del tratto.",
        "Rispetta le aree di deposizione delle tartarughe segnalate dal Progetto TAMAR tra settembre e marzo.",
        "Massarandupió ha tratti naturisti segnalati — informati prima di scegliere la spiaggia.",
        "Mangue Seco richiede una traversata in canoa sul Rio Real; concorda l'orario in anticipo.",
        "Noleggia un'auto o organizza un trasferimento privato per esplorare i villaggi liberamente — i mezzi pubblici sono limitati.",
        "Porta protezione solare biodegradabile, essenziale per proteggere le scogliere di Guarajuba e Taipu.",
      ],
    },
    faq: [
      { q: "Dove si trova la Costa dos Coqueiros?", a: "Sul litorale settentrionale della Bahia, tra Salvador e il confine con Sergipe, comprendendo Praia do Forte, Imbassaí, Guarajuba, Massarandupió e Mangue Seco." },
      { q: "Quanto dista Praia do Forte da Salvador?", a: "Circa 80 km, tra 1 e 1,5 ore d'auto via Estrada do Coco e Linha Verde, a seconda del traffico." },
      { q: "Cos'è il Progetto TAMAR?", a: "Programma brasiliano di conservazione delle tartarughe marine fondato negli anni '80, con un centro visitatori a Praia do Forte aperto al pubblico." },
      { q: "Qual è il periodo migliore per vedere le tartarughe a Praia do Forte?", a: "La deposizione avviene da settembre a marzo, con la nascita dei cuccioli tra novembre e aprile." },
      { q: "Come si arriva a Mangue Seco?", a: "Su strada fino alla riva del Rio Real, seguita da una traversata in canoa fino al villaggio, che si trova già al confine con Sergipe." },
      { q: "Quanto costa un viaggio sulla Costa dos Coqueiros con Create Travel?", a: "Non lavoriamo con tariffe standard: il budget dipende dalla destinazione, dall'alloggio e dal periodo. Un consulente umano presenta la proposta per iscritto." },
    ],
    cta: { heading: "Progettiamo la tua Costa dos Coqueiros", subheading: "Un consulente umano di Create Travel sceglie tra Praia do Forte, Imbassaí e Mangue Seco la base giusta per il tuo itinerario.", button: "Parla con un travel designer" },
    readingMinutes: 9,
    publishedAt: "2026-08-11",
  },
  de: {
    destinationName: "Kokosnuss-Küste",
    blurb: "Praia do Forte, Imbassaí und Mangue Seco: Dünen, Kokospalmenhaine und Bahias Nordküste, Referenz für bewussten Tourismus.",
    metaTitle: "Kokosnuss-Küste: Guide von Praia do Forte bis Mangue Seco",
    metaDescription: "Kompletter Guide zur Kokosnuss-Küste in Bahia: beste Reisezeit, Praia do Forte und Projekt TAMAR, Imbassaí, Guarajuba, Mangue Seco, echte Unterkünfte und Route.",
    keywords: "costa dos coqueiros bahia, praia do forte, tamar projekt, imbassai, guarajuba, mangue seco, sauipe, tivoli ecoresort, vila dos orixas",
    h1: "Kokosnuss-Küste: Bahias Nordküste, bewusst unberührt gehalten",
    aiAnswer: "Die Kokosnuss-Küste ist Bahias Nordküste zwischen Salvador und der Grenze zu Sergipe, mit Praia do Forte, Imbassaí, Santo André, Guarajuba, Massarandupió, Mangue Seco und dem Sauípe-Resortkomplex; die beste Reisezeit ist September bis März, 1 bis 3 Autostunden vom Flughafen Salvador entfernt.",
    intro: [
      "Die Kokosnuss-Küste beginnt dort, wo die asphaltierte Straße von Salvador endet, und reicht bis Mangue Seco an der Grenze zu Sergipe — 190 Kilometer Dünen, Kokospalmenhaine, dunkle Flüsse und Fischerdörfer, die der Bauspekulation dank einer alten Entscheidung widerstanden: die Küste im Namen der Meeresschildkröten zu schützen. Genau diese Entscheidung, in den 1980er-Jahren mit der Gründung des Projekts TAMAR in Praia do Forte getroffen, prägt bis heute den Ton des Ziels: Tourismus mit geringem Einfluss, dezente Architektur und erhaltene Natur.",
      "Dieser Guide fasst zusammen, was wir beim Bereisen dieser Küste gelernt haben: warum Praia do Forte weiterhin das vollständigste Tor ist, was Imbassaí zu einem gut gehüteten Geheimnis unter anspruchsvollen Reisenden macht, und warum Mangue Seco, Schauplatz eines Romans von Jorge Amado, noch immer wie das Ende der Welt wirkt.",
    ],
    seasons: {
      heading: "Beste Reisezeit für die Kokosnuss-Küste",
      intro: "Bahias Nordküste hat weniger Regen als der Süden, mit einem langen Sommer und einer Schildkröten-Nistzeit, die man kennen sollte.",
      windows: [
        { window: "September bis März — Trockenzeit und Hauptsaison", text: "Ruhigeres Meer, klarerer Himmel und Nistzeit der Meeresschildkröten in Praia do Forte, mit schlüpfenden Jungtieren bis April." },
        { window: "Dezember bis Februar — Hochsaison", text: "Sauípe und Praia do Forte verzeichnen den stärksten Andrang des Jahres; wir buchen für hochwertige Unterkünfte in dieser Zeit sechs Monate im Voraus." },
        { window: "April bis August — bahianischer Winter", text: "Häufigerer, aber kürzerer Regen, leerere Strände und günstigere Konditionen, während die Küste noch warm genug zum Baden bleibt." },
        { window: "Winde von Juli bis Januar", text: "Massarandupió und Guarajuba erhalten beständige Winde, die Kitesurfer anziehen, besonders zwischen Oktober und Januar." },
      ],
    },
    experiences: {
      heading: "Erlebnisse, die die Reise rechtfertigen",
      intro: "Die Kokosnuss-Küste funktioniert abschnittsweise — jedes Dorf hat seinen eigenen Charakter.",
      items: [
        { title: "Projekt TAMAR in Praia do Forte", text: "Besucherzentrum mit Beobachtungsbecken für Meeresschildkröten und dem dort in den 1980ern entstandenen Schutzprogramm. Pflichthalt, besonders mit Kindern." },
        { title: "Fluss Imbassaí per Boot oder Kajak", text: "Der dunkle Fluss durchquert Dünen und Atlantikwald, bevor er ins Meer mündet — ein kurzer, stiller Ausflug im Gegensatz zum Trubel von Praia do Forte." },
        { title: "Leuchtturm von Praia do Forte und Schloss Garcia D'Ávila", text: "Ruinen aus dem 16. Jahrhundert, eines der ersten Steingebäude im kolonialen Brasilien, wenige Minuten vom Dorfzentrum entfernt." },
        { title: "Dünen von Massarandupió und Praia do Forno", text: "Weißer Sand und erhaltene Restinga-Vegetation, mit ausgewiesenen Naturisten-Abschnitten und beschränktem Fahrzeugzugang — eine Atempause der Isolation weniger als eine Stunde von Praia do Forte entfernt." },
        { title: "Mangue Seco und die Dünen von Jorge Amado", text: "Schauplatz des Romans 'Tieta do Agreste', mit Dünen, die direkt ins Meer abfallen, und einer Kanuüberfahrt über den Rio Real an der Grenze zu Sergipe." },
        { title: "Guarajuba und die natürlichen Riffpools", text: "Ein städtischerer Strandabschnitt mit Korallenriffen bei Ebbe und guten Strandrestaurants, ohne den Dorfcharakter zu verlieren." },
      ],
    },
    stays: {
      heading: "Wo übernachten an der Kokosnuss-Küste — Adressen nach Profil",
      intro: "Wir kennen jede dieser Adressen persönlich; die richtige Wahl hängt vom gewünschten Tempo ab — Vollresort, charmante Pousada oder abgelegener Rückzugsort.",
      items: [
        { name: "Tivoli Ecoresort Praia do Forte", profile: "Familien und Paare mit Anspruch auf ein Vollresort", text: "Referenzstrandresort in Bahia, mit umfangreicher Infrastruktur, Spa und Fußweg-Nähe zum Dorf Praia do Forte." },
        { name: "Vila dos Orixás (Praia do Forte)", profile: "Paare, die Intimität und Design suchen", text: "Wenige Suiten mit privatem Pool, dezente Architektur inmitten einheimischer Vegetation, wenige Minuten vom Dorfzentrum entfernt." },
        { name: "Pousada Porto da Lua (Imbassaí)", profile: "Reisende, die authentische Ruhe suchen", text: "Eine kleine, einladende Adresse am Ufer des Imbassaí-Flusses, mit persönlicher Betreuung und einfachem Zugang zu Dünen und Meer." },
      ],
    },
    profiles: {
      heading: "Für wen die Kokosnuss-Küste funktioniert",
      items: [
        { title: "Familien mit kleinen Kindern", text: "Praia do Forte vereint ruhiges Meer, das Projekt TAMAR und vollständige Hotelinfrastruktur und ist damit die einfachste Basis an der Nordküste." },
        { title: "Paare, die Ruhe wenige Stunden von Salvador suchen", text: "Imbassaí und Mangue Seco bieten echte Abgeschiedenheit, ohne Regionalflüge oder lange Transfers zu erfordern." },
        { title: "Für wen es vielleicht nicht passt", text: "Wer intensives Nachtleben oder ein großes Stadtzentrum sucht, sollte Salvador wählen; die Kokosnuss-Küste steht für Natur und Entschleunigung." },
      ],
    },
    itinerary: {
      heading: "Wie man die Kokosnuss-Küste in eine Bahia-Reise einbindet",
      intro: "Die Nähe zum Flughafen Salvador macht diese Region zur einfachsten Ergänzung jeder Bahia-Reise.",
      items: [
        { title: "Salvador + Kokosnuss-Küste — 6 bis 8 Tage", text: "Drei Nächte historische Stadt, gefolgt von drei bis fünf Nächten zwischen Praia do Forte und Imbassaí, alles auf dem Landweg." },
        { title: "Kokosnuss-Küste + Dendê-Küste — 10 bis 12 Tage", text: "Verbindet Bahias Nord- und Südküste, mit Salvador als Wendepunkt zwischen den beiden Regionen." },
        { title: "Kokosnuss-Küste als An- oder Abreisepunkt", text: "Gute Option, um zu Beginn oder Ende einer längeren Reise durch Bahia oder den Nordosten zu entspannen." },
      ],
    },
    tips: {
      heading: "Praktische Tipps, die den Unterschied machen",
      items: [
        "Die Anreise erfolgt auf dem Landweg vom Flughafen Salvador, je nach Abschnitt zwischen 1 und 3 Stunden.",
        "Respektieren Sie die von Projekt TAMAR markierten Schildkröten-Nistgebiete zwischen September und März.",
        "Massarandupió hat ausgewiesene Naturisten-Abschnitte — vor der Strandwahl informieren.",
        "Mangue Seco erfordert eine Kanuüberfahrt über den Rio Real; die Zeit im Voraus abstimmen.",
        "Mieten Sie ein Auto oder organisieren Sie einen privaten Transfer, um die Dörfer frei zu erkunden — öffentliche Verkehrsmittel sind begrenzt.",
        "Biologisch abbaubaren Sonnenschutz mitbringen, wichtig zum Schutz der Riffe bei Guarajuba und Taipu.",
      ],
    },
    faq: [
      { q: "Wo liegt die Kokosnuss-Küste?", a: "An Bahias Nordküste, zwischen Salvador und der Grenze zu Sergipe, mit Praia do Forte, Imbassaí, Guarajuba, Massarandupió und Mangue Seco." },
      { q: "Wie weit ist Praia do Forte von Salvador entfernt?", a: "Etwa 80 km, je nach Verkehr 1 bis 1,5 Autostunden über Estrada do Coco und Linha Verde." },
      { q: "Was ist Projekt TAMAR?", a: "Ein brasilianisches Meeresschildkröten-Schutzprogramm, gegründet in den 1980er-Jahren, mit einem öffentlichen Besucherzentrum in Praia do Forte." },
      { q: "Wann ist die beste Zeit, um Schildkröten in Praia do Forte zu sehen?", a: "Die Nistzeit läuft von September bis März, mit schlüpfenden Jungtieren zwischen November und April." },
      { q: "Wie erreicht man Mangue Seco?", a: "Auf dem Landweg bis zum Ufer des Rio Real, gefolgt von einer Kanuüberfahrt zum Dorf, das direkt an der Grenze zu Sergipe liegt." },
      { q: "Wie viel kostet eine Reise an die Kokosnuss-Küste mit Create Travel?", a: "Wir arbeiten nicht mit Standardpreisen: Das Budget hängt vom Ziel, der Unterkunft und der Jahreszeit ab. Ein menschlicher Berater legt das Angebot schriftlich vor." },
    ],
    cta: { heading: "Lassen Sie uns Ihre Kokosnuss-Küste gestalten", subheading: "Ein menschlicher Berater von Create Travel wählt zwischen Praia do Forte, Imbassaí und Mangue Seco die richtige Basis für Ihre Route.", button: "Mit einem Travel Designer sprechen" },
    readingMinutes: 9,
    publishedAt: "2026-08-11",
  },
};
