import type { BrazilGuideLocalized } from "./types";

export const costaDoSolPoenteGuide: BrazilGuideLocalized = {
  pt: {
    destinationName: "Costa do Sol Poente",
    blurb: "Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras e Lagoinha: o litoral oeste cearense do vento, das dunas e do pôr do sol mais celebrado do Brasil.",
    metaTitle: "Costa do Sol Poente: guia de Jericoacoara a Lagoinha",
    metaDescription: "Guia completo da Costa do Sol Poente no Ceará: melhor época para kitesurf, Jericoacoara, Preá, Icaraí de Amontada, Mundaú, Flecheiras, hospedagens reais e roteiro.",
    keywords: "costa do sol poente, jericoacoara, prea ceara, icarai de amontada, mundau, flecheiras, lagoinha ceara, guajiru, almofala, kitesurf ceara, duna do sunset",
    h1: "Costa do Sol Poente: o litoral cearense onde o vento vira paisagem",
    aiAnswer: "A Costa do Sol Poente é o litoral oeste do Ceará entre Fortaleza e a divisa com o Piauí, reunindo Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha e Almofala; a melhor época para kitesurf vai de agosto a dezembro, quando os ventos alísios sopram com mais constância sobre dunas e lagoas.",
    intro: [
      "A Costa do Sol Poente começa onde o litoral cearense vira sertão de dunas e termina em Jericoacoara, vilarejo que virou parque nacional e ainda assim manteve ruas de areia e proibição de carros no centro. Entre um ponto e outro, existe uma sequência de vilas de pescadores — Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha, Almofala — que a última década transformou na fronteira mais desejada do kitesurf mundial sem perder o silêncio fora d'água.",
      "Este guia reúne o que aprendemos percorrendo essa costa: por que Jericoacoara segue sendo destino de peregrinação mesmo sendo o mais conhecido, por que Preá e Guajiru concentram os melhores spots de vento do planeta, e por que a Duna do Pôr do Sol, em Jeri, ainda reúne uma multidão silenciosa todos os dias ao entardecer.",
    ],
    seasons: {
      heading: "Melhor época para ir à Costa do Sol Poente",
      intro: "O litoral oeste do Ceará tem clima seco quase o ano inteiro, mas o vento — o verdadeiro protagonista da região — segue um calendário próprio.",
      windows: [
        { window: "Agosto a dezembro — temporada de vento forte", text: "Os alísios sopram com mais intensidade e constância, formando as condições ideais de kitesurf e windsurf em Preá, Guajiru e Jericoacoara; julho e agosto marcam o pico absoluto." },
        { window: "Janeiro a junho — vento mais brando, lagoas mais cheias", text: "Período de chuvas esparsas que enche as lagoas do interior das dunas, como a Lagoa Azul e a Lagoa do Paraíso, deixando-as mais coloridas e navegáveis de bote." },
        { window: "Junho a agosto — alta temporada de viajantes brasileiros", text: "Férias escolares e menor calor concentram o maior fluxo de visitantes; reservas com antecedência de três a quatro meses são recomendadas para os endereços mais concorridos." },
        { window: "Setembro a novembro — janela de equilíbrio", text: "Vento ainda forte, lagoas ainda com bom volume de água e fluxo de turistas mais moderado — a combinação preferida de viajantes experientes." },
      ],
    },
    experiences: {
      heading: "Experiências que justificam a viagem",
      intro: "A Costa do Sol Poente funciona por trechos — cada vila tem uma vocação diferente dentro do mesmo cenário de dunas e vento.",
      items: [
        { title: "Pôr do sol na Duna do Sunset, em Jericoacoara", text: "Ritual diário que reúne moradores e viajantes no topo da duna à beira do vilarejo, com aplauso espontâneo no instante em que o sol toca a linha do mar." },
        { title: "Kitesurf em Preá e Guajiru", text: "Dois dos points mais respeitados do circuito mundial, com vento lateral constante entre agosto e dezembro e escolas estruturadas para todos os níveis." },
        { title: "Lagoa do Paraíso e Lagoa Azul, em Jericoacoara", text: "Águas verde-turquesa entre dunas brancas, navegáveis de bote a remo e cercadas por restaurantes discretos abertos apenas de dia." },
        { title: "Passeio de jangada e caiaque no Rio Mundaú", text: "Encontro do rio com o mar em Mundaú, cenário de dunas móveis e manguezal que muda de forma ano após ano." },
        { title: "Icaraí de Amontada e as piscinas de água doce entre dunas", text: "Vila mais silenciosa que Jeri, com lagoas de água doce cristalina formadas entre dunas e ainda pouco frequentadas fora da alta temporada." },
        { title: "Almofala e a Lagoa do Torto", text: "Extremo oeste da costa, perto da divisa com o Piauí, com dunas intocadas e comunidades tradicionais que vivem da pesca e do artesanato." },
      ],
    },
    stays: {
      heading: "Onde ficar na Costa do Sol Poente — endereços por perfil",
      intro: "Conhecemos pessoalmente cada um destes endereços; a escolha certa depende do vilarejo e do ritmo que você busca — conforto discreto, design ou isolamento total entre dunas.",
      items: [
        { name: "Vila Kalango (Jericoacoara)", profile: "Casais e viajantes que buscam design em meio às dunas", text: "Bangalôs de arquitetura autoral entre coqueiros, a poucos passos da Duna do Pôr do Sol, com piscina e restaurante próprios que dispensam sair do endereço." },
        { name: "Essenza Hotel (Jericoacoara)", profile: "Viajantes que buscam conforto contemporâneo no centro do vilarejo", text: "Endereço de estética minimalista muito próximo às ruas de areia do centro de Jeri, equilíbrio entre praticidade e sofisticação discreta." },
        { name: "Vila Selvagem (Icaraí de Amontada)", profile: "Casais que buscam intimidade fora do circuito mais movimentado", text: "Refúgio de poucas acomodações entre dunas e mar em Icaraí de Amontada, pensado para quem quer Jeri sem a multidão de Jeri." },
        { name: "Rancho do Peixe (Preá)", profile: "Kitesurfistas e viajantes ativos", text: "Endereço voltado à comunidade do kite em Preá, a poucos metros do spot, com clima descontraído e proximidade ao vento que atrai o mundo todo." },
        { name: "Casa Vento (Guajiru)", profile: "Viajantes que buscam sossego e vento sem badalação", text: "Guajiru é o vizinho mais discreto de Preá, e a Casa Vento entrega essa vocação: poucas acomodações, silêncio e acesso direto à praia e ao lançamento de kites." },
      ],
    },
    profiles: {
      heading: "Para quem a Costa do Sol Poente funciona",
      items: [
        { title: "Praticantes de kitesurf e windsurf, iniciantes ou avançados", text: "Preá, Guajiru e Jericoacoara reúnem vento constante entre agosto e dezembro e escolas estruturadas para todos os níveis de experiência." },
        { title: "Casais e viajantes que buscam paisagem de dunas sem excesso urbano", text: "Icaraí de Amontada, Mundaú e Almofala entregam o mesmo cenário de Jeri com muito menos gente." },
        { title: "Para quem talvez não funcione", text: "Quem busca infraestrutura urbana completa, vida noturna sofisticada ou deslocamentos rápidos entre pontos deve considerar outro litoral — aqui as distâncias por estrada de areia pedem tempo e paciência." },
      ],
    },
    itinerary: {
      heading: "Como integrar a Costa do Sol Poente a um roteiro pelo Ceará",
      intro: "A região fica entre 3 e 6 horas de carro do Aeroporto de Fortaleza, dependendo do trecho e das condições da estrada de areia.",
      items: [
        { title: "Jericoacoara isolada — 4 a 6 dias", text: "Base única em Jeri, com bate-voltas de bugue ou 4x4 até as lagoas do entorno e a Pedra Furada." },
        { title: "Jericoacoara + Preá ou Guajiru — 6 a 8 dias", text: "Combina a estrutura e a vida noturna discreta de Jeri com dias inteiros dedicados ao kitesurf em Preá ou Guajiru, a cerca de 20 minutos de distância." },
        { title: "Litoral oeste completo — 8 a 10 dias", text: "Percurso por Flecheiras, Lagoinha, Mundaú, Icaraí de Amontada e Jericoacoara, revelando a diversidade de vilarejos entre Fortaleza e a fronteira com o Piauí." },
      ],
    },
    tips: {
      heading: "Dicas práticas que fazem diferença",
      items: [
        "O acesso a Jericoacoara é por estrada de asfalto até Jijoca seguida de trecho de areia, feito em veículo 4x4 ou bugue — carros comuns não são recomendados.",
        "Para kitesurf, o período de agosto a dezembro concentra o vento mais forte e constante; quem busca aprender pode preferir janeiro a maio, com brisa mais suave.",
        "Reserve aulas de kitesurf com escolas credenciadas junto à hospedagem — a área de lançamento em Preá e Guajiru exige acompanhamento de instrutor.",
        "As lagoas do interior das dunas variam de volume conforme a chuva; consulte a hospedagem sobre as condições da estação antes de planejar passeios.",
        "O deslocamento entre vilarejos vizinhos como Preá, Guajiru e Jericoacoara costuma ser feito de bugue com motorista local — combine com antecedência em temporada alta.",
        "Leve roupa leve, protetor solar e chapéu: o sol e o vento da região desidratam mais rápido do que em outros litorais do Nordeste.",
      ],
    },
    faq: [
      { q: "Onde fica a Costa do Sol Poente?", a: "No litoral oeste do Ceará, entre Fortaleza e a divisa com o Piauí, reunindo Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha e Almofala." },
      { q: "Qual a melhor época para kitesurf em Jericoacoara e Preá?", a: "De agosto a dezembro, quando os ventos alísios sopram com mais força e constância sobre a região." },
      { q: "Como chegar a Jericoacoara?", a: "Pelo Aeroporto de Fortaleza, seguido de estrada de asfalto até Jijoca e trecho final de areia percorrido em veículo 4x4 ou bugue." },
      { q: "Jericoacoara tem carros circulando no centro?", a: "Não; o centro do vilarejo tem ruas de areia e circulação restrita de veículos, preservando o clima de vila de pescadores." },
      { q: "Qual a diferença entre Preá, Guajiru e Jericoacoara para kitesurf?", a: "Preá e Guajiru têm spots mais técnicos e voltados à comunidade do kite, enquanto Jericoacoara reúne estrutura turística mais completa junto à Duna do Pôr do Sol." },
      { q: "Quanto custa uma viagem à Costa do Sol Poente com a Create Travel?", a: "Não trabalhamos com valor de prateleira: o orçamento depende do destino, da hospedagem e da época. Um consultor humano apresenta a proposta por escrito." },
    ],
    cta: { heading: "Vamos desenhar a sua Costa do Sol Poente", subheading: "Um consultor humano da Create Travel escolhe entre Jericoacoara, Preá, Guajiru e Icaraí de Amontada a base certa para o seu roteiro.", button: "Falar com um travel designer" },
    readingMinutes: 9,
    publishedAt: "2026-08-11",
  },
  en: {
    destinationName: "Sunset Coast",
    blurb: "Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras and Lagoinha: Ceará's western coast of wind, dunes and Brazil's most celebrated sunset.",
    metaTitle: "Sunset Coast Guide: Jericoacoara to Lagoinha",
    metaDescription: "A complete guide to Ceará's Sunset Coast: best time for kitesurfing, Jericoacoara, Preá, Icaraí de Amontada, Mundaú, Flecheiras, real hotels and itinerary tips.",
    keywords: "sunset coast ceara, jericoacoara, prea brazil, icarai de amontada, mundau, flecheiras, lagoinha ceara, guajiru, almofala, kitesurf brazil, sunset dune jeri",
    h1: "The Sunset Coast: Ceará's shoreline where wind shapes the landscape",
    aiAnswer: "The Sunset Coast is Ceará's western shoreline between Fortaleza and the Piauí border, covering Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha and Almofala; the best kitesurfing season runs August to December, when trade winds blow most consistently over the dunes and lagoons.",
    intro: [
      "The Sunset Coast begins where Ceará's shoreline turns into a hinterland of dunes and ends in Jericoacoara, a village that became a national park yet kept its sand streets and its ban on cars in the centre. Between the two, a string of fishing villages — Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha, Almofala — has become, over the last decade, the most coveted frontier of world kitesurfing without losing its silence away from the water.",
      "This guide gathers what we learned travelling this coast: why Jericoacoara remains a place of pilgrimage even as the best-known stop, why Preá and Guajiru concentrate some of the planet's finest wind spots, and why the Sunset Dune in Jeri still gathers a quiet crowd every single evening.",
    ],
    seasons: {
      heading: "Best time to visit the Sunset Coast",
      intro: "Ceará's western coast has dry weather nearly year-round, but the wind — the region's true protagonist — follows its own calendar.",
      windows: [
        { window: "August to December — strong wind season", text: "Trade winds blow with the most intensity and consistency, creating ideal kitesurf and windsurf conditions in Preá, Guajiru and Jericoacoara; July and August mark the absolute peak." },
        { window: "January to June — softer wind, fuller lagoons", text: "A period of sparse rain that fills the dune lagoons, such as Lagoa Azul and Lagoa do Paraíso, making them more colourful and navigable by boat." },
        { window: "June to August — peak season for Brazilian travellers", text: "School holidays and cooler weather concentrate the year's heaviest visitor flow; booking three to four months ahead is advisable for the most sought-after addresses." },
        { window: "September to November — the balanced window", text: "Wind still strong, lagoons still well filled and a more moderate flow of tourists — the combination seasoned travellers tend to prefer." },
      ],
    },
    experiences: {
      heading: "Experiences worth the trip",
      intro: "The Sunset Coast works stretch by stretch — each village has its own character within the same landscape of dunes and wind.",
      items: [
        { title: "Sunset at the Sunset Dune, Jericoacoara", text: "A daily ritual that gathers locals and travellers atop the dune at the edge of the village, with spontaneous applause the moment the sun touches the sea." },
        { title: "Kitesurfing in Preá and Guajiru", text: "Two of the most respected spots on the world circuit, with steady side-shore wind between August and December and structured schools for every level." },
        { title: "Lagoa do Paraíso and Lagoa Azul, Jericoacoara", text: "Turquoise-green waters between white dunes, navigable by rowboat and surrounded by low-key restaurants open only during the day." },
        { title: "Rowboat and kayak trips on the Mundaú River", text: "Where river meets sea in Mundaú, amid mobile dunes and mangrove that reshape themselves year after year." },
        { title: "Icaraí de Amontada's freshwater pools among dunes", text: "A quieter village than Jeri, with crystal-clear freshwater lagoons formed between dunes and still lightly visited outside peak season." },
        { title: "Almofala and Lagoa do Torto", text: "The far western edge of the coast, near the Piauí border, with untouched dunes and traditional communities living from fishing and craft." },
      ],
    },
    stays: {
      heading: "Where to stay on the Sunset Coast — addresses by profile",
      intro: "We know each of these addresses personally; the right pick depends on the village and the pace you want — discreet comfort, design or total isolation among dunes.",
      items: [
        { name: "Vila Kalango (Jericoacoara)", profile: "Couples and travellers seeking design amid the dunes", text: "Bungalows of distinctive architecture among coconut palms, steps from the Sunset Dune, with its own pool and restaurant that make leaving unnecessary." },
        { name: "Essenza Hotel (Jericoacoara)", profile: "Travellers seeking contemporary comfort in the village centre", text: "A minimalist-aesthetic address very close to Jeri's sand streets, balancing practicality with understated sophistication." },
        { name: "Vila Selvagem (Icaraí de Amontada)", profile: "Couples seeking intimacy off the busier circuit", text: "A handful of accommodations between dunes and sea in Icaraí de Amontada, designed for those who want Jeri without Jeri's crowds." },
        { name: "Rancho do Peixe (Preá)", profile: "Kitesurfers and active travellers", text: "An address built for Preá's kite community, steps from the spot, with a relaxed vibe and proximity to the wind that draws people from around the world." },
        { name: "Casa Vento (Guajiru)", profile: "Travellers seeking quiet and wind without the buzz", text: "Guajiru is Preá's more discreet neighbour, and Casa Vento delivers exactly that: few rooms, silence and direct access to the beach and kite launch." },
      ],
    },
    profiles: {
      heading: "Who the Sunset Coast is for",
      items: [
        { title: "Kitesurfers and windsurfers, beginner or advanced", text: "Preá, Guajiru and Jericoacoara offer steady wind between August and December and structured schools for every experience level." },
        { title: "Couples and travellers seeking dune landscapes without urban excess", text: "Icaraí de Amontada, Mundaú and Almofala deliver the same scenery as Jeri with far fewer people." },
        { title: "Who it might not suit", text: "Travellers seeking full urban infrastructure, sophisticated nightlife or quick transfers between points should consider another coast — here, distances on sand roads demand time and patience." },
      ],
    },
    itinerary: {
      heading: "How to combine the Sunset Coast with a Ceará itinerary",
      intro: "The region sits 3 to 6 hours by car from Fortaleza airport, depending on the stretch and the condition of the sand road.",
      items: [
        { title: "Jericoacoara on its own — 4 to 6 days", text: "A single base in Jeri, with buggy or 4x4 day trips to the surrounding lagoons and Pedra Furada." },
        { title: "Jericoacoara + Preá or Guajiru — 6 to 8 days", text: "Combines Jeri's infrastructure and low-key nightlife with full days devoted to kitesurfing in Preá or Guajiru, about 20 minutes away." },
        { title: "The full western coast — 8 to 10 days", text: "A route through Flecheiras, Lagoinha, Mundaú, Icaraí de Amontada and Jericoacoara, revealing the diversity of villages between Fortaleza and the Piauí border." },
      ],
    },
    tips: {
      heading: "Practical tips that make a difference",
      items: [
        "Access to Jericoacoara is by paved road to Jijoca, followed by a sand stretch covered by 4x4 vehicle or buggy — regular cars are not recommended.",
        "For kitesurfing, August to December brings the strongest, steadiest wind; those learning may prefer January to May, with a gentler breeze.",
        "Book kitesurf lessons through accredited schools linked to your lodging — the launch area in Preá and Guajiru requires an instructor's supervision.",
        "The lagoons among the dunes vary in volume depending on rainfall; check with your lodging about seasonal conditions before planning outings.",
        "Transfers between neighbouring villages like Preá, Guajiru and Jericoacoara are usually done by buggy with a local driver — arrange ahead during peak season.",
        "Bring light clothing, sunscreen and a hat: the region's sun and wind dehydrate faster than on other Northeast coasts.",
      ],
    },
    faq: [
      { q: "Where is the Sunset Coast?", a: "On Ceará's western shoreline, between Fortaleza and the Piauí border, covering Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha and Almofala." },
      { q: "What is the best time for kitesurfing in Jericoacoara and Preá?", a: "From August to December, when trade winds blow with the most force and consistency over the region." },
      { q: "How do you get to Jericoacoara?", a: "Via Fortaleza airport, followed by a paved road to Jijoca and a final sand stretch covered by 4x4 vehicle or buggy." },
      { q: "Do cars circulate in Jericoacoara's centre?", a: "No; the village centre has sand streets and restricted vehicle circulation, preserving its fishing-village atmosphere." },
      { q: "What's the difference between Preá, Guajiru and Jericoacoara for kitesurfing?", a: "Preá and Guajiru have more technical spots geared to the kite community, while Jericoacoara offers fuller tourist infrastructure alongside the Sunset Dune." },
      { q: "How much does a trip to the Sunset Coast with Create Travel cost?", a: "We do not work with shelf pricing: the budget depends on the destination, accommodation and season. A human consultant presents the proposal in writing." },
    ],
    cta: { heading: "Let's design your Sunset Coast", subheading: "A human consultant at Create Travel chooses between Jericoacoara, Preá, Guajiru and Icaraí de Amontada the right base for your itinerary.", button: "Talk to a travel designer" },
    readingMinutes: 9,
    publishedAt: "2026-08-11",
  },
  es: {
    destinationName: "Costa del Sol Poniente",
    blurb: "Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras y Lagoinha: el litoral oeste de Ceará del viento, las dunas y el atardecer más celebrado de Brasil.",
    metaTitle: "Costa del Sol Poniente: guía de Jericoacoara a Lagoinha",
    metaDescription: "Guía completa de la Costa del Sol Poniente en Ceará: mejor época para kitesurf, Jericoacoara, Preá, Icaraí de Amontada, Mundaú, Flecheiras, hospedajes reales y ruta.",
    keywords: "costa del sol poniente ceara, jericoacoara, prea brasil, icarai de amontada, mundau, flecheiras, lagoinha ceara, guajiru, almofala, kitesurf brasil, duna del atardecer",
    h1: "Costa del Sol Poniente: el litoral cearense donde el viento se hace paisaje",
    aiAnswer: "La Costa del Sol Poniente es el litoral oeste de Ceará entre Fortaleza y el límite con Piauí, que reúne Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha y Almofala; la mejor época para el kitesurf va de agosto a diciembre, cuando los vientos alisios soplan con más constancia sobre dunas y lagunas.",
    intro: [
      "La Costa del Sol Poniente comienza donde el litoral cearense se convierte en un sertão de dunas y termina en Jericoacoara, un pueblo que se transformó en parque nacional y aun así conservó calles de arena y la prohibición de autos en el centro. Entre un punto y otro existe una sucesión de pueblos de pescadores —Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha, Almofala— que la última década transformó en la frontera más deseada del kitesurf mundial sin perder el silencio fuera del agua.",
      "Esta guía reúne lo que aprendimos recorriendo esta costa: por qué Jericoacoara sigue siendo destino de peregrinación aun siendo el más conocido, por qué Preá y Guajiru concentran algunos de los mejores spots de viento del planeta, y por qué la Duna del Atardecer, en Jeri, sigue reuniendo cada tarde a una multitud silenciosa.",
    ],
    seasons: {
      heading: "Mejor época para ir a la Costa del Sol Poniente",
      intro: "El litoral oeste de Ceará tiene clima seco casi todo el año, pero el viento —el verdadero protagonista de la región— sigue un calendario propio.",
      windows: [
        { window: "Agosto a diciembre — temporada de viento fuerte", text: "Los alisios soplan con más intensidad y constancia, generando las condiciones ideales de kitesurf y windsurf en Preá, Guajiru y Jericoacoara; julio y agosto marcan el pico absoluto." },
        { window: "Enero a junio — viento más suave, lagunas más llenas", text: "Período de lluvias esporádicas que llena las lagunas del interior de las dunas, como la Lagoa Azul y la Lagoa do Paraíso, dejándolas más coloridas y navegables en bote." },
        { window: "Junio a agosto — alta temporada de viajeros brasileños", text: "Las vacaciones escolares y el calor más moderado concentran el mayor flujo de visitantes del año; se recomienda reservar con tres o cuatro meses de anticipación en los alojamientos más solicitados." },
        { window: "Septiembre a noviembre — ventana de equilibrio", text: "Viento todavía fuerte, lagunas con buen volumen de agua y un flujo de turistas más moderado — la combinación preferida de los viajeros experimentados." },
      ],
    },
    experiences: {
      heading: "Experiencias que justifican el viaje",
      intro: "La Costa del Sol Poniente funciona por tramos — cada pueblo tiene una vocación distinta dentro del mismo escenario de dunas y viento.",
      items: [
        { title: "Atardecer en la Duna del Sol Poniente, en Jericoacoara", text: "Ritual diario que reúne a residentes y viajeros en lo alto de la duna junto al pueblo, con aplauso espontáneo en el instante en que el sol toca la línea del mar." },
        { title: "Kitesurf en Preá y Guajiru", text: "Dos de los spots más respetados del circuito mundial, con viento lateral constante entre agosto y diciembre y escuelas estructuradas para todos los niveles." },
        { title: "Lagoa do Paraíso y Lagoa Azul, en Jericoacoara", text: "Aguas verde turquesa entre dunas blancas, navegables en bote de remos y rodeadas de restaurantes discretos abiertos solo de día." },
        { title: "Paseo en jangada y kayak por el Río Mundaú", text: "Encuentro del río con el mar en Mundaú, escenario de dunas móviles y manglar que cambia de forma año tras año." },
        { title: "Icaraí de Amontada y las piscinas de agua dulce entre dunas", text: "Pueblo más silencioso que Jeri, con lagunas de agua dulce cristalina formadas entre dunas y todavía poco frecuentadas fuera de temporada alta." },
        { title: "Almofala y la Lagoa do Torto", text: "Extremo oeste de la costa, cerca del límite con Piauí, con dunas intactas y comunidades tradicionales que viven de la pesca y la artesanía." },
      ],
    },
    stays: {
      heading: "Dónde alojarse en la Costa del Sol Poniente — direcciones por perfil",
      intro: "Conocemos personalmente cada una de estas direcciones; la elección correcta depende del pueblo y del ritmo que busques — confort discreto, diseño o aislamiento total entre dunas.",
      items: [
        { name: "Vila Kalango (Jericoacoara)", profile: "Parejas y viajeros que buscan diseño en medio de las dunas", text: "Bungalós de arquitectura de autor entre cocoteros, a pocos pasos de la Duna del Sol Poniente, con piscina y restaurante propios que evitan salir del predio." },
        { name: "Essenza Hotel (Jericoacoara)", profile: "Viajeros que buscan confort contemporáneo en el centro del pueblo", text: "Dirección de estética minimalista muy cercana a las calles de arena del centro de Jeri, equilibrio entre practicidad y sofisticación discreta." },
        { name: "Vila Selvagem (Icaraí de Amontada)", profile: "Parejas que buscan intimidad fuera del circuito más concurrido", text: "Refugio de pocas habitaciones entre dunas y mar en Icaraí de Amontada, pensado para quien quiere Jeri sin la multitud de Jeri." },
        { name: "Rancho do Peixe (Preá)", profile: "Kitesurfistas y viajeros activos", text: "Dirección orientada a la comunidad del kite en Preá, a pocos metros del spot, con ambiente relajado y cercanía al viento que atrae a todo el mundo." },
        { name: "Casa Vento (Guajiru)", profile: "Viajeros que buscan tranquilidad y viento sin bullicio", text: "Guajiru es el vecino más discreto de Preá, y Casa Vento entrega exactamente eso: pocas habitaciones, silencio y acceso directo a la playa y al lanzamiento de kites." },
      ],
    },
    profiles: {
      heading: "Para quién funciona la Costa del Sol Poniente",
      items: [
        { title: "Practicantes de kitesurf y windsurf, principiantes o avanzados", text: "Preá, Guajiru y Jericoacoara reúnen viento constante entre agosto y diciembre y escuelas estructuradas para todos los niveles de experiencia." },
        { title: "Parejas y viajeros que buscan paisaje de dunas sin exceso urbano", text: "Icaraí de Amontada, Mundaú y Almofala entregan el mismo escenario de Jeri con mucha menos gente." },
        { title: "Para quién quizás no funcione", text: "Quien busca infraestructura urbana completa, vida nocturna sofisticada o traslados rápidos entre puntos debe considerar otro litoral — aquí las distancias por camino de arena piden tiempo y paciencia." },
      ],
    },
    itinerary: {
      heading: "Cómo integrar la Costa del Sol Poniente a una ruta por Ceará",
      intro: "La región está entre 3 y 6 horas en auto del Aeropuerto de Fortaleza, según el tramo y las condiciones del camino de arena.",
      items: [
        { title: "Jericoacoara aislada — 4 a 6 días", text: "Base única en Jeri, con excursiones de un día en buggy o 4x4 hasta las lagunas del entorno y la Pedra Furada." },
        { title: "Jericoacoara + Preá o Guajiru — 6 a 8 días", text: "Combina la estructura y la vida nocturna discreta de Jeri con días enteros dedicados al kitesurf en Preá o Guajiru, a unos 20 minutos de distancia." },
        { title: "Litoral oeste completo — 8 a 10 días", text: "Recorrido por Flecheiras, Lagoinha, Mundaú, Icaraí de Amontada y Jericoacoara, revelando la diversidad de pueblos entre Fortaleza y la frontera con Piauí." },
      ],
    },
    tips: {
      heading: "Consejos prácticos que marcan la diferencia",
      items: [
        "El acceso a Jericoacoara es por carretera asfaltada hasta Jijoca seguida de un tramo de arena recorrido en vehículo 4x4 o buggy — no se recomiendan autos comunes.",
        "Para kitesurf, el período de agosto a diciembre concentra el viento más fuerte y constante; quien busca aprender puede preferir enero a mayo, con brisa más suave.",
        "Reserve clases de kitesurf con escuelas acreditadas junto al alojamiento — el área de lanzamiento en Preá y Guajiru exige acompañamiento de instructor.",
        "Las lagunas del interior de las dunas varían de volumen según la lluvia; consulte con el alojamiento sobre las condiciones de la estación antes de planear paseos.",
        "El traslado entre pueblos vecinos como Preá, Guajiru y Jericoacoara suele hacerse en buggy con conductor local — coordine con anticipación en temporada alta.",
        "Lleve ropa liviana, protector solar y sombrero: el sol y el viento de la región deshidratan más rápido que en otros litorales del Nordeste.",
      ],
    },
    faq: [
      { q: "¿Dónde está la Costa del Sol Poniente?", a: "En el litoral oeste de Ceará, entre Fortaleza y el límite con Piauí, reuniendo Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha y Almofala." },
      { q: "¿Cuál es la mejor época para kitesurf en Jericoacoara y Preá?", a: "De agosto a diciembre, cuando los vientos alisios soplan con más fuerza y constancia sobre la región." },
      { q: "¿Cómo llegar a Jericoacoara?", a: "Por el Aeropuerto de Fortaleza, seguido de carretera asfaltada hasta Jijoca y un tramo final de arena recorrido en vehículo 4x4 o buggy." },
      { q: "¿Circulan autos en el centro de Jericoacoara?", a: "No; el centro del pueblo tiene calles de arena y circulación restringida de vehículos, preservando el ambiente de pueblo de pescadores." },
      { q: "¿Cuál es la diferencia entre Preá, Guajiru y Jericoacoara para kitesurf?", a: "Preá y Guajiru tienen spots más técnicos y orientados a la comunidad del kite, mientras Jericoacoara reúne una infraestructura turística más completa junto a la Duna del Sol Poniente." },
      { q: "¿Cuánto cuesta un viaje a la Costa del Sol Poniente con Create Travel?", a: "No trabajamos con precios estándar: el presupuesto depende del destino, el alojamiento y la temporada. Un consultor humano presenta la propuesta por escrito." },
    ],
    cta: { heading: "Diseñemos su Costa del Sol Poniente", subheading: "Un consultor humano de Create Travel elige entre Jericoacoara, Preá, Guajiru e Icaraí de Amontada la base correcta para su itinerario.", button: "Hablar con un travel designer" },
    readingMinutes: 9,
    publishedAt: "2026-08-11",
  },
  it: {
    destinationName: "Costa del Sole al Tramonto",
    blurb: "Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras e Lagoinha: la costa occidentale del Ceará fatta di vento, dune e il tramonto più celebrato del Brasile.",
    metaTitle: "Costa del Sole al Tramonto: guida da Jericoacoara a Lagoinha",
    metaDescription: "Guida completa alla Costa del Sole al Tramonto in Ceará: periodo migliore per il kitesurf, Jericoacoara, Preá, Icaraí de Amontada, Mundaú, Flecheiras, indirizzi reali e itinerario.",
    keywords: "costa do sol poente, jericoacoara, prea brasile, icarai de amontada, mundau, flecheiras, lagoinha ceara, guajiru, almofala, kitesurf brasile, duna del tramonto",
    h1: "Costa del Sole al Tramonto: il litorale del Ceará dove il vento disegna il paesaggio",
    aiAnswer: "La Costa del Sole al Tramonto è il litorale occidentale del Ceará tra Fortaleza e il confine con il Piauí, che include Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha e Almofala; il periodo migliore per il kitesurf va da agosto a dicembre, quando gli alisei soffiano con più costanza su dune e lagune.",
    intro: [
      "La Costa del Sole al Tramonto inizia dove il litorale del Ceará si trasforma in un entroterra di dune e termina a Jericoacoara, villaggio diventato parco nazionale che ha comunque conservato strade di sabbia e il divieto di auto nel centro. Tra un punto e l'altro si susseguono villaggi di pescatori — Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha, Almofala — che nell'ultimo decennio sono diventati la frontiera più ambita del kitesurf mondiale senza perdere il silenzio lontano dall'acqua.",
      "Questa guida raccoglie ciò che abbiamo imparato percorrendo questa costa: perché Jericoacoara resta meta di pellegrinaggio pur essendo la più conosciuta, perché Preá e Guajiru concentrano alcuni dei migliori spot di vento del pianeta, e perché la Duna del Tramonto, a Jeri, riunisce ogni sera una folla silenziosa.",
    ],
    seasons: {
      heading: "Periodo migliore per visitare la Costa del Sole al Tramonto",
      intro: "Il litorale occidentale del Ceará ha clima secco quasi tutto l'anno, ma il vento — il vero protagonista della regione — segue un calendario proprio.",
      windows: [
        { window: "Agosto a dicembre — stagione dei venti forti", text: "Gli alisei soffiano con maggiore intensità e costanza, creando le condizioni ideali per kitesurf e windsurf a Preá, Guajiru e Jericoacoara; luglio e agosto segnano il picco assoluto." },
        { window: "Gennaio a giugno — vento più mite, lagune più piene", text: "Periodo di piogge sparse che riempie le lagune tra le dune, come la Lagoa Azul e la Lagoa do Paraíso, rendendole più colorate e navigabili in barca." },
        { window: "Giugno ad agosto — alta stagione per i viaggiatori brasiliani", text: "Vacanze scolastiche e caldo più mite concentrano il maggior flusso di visitatori dell'anno; si consiglia di prenotare con tre o quattro mesi di anticipo gli indirizzi più richiesti." },
        { window: "Settembre a novembre — la finestra di equilibrio", text: "Vento ancora forte, lagune con buon volume d'acqua e flusso turistico più moderato — la combinazione preferita dai viaggiatori più esperti." },
      ],
    },
    experiences: {
      heading: "Esperienze che giustificano il viaggio",
      intro: "La Costa del Sole al Tramonto funziona per tratti — ogni villaggio ha una vocazione diversa all'interno dello stesso scenario di dune e vento.",
      items: [
        { title: "Tramonto sulla Duna del Sole, a Jericoacoara", text: "Rituale quotidiano che riunisce residenti e viaggiatori in cima alla duna ai margini del villaggio, con applauso spontaneo nell'istante in cui il sole tocca la linea del mare." },
        { title: "Kitesurf a Preá e Guajiru", text: "Due degli spot più rispettati del circuito mondiale, con vento laterale costante tra agosto e dicembre e scuole strutturate per tutti i livelli." },
        { title: "Lagoa do Paraíso e Lagoa Azul, a Jericoacoara", text: "Acque verde-turchese tra dune bianche, navigabili in barca a remi e circondate da ristoranti discreti aperti solo di giorno." },
        { title: "Giro in jangada e kayak sul fiume Mundaú", text: "L'incontro tra fiume e mare a Mundaú, tra dune mobili e mangrovie che cambiano forma anno dopo anno." },
        { title: "Icaraí de Amontada e le piscine di acqua dolce tra le dune", text: "Villaggio più silenzioso di Jeri, con lagune di acqua dolce cristallina formate tra le dune e ancora poco frequentate fuori dall'alta stagione." },
        { title: "Almofala e la Lagoa do Torto", text: "Estremo occidentale della costa, vicino al confine con il Piauí, con dune intatte e comunità tradizionali che vivono di pesca e artigianato." },
      ],
    },
    stays: {
      heading: "Dove alloggiare sulla Costa del Sole al Tramonto — indirizzi per profilo",
      intro: "Conosciamo personalmente ciascuno di questi indirizzi; la scelta giusta dipende dal villaggio e dal ritmo che cercate — comfort discreto, design o isolamento totale tra le dune.",
      items: [
        { name: "Vila Kalango (Jericoacoara)", profile: "Coppie e viaggiatori in cerca di design tra le dune", text: "Bungalow dall'architettura d'autore tra le palme da cocco, a pochi passi dalla Duna del Tramonto, con piscina e ristorante propri che rendono superfluo uscire." },
        { name: "Essenza Hotel (Jericoacoara)", profile: "Viaggiatori in cerca di comfort contemporaneo nel centro del villaggio", text: "Indirizzo dall'estetica minimalista molto vicino alle strade di sabbia del centro di Jeri, equilibrio tra praticità e sofisticazione discreta." },
        { name: "Vila Selvagem (Icaraí de Amontada)", profile: "Coppie in cerca di intimità fuori dal circuito più affollato", text: "Rifugio con poche sistemazioni tra dune e mare a Icaraí de Amontada, pensato per chi vuole Jeri senza la folla di Jeri." },
        { name: "Rancho do Peixe (Preá)", profile: "Kitesurfisti e viaggiatori attivi", text: "Indirizzo rivolto alla comunità del kite a Preá, a pochi metri dallo spot, con atmosfera rilassata e vicinanza al vento che attira persone da tutto il mondo." },
        { name: "Casa Vento (Guajiru)", profile: "Viaggiatori in cerca di quiete e vento senza confusione", text: "Guajiru è il vicino più discreto di Preá, e Casa Vento offre esattamente questo: poche camere, silenzio e accesso diretto alla spiaggia e al punto di lancio dei kite." },
      ],
    },
    profiles: {
      heading: "Per chi funziona la Costa del Sole al Tramonto",
      items: [
        { title: "Praticanti di kitesurf e windsurf, principianti o avanzati", text: "Preá, Guajiru e Jericoacoara offrono vento costante tra agosto e dicembre e scuole strutturate per ogni livello di esperienza." },
        { title: "Coppie e viaggiatori in cerca di paesaggi di dune senza eccessi urbani", text: "Icaraí de Amontada, Mundaú e Almofala offrono lo stesso scenario di Jeri con molte meno persone." },
        { title: "Per chi forse non è adatto", text: "Chi cerca infrastrutture urbane complete, vita notturna sofisticata o spostamenti rapidi tra i punti dovrebbe considerare un altro litorale — qui le distanze su strade di sabbia richiedono tempo e pazienza." },
      ],
    },
    itinerary: {
      heading: "Come integrare la Costa del Sole al Tramonto in un itinerario nel Ceará",
      intro: "La regione dista da 3 a 6 ore di auto dall'Aeroporto di Fortaleza, a seconda del tratto e delle condizioni della strada di sabbia.",
      items: [
        { title: "Jericoacoara isolata — 4-6 giorni", text: "Base unica a Jeri, con escursioni in buggy o 4x4 alle lagune circostanti e alla Pedra Furada." },
        { title: "Jericoacoara + Preá o Guajiru — 6-8 giorni", text: "Unisce la struttura e la vita notturna discreta di Jeri a giorni interi dedicati al kitesurf a Preá o Guajiru, a circa 20 minuti di distanza." },
        { title: "Litorale occidentale completo — 8-10 giorni", text: "Percorso tra Flecheiras, Lagoinha, Mundaú, Icaraí de Amontada e Jericoacoara, che rivela la varietà dei villaggi tra Fortaleza e il confine con il Piauí." },
      ],
    },
    tips: {
      heading: "Consigli pratici che fanno la differenza",
      items: [
        "L'accesso a Jericoacoara avviene su strada asfaltata fino a Jijoca, seguita da un tratto di sabbia percorso con veicolo 4x4 o buggy — le auto comuni non sono consigliate.",
        "Per il kitesurf, il periodo tra agosto e dicembre concentra il vento più forte e costante; chi vuole imparare può preferire gennaio-maggio, con brezza più leggera.",
        "Prenotate le lezioni di kitesurf presso scuole accreditate collegate all'alloggio — l'area di lancio a Preá e Guajiru richiede la supervisione di un istruttore.",
        "Le lagune tra le dune variano di volume in base alle piogge; verificate con l'alloggio le condizioni stagionali prima di pianificare escursioni.",
        "Gli spostamenti tra villaggi vicini come Preá, Guajiru e Jericoacoara avvengono di solito in buggy con autista locale — organizzatevi in anticipo in alta stagione.",
        "Portate abiti leggeri, protezione solare e cappello: il sole e il vento della regione disidratano più rapidamente rispetto ad altri litorali del Nordest.",
      ],
    },
    faq: [
      { q: "Dove si trova la Costa del Sole al Tramonto?", a: "Sul litorale occidentale del Ceará, tra Fortaleza e il confine con il Piauí, comprendendo Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha e Almofala." },
      { q: "Qual è il periodo migliore per il kitesurf a Jericoacoara e Preá?", a: "Da agosto a dicembre, quando gli alisei soffiano con maggiore forza e costanza sulla regione." },
      { q: "Come si arriva a Jericoacoara?", a: "Attraverso l'Aeroporto di Fortaleza, seguito da strada asfaltata fino a Jijoca e un tratto finale di sabbia percorso in veicolo 4x4 o buggy." },
      { q: "Circolano auto nel centro di Jericoacoara?", a: "No; il centro del villaggio ha strade di sabbia e circolazione veicolare limitata, preservando l'atmosfera di villaggio di pescatori." },
      { q: "Qual è la differenza tra Preá, Guajiru e Jericoacoara per il kitesurf?", a: "Preá e Guajiru hanno spot più tecnici orientati alla comunità del kite, mentre Jericoacoara offre un'infrastruttura turistica più completa accanto alla Duna del Tramonto." },
      { q: "Quanto costa un viaggio alla Costa del Sole al Tramonto con Create Travel?", a: "Non lavoriamo con tariffe standard: il budget dipende dalla destinazione, dall'alloggio e dalla stagione. Un consulente umano presenta la proposta per iscritto." },
    ],
    cta: { heading: "Progettiamo la vostra Costa del Sole al Tramonto", subheading: "Un consulente umano di Create Travel sceglie tra Jericoacoara, Preá, Guajiru e Icaraí de Amontada la base giusta per il vostro itinerario.", button: "Parla con un travel designer" },
    readingMinutes: 9,
    publishedAt: "2026-08-11",
  },
  de: {
    destinationName: "Küste der untergehenden Sonne",
    blurb: "Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras und Lagoinha: die Westküste Cearás mit Wind, Dünen und dem meistgefeierten Sonnenuntergang Brasiliens.",
    metaTitle: "Küste der untergehenden Sonne: Guide von Jericoacoara bis Lagoinha",
    metaDescription: "Der vollständige Guide zur Küste der untergehenden Sonne in Ceará: beste Reisezeit für Kitesurfen, Jericoacoara, Preá, Icaraí de Amontada, Mundaú, Flecheiras, echte Unterkünfte und Routenvorschläge.",
    keywords: "costa do sol poente, jericoacoara, prea brasilien, icarai de amontada, mundau, flecheiras, lagoinha ceara, guajiru, almofala, kitesurfen brasilien, sonnenuntergangsdüne",
    h1: "Küste der untergehenden Sonne: Cearás Küstenstrich, wo der Wind die Landschaft formt",
    aiAnswer: "Die Küste der untergehenden Sonne ist der Westküstenabschnitt Cearás zwischen Fortaleza und der Grenze zu Piauí mit Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha und Almofala; die beste Kitesurf-Saison reicht von August bis Dezember, wenn die Passatwinde am beständigsten über Dünen und Lagunen wehen.",
    intro: [
      "Die Küste der untergehenden Sonne beginnt dort, wo Cearás Küste in ein Hinterland aus Dünen übergeht, und endet in Jericoacoara, einem Dorf, das zum Nationalpark wurde und dennoch seine Sandstraßen und das Autoverbot im Zentrum bewahrt hat. Dazwischen reiht sich eine Kette von Fischerdörfern aneinander — Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha, Almofala —, die sich im letzten Jahrzehnt zur begehrtesten Kitesurf-Grenze der Welt entwickelt hat, ohne ihre Stille abseits des Wassers zu verlieren.",
      "Dieser Guide fasst zusammen, was wir auf dieser Küste gelernt haben: warum Jericoacoara trotz seiner Bekanntheit ein Pilgerziel bleibt, warum Preá und Guajiru zu den besten Windspots des Planeten zählen, und warum die Sonnenuntergangsdüne in Jeri jeden Abend eine stille Menschenmenge versammelt.",
    ],
    seasons: {
      heading: "Beste Reisezeit für die Küste der untergehenden Sonne",
      intro: "Cearás Westküste hat fast das ganze Jahr über trockenes Wetter, doch der Wind — der eigentliche Hauptdarsteller der Region — folgt seinem eigenen Kalender.",
      windows: [
        { window: "August bis Dezember — Saison der starken Winde", text: "Die Passatwinde wehen mit größter Intensität und Beständigkeit und schaffen ideale Bedingungen für Kite- und Windsurfen in Preá, Guajiru und Jericoacoara; Juli und August markieren den absoluten Höhepunkt." },
        { window: "Januar bis Juni — sanfterer Wind, fülligere Lagunen", text: "Eine Periode vereinzelter Regenfälle, die die Dünenlagunen wie die Lagoa Azul und die Lagoa do Paraíso füllt und sie farbenprächtiger sowie per Boot befahrbar macht." },
        { window: "Juni bis August — Hochsaison für brasilianische Reisende", text: "Schulferien und mildere Hitze bündeln den größten Besucherstrom des Jahres; für die gefragtesten Unterkünfte empfiehlt sich eine Buchung drei bis vier Monate im Voraus." },
        { window: "September bis November — das ausgewogene Zeitfenster", text: "Der Wind ist noch stark, die Lagunen noch gut gefüllt und der Touristenstrom moderater — die von erfahrenen Reisenden bevorzugte Kombination." },
      ],
    },
    experiences: {
      heading: "Erlebnisse, die die Reise rechtfertigen",
      intro: "Die Küste der untergehenden Sonne funktioniert abschnittsweise — jedes Dorf hat innerhalb derselben Landschaft aus Dünen und Wind seinen eigenen Charakter.",
      items: [
        { title: "Sonnenuntergang an der Sonnenuntergangsdüne in Jericoacoara", text: "Tägliches Ritual, das Einheimische und Reisende auf der Düne am Dorfrand versammelt, mit spontanem Applaus in dem Moment, in dem die Sonne die Meereslinie berührt." },
        { title: "Kitesurfen in Preá und Guajiru", text: "Zwei der angesehensten Spots der Weltszene, mit konstantem Seitenwind zwischen August und Dezember und strukturierten Schulen für jedes Niveau." },
        { title: "Lagoa do Paraíso und Lagoa Azul in Jericoacoara", text: "Türkisgrünes Wasser zwischen weißen Dünen, mit dem Ruderboot befahrbar und umgeben von unaufdringlichen Restaurants, die nur tagsüber geöffnet sind." },
        { title: "Fahrt mit Jangada und Kajak auf dem Rio Mundaú", text: "Das Zusammentreffen von Fluss und Meer in Mundaú, umgeben von wandernden Dünen und Mangroven, die Jahr für Jahr ihre Form verändern." },
        { title: "Icaraí de Amontada und die Süßwasserbecken zwischen den Dünen", text: "Ein stilleres Dorf als Jeri, mit kristallklaren Süßwasserlagunen zwischen den Dünen, außerhalb der Hochsaison noch wenig besucht." },
        { title: "Almofala und die Lagoa do Torto", text: "Der westlichste Punkt der Küste nahe der Grenze zu Piauí, mit unberührten Dünen und traditionellen Gemeinden, die von Fischerei und Handwerk leben." },
      ],
    },
    stays: {
      heading: "Wo man an der Küste der untergehenden Sonne übernachtet — Adressen nach Profil",
      intro: "Wir kennen jede dieser Adressen persönlich; die richtige Wahl hängt vom Dorf und dem Tempo ab, das Sie suchen — dezenter Komfort, Design oder totale Abgeschiedenheit zwischen den Dünen.",
      items: [
        { name: "Vila Kalango (Jericoacoara)", profile: "Paare und Reisende, die Design inmitten der Dünen suchen", text: "Bungalows mit unverwechselbarer Architektur zwischen Kokospalmen, wenige Schritte von der Sonnenuntergangsdüne entfernt, mit eigenem Pool und Restaurant, sodass man das Gelände kaum verlassen muss." },
        { name: "Essenza Hotel (Jericoacoara)", profile: "Reisende, die zeitgenössischen Komfort im Dorfzentrum suchen", text: "Eine Adresse mit minimalistischer Ästhetik ganz in der Nähe der Sandstraßen von Jeris Zentrum, im Gleichgewicht zwischen Praktikabilität und dezenter Raffinesse." },
        { name: "Vila Selvagem (Icaraí de Amontada)", profile: "Paare, die Intimität abseits des belebteren Kreises suchen", text: "Ein Refugium mit wenigen Unterkünften zwischen Dünen und Meer in Icaraí de Amontada, gedacht für alle, die Jeri ohne die Menschenmenge von Jeri wollen." },
        { name: "Rancho do Peixe (Preá)", profile: "Kitesurfer und aktive Reisende", text: "Eine Adresse für die Kite-Community in Preá, wenige Meter vom Spot entfernt, mit entspannter Atmosphäre und Nähe zu dem Wind, der Menschen aus aller Welt anzieht." },
        { name: "Casa Vento (Guajiru)", profile: "Reisende, die Ruhe und Wind ohne Trubel suchen", text: "Guajiru ist der zurückhaltendere Nachbar von Preá, und Casa Vento liefert genau das: wenige Zimmer, Stille und direkten Zugang zum Strand und zum Kite-Startplatz." },
      ],
    },
    profiles: {
      heading: "Für wen die Küste der untergehenden Sonne geeignet ist",
      items: [
        { title: "Kite- und Windsurfer, Anfänger oder Fortgeschrittene", text: "Preá, Guajiru und Jericoacoara bieten zwischen August und Dezember beständigen Wind und strukturierte Schulen für jedes Erfahrungsniveau." },
        { title: "Paare und Reisende, die Dünenlandschaften ohne urbanen Überschwang suchen", text: "Icaraí de Amontada, Mundaú und Almofala bieten dieselbe Szenerie wie Jeri, aber mit deutlich weniger Menschen." },
        { title: "Für wen es vielleicht nicht passt", text: "Wer vollständige urbane Infrastruktur, ein anspruchsvolles Nachtleben oder schnelle Wege zwischen den Orten sucht, sollte eine andere Küste in Betracht ziehen — hier erfordern die Entfernungen auf Sandwegen Zeit und Geduld." },
      ],
    },
    itinerary: {
      heading: "Wie man die Küste der untergehenden Sonne in eine Ceará-Reiseroute einbindet",
      intro: "Die Region liegt je nach Streckenabschnitt und Zustand der Sandstraße 3 bis 6 Autostunden vom Flughafen Fortaleza entfernt.",
      items: [
        { title: "Jericoacoara allein — 4 bis 6 Tage", text: "Ein einziger Standort in Jeri mit Tagesausflügen per Buggy oder 4x4 zu den umliegenden Lagunen und zur Pedra Furada." },
        { title: "Jericoacoara + Preá oder Guajiru — 6 bis 8 Tage", text: "Verbindet Jeris Infrastruktur und dezentes Nachtleben mit ganzen Tagen, die dem Kitesurfen in Preá oder Guajiru gewidmet sind, etwa 20 Minuten entfernt." },
        { title: "Die gesamte Westküste — 8 bis 10 Tage", text: "Eine Route durch Flecheiras, Lagoinha, Mundaú, Icaraí de Amontada und Jericoacoara, die die Vielfalt der Dörfer zwischen Fortaleza und der Grenze zu Piauí offenbart." },
      ],
    },
    tips: {
      heading: "Praktische Tipps, die den Unterschied machen",
      items: [
        "Der Zugang nach Jericoacoara erfolgt über eine asphaltierte Straße bis Jijoca, gefolgt von einem Sandabschnitt, der mit einem 4x4-Fahrzeug oder Buggy zurückgelegt wird — normale Autos werden nicht empfohlen.",
        "Für Kitesurfen bündelt der Zeitraum August bis Dezember den stärksten und beständigsten Wind; wer lernen möchte, bevorzugt eventuell Januar bis Mai mit sanfterer Brise.",
        "Buchen Sie Kitesurf-Kurse bei akkreditierten Schulen in Verbindung mit Ihrer Unterkunft — der Startbereich in Preá und Guajiru erfordert die Begleitung eines Fluglehrers.",
        "Die Lagunen zwischen den Dünen schwanken je nach Regenfällen im Wasserstand; erkundigen Sie sich bei Ihrer Unterkunft nach den saisonalen Bedingungen, bevor Sie Ausflüge planen.",
        "Der Transfer zwischen benachbarten Dörfern wie Preá, Guajiru und Jericoacoara erfolgt meist per Buggy mit lokalem Fahrer — in der Hochsaison im Voraus organisieren.",
        "Bringen Sie leichte Kleidung, Sonnenschutz und einen Hut mit: Sonne und Wind der Region dehydrieren schneller als an anderen Küsten des Nordostens.",
      ],
    },
    faq: [
      { q: "Wo liegt die Küste der untergehenden Sonne?", a: "An Cearás Westküste, zwischen Fortaleza und der Grenze zu Piauí, mit Jericoacoara, Preá, Guajiru, Icaraí de Amontada, Mundaú, Flecheiras, Lagoinha und Almofala." },
      { q: "Wann ist die beste Zeit zum Kitesurfen in Jericoacoara und Preá?", a: "Von August bis Dezember, wenn die Passatwinde am kräftigsten und beständigsten über die Region wehen." },
      { q: "Wie erreicht man Jericoacoara?", a: "Über den Flughafen Fortaleza, gefolgt von einer asphaltierten Straße bis Jijoca und einem letzten Sandabschnitt, der mit einem 4x4-Fahrzeug oder Buggy zurückgelegt wird." },
      { q: "Fahren im Zentrum von Jericoacoara Autos?", a: "Nein; das Dorfzentrum hat Sandstraßen und eingeschränkten Fahrzeugverkehr, wodurch die Atmosphäre eines Fischerdorfs erhalten bleibt." },
      { q: "Was unterscheidet Preá, Guajiru und Jericoacoara beim Kitesurfen?", a: "Preá und Guajiru haben technischere, auf die Kite-Community ausgerichtete Spots, während Jericoacoara neben der Sonnenuntergangsdüne eine vollständigere touristische Infrastruktur bietet." },
      { q: "Wie viel kostet eine Reise an die Küste der untergehenden Sonne mit Create Travel?", a: "Wir arbeiten nicht mit Listenpreisen: Das Budget hängt vom Ziel, der Unterkunft und der Saison ab. Ein menschlicher Berater legt das Angebot schriftlich vor." },
    ],
    cta: { heading: "Lassen Sie uns Ihre Küste der untergehenden Sonne gestalten", subheading: "Ein menschlicher Berater von Create Travel wählt zwischen Jericoacoara, Preá, Guajiru und Icaraí de Amontada die richtige Basis für Ihre Reiseroute.", button: "Mit einem Travel Designer sprechen" },
    readingMinutes: 9,
    publishedAt: "2026-08-11",
  },
};
